### ISSUE TITLE
Can't wand claim without op

### ISSUE THREAD

**Issue by UltimaA380** [FabioZumbi12/RedProtect#102]
Hi, I cannot claim with a wand unless im op.  These are the permissions im using:
    - redprotect.own.claim
    - redprotect.user
    - redprotect.magicwand
    - redprotect.own.claim
    - redprotect.use-claim-modes

**Comment by FabioZumbi12** [comment]
Hi,

On latest version for BVukkit/Spigot you dont need to give the permision. Change the option on config.yml.

``` region-settings:
    claim-type:
      worlds:
        z12: BLOCK
        z12_nether: WAND
```

**Comment by UltimaA380** [comment]
How do I make it both? It works while opped so I thought its a permission.

**Comment by FabioZumbi12** [comment]
Go to your config.yml and search for this option and your worlds.

**Comment by UltimaA380** [comment]
I understand I found it, but I was asking is it possible to have it like this?

`region-settings:
    claim-type:
      worlds:
        z12: BLOCK,WAND
        z12_nether: WAND`

**Comment by FabioZumbi12** [comment]
Oh shure, you can set to "BOTH".

**Comment by UltimaA380** [comment]
Ah thanks!
