### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by PeRFecTxTabZ** [FabioZumbi12/RedProtect#106]
Hello, i really tried everything but...
How can i disable the you can not fly above this region.
I disabled the forcefly and allow-fly flag and gave my teammembers /fly with essentials.
BUT everytime when they fly abouve an rp fly gets disabled it frustrating i tried everything, and i dont want to give them admin permoissions or op.

i have op and can fly above regions

**Comment by FabioZumbi12** [comment]
You need to remove the forcefly because this will, or force to fly or force to not fly. Removing will leave to player/permission choose.

**Comment by PeRFecTxTabZ** [comment]
these are my configs at the moment:

gui config

# 
# ADMIN FLAGS ###########################

gui-strings:
  'false': '&c&odeaktiviert'
  'true': '&a&oaktiviert'
  value: '&3&lWert&r&7: '
  separator: '&7|'
gui-separator:
  material: REDSTONE_BLOCK
  data: 0
gui-flags:
  door:
    slot: 0
    material: WOOD_DOOR
    name: '&e&nTüren öffnen'
    description: '&3&lBeschreibung&7: Erlaube das'
    description1: '&7öffnen/ schließen von Türen.'
    description2: '&3&lBetrifft&7: &c&ofremde Spieler'
  smart-door:
    slot: 1
    material: IRON_DOOR
    name: '&e&nerweiterte Türen Einstellungen'
    description: '&3&lBeschreibung&7: Stelle Doppeltüren'
    description1: '&7an, und öffne Eisentüren per Rechtsklick.'
    description2: '&3&lBetrifft&7: &c&ofremde Spieler, Member, Admins, Leader'
  pvp:
    slot: 4
    material: STONE_SWORD
    name: '&e&nPvP Einstellungen'
    description: '&3&lBeschreibung&7: Erlaube PvP.'
    description1: ''
    description2: '&3&lBetrifft&7: &c&ofremde Spieler, Member, Admins, Leader'
  allow-home:
    slot: 2
    material: BED
    name: '&e&nErlaube /home Befehle'
    description: '&3&lBeschreibung&7: Erlaube den Befehl'
    description1: '&7/home oder /sethome zu benutzen.'
    description2: '&3&lBetrifft&7: &c&ofremde Spieler'
  chest:
    slot: 9
    material: TRAPPED_CHEST
    name: '&e&nKisten Zugriff'
    description: '&3&lBeschreibung&7: Erlaube den'
    description1: '&7Zugriff auf Kisten.'
    description2: '&3&lBetrifft&7: &c&ofremde Spieler'
  lever:
    slot: 5
    material: LEVER
    name: '&e&nHebel Benutzung'
    description: '&3&lBeschreibung&7: Erlaube es anderen'
    description1: '&7Hebel zu benutzen.'
    description2: '&3&lBetrifft&7: &c&ofremde Spieler'
  button:
    slot: 14
    material: WOOD_BUTTON
    name: '&e&nKnopf Benutzung'
    description: '&3&lBeschreibung&7: Erlaube es anderen'
    description1: '&7Knöpfe zu benutzen.'
    description2: '&3&lBetrifft&7: &c&ofremde Spieler'
  passives:
    slot: 13
    material: SADDLE
    name: '&e&nverletzte passive Mobs'
    description: '&3&lBeschreibung&7: Erlaube das töten'
    description1: '&7und interagiern mit passiven Mobs.'
    description2: '&3&lBetrifft&7: &c&ofremde Spieler'
  minecart:
    slot: 11
    material: MINECART
    name: '&e&nLohren Einstellungen'
    description: '&3&lBeschreibung&7: Erlaube das platzieren,'
    description1: '&7benutzen und das zerstören von Lohren.'
    description2: '&3&lBetrifft&7: &c&ofremde Spieler'
  fire:
    slot: 16
    material: BLAZE_POWDER
    name: '&e&nFeuer-, Explosions Verhalten'
    description: '&3&lBeschreibung&7: &7Erlaube Feuerschaden,'
    description1: '&7Explosionen und Feuerausbreitung.'
    description2: '&3&lBetrifft&7: &c&oBlöcke'
  flow:
    slot: 7
    material: WATER_BUCKET
    name: '&e&nWasser-, Lavafluss'
    description: '&3&lBeschreibung&7: Erlaube das Wasser'
    description1: '&7und Lava sich ausbreiten.'
    description2: '&3&lBetrifft&7: &c&oWasser, Lava'
  spawn-animals:
    slot: 3
    material: EGG
    name: '&e&nTiere Spawneinstellungen'
    description: '&3&lBeschreibung&7: Erlaube das Spawnen'
    description1: '&7von Tieren.'
    description2: '&3&lBetrifft&7: &c&ofremde Spieler, Member, Admins, Leader'
  spawn-monsters:
    slot: 12
    material: PUMPKIN
    name: '&e&nMonster Spawneinstellungen'
    description: '&3&lBeschreibung&7: Erlaube das Spawnen'
    description1: '&7von Monstern.'
    description2: '&3&lBetrifft&7: &c&ofremde Spieler, Member, Admins, Leader'
  allow-potions:
    slot: 15
    material: GLASS_BOTTLE
    name: '&e&nerlaube Tränke'
    description: '&3&lBeschreibung&7: Erlaube es Tränke'
    description1: '&7zu Trinken/ zu werfen.'
    description2: '&3&lBetrifft&7: &c&ofremde Spieler, Member, Admins, Leader'
  mob-loot:
    slot: 17
    material: GRASS
    name: '&e&nMob griefing'
    description: '&3&lBeschreibung&7: Erlaube es Mobs'
    description1: '&7Blöcke zu stehlen/ modifizieren.'
    description2: '&3&lBetrifft&7: &c&oBlöcke, Monster'
  flow-damage:
    slot: 8
    material: LAVA_BUCKET
    name: '&e&nFlussschaden'
    description: '&3&lBeschreibung&7: Erlaube es Wasser'
    description1: '&7und Lava Schaden zu verursachen.'
    description2: '&3&lBetrifft&7: &c&oBlöcke, Gegenstände'
  teleport:
    slot: 6
    material: ENDER_PEARL
    name: '&e&nTeleportation'
    description: '&3&lBeschreibung&7: Erlaube Spielern'
    description1: '&7die Benutzung von Enderperlen.'
    description2: '&3&lBetrifft&7: &c&ofremde Spieler'
  ender-chest:
    slot: 10
    material: ENDER_CHEST
    name: '&e&nErlaube Endertruhen Zugriff'
    description: '&3&lBeschreibung&7: Erlaube den'
    description1: '&7Zugriff auf Endertruhen.'
    description2: '&3&lBetrifft&7: &c&ofremde Spieler'
  enter:
    slot: 21
    material: FENCE
    name: '&e&nZugangsrechte'
    description: '&3&lBeschreibung&7: Erlaube fremden Spielern'
    description1: '&7dein Grundstück zu betreten.'
    description2: '&3&lBetrifft&7: &c&ofremde Spieler'
  can-pickup:
    slot: 18
    material: EMERALD
    name: '&e&nItems aufsammeln'
    description: '&3&lBeschreibung&7: Erlaube das Spieler'
    description1: '&7Items aufsammeln dürfen.'
    description2: '&3&lBetrifft&7: &c&ofremde Spieler'
  can-drop:
    slot: 19
    material: REDSTONE
    name: '&e&nItems ablegen'
    description: '&3&lBeschreibung&7: Erlaube das Spieler'
    description1: '&7Items droppen dürfen.'
    description2: '&3&lBetrifft&7: &c&ofremde Spieler'
  portal-exit:
    slot: 24
    material: OBSIDIAN
    name: '&e&nportal-exit'
    description: '&3&lBeschreibung&7: Erlaube Spielern aus Teleportalen'
    description1: '&7heraus auf dein Grundstück zu gelangen.'
    description2: '&3&lBetrifft&7: &c&ofremde Spieler'
  portal-enter:
    slot: 25
    material: OBSIDIAN
    name: '&e&nportal-enter'
    description: '&3&lBeschreibung&7: Erlaube Spielern'
    description1: '&7Teleportale zu benutzen.'
    description2: '&3&lBetrifft&7: &c&ofremde Spieler'


main 


# +--------------------------------------------------------------------+ #
# <               RedProtect World configuration File                  > #
# <--------------------------------------------------------------------> #
# <       This is the configuration file, feel free to edit it.        > #
# +--------------------------------------------------------------------+ #
# <        You can see the complete commented version of this          > #
# <       configuration file in this link: https://goo.gl/SEbYBZ       > #
# +--------------------------------------------------------------------+ #

config-version: 7.3
debug-messages: false
log-actions: false
language: DE
file-type: yml
flat-file:
  region-per-file: false
  auto-save-interval-seconds: 3600
  backup: true
  max-backups: 10
mysql:
  db-name: redprotect
  user-name: root
  user-pass: redprotect
  host: localhost
  region-cache-minutes: 2
  table-prefix: rp_
region-settings:
  default-leader: Server
  border:
    material: GLOWSTONE
    time-showing: 15
  region-list:
    simple-listing: true
    hover-and-click-teleport: true
    show-area: true
  autoexpandvert-ondefine: true
  anti-hopper: true
  claim-modes:
    mode: give
    allow-player-decide: false
    use-perm: true
  limit-amount: 550
  claim-amount: 1
  block-id: FENCE
  max-scan: 600
  date-format: dd/MM/yyyy
  record-player-visit-method: ON-LOGIN
  allow-sign-interact-tags:
  - Admin Shop
  - '{membername}'
  leadership-request-time: 20
  world-colors:
    world: '&a&l'
    world_nether: '&c&l'
    world_the_end: '&5&l'
  enable-flag-sign: false
  deny-build-near: 0
  rent:
    default-level: admin
    add-player: false
    command-renew-adds: 1:MONTH
    renew-anytime: false
  claim-type:
    worlds:
      world: BLOCK
      world_nether: BLOCK
      world_the_end: BLOCK
allowed-claim-worlds:
- world
wands:
  adminWandID: 374
  infoWandID: 339
private:
  use: true
  allow-outside: false
  allowed-blocks-use-ids: false
  allowed-blocks:
  - DISPENSER
  - NOTE_BLOCK
  - BED_BLOCK
  - CHEST
  - WORKBENCH
  - FURNACE
  - JUKEBOX
  - ENCHANTMENT_TABLE
  - BREWING_STAND
  - CAULDRON
  - ENDER_CHEST
  - BEACON
  - TRAPPED_CHEST
  - HOPPER
  - DROPPER
notify:
  region-enter: false
  region-exit: false
  region-enter-mode: BOSSBAR
  welcome-mode: BOSSBAR
netherProtection:
  maxYsize: 128
  execute-cmd:
  - spawn {player}
server-protection:
  deny-playerdeath-by: []
  deny-commands-on-worlds:
    world:
    - op
  nickname-cap-filter:
    enabled: false
  sign-spy:
    enabled: false
    only-console: true
  teleport-player:
    on-join:
      enable: false
      need-world-to-teleport: none
      location: world, 0, 90, 0
    on-leave:
      enable: false
      need-world-to-teleport: none
      location: world, 0, 90, 0
  deny-potions: []
flags:
  pvp: false
  chest: false
  lever: false
  button: false
  door: false
  allow-potions: true
  smart-door: true
  spawn-monsters: true
  spawn-animals: true
  passives: false
  flow: true
  fire: false
  minecart: false
  allow-home: false
  mob-loot: false
  flow-damage: false
  enter: true
  teleport: false
  ender-chest: true
  portal-exit: true
  portal-enter: true
  can-pickup: true
  can-drop: true
  allow-magiccarpet: true
  iceform-player: true
  iceform-entity: true
  allow-fly: false
  clan: ''
flags-configuration:
  effects-duration: 5
  enabled-flags:
  - pvp
  - chest
  - lever
  - button
  - door
  - smart-door
  - spawn-monsters
  - spawn-animals
  - passives
  - flow
  - fire
  - minecart
  - allow-potions
  - allow-home
  - mob-loot
  - flow-damage
  - enter
  - teleport
  - ender-chest
  - portal-exit
  - portal-enter
  - can-pickup
  - can-drop
  pvparena-nopvp-kick-cmd: spawn {player}
  change-flag-delay:
    enable: true
    seconds: 20
    flags:
    - pvp
    - chest
    - lever
    - button
    - door
    - smart-door
    - spawn-monsters
    - spawn-animals
    - passives
    - flow
    - fire
    - minecart
    - allow-potions
    - allow-home
    - mob-loot
    - flow-damage
    - enter
    - teleport
    - portal-exit
    - portal-enter
    - can-pickup
    - can-drop
purge:
  enabled: true
  remove-oldest: 90
  regen:
    enable: false
    max-area-regen: 500
    awe-logs: true
  ignore-regions-from-players:
  - PeRFecTxTabZ
sell:
  enabled: false
  sell-oldest: 60
  ignore-regions-from-players:
  - PeRFecTxTabZ
update-check:
  enable: false
  auto-update: false
performance:
  disable-onPlayerMoveEvent-handler: false
  disable-PistonEvent-handler: true
  piston:
    disable-PistonEvent-handler: true
    use-piston-restricter: false
    restrict-piston-event: 10
hooks:
  essentials:
    import-lastvisits: false
  dynmap:
    enable: false
    marks-groupname: PCGProtect
    layer-priority: 10
    show-label: true
    show-icon: true
    marker-icon: shield
    min-zoom: 0
  magiccarpet:
    fix-piston-getblocks: true
  armor-stands:
    spawn-arms: true
  mcmmo:
    fix-acrobatics-fireoff-leveling: true
    fix-berserk-invisibility: true
needed-claim-to-build:
  worlds:
  - example_world
  allow-only-protections-blocks: true

**Comment by PeRFecTxTabZ** [comment]
ok, thx i fixxed it now ^^
