### ISSUE TITLE
I know this is a stupid issue

### ISSUE THREAD

**Issue by marioandluigi878** [FabioZumbi12/RedProtect#107]
Now I know that may seem a little stupid for you all but for some reason when I put in the permissions for redprotect and try to claim a region with an alt account of mine it gives me the error 

"[RedProtect] [RP] Error: You don't have permission to make regions!"

Think someone can help me with that?

**Comment by FabioZumbi12** [comment]
I dont know what you mean...

**Comment by marioandluigi878** [comment]
Ok so I'm on my testing  server right and I'm trying to claim a region with an alt account that has the default rank and the permissions to claim yet when im trying to have it claim a region it says I don't have that permission even though I do...

**Comment by FabioZumbi12** [comment]
Maybe you need to check the claim options con configuration in **region-settings.claim-type.worlds.world: BLOCK or WAND**

And check if the player has the perm **redprotect.player** too
