### ISSUE TITLE
KCauldron 1.7.10 And Tekkit Legends pack not work on RedProtect v6.3.6

### ISSUE THREAD

**Issue by mat41997** [FabioZumbi12/RedProtect#11]
Screen,

http://i.imgur.com/J5XFKqQ.png

------------------------------------------

server.properties,

level-name=swiat_tekkita

------------------------------------------

redprotect config,

allowed-claim-worlds:
- swiat_tekkita

**Comment by lordskout** [comment]
Having this same problem under 6.3.6. I can make regions with adminwand, but users cannot with fences and signs.

**Comment by mat41997** [comment]
Thanks @ lordskout : )

**Comment by FabioZumbi12** [comment]
I will make tests today with KCauldron to get this problem ;)

**Comment by FabioZumbi12** [comment]
Reproduced this on my tests!! Looking for a fix!!

**Comment by FabioZumbi12** [comment]
Until o not found a solution, uses the 6.3.0! To fix i need to revert some of changes i have maded on 6.3.x and will give me a bit o work.

**Comment by FabioZumbi12** [comment]
Fixed on 6.4+
