### ISSUE TITLE
Flag Suggestion 

### ISSUE THREAD

**Issue by Icodak** [FabioZumbi12/RedProtect#110]
Hi ! 

Could you add flags that would:
- stop leaves decay
- stop snow melt

It would really help builders to add small details (that makes the difference) to their builds.
Best regards 
-Icodak :D

**Comment by FabioZumbi12** [comment]
Hi,
Already added on latest build. Leaves decay is already on /rp flag fire.
Snow ,elt is on /rp flag iceform-world
