### ISSUE TITLE
Flag Suggestion

### ISSUE THREAD

**Issue by Ritcheur** [FabioZumbi12/RedProtect#111]
I had an idea which could help a lot of builders. 
Could you add flags that would permit to have the equivalent of the gamerule randomtickspeed 0.
Thanks to that, we could have varied field or have grass and dirt next to each other.

**Comment by CloudeLecaw** [comment]
you should tell the dev what u mean with Randomtickspeed 0?
Why u need this? pls descript it a bit more.
There is a flag allready that allow to set you to different gamemode.. but i think thats not what u want..
there is also a flag to avoid fluiddamge that u can add in the flag gui (like all true/false flags they can be added  in the gui by yourself if u need them in the /rp flag gui)

but why no tickspeed? everything lives in tickspeeds.
The only thing i could currently think of maybe is that u wanted a flag that disables redstone from ticking... am i right?

**Comment by Ritcheur** [comment]
I don't know if there is already  a flag for this, but I would like to stop plantation to grow. That way I would be able to have wheat att different growing stage.

**Comment by CloudeLecaw** [comment]
hm i dont know if this is a so good idea.
i renember a plugin that was controlling plants planttation grow and it was a horrorble ressource eater for the server. Maybe fabio has an idea how to handle a thing like that :)

**Comment by Ritcheur** [comment]
My idea isn't to modify the plantations grow by increasing it or decreasing it, but to enable or disable it to have the same plants at different growing stages permanently.

**Comment by FabioZumbi12** [comment]
The flag "can-grow" already added, will be fully available on next version. (see the plugin comments to fix  a bug)
