### ISSUE TITLE
Plugins that "jump" over the Protection... any ideas?

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#112]
Hello Fabio Today i got a problem with a plugin that created a new Idea.. i know u love suggestions 

Is it possible to create a list with permissions in the config?

Idea: If Player is no member of Region these permissions are negated for him when he enter this region.
(Even if he normaly has them) If he gets Member then the permissions work normal.

What happend: i have a plugin that allow to change peoples Frameitems and Pictures with a mouseclick (rightclick)
the only way this plugin can handle is a permission. now when player has the permission he can change the pictures,
Normaly they would be saved now...but if he has no permission redprotect only sees it if he left the pictures.

Before:
![852afc0f341008bc04429f19eaba6e39022600bc](https://cloud.githubusercontent.com/assets/12080017/20960725/124485b8-bc62-11e6-8cd5-40bc42a76a2f.png)

After:
![390f69467bfd5f5dfdda9c9ffb68e4f5b7506b51](https://cloud.githubusercontent.com/assets/12080017/20960726/1416952a-bc62-11e6-8db3-5911e3c585de.png)

The Plugin self is called NeoPaintingSwitch and can be optianed here.
https://dev.bukkit.org/bukkit-plugins/paintingswitch/

i hope you have an idea for this..
i think there are also other plugins that allow strangers some "in region" unwanted actions...

**Comment by FabioZumbi12** [comment]
I only deny interact with painting if the player is not member of region ;)

Actually i posting dev build on our discord. if you want, join on https://discord.gg/bFssjQq
