### ISSUE TITLE
ChatProtection

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#113]
The ChatScann is a bit wrong..the protectionpart

One in Our World said "bb i leave for today"
Player2: bb
Player3: bb
Player4: bb

- Player 3 got wanted not to Chat so fast.
- Player 4 got muted for spamming.. :§

![2016-12-10_20-18-42](https://cloud.githubusercontent.com/assets/12080017/21075659/b69a8ac4-bf17-11e6-84d2-120b65a5dad4.png)

**Comment by FabioZumbi12** [comment]
Anyway, the same EXACT messages sent by other players still be flood! This is not an issue or wrong.
