### ISSUE TITLE
Fence duplication with modded block

### ISSUE THREAD

**Issue by hugeblank** [FabioZumbi12/RedProtect#115]
So there's this mod titled ComputerCraft that implements computers into the game, and we wanted to stress test RedProtect's modded block handling. We made a small claim, and placed a [turtle](http://www.computercraft.info/wiki/Turtle) down next to it. We started off by trying to break the claimed fence... It was at this point things got interesting. The turtle broke the block and the protection plugin replaced it. But when we checked the inventory, the fence was in there too. So ultimately, we just duplicated a fence using nothing but a modded block. I plan on reporting this bug to the "developer" (long story short, the dev has for the most part given up on the mod, and a member of the community picked it up. This was a very recent). 

Steps to recreate:
1: load up a world with CC, and RedProtect
2: make a claim with fences.
3: get a mining turtle, and place it down facing into the fences
4:  boot up the turtle (right click it), and type in 'lua', and then 'turtle.dig()'
5: the turtle will break the fence and get it in its inventory, but the fence will reappear where it was.

If this could get fixed, you would be:
1: a server hero
2: the only reliable modded protection plugin, griefprevention literally doesn't work for my server.

**Comment by FabioZumbi12** [comment]
Hi,

Can you confirm if this is only happens inside regions or on wilderness too?
Have you tryed withou redprotect installed?

**Comment by hugeblank** [comment]
1. It occurs on the outside of the regions, in the wilderness.
2. Fences break normally without redprotect. 

the developer got to me and said that an event called 'ChangeBlockEvent.Pre' is not being listened to. The issue I posted on his page can be found [here](https://github.com/SquidDev-CC/CCTweaks/issues/133)

**Comment by FabioZumbi12** [comment]
Tested with newer versions? I nenver heard about this bug with other users.
