### ISSUE TITLE
Ore drop XP in region

### ISSUE THREAD

**Issue by LunyashaRu** [FabioZumbi12/RedProtect#117]
Ore like diamond drop xp then player who can't break block here try to break block.
RedProtect-Sponge-6.5.1-b220
(Sorry for my English) 
![2016-12-26_15 42 53_2](https://cloud.githubusercontent.com/assets/22874697/21482324/56de35a4-cb83-11e6-91bd-3695fc4b50dd.png)

**Comment by FabioZumbi12** [comment]
Try the lates version of RedProtect 7.0.3

**Comment by LunyashaRu** [comment]
I talking about RedProtect for Sponge

**Comment by FabioZumbi12** [comment]
oh sorry... then i need to check.

**Comment by FabioZumbi12** [comment]
Wrong location (Sponge version)
