### ISSUE TITLE
Crops wont grow at all

### ISSUE THREAD

**Issue by Klonkcraft** [FabioZumbi12/RedProtect#121]
In 7.1 RedProtect my crops wont grow at all, and bonemeal doesn't do anything either. I think it's because of the can-grow flags . Any ideas why it wont grow? It works fine with 7.0.3

**Comment by dnaf** [comment]
Having this problem too. Crops will grow outside of defined regions, trees/saplings work fine. If there's a flag or a config option, I can't find it.

**Comment by FabioZumbi12** [comment]
Until i dont release a new version (still add some thinks), a fix for growts dont grow its:

> Go to config.yml
> and add "can-grow" to this section: "flags-configuration: > enabled-flags"
> and add "can-grow: true" to this section: "flags:"
> and use /rp reload-config

Or go to our Discord and download our dev version with this fix: https://discord.gg/RyEVJC3
