### ISSUE TITLE
Suggestion for dynmap optimization with claims

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#126]
On my dynmap the RedProtect claims are displayed but as soon as there are many it is very difficult to move on this map. I think it would be possible to optimize this as with other similar plugins.

It would be great because you have to deactivate the RedProtect claims as soon as you arrive on a map with many claims, I tried to remove the name of the claims hoping that it changes something but it did nothing.

To find out : http://play.freebuild.fr:8129/?zoom=3 (Map Build Overworld V1)

**Comment by FabioZumbi12** [comment]
I added the option to hide by default. Try this version: https://discord.gg/RyEVJC3

**Comment by aurel85** [comment]
In spite of this RedProtect is always displayed basic on the dynmap.

**Comment by FabioZumbi12** [comment]
I dont know what you mean...

**Comment by aurel85** [comment]
Sorry, my english is bad and I wrote too fast, I have edit my precedent message.

**Comment by FabioZumbi12** [comment]
Download again from Discord, now i found what i maded wrong and tested ;) Its the build 273

**Comment by FabioZumbi12** [comment]
U uploaded a new version with a lot of additions for dynmap ;)
