### ISSUE TITLE
WitherSpawnFlag Error

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#129]
On my Globalflag is have this_
On my world i have
  spawn-wither: false
here all works fine..

In the Nether and End i have the global flag
  spawn-wither: true

But Players cant build the wither.

i added the   spawn-wither flag also in the gui
so Players can decide it on their Region
if here the flag is set to true in there own Region
then they can build the wither

The Question is - what is blocking the globaly build of the wither when
  spawn-wither: true?

**Comment by aurel85** [comment]
I noticed the same thing on my server.

**Comment by FabioZumbi12** [comment]
Have you tryed to enable spawn monsters on that region to see if the flag mosnters is taking effect under this flag?

**Comment by CloudeLecaw** [comment]
I think u understand it wrong : 3

This witherspawn problem happens in the Global world,  World, world_nether, world_nether_end
In Regions the flag works fine when and players can buidl the wither with spawn monsters is enabled.

**Comment by aurel85** [comment]
From the moment we are not in a claim, it does not work.

**Comment by CloudeLecaw** [comment]
This Error is fixed with 7.1.2 Build 303

https://cdn.discordapp.com/attachments/215574654050500608/280845973234909186/RedProtect-7.1.2-b303.jar
