### ISSUE TITLE
Beacon effect

### ISSUE THREAD

**Issue by Ritcheur** [FabioZumbi12/RedProtect#130]
The flag potions now affect beacon effect,  which, I think is a bug

**Comment by aurel85** [comment]
Yes if the flag is false the effect of the beacon will work very badly. It is absolutely necessary that it is on true so for that the beacon works correctly.

**Comment by FabioZumbi12** [comment]
Humm, i will add other flag to deny potion-usage to split the usage and walk on region with potion effect.

**Comment by FabioZumbi12** [comment]
The flag added on latest version, separated of can-potions. Update available soon.
