### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by JHost-iso** [FabioZumbi12/RedProtect#131]
why protected areas are not working NPCs?

**Comment by JHost-iso** [comment]
https://pp.vk.me/c837539/v837539895/20c99/Wa-GJabgIGk.jpg

**Comment by FabioZumbi12** [comment]
Read the wiki!

If you are not member of a region and the flag "passives" is "false", the player cant interact with NPCs.

**Comment by JHost-iso** [comment]
but  passives=true

what could be the problem?

**Comment by FabioZumbi12** [comment]
To reproduce this:

If you are not admin or leader of region:
- Cant interact!
If you are the leader or admin of region:
- Use /rp flag
- Click on passives icon to enable;
- Now non members will be allowed to interact.

If theres no rp where the NPC is, enable "interact" on "globalflags.yml"
Read more on globalflags!

If you are having errors, paste the logs here.

**Comment by JHost-iso** [comment]
https://pp.vk.me/c837539/v837539895/20ca3/oxTkCRtCGGo.jpg

NPC is still not working
mods custom npc

**Comment by JHost-iso** [comment]
no error, but it does not work, I'll be your documentation for memory will know

**Comment by FabioZumbi12** [comment]
Man, you need specify the server version as mods you are trying to use with redprotect '-'

Here is for Bukkit/Spigot issues.

Btw, enable the flag **/rp flag allow-mods true** to allow players interact with mod entity on regions.

For more, use the issue tracker on RedProtect-Sponge version: https://github.com/FabioZumbi12/Sponge-Redprotect

**Comment by JHost-iso** [comment]
Спасибо большое! /rp flag allow-mods true решило проблему.
