### ISSUE TITLE
Add leaf-decay flag

### ISSUE THREAD

**Issue by Klonkcraft** [FabioZumbi12/RedProtect#134]

**Comment by CloudeLecaw** [comment]
what should this flag be able to do...
decay leafs completly if a woodtree is destoid?
If so, a replant flag - true/false with a setup timer also would be needed, to allow replanting of the tree too... some treefarmerplugins do this.. so many ideas here... decay, replant, adition drops, change for it, woodcutter...

**Comment by CloudeLecaw** [comment]
leav decay is handel by the flow flag.

Please close this issues-suggestion :)
