### ISSUE TITLE
Suggestion: default command on Entry and Leave

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#135]
A command on entry and Leave in the config that counts for all regions like the message on entry/wilderness would be nice.

Why?
That way Fabio Should not design millions things that happens on entry and leave or wilderness,
Also Owner could use their own Plugins for Showing The Regionname in a Bossbar,Actionbar,titlebar or what ever.
say someting nice, announce a bit, an acctionbarmmeassge what ever , there would be a few varrriants
Recommand placholder maybe the Playername, the Regionowners and the Regionname
It should be able to setup NONE for disabling it.

Special Region allready can have commands like that :3 with the flag if special once needed

**Comment by FabioZumbi12** [comment]
You can set the default value on config, like other flags. I only cant confirm if works for non true/false flags.
