### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by JHost-iso** [FabioZumbi12/RedProtect#137]
I can not figure out how to configure the plug-in version RedProtect-Sponge-6.5.1-b220 version games 1.10.2

**Comment by FabioZumbi12** [comment]
I cannot configure to you or cant help if you dont give specific info about your problem.

if is only configuration issue, read the Sponge topic to help you, and update to latest versions: https://forums.spongepowered.org/t/shield-anti-grief-with-flag-gui-redprotect-1-8-9-1-11/11846
