### ISSUE TITLE
Conflict with other plugin!

### ISSUE THREAD

**Issue by DeeCaaD** [FabioZumbi12/RedProtect#139]
Hello,

seems like RedProtect conflicts with my plugin SurvivalMechanics. One of SurvivalMechanics buyers told me this, [here](https://www.youtube.com/watch?v=6KPZDnQKjxc) is also video he/she sent me to verify that RedProtect is causing it.

What could be causing this? What does RedProtect do in gliding event?

https://www.youtube.com/watch?v=6KPZDnQKjxc

- DeeCaaD

**Comment by DeeCaaD** [comment]
Found this:
`    @EventHandler
	public void onPlayerMove(PlayerMoveEvent e) {
    	Player p = e.getPlayer();
    	
    	//set velocities
    	if (!p.hasPermission("redprotect.bypass.velocity")){
    		if (RPConfig.getGlobalFlagFloat(p.getWorld().getName()+".player-velocity.walk-speed") >= 0){
        		p.setWalkSpeed(RPConfig.getGlobalFlagFloat(p.getWorld().getName()+".player-velocity.walk-speed"));
        	}
        	if (RPConfig.getGlobalFlagFloat(p.getWorld().getName()+".player-velocity.fly-speed") >= 0){
        		p.setFlySpeed(RPConfig.getGlobalFlagFloat(p.getWorld().getName()+".player-velocity.fly-speed"));
        	}
    	}
    	
    	if (RedProtect.version >= 191){    		
    		if (!RPConfig.getGlobalFlagBool(p.getWorld().getName()+".elytra.allow")){
    			ItemStack item = p.getInventory().getChestplate();
    			if (item != null && item.getType().equals(Material.ELYTRA)){
    				PlayerInventory inv = p.getInventory();
    				inv.setChestplate(new ItemStack(Material.AIR));
    				if (inv.firstEmpty() == -1){
    					p.getWorld().dropItem(p.getLocation(), item);
    				} else {
    					inv.setItem(inv.firstEmpty(),item);
    				}    				
    				p.playSound(p.getLocation(), Sound.ENTITY_ITEM_PICKUP, 10, 1);
    				RPLang.sendMessage(p, "globallistener.elytra.cantequip");
    				return;
    			}
    		}
    		    		 		    		
    		if (p.isGliding() && RPConfig.getGlobalFlagBool(p.getWorld().getName()+".elytra.allow")){
    			Vector vec = new Vector(0.0D, p.getLocation().getDirection().getY(), 0.0D);
                p.setVelocity(p.getVelocity().add(vec.multiply(0.1D*RPConfig.getGlobalFlagDouble(p.getWorld().getName()+".elytra.boost")/2)));
    		}
    	}    	
}`

Ill just tell user to put that world.elytra.allow boolean to false.

**Comment by DeeCaaD** [comment]
Also thats kinda stupid when you can either disable elytra or make gliding have its own speeds. Those speeds should be optional.

**Comment by FabioZumbi12** [comment]
Its not stupid until we have no issues '-' Whats your problem?

Btw, this version can solve this: https://www.spigotmc.org/resources/redprotect-for-all-versions-anti-grief-server-protection.15841/update?update=146200

Simple and not stupid, like your comment ;)
