### ISSUE TITLE
suggestion "cant leave flag" - jails falg

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#140]
currently u have to create 2 regions.
a reagion arrounf a reagion... where the entern gis not allowed.

An Adminflag would be nice to have:
i found something simliar in a plugin called iZone: The Flag is called:
JAIL and descriped with "Can't get out of it "

So an adminflag jail (that is false by default) would be cool.
even if the flag is true, the player should be able to get teleported out.
thisway you could ealy designed protected zones where only one way is out (a teleporter or something simliar :) )

So pls, add this "jail" flag =)

**Comment by FabioZumbi12** [comment]
I ll se possibility fo add this flag.

**Comment by FabioZumbi12** [comment]
Added on latest dev build!
