### ISSUE TITLE
Errors at console

### ISSUE THREAD

**Issue by LeftBoy** [FabioZumbi12/RedProtect#142]
Hello! I have a problem.
Every second in my console writes only one same error. It very much distract, I except this error see nothing, even a chat of players because it quickly disappears after a error. I request you to fix as soon as possible it, very much distract!
Copy of error: http://pastebin.com/DT02Tia1
My RPalm is latest version for SpongeForge.

**Comment by FabioZumbi12** [comment]
This is not Spigot/Bukkit version. Post Sponge issues here https://github.com/FabioZumbi12/Sponge-Redprotect/issues
