### ISSUE TITLE
MySQL - leaders disappear

### ISSUE THREAD

**Issue by krzxsiek** [FabioZumbi12/RedProtect#143]
Hello, 
I have problem. [Spigot 1.11.2 / RedProtect-7.1.2-b308 via MySQL]
When I use "/rp addleader <player>" leaders disappear from the database
When I use "/rp addmember <player>" members overwrite leaders from the database

Any suggestions?

**Comment by FabioZumbi12** [comment]
Sorry, a mistake from my part, i uploading a fix for this!

**Comment by krzxsiek** [comment]
> admins

Thanks! :) I have another problem, but that's to developers "dynmap" plugin.
https://github.com/webbukkit/dynmap/issues/2066

**Comment by krzxsiek** [comment]
/rp addleader 
/rp addmember
/rp addadmin
is OK

but this NOT :(
/rp removeleader - (i have 2 leaders) not remove

/rp addleader - add another leader from member replace second leader

Sorry for my english. I hope you understand :)

**Comment by xVANKO95** [comment]
I can confirm this bug - something is wrong with MySQL Database Engine included in this plugin. @FabioZumbi12 - please check this out and create a fix for it. 
I would be very grateful for this.

**Comment by FabioZumbi12** [comment]
Ok, lets check!

**Comment by xVANKO95** [comment]
works like a charm - thanks

**Comment by krzxsiek** [comment]
True, works good :) Thanks! :) Continue testing
