### ISSUE TITLE
Problem with SQL queries

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#144]
On our server we wanted to pass our RedProtect claims from yml files to mysql (through the command /rp ymlToMysql in the console) but there is a problem, here is the most important part of this error who spam the console:

28.02 01:15:39 [Server] WARN com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; Check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Baen en vu! ',' 0 ',' world_overworld2 ',' 0 ',' ',' can-grow: true, door: false, allo 'at line 1

The basic message: welcome: 'Capitaine ! &2Uru''Baen en vu ! '

28.02 01:15:39 [Server] WARN com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; Check the manual that corresponds to your MariaDB server version for the right syntax to use near 'espace Judge "For events. ',' 3 ',' world_overworld2 ',' 0 ',' ',' can-grow: tr 'at line 1

The basic message: 'Bienvenue dans l''espace "Juge" Pour les events. '

The problem comes from quotes that are not escaped.

PS: I think that this documentation can help you on this subject: http://docs.oracle.com/javase/tutorial/jdbc/basics/prepared.html

**Comment by FabioZumbi12** [comment]
Paste the whole error log to i see where in my code is the problem. RedProtect for Spigot/Bukkit already uses preparedStatements: https://github.com/FabioZumbi12/RedProtect/blob/master/src/main/java/br/net/fabiozumbi12/RedProtect/WorldMySQLRegionManager.java#L61

**Comment by zedentox** [comment]
@FabioZumbi12 yes but... it doesn't use them correctly...

A correct way is :
```java
PreparedStatement ps = con.prepareStatement("
    INSERT INTO mytable(field1, field2, field3) 
    VALUES (?, ?, ?)
");
ps.setInt(1, 42);
ps.setString(2, "Anything you want");
ps.setString(3, "Even with 'quotes' !");
ps.executeUpdate();
```
Actually it uses : 
```java
PreparedStatement ps = con.prepareStatement("
    INSERT INTO mytable(field1, field2, field3) 
    VALUES (42, 'Anything you want', 'Event with 'quotes' !')
");
ps.executeUpdate();
```

**Comment by FabioZumbi12** [comment]
Thanks. I changed to this way ^^ I am not familiar with Mysql :P

Try this version: https://discord.gg/RyEVJC3
And plugin, check the note about experimental performance improvement.

**Comment by aurel85** [comment]
With build 329 everything is ok for the different problems with sql.
