### ISSUE TITLE
No Elytraboost.

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#145]
Since 1.11.2 u can boost in "vanilla" the Elytra flight with clean rockets.
i wanne disable this boosting.
is this possible with redprotect for the global area (maybe a flag? :) )

i dont wanne forbit the useage of clean rockets as firework itself 🥉 

Any ideas? 🥉 

Current Settings are these:
  elytra:
    allow: true
    boost: -1.0

**Comment by FabioZumbi12** [comment]
Theres no flag to deny elytra boost. Seeting to "zero" or negative values will disable boost.

**Comment by CloudeLecaw** [comment]
ohw 🥉 
so i just can disallow the elyra 🥉 

Is it possible that elytra got uneqipted when he enter a zone where elytra is not allowed?
and TPs on the next save TOP-Block on the buttom? (to prevent he falls down when he enter the region while flying elytra)
