### ISSUE TITLE
Dynmap Markers doesn't work if mysql is set

### ISSUE THREAD

**Issue by krzxsiek** [FabioZumbi12/RedProtect#146]
Dynmap 2.3 and 2.4 does not show regions markers if RedProtect settings to mysql.
You can fix it? :)

**Comment by bbruno5** [comment]
What's the problem that you can see on log?
Maybe you can solve this adding this line in mysql settings on config.yml: useSSL: false

This works for me on some plugins that's necessary. Not exactly this. :)

**Comment by FabioZumbi12** [comment]
The problem still? Reopen if yes.
