### ISSUE TITLE
ForceFly

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#147]
When u enter a Region as PLAYER and the flag ForceFly is enabled
then the player is allow to fly, so long all is ok..

but when u just stand on the floor in Survivalmode in this region (gm0)
then this flag "zooms" the Screens for a little movement.
zoom in zoom out - its like a little shaking of the screen every few secounds.

If your admin then u bypass the forcefly flag and then your not settet to flymode...so the screen is not "shaking"...

To Reproduce this:
1. create(define) a region (define it, so the server is the owner of this region)
2. set forcefly flag to true
3. make yourself player in survival mode (and make sure u have no bypasspass permissions)
4. enter the region
5. stand a bit somewhere on the buttom (not in the air)
....- after a few secound u see the screen "shaking" like a little zoom in, zzom out..
...this repeats everyer few secounds..

Is there a way to fix this? :3

**Comment by FabioZumbi12** [comment]
> About your issue, this is a minecraft/essentials issue
> that "zoom" on screen
> redprotect only enable/disable the player's fly
