### ISSUE TITLE
[Suggestion] Access to settp and deltp

### ISSUE THREAD

**Issue by NicolasDelahaigue** [FabioZumbi12/RedProtect#149]
By default commands settp and deltp are available only for admin but if we add the permission to users in plugin.yml (`redprotect.own.settp: true` and `redprotect.own.deltp: true`) there is a problem. All player can change their own claims tp point (normal) and the tp point of the other players's claims (problem).

Suggestion :
Add RedProtect.ph.hasRegionPermLeader verification
http://pastebin.com/buXn808V

**Comment by FabioZumbi12** [comment]
Cool ^^ added this (with some changes). Will be on next update.

**Comment by CloudeLecaw** [comment]
This Feature Fabio added with Buld 319.
Only the Owner of a Region can settp anymore 🥉 
i hope Fabio didnt forgot the deltp *g*..pls Test it ;)

Download the Latest Build - 325 pls *g*
https://cdn.discordapp.com/attachments/215573884940976148/288584715324227584/RedProtect-7.1.2-b325.jar

**Comment by aurel85** [comment]
Hey,

With the Build 329 everything is ok. Only claim owners can /rp settp and /rp deltp once they have permission.

**Comment by CloudeLecaw** [comment]
solved since 7 days - So please close it :)
