### ISSUE TITLE
Suggestion : Possibility for remove the 3 seconds during the tp by /rp list

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#153]
Hi,

A player has a waiting time of 3 seconds when he wants to be tp by the /rp list, I look in the config to remove this waiting time but I have not found. Would it be possible to add something to disable it ?

**Comment by CloudeLecaw** [comment]
Maybe you have a plugin that is cooldown/warmup your tps?
Why i ask...
i tested it on my server and the normal player had no warmup on clicking on his region on /rp list
the regionwas directly shown and they was able to click it imidatly without waiting time.
So i just can imagine that some of your plugins may insert a waiing time" if they click.. it

**Comment by FabioZumbi12** [comment]
The cloud explanation its ok with your needs @aurel85 ?

**Comment by aurel85** [comment]
Not quite because with the redprotect.admin.teleport permission, they can also do /rp tp claimexemple, no matter who it belongs to and it bothers me for my server.

The best would be what @CloudeLecaw  has proposed: to add in the configuration the possibility of modifying the waiting time before the teleportation and thus being able to put 0 as 10.

After that, it's really a secondary element, but it would be a good addition.

**Comment by FabioZumbi12** [comment]
I ll add the option on config.

**Comment by FabioZumbi12** [comment]
Added on https://github.com/FabioZumbi12/RedProtect/commit/154eedd5f7b49461442af31891b0400e0b2fb70f
