### ISSUE TITLE
Worldflag for item drop, pickup

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#154]
the region itself allready allowed blocking of droping and pickup of items

If u try to use these flag as global flag to block it for a whole world, or allow it only for speciffic regions, then this will not work :(

so i suggest the creation of global flags of these cool allready existing region flags :)
Pls make them be allowed in globalflag too if wanted

**Comment by FabioZumbi12** [comment]
Fixed, try the dev version: https://discord.gg/RyEVJC3
