### ISSUE TITLE
flag allow-break redstone_ore doesn't work

### ISSUE THREAD

**Issue by krzxsiek** [FabioZumbi12/RedProtect#155]
Hi, i have add flag to region "Mine" (priority: 1) inside region "Spawn_Area" (priority: 0): 
/rp flag allow-break REDSTONE_ORE

Still can not destroy redstone ores.
He tells me "You can't toggle this lever here!" when when I try to destroy REDSTONE_ORE

Region "Mine" have also flag
/rp flag minefarm true

Region "Spawn_Area" and "Mine" set flag use lever false (when true I can destroy)

Please help, sorry for my English :)

**Comment by FabioZumbi12** [comment]
lol
I will fix this on next version :P

**Comment by FabioZumbi12** [comment]
Fixed: https://discord.gg/RyEVJC3
