### ISSUE TITLE
Problem with the iceform-world flag

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#156]
Hey,

With the b311 version (the problem is always present on the b330) when someone puts the iceform-world flag on false the ice still appears in the snow biomes.

I use PaperSpigot

**Comment by CloudeLecaw** [comment]
i thought this is normal..because its not made by an Entity.... 🥉 

Should it be like this? i just renember the iceform-world was iceform-entity before...

the global flags are:
  iceform-by:
    player: true/false
    world: true/false

The region flags are:
  iceform-player: true/false
  iceform-world: true/false

**Comment by aurel85** [comment]
Even by having both on false the ice appears anyway even though before I no longer know what flag prevented the ice from appearing when it was on false. I do not know if this is really a bug but it is a pity that we can no longer prevent the ice from appearing in its claim.

**Comment by CloudeLecaw** [comment]
Try newest jenkins :)
http://158.69.121.149:8080/job/RedProtect/5/

This build has version number 340
The Problem was solved with build  338 allready:)

**Comment by aurel85** [comment]
With version 341 everything works well, thank you !
