### ISSUE TITLE
CustomNPC and RedProtect are not liking eachothers company it seems

### ISSUE THREAD

**Issue by NineDivinez** [FabioZumbi12/RedProtect#157]
--> Click on PREVIEW tab!

## Fill all info below to help us to find the problem are you having or with your suggestion:

_Put if is the **Spigot** or **Sponge** version._
Plataform:  
Sponge

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._
Jar version:  
RedProtect-Sponge-7.0.0-b3.jar

_Your server Minecraft version_
Minecraft version:  
1.10.2

_Issue or Suggestion?_
What you want?:  
issue?

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  
I'm using this with a mod called customnpc.  I have defined my spawn, and created a bunch of npcs, but when I went to make sure that regular users could still interact with everything, the message "[RepProtect} You can't interact with this here!" appears.  I'm not using any permission mods, but it seems to only happen in the spawn.  I tried spawning one outside the spawn's defined area and was able to interact with them just fine, but I'm guessing it does have something to do with that.  If you could give me help or assistance of any kind, it would be greatly appreciated.

**Comment by FabioZumbi12** [comment]
You only need to add the flag "/rp flag allow-mods true" to allow players interact with mod entities and machines, or the flag passives.

**Comment by NineDivinez** [comment]
That doesn't seem to work. I don't see it listed in the help command either.

**Comment by FabioZumbi12** [comment]
Is not a command, its a flag use to allow players interact with mods on public locations. Btw, download the latest version 7.1.3 from here: http://158.69.121.149:8080/job/RedProtect/

**Comment by NineDivinez** [comment]
Ok... I guess I'm confused as to how to use flags then.  Where am I supposed to put this?

**Comment by FabioZumbi12** [comment]
This is a command, use "/rp flag allow-mods true" inside your spawn region.

**Comment by NineDivinez** [comment]
And I'm getting an error because I'm not updated to the latest?

**Comment by FabioZumbi12** [comment]
Maybe... try to update. The latest its a dev build.

**Comment by NineDivinez** [comment]
Alright, giving it a try.  Thanks for working with me, I'll let you know if it works :)

**Comment by NineDivinez** [comment]
It seems as though it's not loading now.

**Comment by NineDivinez** [comment]
Oh I see now, the link you gave me was for spiggot.  Unless I'm just missing something on the page.

**Comment by FabioZumbi12** [comment]
No, the server versions is on the jar names.

**Comment by NineDivinez** [comment]
I'm sorry, what?

**Comment by FabioZumbi12** [comment]
The Sponge versions: http://prntscr.com/ep7ien

**Comment by NineDivinez** [comment]
Well I can talk to npcs now, but can't open chests, but that's ok.  I'm not really needing that.  Thanks for all the help!

**Comment by FabioZumbi12** [comment]
Use other flag with command "/rp flag" to allow players interact with other blocks.

**Comment by NineDivinez** [comment]
Yea, I have that set, but it doesn't like certain items it seems.
