### ISSUE TITLE
Suggestion: Add members to a region via Console/Command Block

### ISSUE THREAD

**Issue by TT702** [FabioZumbi12/RedProtect#159]
Plataform:  **Sponge**

Jar version:  **RedProtect-Sponge-6.0.0-7.1.4-b94.jar**

Minecraft version:  1.10.2

What you want?:  Add the members to region via Console/Command Block

Description:  Hi there! Is it possible to add the optional args to "/rp addmember" like "/rp addmember [player] [**regionName**]" ?
it will be easier to use the Console or the Command Block to add player to the region. :D

**Comment by FabioZumbi12** [comment]
Will be added.

**Comment by FabioZumbi12** [comment]
After a long time... added on latest dev build.
