### ISSUE TITLE
button and lever flags doesn't work

### ISSUE THREAD

**Issue by Faryzal2020** [FabioZumbi12/RedProtect#161]
Platform:  SpongeForge 5.2.0 BETA 2254
Jar version:  RedProtect-Sponge-7.0.0-b3.jar
Minecraft version:  1.10.2

I made a spawn region with #server# or the default owner as the owner, i've turned on the button and lever flags from the config but everyone without the redprotect.* permission can't interact with button and lever.
the players have redprotect.user and redprotect.flag.all permissions.
i'm using LuckPerms-Sponge-3.0.83

also why there is no build flag for spesific region instead of global ?

**Comment by FabioZumbi12** [comment]
Maybe I ll add a build flag. Try the latest jenkins version if its not fixed.
