### ISSUE TITLE
MySQL Data Not Sanitized.

### ISSUE THREAD

**Issue by Tenelia** [FabioZumbi12/RedProtect#162]
--> Click on PREVIEW tab!

## Fill all info below to help us to find the problem are you having or with your suggestion:

_Put if is the **Spigot** or **Sponge** version._
Plataform:  Sponge

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._
Jar version:  7.0.0 b3

_Your server Minecraft version_
Minecraft version:  1.11.2

_Issue or Suggestion?_
What you want?:  MySQL Data Not Sanitized.

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  

> 
> [01:05:53 ERROR] [STDERR]: java.sql.SQLSyntaxErrorException: (conn:1755) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1' at line 1
> Query is : CREATE DATABASE redprotect_DIM-1
> [01:05:53 ERROR] [STDERR]: at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:134)
> [01:05:53 ERROR] [STDERR]: at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101)
> [01:05:53 ERROR] [STDERR]: at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77)
> [01:05:53 ERROR] [STDERR]: at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:224)
> [01:05:53 ERROR] [STDERR]: at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:258)
> [01:05:53 ERROR] [STDERR]: at org.mariadb.jdbc.MariaDbStatement.executeUpdate(MariaDbStatement.java:387)
> [01:05:53 ERROR] [STDERR]: at br.net.fabiozumbi12.redprotect.WorldMySQLRegionManager.(WorldMySQLRegionManager.java:54)
> [01:05:53 ERROR] [STDERR]: at br.net.fabiozumbi12.redprotect.RegionManager.loadAll(RegionManager.java:32)
> [01:05:53 ERROR] [STDERR]: at br.net.fabiozumbi12.redprotect.RedProtect.onServerStart(RedProtect.java:88)
> [01:05:53 ERROR] [STDERR]: at org.spongepowered.common.event.listener.GameStartedServerEventListener_RedProtect_onServerStart64.handle(Unknown Source)
> [01:05:53 ERROR] [STDERR]: at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
> [01:05:53 ERROR] [STDERR]: at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:305)
> [01:05:53 ERROR] [STDERR]: at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:319)
> [01:05:53 ERROR] [STDERR]: at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:323)
> [01:05:53 ERROR] [STDERR]: at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:188)
> [01:05:53 ERROR] [STDERR]: at org.spongepowered.server.SpongeVanilla.onServerStarting(SpongeVanilla.java:166)
> [01:05:53 ERROR] [STDERR]: at net.minecraft.server.dedicated.DedicatedServer.handler$callServerStarting$zob000(SourceFile:1249)
> [01:05:53 ERROR] [STDERR]: at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:229)
> [01:05:53 ERROR] [STDERR]: at net.minecraft.server.MinecraftServer.run(SourceFile:436)
> [01:05:53 ERROR] [STDERR]: at java.lang.Thread.run(Unknown Source)
> [01:05:53 ERROR] [STDERR]: Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1' at line 1
> Query is : CREATE DATABASE redprotect_DIM-1
> [01:05:53 ERROR] [STDERR]: at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1114)
> [01:05:53 ERROR] [STDERR]: at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:137)
> [01:05:53 ERROR] [STDERR]: at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:249)

**Comment by FabioZumbi12** [comment]
Update to latest: https://www.spigotmc.org/resources/redprotect-for-all-versions-anti-grief-server-protection.15841/

We are on 7.1.4

**Comment by Tenelia** [comment]
Issue still exists on 7.1.4.

> [10:17:22 ERROR] [STDERR]: java.sql.SQLSyntaxErrorException: (conn:2474) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1 (name varchar(20) PRIMARY KEY NOT NULL, leaders varchar(36), admins longtext,' at line 1
> Query is: CREATE TABLE nullDIM-1 (name varchar(20) PRIMARY KEY NOT NULL, leaders varchar(36), admins longtext, members longtext, maxMbrX int, minMbrX int, maxMbrZ int, minMbrZ int, centerX int, centerZ int, minY int, maxY int, date varchar(10), wel longtext, prior int, world varchar(16), value Long not null, tppoint mediumtext, rent longtext, flags longtext, candelete tinyint(1)) CHARACTER SET utf8 COLLATE utf8_general_ci
> [10:17:22 ERROR] [STDERR]:      at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:134)
> [10:17:22 ERROR] [STDERR]:      at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101)
> [10:17:22 ERROR] [STDERR]:      at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77)
> [10:17:22 ERROR] [STDERR]:      at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:224)
> [10:17:22 ERROR] [STDERR]:      at org.mariadb.jdbc.MariaDbClientPreparedStatement.executeInternal(MariaDbClientPreparedStatement.java:239)
> [10:17:22 ERROR] [STDERR]:      at org.mariadb.jdbc.MariaDbClientPreparedStatement.executeUpdate(MariaDbClientPreparedStatement.java:198)
> [10:17:22 ERROR] [STDERR]:      at br.net.fabiozumbi12.redprotect.WorldMySQLRegionManager.<init>(WorldMySQLRegionManager.java:58)
> [10:17:22 ERROR] [STDERR]:      at br.net.fabiozumbi12.redprotect.RegionManager.load(RegionManager.java:40)
> [10:17:22 ERROR] [STDERR]:      at br.net.fabiozumbi12.redprotect.RegionManager.loadAll(RegionManager.java:30)
> [10:17:22 ERROR] [STDERR]:      at br.net.fabiozumbi12.redprotect.RedProtect.loadRegions(RedProtect.java:109)
> [10:17:22 ERROR] [STDERR]:      at br.net.fabiozumbi12.redprotect.RedProtect.onServerStart(RedProtect.java:94)
> [10:17:22 ERROR] [STDERR]:      at org.spongepowered.common.event.listener.GameStartedServerEventListener_RedProtect_onServerStart65.handle(Unknown Source)
> [10:17:22 ERROR] [STDERR]:      at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
> [10:17:22 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:305)
> [10:17:22 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:319)
> [10:17:22 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:323)
> [10:17:22 ERROR] [STDERR]:      at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:188)
> [10:17:22 ERROR] [STDERR]:      at org.spongepowered.server.SpongeVanilla.onServerStarting(SpongeVanilla.java:166)
> [10:17:22 ERROR] [STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.handler$callServerStarting$zob000(SourceFile:1249)
> [10:17:22 ERROR] [STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:229)
> [10:17:22 ERROR] [STDERR]:      at net.minecraft.server.MinecraftServer.run(SourceFile:436)
> [10:17:22 ERROR] [STDERR]:      at java.lang.Thread.run(Unknown Source)
> [10:17:22 ERROR] [STDERR]: Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1 (name varchar(20) PRIMARY KEY NOT NULL, leaders varchar(36), admins longtext,' at line 1
> Query is: CREATE TABLE nullDIM-1 (name varchar(20) PRIMARY KEY NOT NULL, leaders varchar(36), admins longtext, members longtext, maxMbrX int, minMbrX int, maxMbrZ int, minMbrZ int, centerX int, centerZ int, minY int, maxY int, date varchar(10), wel longtext, prior int, world varchar(16), value Long not null, tppoint mediumtext, rent longtext, flags longtext, candelete tinyint(1)) CHARACTER SET utf8 COLLATE utf8_general_ci
> [10:17:22 ERROR] [STDERR]:      at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1114)
> [10:17:22 ERROR] [STDERR]:      at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:172)
> [10:17:22 ERROR] [STDERR]:      at org.mariadb.jdbc.MariaDbClientPreparedStatement.executeInternal(MariaDbClientPreparedStatement.java:230)
> [10:17:22 ERROR] [STDERR]:      ... 17 more

**Comment by FabioZumbi12** [comment]
You need to remove(or backup) all data from mysql before update to this.

**Comment by FabioZumbi12** [comment]
Fixed?

**Comment by Tenelia** [comment]
Nope.

**Comment by FabioZumbi12** [comment]
What jar version? (Copy the jar name)

**Comment by Tenelia** [comment]
RedProtect-Sponge-6.0.0-7.1.4-b103

**Comment by FabioZumbi12** [comment]
You need to remove all redprotect from your DB to update or use RedProtect from 7.0.0 to +7.1.x

**Comment by Tenelia** [comment]
I tried using 7.1.0 and got:


[08:40:15 ERROR] [Sponge]: No valid plugins found in mods\RedProtect-Spigot-7.1.4-b370.jar. Is the file actually a plugin JAR? Please keep in mind Forge mods can be only loaded on SpongeForge servers, SpongeVanilla supports only Sponge plugins.

**Comment by FabioZumbi12** [comment]
You downloaded Spigot version '-' See the jar name.

**Comment by Tenelia** [comment]
>_>" Was about to say that. My bad ><"

**Comment by Tenelia** [comment]
Update: I removed everything. 

[08:59:29 ERROR] [STDERR]: java.sql.SQLSyntaxErrorException: (conn:396) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1 (name varchar(20) PRIMARY KEY NOT NULL, leaders varchar(36), admins longtext,' at line 1

**Comment by Tenelia** [comment]
Okay this is weird. The error disappeared after I ran it the second time.
