### ISSUE TITLE
Suggestion : Flag can-grow

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#163]
Hi,

_Suggestion
PaperSpigot 1.11.2
RedProtect 7.1.4 b367
Minecraft 1.11.2_

Would it be possible that in the can-grow flag the propagation of mushrooms and vines would be taken into account by this flag ?

**Comment by FabioZumbi12** [comment]
Flag added.

**Comment by aurel85** [comment]
It's ok, thank you !

**Comment by aurel85** [comment]
It's ok, thank you !
