### ISSUE TITLE
not enough money when buying

### ISSUE THREAD

**Issue by L31H4** [FabioZumbi12/RedProtect#164]
Plataform:  SpongeForge (Sponge-build 2004, Forge-build 2195)

Jar version:  7.0.0-b3

Minecraft version:  1.11

What you want?:  Issue

Description:  
Hi, I really like your plugin, but I have some trouble with the selling-system. When I put a region for sale, everyone who is trying to buy the region gets the message "You don´t have enough Money", doesnt matter how much he has. As admin I´m not able to cancel the selling or put someone as leader of the region.
I´m using EconomyLite, maybe they don´t work together?

**Comment by bbruno5** [comment]
You tried to set /rp value before sell the RP? I think that without it, isn't possible to buy without error.
