### ISSUE TITLE
Plugin doesn´t load

### ISSUE THREAD

**Issue by SirLuckey** [FabioZumbi12/RedProtect#165]
--> Click on PREVIEW tab!

## Fill all info below to help us to find the problem are you having or with your suggestion:

_Put if is the **Spigot** or **Sponge** version._
Platform: Spigot

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._
Jar version:    RedProtect-Spigot-7.1.4-b370.jar

_Your server Minecraft version_
Minecraft version:  1.11.2

_Issue or Suggestion?_
What you want?:  help to solve the Issue

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  The Plugin doesn´t load at server start

**Comment by aurel85** [comment]
Hi,

It would be necessary to give your start logs if not it will be difficult to help you...
And also try with the latest version of the plugin : http://158.69.121.149:8080/job/RedProtect/

**Comment by SirLuckey** [comment]
I´ve just restartet the server and copied the log, but it is too big for hastebin, do you have any other ideas I can upload the restart.log?
