### ISSUE TITLE
Suggestion : A single flag for decay

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#166]
Hi,

_Suggestion
PaperSpigot 1.11.2
RedProtect 7.1.4 b367
Minecraft 1.11.2_

Would it be possible that there is a flag only for the decay of the leaves ? Because putting it with flag "flow" disturbs some players in their projects.

**Comment by FabioZumbi12** [comment]
Flag added.

**Comment by aurel85** [comment]
It's ok, thank you !
