### ISSUE TITLE
Suggestion : Redstone beetween 2 claims

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#167]
Hi,

_Suggestion
PaperSpigot 1.11.2
RedProtect 7.1.4 b367
Minecraft 1.11.2_

A redstone system that is on 2 different claims (of the same owner) does not work. I understand why it is like this but would it be possible that between claims of the same person they can function anyway ? (It's the same with water currents).

**Comment by FabioZumbi12** [comment]
Maybe yes. I ll check this.

**Comment by FabioZumbi12** [comment]
Added a check for this on latest version, please test.

**Comment by aurel85** [comment]
It already works on my server while I run with the b402 version so everything is ok ^^
