### ISSUE TITLE
Issue / Suggestion : Flag to melt ice and snow

### ISSUE THREAD

**Issue by NicolasDelahaigue** [FabioZumbi12/RedProtect#168]
PaperSpigot 1.11.2
RedProtect 7.1.4 b367
Minecraft 1.11.2

Hello,

[Bug]
I saw there is a similar issue closed about this subject #65 but the proposed solutions don't work, neither flag fire nor flow 

Does a flag exist to stop the melting of ice and snow ? Or maybe it worked before but something broke in the latest versions ?

[Suggestion] 
If it doesn't exist is it possible to create a flag for this task ?

Thanks

**Comment by FabioZumbi12** [comment]
Flag added.

**Comment by NicolasDelahaigue** [comment]
Which name of flag did you add ? or to which flag did you link your modificaions ?
Because I tried like the last time all combinaisons of flags "iceform-world", "iceform-player", "flow-damage" and "fire" but none works.

**Comment by FabioZumbi12** [comment]
Here: https://github.com/FabioZumbi12/RedProtect/wiki/(5)-Region-Flags#iceform-player

You need to enable and add a default value on config, and give the permission too.

**Comment by NicolasDelahaigue** [comment]
The flag is already enable, have a default value and the player have the merission too. And it still don't work.

**Comment by FabioZumbi12** [comment]
Using the latest RedProtect version?

**Comment by aurel85** [comment]
Yes, 7.2.0 b398

**Comment by FabioZumbi12** [comment]
Reproducing on my test server is working fine, ice cant melt if this flag is false.

**Comment by aurel85** [comment]
When I put a torch next to the ice and snow it melts even if the flag of the ice are on false. Whether it is generated naturally or posited by me it ends up melting nevertheless.

I use b419.

**Comment by FabioZumbi12** [comment]
Seems is fixed (on my server its). If no, reopen.
