### ISSUE TITLE
Hi..It‘s new problem now！PVP flag was not effect.

### ISSUE THREAD

**Issue by SmithJiong** [FabioZumbi12/RedProtect#17]
So it's Kcauldron again... I have tried some versions like Kcauldron 1614.108 and 1614.184 and so on,the player can pvp in the region whether the region’s pvp flag is true or false.

I think it's Kcauldron‘s erro possibly cause It is the same situation when i use worldguard.

so i just report this erro for you..and Kcauldron's author...

PS:No erro message
PPS:why did it  defined region so slowy when i use mysql database.....

**Comment by FabioZumbi12** [comment]
Thanks to report! Can you post here the KCauldron report you have openned to i follow too?

**Comment by SmithJiong** [comment]
well....It's may be the incompatibility between TFC mod and Kcauldron's Vanilla Damage...
https://gitlab.prok.pw/KCauldron/KCauldron/issues/340

**Comment by FabioZumbi12** [comment]
Well, since the bug is not with RP, wait the KCauldron fix the issue. O have noticed a new fork of cauldron called Thernos, try this too.
