### ISSUE TITLE
Admin flags don't saving on MySQL

### ISSUE THREAD

**Issue by bbruno5** [FabioZumbi12/RedProtect#173]
Plataform:  Spigot

Jar version:  RedProtect-Spigot-7.1.4-b354.jar

Minecraft version:  1.11.2

Description:  I'm OP, have all existing perms. When I trying to change any admin flags, everything seems to work, however the flags aren't saved to MySQL and changes don't occur. I tested the flags allow-place, allow-break, max-players, minefarm.
However, if I put the flags directly on correct table on MySQL and try /rp reload, the changes works fine. Any suggestion?

**Comment by FabioZumbi12** [comment]
Have you tryed the latest dev builds: http://areaz12server.net.br:8080/job/RedProtect/

Are you on spectator mode?

**Comment by bbruno5** [comment]
No, I'm on creative mode.
I'll try that latest version now and tell you if it works.

**Comment by bbruno5** [comment]
I tried, with last version, but the problem persists. Below I'm leaving prints from command logs and respective table on MySQL, after try the commands

**Comment by bbruno5** [comment]
I tried, with last version, but the problem persists. Below I'm leaving prints from command logs and respective table on MySQL, after try the commands.

![2017-06-01_20 41 09](https://cloud.githubusercontent.com/assets/23748196/26705292/ab20c11e-470b-11e7-9e3b-261fd495e0dc.png)
![2017-06-01_20 41 50](https://cloud.githubusercontent.com/assets/23748196/26705291/ab2051e8-470b-11e7-98c1-80c2e48533f1.png)
![2017-06-01_20 42 12](https://cloud.githubusercontent.com/assets/23748196/26705295/ab2395ba-470b-11e7-8a2f-fa287e4c28e3.png)
![2017-06-01_20 42 28](https://cloud.githubusercontent.com/assets/23748196/26705293/ab22aeac-470b-11e7-8787-554861b753b6.png)
![screenshot_20170601_204348](https://cloud.githubusercontent.com/assets/23748196/26705294/ab22ce96-470b-11e7-8d01-6e66bea21ad8.png)

**Comment by FabioZumbi12** [comment]
Try the latest from jenkins if still.

**Comment by bbruno5** [comment]
I'll test and return the results soon.
