### ISSUE TITLE
deny build/break in region

### ISSUE THREAD

**Issue by erposse90** [FabioZumbi12/RedProtect#174]
--> Click on PREVIEW tab!

## Fill all info below to help us to find the problem are you having or with your suggestion:

_Put if is the **Spigot** or **Sponge** version._
Plataform:  sponge-forge-1.10.2-2281-5.2.0-BETA-2350.jar

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._
Jar version:  RedProtect-Sponge-6.0.0-7.1.4-b94.jar

_Your server Minecraft version_
Minecraft version:  1.10.2

_Issue or Suggestion?_
What you want?:  

Hello, when I create a claim I can not set if strangers can place or destroy blocks.
How do I fix it?

**Comment by FabioZumbi12** [comment]
You are using 6.0.0. Try the latest from our Jenkins where this is already fixed.
