### ISSUE TITLE
Mysql CommunicationsException

### ISSUE THREAD

**Issue by Naghtrion** [FabioZumbi12/RedProtect#176]
Plataform:  **Spigot**

Jar version:  RedProtect-Spigot v7.1.4

Minecraft version:  Spigot v1.11.2

_Issue or Suggestion?_
What you want?:  Informar sobre um erro que ocorre usando o MySql

Description:  Link: https://hastebin.com/goricixadi.sql
acho que é causado por você deixar a conexão com o banco aberta o tempo todo...

**Comment by FabioZumbi12** [comment]
Isso pode ser varias coisas, mas geralmente algum dado incorreto de login. De qqr modo, testa as ultimas builds do red.
