### ISSUE TITLE
RedProtect with CustomNPCs

### ISSUE THREAD

**Issue by kasdo** [FabioZumbi12/RedProtect#177]
Hi, 
Players cant interact with NPCs from CustomNPC mod in regions. All flags in this regions is "true", but players cant interact with NPC.

Version: 1.10.2
If u have qvestions add me in skype: pasha_kasdo

**Comment by FabioZumbi12** [comment]
Its on Sponge? Have you tryed to enable the flag **/rp flag allow-mod true** ?

**Comment by kasdo** [comment]
Its help me, ty

**Comment by kasdo** [comment]
But now I have new bug. Players get experience from ores that are in my region (ores isnt destroyed)

**Comment by FabioZumbi12** [comment]
This is a know issue with Sponge. Other anti-grief plugin is having the same issue on Sponge :/
