### ISSUE TITLE
Erro no console, apesar de parecer estar tudo ok no jogo.

### ISSUE THREAD

**Issue by comonier** [FabioZumbi12/RedProtect#178]
Plataform:  spigot cd6... last
Jar version:  RP 7.1.4
Minecraft version:  1.12
What you want?:  report problem
Description:  https://codeshare.io/5zE8gr

Alguns players do servidor estão sendo teleportados para lugares aleatórios, não descobri o motivo, mas quando fui olhar a log, vi muitas mensagens de erro do RedProtection, não sei se tem algo a ver com o problema do teleport até acho que não.... mas achei melhor reportar para, caso vc já tenha visto algo parecido me dar uma luz. E parabéns pelo Uchat e pelo PixelVip são ótimos, estou usando no meu servidor.

**Comment by FabioZumbi12** [comment]
Iae comonier. Vlws ai man ^^
O link dos logs ali ta em branco... pode postar denovo pra eu ver as mensagens que ta dando?

**Comment by comonier** [comment]
mals, não sei pq sumiu pronto

**Comment by comonier** [comment]
aconteceu hoje novamente
`17.06 11:02:53 [Server] ERROR Could not pass event PlayerInteractEvent to RedProtect v7.1.4
17.06 11:02:53 [Server] INFO org.bukkit.event.EventException: null
17.06 11:02:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-cd6ba67-a7d074c]
17.06 11:02:53 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-cd6ba67-a7d074c]
17.06 11:02:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-cd6ba67-a7d074c]
17.06 11:02:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-cd6ba67-a7d074c]
17.06 11:02:53 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot.jar:git-Spigot-cd6ba67-a7d074c]
17.06 11:02:53 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) [spigot.jar:git-Spigot-cd6ba67-a7d074c]
17.06 11:02:53 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:944) [spigot.jar:git-Spigot-cd6ba67-a7d074c]
17.06 11:02:53 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot.jar:git-Spigot-cd6ba67-a7d074c]
17.06 11:02:53 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot.jar:git-Spigot-cd6ba67-a7d074c]
17.06 11:02:53 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-cd6ba67-a7d074c]
17.06 11:02:53 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
17.06 11:02:53 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
17.06 11:02:53 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-cd6ba67-a7d074c]
17.06 11:02:53 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-cd6ba67-a7d074c]
17.06 11:02:53 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-cd6ba67-a7d074c]
17.06 11:02:53 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-cd6ba67-a7d074c]
17.06 11:02:53 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-cd6ba67-a7d074c]
17.06 11:02:53 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
17.06 11:02:53 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getLineOfSight(Ljava/util/HashSet;I)Ljava/util/List;
17.06 11:02:53 [Server] INFO at br.net.fabiozumbi12.RedProtect.listeners.RPBlockListener.onPlayerInteract(RPBlockListener.java:367) ~[?:?]
17.06 11:02:53 [Server] INFO at sun.reflect.GeneratedMethodAccessor360.invoke(Unknown Source) ~[?:?]
17.06 11:02:53 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
17.06 11:02:53 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
17.06 11:02:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-cd6ba67-a7d074c]
17.06 11:02:53 [Server] INFO ... 17 more`

**Comment by adminmip** [comment]
I know that this is an non-English issue, but I also have this issue...not sure of the circumstances, but I have the exact same console output, every time I place or break a block.

Thanks!
Mip

**Comment by comonier** [comment]
http://areaz12server.net.br:8080/job/RedProtect/25/
last build of redprotection: #25 > Not load on last spigot build 0869666b3a7 https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/0869666b3a7730fbecb02fbbf8d7fefec3b1173a
so... i back to build #24
http://areaz12server.net.br:8080/job/RedProtect/24/
