### ISSUE TITLE
Erro no console

### ISSUE THREAD

**Issue by Sakanas** [FabioZumbi12/RedProtect#179]
estou recebendo o seguinte erro no console 

> 20.06 11:17:38 [Server] INFO ... 18 more
20.06 11:17:38 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.125.jar:git-Spigot-9f26059-6aa0fa3]
20.06 11:17:38 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
20.06 11:17:38 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
20.06 11:17:38 [Server] INFO at sun.reflect.GeneratedMethodAccessor89.invoke(Unknown Source) ~[?:?]
20.06 11:17:38 [Server] INFO at br.net.fabiozumbi12.RedProtect.listeners.RPBlockListener.onPlayerInteract(RPBlockListener.java:367) ~[?:?]
20.06 11:17:38 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getLineOfSight(Ljava/util/HashSet;I)Ljava/util/List;
20.06 11:17:38 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
20.06 11:17:38 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.125.jar:git-Spigot-9f26059-6aa0fa3]
20.06 11:17:38 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.125.jar:git-Spigot-9f26059-6aa0fa3]
20.06 11:17:38 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.125.jar:git-Spigot-9f26059-6aa0fa3]
20.06 11:17:38 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.125.jar:git-Spigot-9f26059-6aa0fa3]
20.06 11:17:38 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.125.jar:git-Spigot-9f26059-6aa0fa3]
20.06 11:17:38 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
20.06 11:17:38 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
20.06 11:17:38 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.125.jar:git-Spigot-9f26059-6aa0fa3]
20.06 11:17:38 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.125.jar:git-Spigot-9f26059-6aa0fa3]
20.06 11:17:38 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.125.jar:git-Spigot-9f26059-6aa0fa3]
20.06 11:17:38 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:868) [spigot-1.125.jar:git-Spigot-9f26059-6aa0fa3]
20.06 11:17:38 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:108) [spigot-1.125.jar:git-Spigot-9f26059-6aa0fa3]
20.06 11:17:38 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [spigot-1.125.jar:git-Spigot-9f26059-6aa0fa3]
20.06 11:17:38 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot-1.125.jar:git-Spigot-9f26059-6aa0fa3]
20.06 11:17:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.125.jar:git-Spigot-9f26059-6aa0fa3]
20.06 11:17:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.125.jar:git-Spigot-9f26059-6aa0fa3]
20.06 11:17:38 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.125.jar:git-Spigot-9f26059-6aa0fa3]
20.06 11:17:38 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.125.jar:git-Spigot-9f26059-6aa0fa3]
20.06 11:17:38 [Server] INFO org.bukkit.event.EventException: null
20.06 11:17:38 [Server] ERROR Could not pass event PlayerInteractEvent to RedProtect v7.1.4

**Comment by FabioZumbi12** [comment]
Já foi arrumado nas ultimas dev builds: http://areaz12server.net.br:8080/job/RedProtect/

**Comment by Sakanas** [comment]
Obrigado resolveu
