### ISSUE TITLE
Big load from RedProtect. Timings

### ISSUE THREAD

**Issue by kasdo** [FabioZumbi12/RedProtect#180]
Hi, how I can fix this load?
https://timings.aikar.co/?id=c01d7c06481d4f189f7d6c71d24f5fb3

**Comment by FabioZumbi12** [comment]
As a antigrief plugin, all player actions will be listen by redprotect. You can ignore this load until you get lag, what's seems is not your case on lag graphics.

**Comment by kasdo** [comment]
I already have big lags (freezes)

**Comment by kasdo** [comment]
WorldGUard in Spigot have no load

**Comment by FabioZumbi12** [comment]
Redprotect for spigot don't load too. Spigot is other and too improved platform comparing with sponge, in dev stage.

**Comment by kasdo** [comment]
What I can do? I need fix this lags

**Comment by FabioZumbi12** [comment]
You can try other antigrief plugins to see if the lag still. And maybe check if your host machine is enough for your server mods and plugins.

**Comment by kasdo** [comment]
HOst machine is good.
Hmm... I can find other good antigrief plugins. FoxGuard isnt good plugin...
