### ISSUE TITLE
Error when the server stop

### ISSUE THREAD

**Issue by StarchierOrb** [FabioZumbi12/RedProtect#182]
Plataform:  Sponge

Jar version:  RedProtect-Sponge-5.2.0-7.1.4-b104.jar

Minecraft version:  1.10.2

Issue:
error log:  https://hastebin.com/eyojomeqeb

Description:  
   an error occurred when the server is stopping

**Comment by FabioZumbi12** [comment]
Seems this is the first time you run the server with redprotect, on other stops you get the same errors? Btw, try the latest version on our jenkins.

**Comment by StarchierOrb** [comment]
yes,everytime i stop the server i still get the same error.....

**Comment by FabioZumbi12** [comment]
This still on latest 7.2.1 from our jenkins?
