### ISSUE TITLE
Problem with realistic-swimming

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#183]
when in the global settings the value
  elytra:
    allow: true
    boost: 0.5

is set and using this plugin https://www.spigotmc.org/resources/realistic-swimming.23082/

then u have the following issues

try to swim in deepr water and u sink like a stone, also redproted warns u that fling is not allowed
the plugin self is mimiken Elytra in the water to get the swim animation
is there any change to make this work with redprotect?
Idea: elyta check only work on a block high Y and higher that can be setup in the config.
So the owner could setup the deep of his water and so allow plugins like realistic swimming to work.

**Comment by FabioZumbi12** [comment]
Try to set elytra-speed to -1 on globalflags.yml.

**Comment by CloudeLecaw** [comment]
is this a hhidle global flag? :D

**Comment by FabioZumbi12** [comment]
Its boost! xD

Have u tryed?

**Comment by CloudeLecaw** [comment]
Hello Faabio, sorry for the delay. Jep setting it to -1 helps. the player still "sink" a bit but not like a stone anymore
