### ISSUE TITLE
Conflito com McMMO

### ISSUE THREAD

**Issue by Sakanas** [FabioZumbi12/RedProtect#184]
quando coloco a ultima versão do mcmmo recebo esse erro 

02.07 15:35:47 [Server] INFO Redprotect: [RedProtect v7.2.0 disabled.]
02.07 15:35:47 [Server] INFO Redprotect: [Error enabling RedProtect, plugin will shut down.]
02.07 15:35:47 [Server] WARN at java.lang.Thread.run(Thread.java:745)
02.07 15:35:47 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
02.07 15:35:47 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
02.07 15:35:47 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
02.07 15:35:47 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
02.07 15:35:47 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
02.07 15:35:47 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
02.07 15:35:47 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377)
02.07 15:35:47 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
02.07 15:35:47 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
02.07 15:35:47 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
02.07 15:35:47 [Server] WARN at br.net.fabiozumbi12.RedProtect.RedProtect.onEnable(RedProtect.java:183)
02.07 15:35:47 [Server] WARN at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:525)
02.07 15:35:47 [Server] WARN at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:581)
02.07 15:35:47 [Server] WARN at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:583)
02.07 15:35:47 [Server] WARN org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event org.bukkit.event.player.PlayerEvent. Static getHandlerList method required!
02.07 15:35:47 [Server] INFO Redprotect: [MyPet found. Hooked.]
02.07 15:35:47 [Server] INFO Redprotect: [Essentials found. Hooked.]
02.07 15:35:47 [Server] INFO Redprotect: [Vault found. Hooked.]
02.07 15:35:47 [Server] INFO Redprotect: [Language file loaded - Using: pt-BR]
02.07 15:35:47 [Server] INFO Redprotect: [All configurations loaded!]
02.07 15:35:46 [Server] INFO Redprotect: [Server version: 1.12-R0.1-SNAPSHOT]
02.07 15:35:46 [Server] INFO [RedProtect] Enabling RedProtect v7.2.0

**Comment by FabioZumbi12** [comment]
Qual a numeração da ultima versão do mcmmo? E baixou ela daonde?

**Comment by Sakanas** [comment]
1.5.08 https://ci.drtshock.net/job/mcMMO/194/

**Comment by FabioZumbi12** [comment]
Isso é um erro do McMMo que removeu um método dos eventos dele. Já modifiquei e enviei uma sugestão de alteração pra eles: https://github.com/mcMMO-Dev/mcMMO/pull/3234

**Comment by TiNTin0TAG** [comment]
Já é possivel arrumar o conflito com o mcmmo, como?

**Comment by Sakanas** [comment]
Use a versão 1.5.10 ou 1.6.0 do mcmmo você pode baixar aqui [https://popicraft.net/jenkins/job/mcMMO/](Link Mcmmo)  e a versão mais recente do red protect também aqui [https://host.areaz12server.net.br:8080/job/RedProtect/](Link redprotect) essas ultimas versões são compatíveis com 1.13
