### ISSUE TITLE
I can't break any crops in the protect when i have all permission and op 

### ISSUE THREAD

**Issue by GTBisnotgay** [FabioZumbi12/RedProtect#185]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-Spigot-7.2.0-b414.jar

_Your server Minecraft version_  
Minecraft version:  1.11.2

_Issue or Suggestion?_  
What you want?:  Its bugged Because when i have all permission , Its tell me I  can't interact with it(crops).

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  No any errors with log

**Comment by NicolasDelahaigue** [comment]
It doesn't work either with this config :
PaperSpigot 1.12
RedProtect 7.2.0 b415
Minecraft 1.12

**Comment by GTBisnotgay** [comment]
Thats mean it only work in PaperSpigot 1.12 ?

**Comment by GTBisnotgay** [comment]
I can use which version that can slove the problems

**Comment by NicolasDelahaigue** [comment]
No I just say that the problem exist also with PaperSpigot 1.12 and RedProtect 7.2.0 b415. We have to wait that @FabioZumbi12 fixes the problem.

**Comment by GTBisnotgay** [comment]
Oh Thanks you i am suck at english zZ

**Comment by aurel85** [comment]
This is repaired with version b416 : http://areaz12server.net.br:8080/job/RedProtect/40/

**Comment by FabioZumbi12** [comment]
Yeah, try the latest and if fixed, we ill close this issue.

**Comment by FabioZumbi12** [comment]
Fixed (ops cant break crops)

**Comment by aurel85** [comment]
The bug is still present in the b419.
