### ISSUE TITLE
RedProtection crash 1.10.2

### ISSUE THREAD

**Issue by kasdo** [FabioZumbi12/RedProtect#186]
Forge Mod Loader version 12.18.3.2316
spongeforge-1.10.2-2281-5.2.0-BETA-2424
Mods: CustomNpcs, Mo'Creatures, CustomMobSpawner, LotsOfFood
Plugins: WorldEdit, RedProtect, EssentialCMDs, ProjectWorlds, ProjectPortals, Twentyticks, PermissionsEx, Holograms

https://hastebin.com/yasateziwu.pl

**Comment by kasdo** [comment]
+ errors in log
https://hastebin.com/bihuwivape.rb

**Comment by kasdo** [comment]
+ 1 more crash by redprotection
https://hastebin.com/opinegeboc.sql

FabioZombi12 where are u? Can u fix this?

**Comment by kasdo** [comment]
I install last version of redprotect and again I have this crash:
https://hastebin.com/xerivokosi.pl
Log:
https://hastebin.com/nuwulisoxu.md

**Comment by FabioZumbi12** [comment]
You have serious problems with connection and machine connections... Theres no _issues_ from redprotect in this ambients. Says redprotect on crash but redprotect is tryng to get UUID or player profile from mojang.

**Comment by kasdo** [comment]
Have not bungee, connection is good. Okay, I will create issue on sponge
