### ISSUE TITLE
Big load from redprotect 1.10.2 b137

### ISSUE THREAD

**Issue by kasdo** [FabioZumbi12/RedProtect#187]
Timing: https://timings.aikar.co/?id=96b22c43c0134eb7a6e6bea8ae8ee4c9
Can u fix this, pls?

**Comment by FabioZumbi12** [comment]
What i need to fix?

**Comment by kasdo** [comment]
RedProtect::RPPlayerListenercount(34671)  total(13.16% 0.292s, 18.82% of tick)avg(0.01ms per - 9.41ms/1,118.42 per tick)
RedProtect::RPBlockListenercount(82)  total(4.83% 0.107s, 6.90% of tick)avg(1.30ms per - 3.45ms/2.65 per tick)

18.82% and 6.9%
My server have 7 tps

**Comment by FabioZumbi12** [comment]
as antigrief plugin, its shure the most will be from RedProtect. I think you need a more robust machine or remove some MODs. Or maybe test other antigrief plug-ins.

In resume, theres no `fix` for this on code side.

**Comment by kasdo** [comment]
I have good machine. Plugins like worldguard have not load on spigot
