### ISSUE TITLE
Calculation of claim blocks with sub-claim

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#191]
Hi,

_PaperSpigot
RedProtect-Spigot-7.2.1-b430.jar
Minecraft 1.12
Suggestion/Issue_

When a player makes a sub-claim, this does not remove it from the claim blocks, perfect. But the problem is that it always requires the number of blocks of complaint necessary to be able to make the sub-claim even if it does not count these blocks in the end. I would like the players to be able to make sub-claims even if they are at 1000/1000 for example, but not if they are at 1100/1000, of course.

This is the same kind of concern as the #175  problem with /rp redefine

**Comment by FabioZumbi12** [comment]
No other users with this problem (including me on my server). Btw, try the latests versions.

**Comment by aurel85** [comment]
This problem has been present for a very long time and is still there. This is the same concern as with the /rp redefine #175 . For claim this requires claim blocks that are not actually required for claim. Because being able to make a sub-claim with 0 blocks of still available claim should work (since we are already in a claim area, so it does not add any blocks to /rp limit) but this has never been the case.

**Comment by aurel85** [comment]
Hum finally it doesn't look like the bug as I thought, doing tests. In short, indeed this issue can be closed and if there really is a concern that reappears on this subject I will open a new one.
