### ISSUE TITLE
Item Frames and Paintings in Global

### ISSUE THREAD

**Issue by QueenKisaki** [FabioZumbi12/RedProtect#192]
Plataform:  Spigot 
Jar version:  RedProtect 7.2.1 - Build 430
Minecraft version:  1.11.2
What you want?:  to be able to break item frames and paintings in non rp regions or at least give ops the ability to break those items.

Description:  Trying to build and not being able to take down paintings or item frames without having to /kill them, it becomes a pain in the butt

**Comment by FabioZumbi12** [comment]
Fixed.
