### ISSUE TITLE
[Bug] Admin FarmCrops Flag not working properly

### ISSUE THREAD

**Issue by pinkpig3777** [FabioZumbi12/RedProtect#193]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-Spigot-7.1.4-b354.jar

_Your server Minecraft version_  
Minecraft version:  1.10.2

_Issue or Suggestion?_  
What you want?:  The FarmCrops admin flag to be fixed so it works properly.

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description: I made it so players can use the admin flag "FarmCrops" using /rp flag. However, when a player not added to the claim tries to farm land while the flag is enabled, it allows players to break sugarcane but not place it. It also doesn't allow players to break OR place nether warts. I'm not sure for the other plants. 

Players should be able to break AND place all crops within the claim if the flag is enabled. Please fix this. Thank you!

**Comment by pinkpig3777** [comment]
Still waiting for a fix.....

**Comment by pinkpig3777** [comment]
Still waiting.....

**Comment by FabioZumbi12** [comment]
Will be fixed when i get back to work on Redprotect. For now, i am working on my other plugins.

**Comment by FabioZumbi12** [comment]
Its fixed on latest versions. If not, reopen.

**Comment by pinkpig3777** [comment]
I no longer use the plugin due to lack of bug fixes for months. Thanks anyway though.
