### ISSUE TITLE
Bypass claim limit with /rp buy

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#194]
Hi,

PaperSpigot
RedProtect-Spigot-7.2.1-b430.jar
Minecraft 1.12
Issue

When a player buys a claim via /rp buy its claim limit increases even if it no longer has available blocks. So some players can easily exceed their claim limit with this system. Thank you in advance to avoid the claim limit being easily exceeded through this system.

**Comment by FabioZumbi12** [comment]
Economy will be removed from redprotect (will be created a new add-on for redprotect to do this)
