### ISSUE TITLE
/rp border, /rp wand - glowstone dupe [SPONGE 5.2]

### ISSUE THREAD

**Issue by linkinkov** [FabioZumbi12/RedProtect#195]
Plataform:  **Sponge**

Jar version:  **RedProtect-Sponge-5.2.0-7.2.0-b138.jar**

Minecraft version:  1.10.2

What you want?:  Fix the problem with border dupe

Description:  Need more protection for glowstone blocks, because then border start hide players can destroy blocks.

**Comment by linkinkov** [comment]
@FabioZumbi12 its important

**Comment by FabioZumbi12** [comment]
Dupe bugs its not related to Redprotect and yes with SpongeAPI. Try to search for help with Sponge team

**Comment by linkinkov** [comment]
Glowstone blocks what created by border of claim region not related to plugin?
@FabioZumbi12

**Comment by FabioZumbi12** [comment]
Yeah. Since the plugin not allow players to break glowstone, you have a issue with API. The same with dupe. Try to update your SPongeAPI version or forge.

**Comment by linkinkov** [comment]
I found probem.
    border {
        material="minecraft:glowstone"
        time-showing=2
    }
If time-showing more then 2, players can mine glowstone.
@FabioZumbi12
