### ISSUE TITLE
Compatibility issue with ExoticGarden (SlimeFun)

### ISSUE THREAD

**Issue by yariplus** [FabioZumbi12/RedProtect#196]
RedProtect is not compatible with ExoticGarden due to both plugins defining a package `org.jnbt`

Can be easily fixed by renaming or shading the package `org.jnbt`

[example error](https://hastebin.com/melilaqoka.vbs)

Platform:  Spigot
Jar version:  RedProtect-Spigot-7.2.1-b432.jar
Minecraft version:  1.12

What you want?:  Rename or shade `org.jnbt` to fix this issue and potentially issues with other plugins also defining `org.jnbt`

**Comment by FabioZumbi12** [comment]
Already changed ;) Try the latest version from jenkins.

**Comment by yariplus** [comment]
Thanks! Working good.
