### ISSUE TITLE
Compatible with Skillapi?

### ISSUE THREAD

**Issue by QueenKisaki** [FabioZumbi12/RedProtect#197]
Jar version:  RedProtect 7.2.1 - Build 430

_Your server Minecraft version_  
Minecraft version:  1.11.2 Spigot

_Issue= Getting this message while standing in an RP: https://pastebin.com/xWuUXT8k

Description:  If there is something I need to enable to make this work please tell me.

**Comment by FabioZumbi12** [comment]
Its a SkillAPI problem. I dont know what can be exactly but i never have seenthis error before.
