### ISSUE TITLE
Problem with Sugar in private

### ISSUE THREAD

**Issue by kasdo** [FabioZumbi12/RedProtect#198]
Hi fabio.
If player have door in inventory and click with this door on sugar cane. Sugar will stand and drop. So we have 2 sugarcane. If player do this with autoclicker server will go down. Error in log:
https://hastebin.com/alezopokik.rb

RedProtect last version
Sponge 1.10.2 last version

**Comment by FabioZumbi12** [comment]
Seems to be Sponge bug and Dupe Bug. Dupe bugs and similar to this you need to report to Sponge devs!
