### ISSUE TITLE
Crashes in console

### ISSUE THREAD

**Issue by Zoiter7** [FabioZumbi12/RedProtect#199]
Plataform:  Spigot
Jar version:  RedProtect-Spigot-7.2.1-b430
Minecraft version:  1.8.8
What you want?:   Issue

Description:  
Sometimes in console gives this error https://hastebin.com/oluzumoxit.bash

**Comment by FabioZumbi12** [comment]
Its an error from 1.8.8 potions and consumables... Works fine on latest versions of minecraft :x

**Comment by Zoiter7** [comment]
Okay,  you closed the issue so you can't fix it. 

Thanks
