### ISSUE TITLE
/rp buy has typo for seller and still says unknown command for buyer

### ISSUE THREAD

**Issue by RogueCmdr** [FabioZumbi12/RedProtect#2]
Tested selling a region buy when a user went to buy it, it still say invalid command. Also if you own the region and do /rp buy it says "Youn can't buy your own region! /rp cancelbuy to dont sell this region."

**Comment by FabioZumbi12** [comment]
After update to 5.4.3 too?

**Comment by RogueCmdr** [comment]
yes even after the update. The update patched the UUID's and the seller side of the /rp buy command but not the buyer side

**Comment by FabioZumbi12** [comment]
I tryed on my server running in Online mode but didnt reproduce this problem... can you give me more details? Or show me on your server?
