### ISSUE TITLE
Hoppers bypass [private] signs

### ISSUE THREAD

**Issue by CoolV1994** [FabioZumbi12/RedProtect#20]
Would it be possible to add hopper protection to [private] signs?
Possibly add an  'anti-hopper' to the sign protection as well as region protection.
Hoppers can currently bypass the sign protection outside of RedProtect regions.
Thanks for making an awesome plugin.

**Comment by FabioZumbi12** [comment]
On my tests, the private chests is already protected against block placement under chest.
On my test i tryed to break this block to place rails or hoppers, but cant: http://prntscr.com/a7nx42

**Comment by CoolV1994** [comment]
Thank for pointing that out, I did not realize other players could not break that block.
I did find a new bug though. Other players are able to use a piston to move blocks from underneath the chest and sign. Once those blocks are moved, you can send in a hopper minecart to steal the items. Players can also place blocks under locked chests, hoppers are blocks though.

http://i66.tinypic.com/xcubrl.png - Area player can break already
http://i63.tinypic.com/2cibpj7.png - Place down pistons
http://i64.tinypic.com/2nhp8n9.png - Pistons move blocks
http://i63.tinypic.com/23rsfvc.png - Place rail so hopper minecart interacts with corners
http://i65.tinypic.com/2112s7s.png - Chest before
http://i65.tinypic.com/vx1z0p.png - Hopper cart placed
http://i63.tinypic.com/tafrro.png - Hopper cart moved
http://i63.tinypic.com/fa32ip.png - Hopper result
http://i68.tinypic.com/2h6vk1d.png - Chest after

**Comment by FabioZumbi12** [comment]
I cant see the images, but i undertod qhat happens and i will try to fix ;)

**Comment by FabioZumbi12** [comment]
I fixed on next version. If you want to try, download [HERE](http://areaz12server.net.br/download/RedProtect.jar)!

**Comment by CoolV1994** [comment]
Thanks for the fix. I would be glad to test.

**Comment by CoolV1994** [comment]
I believe this update has secured chests.

**Comment by FabioZumbi12** [comment]
Thats ok, closing the issue.
