### ISSUE TITLE
PvP flag not working.

### ISSUE THREAD

**Issue by totaljerkface216** [FabioZumbi12/RedProtect#200]
_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  redprotect_for_all_versions_anti_grief_server_protection_7_2_2

_Your server Minecraft version_  
Minecraft version:  1.10-latest

_Issue or Suggestion?_  
What you want?:  issue

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  Hello. In my region i have pvp off but people can still kill each other. How do i fix this. I cant hit people but people can hit me and others. The no pvp flag only affects me but not other people.

**Comment by FabioZumbi12** [comment]
This is because you is OP and probally you have enabled WAR on redprotect config. OP bypass pvp flag if using WAR.
