### ISSUE TITLE
I have some translation questions.

### ISSUE THREAD

**Issue by ozeurk033** [FabioZumbi12/RedProtect#201]
`cmdmanager.region.doesexists=&cThis region does exists anymore or has been removed\!`
It exists or not?

`blocklistener.container.protected.notadded=&bThe sign must be on the side of a private sign on the same chest!`
~~What does mean "private sign"? It is same of normal sign?~~
~~Please describe this situation anymore, so I could be accurate to translate this.~~
I will trial your plugin for a moment to see

`cmdmanager.region.kicked=&cPlayer {player} kicked from {region} for {time} seconds\!`
It is kicking or banning? it sounds like a ban.

`cmdmanager.region.flag.usageallow-cmds=&cUsage\: /rp {cmd} allow-cmds cmd:<command> [arg:<argumment>], ...`
`cmdmanager.region.flag.usagedeny-cmds=&cUsage\: /rp {cmd} deny-cmds cmd:<command> [arg:<argumment>], ...`
> argumment

`cmdmanager.rent.renewfail=&cYour money is not enought to renew your rent in this region!`
> enought

I am sorry?

I am translating your plugin to Chinese including your new guiconfig. Please answer my question.

**Comment by FabioZumbi12** [comment]
Yeah, english is not my native language and i am not fluent too :P - Thanks, i will fix ths.

**Comment by ozeurk033** [comment]
I am glad you are active on this project.
`gui.edit.error=&cERROR! You have invalid items on Flag Gui！ Please, don't leave blank slots od diferent items.`
>od

Sorry?

**Comment by FabioZumbi12** [comment]
Fixed:
`cmdmanager.region.doesexists=&cThis region does exists anymore or has been removed\!
It exists or not?`
`blocklistener.container.protected.notadded=&bThe sign must be on one side of an other private sign and in the same chest\!
`

These mistakes nobody has noticed before, believe me. xD

**Comment by ozeurk033** [comment]
https://github.com/FabioZumbi12/RedProtect/search?utf8=%E2%9C%93&q=this+chest+for+take+and+put+itens.&type=
Sorry?

**Comment by ozeurk033** [comment]
Sometimes I will look here and try Google Translate for help me understand and translate your sentance means.
https://github.com/FabioZumbi12/RedProtect/blob/master/RedProtect-Spigot/src/main/resources/lang_pt-BR.properties

`cmdmanager.region.doesexists=&cThis region does exists anymore or has been removed\! It exists or not?`
It tell me https://translate.google.com/#pt/en/Esta%20RP%20regi%C3%A3o%20n%C3%A3o%20existe%20ou%20foi%20removida!

**Comment by ozeurk033** [comment]
Based on https://github.com/FabioZumbi12/RedProtect/pull/171 your comment.
I could translate `blocklistener.container.protected.notadded` be accurated.
`accurated` `accelerated` =P

**Comment by ozeurk033** [comment]
https://github.com/FabioZumbi12/RedProtect/blob/0552c0e78799bd2b0998188227f025f7e0460e70/RedProtect-Spigot/src/main/resources/guiconfig.yml#L14
https://github.com/FabioZumbi12/RedProtect/blob/0552c0e78799bd2b0998188227f025f7e0460e70/RedProtect-Spigot/src/main/resources/guiconfig.yml#L35
https://github.com/FabioZumbi12/RedProtect/blob/0552c0e78799bd2b0998188227f025f7e0460e70/RedProtect-Spigot/src/main/resources/guiconfig.yml#L42

No? Non?
Are you allow or not?

Why are you wrote description1 description2 description3?

**Comment by ozeurk033** [comment]
`cmdmanager.region.leader.cantremove.lowregion=&cYou cant remove the player {player} because he is an leader of the main region\:`
Where is `{region}`? Please, not every language arrangement like that natively as well

http://regexr.com/
Regex Search: `/\\:(&.)?$/gm`
Target Text File Content: https://github.com/FabioZumbi12/RedProtect/blob/0552c0e78799bd2b0998188227f025f7e0460e70/RedProtect-Spigot/src/main/resources/lang_en-EN.properties
Should I help you to modify that translate message java code? Do I? Three version of your plugin, so terrible.

**Comment by FabioZumbi12** [comment]
All fixed, thanks.
