### ISSUE TITLE
bossbar duble

### ISSUE THREAD

**Issue by mat41997** [FabioZumbi12/RedProtect#202]
![2017-08-21_21 05 20](https://user-images.githubusercontent.com/5884000/29534020-aff77564-86b4-11e7-9a77-199ea937d34a.png)

timings
https://timings.aikar.co/?id=394e226315e2463e93fb9411754e4be0#plugins

**Comment by FabioZumbi12** [comment]
One region under other can aswer you. Since theres no new updates, seems some problems with your server or configuration.
