### ISSUE TITLE
Suggestion: Breakable blocks list on needed-claim-to-build worlds

### ISSUE THREAD

**Issue by hsombini** [FabioZumbi12/RedProtect#203]
Hello,

The needed-claim-to-build feature is awesome, it keeps the claim world nice and clean, but alot of players has trouble to claim a land where some pesky grass and flowers are on their way, they simply cannot get over it.

It would be great if we could have a whitelist that allow players to break blocks we list on non claimed land to make their lives easier!

**Comment by FabioZumbi12** [comment]
Added on https://github.com/FabioZumbi12/RedProtect/commit/40d287e24dda2bbe432fcca874c93c3b8ea8ed4b
