### ISSUE TITLE
Suggestion : Dynmap optimization

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#204]
Hi,

_PaperSpigot
RedProtect-Spigot-7.2.2-b435.jar
Minecraft 1.12.1
Suggestion_

I raise what I said at #126 . When you activate the claims on the dynmap and there are many claims, the user can not navigate quietly. Too bad, if this could be optimized so that activating RedProtect's claims on the dynmap does not make the user's browser slower it would be perfect !

To realize what I say : http://play.freebuild.fr:8129/?zoom=3 (especially the map overworld v1 and v2)

**Comment by FabioZumbi12** [comment]
Theres no optmizations to do ... you can disable redprotect regions to show by default.
