### ISSUE TITLE
player can not ride a horse

### ISSUE THREAD

**Issue by KonoromiHimaries** [FabioZumbi12/RedProtect#206]
![2017-09-10_20 04 38](https://user-images.githubusercontent.com/5884000/30251623-b59372ac-9663-11e7-87bb-8e611539271f.png)
![2017-09-10_20 08 29](https://user-images.githubusercontent.com/5884000/30251636-e7d948ae-9663-11e7-8801-19a3725097ab.png)

timings
https://timings.aikar.co/?id=47bf82b7777d451291cdea915ff79228

**Comment by FabioZumbi12** [comment]
No more descriptions, logs or info, cant help (as you can see the time to me to respond you)
