### ISSUE TITLE
you can add a new command?

### ISSUE THREAD

**Issue by mat41997** [FabioZumbi12/RedProtect#208]
e.g. ```/rp expel - removes a visitors from your field``` and 
```/rp block-enter - blocked a enters other players to your field```

![2017-09-17_17 47 23](https://user-images.githubusercontent.com/5884000/30522472-c76bb8e6-9bd0-11e7-9de1-848f9c830f83.png)

**Comment by FabioZumbi12** [comment]
You aleary can deny others to enter on your region making the admin flag **enter** to player flag. Just give the flag permissions to your players (check wiki).

And theres a command to kick players from regions, is **/rp kick**.

**Comment by mat41997** [comment]
you can add a entry flag to gui-menu?

i don't can
