### ISSUE TITLE
Suggestion: Add [more users] sign and make signs editable.

### ISSUE THREAD

**Issue by CoolV1994** [FabioZumbi12/RedProtect#21]
Would it be possible to add [more users] signs for chest protections?
Currently only 1 sign has effect only allowing up to 2 additional users per chest.
This would allow up to 11 additional users per single chest and up to 17 additional users per double chest.
Is it also possible to make the signs editable so you don't have to replace the sign each time you want to add/remove somebody?

**Comment by CloudeLecaw** [comment]
you could use a plugin like EditableSign for this ;)
Version 1.27 works well (simple shift + RIGHTKlick without item in hand.
since Version 2.0 u have to enable sign editmode before with /se

**Comment by FabioZumbi12** [comment]
I will add ^^

**Comment by FabioZumbi12** [comment]
Will be added on next update.
