### ISSUE TITLE
[Sponge][1.10.2]Plugin doesn't load on server

### ISSUE THREAD

**Issue by EZKatnipz** [FabioZumbi12/RedProtect#210]
Hello,
Having an issue with RedProtect not loading on the server. Looked through some logs and found an error with the plugin, will include the error separated out from the main log.

Full log:
    [fml-server-latest.txt](https://github.com/FabioZumbi12/RedProtect/files/1323505/fml-server-latest.txt)

Separate error:
    [Error.txt](https://github.com/FabioZumbi12/RedProtect/files/1323506/Error.txt)

Versions used with the included logs:
    RedProtect-Sponge-5.2.0-7.2.2-b145
    spongeforge-1.10.2-2477-5.2.0-BETA-2637

Other versions tried that produced the same result:
    RedProtect-Sponge-5.2.0-7.3.0
    spongeforge-1.10.2-2281-5.2.0-BETA-2620

**Comment by FabioZumbi12** [comment]
I dont from where comes this error, but try the latest build and paste the error again (if still).

**Comment by EZKatnipz** [comment]
using the new all-in-one build, looks like the same error.
https://pastebin.com/a6UZkN1m
