### ISSUE TITLE
regions not saved (Sponge, 1.12.2)

### ISSUE THREAD

**Issue by L31H4** [FabioZumbi12/RedProtect#213]
Yesterday i created about 10-15 regions and edited them, everything worked fine. Today i was wondering about spawning mobs in a region whrer i disabled, so i wanted to check the flags. After typing /rp flag i got "You need to be in a region to do this." /rp info -> same, i did not check all regions yet, but so far i found one left, the first one i created
I´m on 1.12.2, Sponge build 2696 and forge build 2509 and i´m using the latest build of RedProtect (#51)
List of mods/plugins:
CustomNPCs
EconomyLite
ForgedPerms
JourneyMap
LuckPerms
Nucleus
projectcore
SleepVote
walletdrop

the latest release of each

**Comment by FabioZumbi12** [comment]
You need to paste your server logs to get errors is causing regions not saving.

**Comment by L31H4** [comment]
I´m sry, I had much to do the last to months and no time for minecraft and just forgot that issue.
I recently updated RedProtect to the latest available build and the problem doesn´t occured again. I will open a new Issue, if I have the same problem again.
