### ISSUE TITLE
custom flag in gui-flag not work

### ISSUE THREAD

**Issue by mat41997** [FabioZumbi12/RedProtect#214]
![2017-10-21 13_10_18-_c__users_y7_appdata_local_temp_fz3temp-2_guiconfig yml - notepad](https://user-images.githubusercontent.com/5884000/31851201-4e13d824-b661-11e7-8433-1eda8f70e3f0.png)

**Comment by FabioZumbi12** [comment]
You need to give the permission to your players too, but remove the `admin` from permission.
