### ISSUE TITLE
Right-click to retrieve item not blocked properly

### ISSUE THREAD

**Issue by AeoniaMC** [FabioZumbi12/RedProtect#215]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform:  Sponge

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-Sponge-6.1.0-7.2.0-b137.jar

_Your server Minecraft version_  
Minecraft version:  1.11.2

_Issue or Suggestion?_  
What you want?:  Bugfix / Mod compatibility improvement

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  In the PokeCube mod, there are berry trees that are harvested by right-clicking on them to drop a berry. If the player is right-clicking a plant that is growing on someone else's claim (that they do not have perms to) then the berry item drops, but the plant is not destroyed, allowing for infinite clicks that spawns infinite berries. I'm not sure if there are other mods or other items that have this happen to it. The PokeCube dev believes it to be the plugin cancelling the block destruction, and not the the click, which lets the berry spawn but the plant not get destroyed.

**Comment by FabioZumbi12** [comment]
You is not using the latest version (dev build on http://areaz12server.net.br:8080/job/RedProtect) and this bugs can be fixed by the modders, since redprotect cancels Sponge events, not handling in other ways.

**Comment by Bartek200219** [comment]
I have the same problem on 1.17 Paper Spigot
