### ISSUE TITLE
rp wand not working api7

### ISSUE THREAD

**Issue by baconetworks** [FabioZumbi12/RedProtect#216]
_Put if is the **Spigot** or **Sponge** version._  
Plataform:  spongeforge-1.12.2-2503-7.0.0-BETA-2706

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-Sponge-6.1.0-7.2.0-b137

_Your server Minecraft version_  
Minecraft version:  1.12.2 

_Issue or Suggestion?_  
What you want?:  issue

Description:  /rp wand does work but the region selection doesn't (so left/rightclick with wand)

ps. no error logs apear

**Comment by baconetworks** [comment]
http://prntscr.com/h2quey

screenshot from in game command gives glass bottle but it doesnt glow

**Comment by FabioZumbi12** [comment]
Your jar is too old, use the latest from http://areaz12server.net.br:8080/job/RedProtect/
And additionally, try to change the wand item on config.

**Comment by baconetworks** [comment]
dont forget to update your ore page <3

**Comment by FabioZumbi12** [comment]
This builds on jenkins is only for who is having issues. Actually is not fully tested to be uploaded to Sponge/Spigot/Bukkit as release.

The last buils solved your problem?

**Comment by baconetworks** [comment]
yes it did
