### ISSUE TITLE
Rp bug do forcefly

### ISSUE THREAD

**Issue by Sakanas** [FabioZumbi12/RedProtect#217]
quando tem duas rp com forcefly ativado e voce teleportar de uma para outra e sair andando de dentro dela quando sair ficar com fly no mundo todo

**Comment by Sakanas** [comment]
update: quando deleta uma rp com forcefly voce fica com fly no mundo todo

**Comment by FabioZumbi12** [comment]
Arrumado nas ultimas builds.
