### ISSUE TITLE
Could not pass SpawnEntityEvent$ChunkLoad$Impl to RedProtect (1.10.2 - SpongeForge)

### ISSUE THREAD

**Issue by guuslieben** [FabioZumbi12/RedProtect#218]
_Put if is the **Spigot** or **Sponge** version._  
Platform: **SpongeForge 1.10.2-2281-5.2.0** 

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  **RedProtect-Sponge-56-7.3.0.jar**

_Your server Minecraft version_  
Minecraft version:  **1.10.2**

_Issue or Suggestion?_  
**Issue**

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  Whenever a player moved around the world, the console gets spammed with the message as seen [here](https://hastebin.com/wehibekoda.vbs)

**Comment by FabioZumbi12** [comment]
Use the latest dev build from our jenkins http://areaz12server.net.br:8080/job/RedProtect/53/artifact/RedProtect-Sponge-7/target/RedProtect-7.3.0-b53-Universal.jar
