### ISSUE TITLE
Console errors! Need help please!

### ISSUE THREAD

**Issue by EmeraldG** [FabioZumbi12/RedProtect#219]
I found this error in the console at first:

 WARN org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event org.bukkit.event.player.PlayerEvent. Static getHandlerList method required! 01.11 22:50:13 [Server] WARN at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:582) 01.11 22:50:13 [Server] WARN at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:580) 01.11 22:50:13 [Server] WARN at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:524) 01.11 22:50:13 [Server] WARN at br.net.fabiozumbi12.RedProtect.RedProtect.onEnable(RedProtect.java:180) 01.11 22:50:13 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) 01.11 22:50:13 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) 01.11 22:50:13 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:401) 01.11 22:50:13 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:370)

I tried to fix the issue by downloading different versions, none of which worked either, I then tried deleting the config file and reloading:

01.11 23:18:14 [Server] INFO [RedProtect] Enabling RedProtect v7.2.2 01.11 23:18:14 [Server] INFO Redprotect: [Server version: 1.12.2-R0.1-SNAPSHOT] 01.11 23:18:14 [Server]  etc... BUT, the plugin never fully loaded past this and it is still not working. I've tried both java versions too. Any suggestions?? 

Thank you!

**Comment by FabioZumbi12** [comment]
This is fixed on latest dev build for 1.12: http://149.56.100.129:8080/job/RedProtect/

This is on this github's issue template :/
