### ISSUE TITLE
No Message upon entering region

### ISSUE THREAD

**Issue by Red3Tango** [FabioZumbi12/RedProtect#221]
Plataform:  Spigot [git-Spigot-5695bca-53fccdf (MC: 1.12.2)]
Jar version:  RedProtect-7.3.0-b53-Universal.jar (also tested with 7.2.2-b435)
Minecraft version:  1.12.2

Issue:
When leaving a region, I get the message "There's no regions here. You are on Wilderness." However, when entering any region, despite having a welcome message, there is nothing displayed. I have tried with using BossBar and Chat, and with and without custom welcome message. There are no errors recorded in event log. So am only getting the above message when leaving regions, but nothing on entering.

**Comment by FabioZumbi12** [comment]
Fixed on latest dev build
