### ISSUE TITLE
Sugestao para melhoria ou criaçao de um novo plugin

### ISSUE THREAD

**Issue by Ricardogame23** [FabioZumbi12/RedProtect#222]
_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  

_Your server Minecraft version_  
Minecraft version:  +1.8

_Issue or Suggestion?_  
estou tendo problemas em conseguir que os jogaroes tenham permissão para vender seus terrenos.
Por isso deixo uma sugestão
o plugin que procuro e um plugin onde qualquer jogador possa comprar em vender terrenos pelo preço que quiser. podendo colocar a placa de venda em qualquer lugar. O dono do terreno possa vender o seu espaço para outros jogadores e ainda receba a grana. sem nenhum problema. O melhor seria se cada terreno tivesse so como colar um nome, e ninguem poderia copiar se estiver em uso por outros.
Outra possibilidade de poder selecionar uma area especifica, um cubo onde nesse esoaço que poderia construir ou vender sendo so op que poderia selecionar mas ainda os jogadores poderiam vender ou comprar esses terrenos.

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:

**Comment by FabioZumbi12** [comment]
Venda e aluguel de rps eh experimental e pode ter varios error, mas nao pretendo mexer nisso por agora.
