### ISSUE TITLE
Help! I can't interact with AdminShop in others region.

### ISSUE THREAD

**Issue by mantinghui** [FabioZumbi12/RedProtect#224]
I set an AdminShop(a sign) in my region(I'm op), and i use another account(not member,not op) to use this shop, but nothing happend.And I released all permission of my region,still not work.How can i solve it?

**Comment by mantinghui** [comment]
Oh,by the way,my server is sponge

**Comment by FabioZumbi12** [comment]
Use the flag `/rp flag sign true` and on config dont forget to set your AdminShop sign header to Redprotect know what signs is shops.
