### ISSUE TITLE
enabled-flags teleport permission

### ISSUE THREAD

**Issue by Red3Tango** [FabioZumbi12/RedProtect#225]
Plataform: Spigot [git-Spigot-5695bca-53fccdf (MC: 1.12.2)]
Jar version: RedProtect-7.3.0-b53-Universal.jar (also tested with 7.2.2-b435)
Minecraft version: 1.12.2

Issue:
When you remove the " - 'teleport'" flag from the "enabled-flags:" section in config.xml file, the flag is still changeable using a sign or using the GUI.

**Comment by FabioZumbi12** [comment]
Yeah, you need to remove the permission too.

**Comment by Red3Tango** [comment]
Ok, that does work. Thought this might have been a bug as its the only flag that doesn't disable when removing it from the "enabled-flags:" section in the config.yml, without removing any permissions.
