### ISSUE TITLE
Invalid default setting in config.yml

### ISSUE THREAD

**Issue by Red3Tango** [FabioZumbi12/RedProtect#227]
Version: Spigot
RP: 7.3.0-b55

https://github.com/FabioZumbi12/RedProtect/blob/1e0912fda8aed3db86f392f395ec8a89ee0c1234/RedProtect-Spigot/src/main/java/br/net/fabiozumbi12/RedProtect/Bukkit/config/RPCommentedConfig.java#L62

This setting expects an integer value, but default is set to "BLOCK" instead of "5".

**Comment by FabioZumbi12** [comment]
lol thank you to point this xD
