### ISSUE TITLE
IllegalPluginAccessException: Unable to find handler list for event org.bukkit.event.player.PlayerEvent. Static getHandlerList method required!

### ISSUE THREAD

**Issue by Rsl1122** [FabioZumbi12/RedProtect#228]
**Platform**:  PaperSpigot-1.12.1.jar:git-Paper-1190

**Jar version**:  RedProtect-Spigot-7.2.2-b435

**Minecraft version**:  1.12.1

**What you want?**:  Issue

**Description**:  
On enable:
https://hastebin.com/qanijaqesu.css

**Comment by bbruno5** [comment]
Update your mcMMO to latest version 1.0.9 and the error will disappear.

**Comment by FabioZumbi12** [comment]
And update to latest dev build of redprotect 7.3.0 http://areaz12server.net.br:8080/job/RedProtect/ where this is fixed too
