### ISSUE TITLE
Titleaction problem

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#23]
The old Titleaction was showing creator, and member
now where there is no  creator anymore it throws arrows.

have the methods changed for this?
or can i inform the dev of Titleaction that he needs to look for leaders instead of creator
and for admins and members instead of just members?

**Comment by FabioZumbi12** [comment]
Exactly! He need to update his plugin to look for leaders and admins.

**Comment by CloudeLecaw** [comment]
This experemental version from you solved it :-)

**Comment by CloudeLecaw** [comment]
you could use a plugin like EditableSign for this ;)
Version 1.27 works well
since Version 2.0 u have to enable sign editmode before with /se
