### ISSUE TITLE
Rent a region

### ISSUE THREAD

**Issue by EveLynn666** [FabioZumbi12/RedProtect#231]
_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  7.2.2

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  I have a problem with rent commands

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  Every time i try to use rent commands it says "invalid command! See all commands using /rp help"..Do i need a plugin to use or what should i do to solve this...?

**Comment by FabioZumbi12** [comment]
Rent on redprotect its experimental, and its not fully implemented :/

**Comment by LordBlaZze** [comment]
Seria ótimo se o aluguel de Rps funcionasse de forma automática. Tipo Um player clica numa placa pra alugar e depois escreve um comando para confirmar.

**Comment by FabioZumbi12** [comment]
Rent will be removed (already removed on latest dev builds). Other plugins can make this system using the RedProtect API.
