### ISSUE TITLE
Sugestão  

### ISSUE THREAD

**Issue by Ricardogame23** [FabioZumbi12/RedProtect#232]
adicionar um livro onde possa mostrar todos as regiões que pertencem ao jogador  dando a ele a possibilidade de se teletransportar clicando no nome da região 
/rp claimbook   . ---- da a ele o livro.

**Comment by FabioZumbi12** [comment]
Desnecessário, pois o player ja pode usar /rp list e clicar no nome da rp pra se teleportar pra ela. (se dada a permissão)
