### ISSUE TITLE
API 7

### ISSUE THREAD

**Issue by Gunslito** [FabioZumbi12/RedProtect#234]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Sponge

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-Sponge-6.1.0-7.2.0-b137.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Suggestion

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  Can you add support for API7? It says on console that it was unable to send initialize command to RedProtect so it just doesn't start the plugin.

**Comment by Mine15029** [comment]
That RedProtect version is old and does not work for API7. Use the latest dev build on jenkins: http://areaz12server.net.br:8080/job/RedProtect/
