### ISSUE TITLE
I can't build on regionless areas

### ISSUE THREAD

**Issue by Gunslito** [FabioZumbi12/RedProtect#236]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform: spongeforge-1.12.2-2555-7.1.0-BETA-2840

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-7.3.0-b64-Universal

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Issue

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  

When there's not region it will not let me build if I have defaults permissions. 
Leaving only RedProtect jar will cause this issue, only on region area with flag build true I can build.

My Globalflags.conf & config.conf 

https://pastebin.com/aWSX3sgK

**Comment by FabioZumbi12** [comment]
Fixed on latest build too.
ref https://github.com/FabioZumbi12/RedProtect/commit/91e196bf966588e29c5168b94e05e12315426e16
