### ISSUE TITLE
PVP-Zonen-Problem

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#237]
_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Paperspigot 1.12.2

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect 7.3.0 b68

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  PvP is out on the zone. Players can not beat each other. But players can injure other ranks like Dev or Mod if they have / gm 0.

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:

**Comment by FabioZumbi12** [comment]
I think you is using SimpleClans with war enabled?

**Comment by Blueeyestar** [comment]
simpleclans:
  # Enable Clan Wars from SimleClans.
  use-war: **false**
  # Allow war clans to pvp on #server# regions?
  war-on-server-regions: **false**
