### ISSUE TITLE
Corrected langDE-EN.properties file with umlauts

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#238]
_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Paperspigot 1.12.2

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect 7.3.0 b68

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Clean corrected langDE-DE.properties. German umlauts have been adjusted.
Missing translations have been adjusted.

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  https://pastebin.com/iTmRBux0

**Comment by FabioZumbi12** [comment]
Corrections added, thanks ;)
