### ISSUE TITLE
Bug and Dupe

### ISSUE THREAD

**Issue by viktor141** [FabioZumbi12/RedProtect#242]
https://www.youtube.com/edit?o=U&feature=vm&video_id=331PilOmOkY
dupes with the help of the auto-breacker unit from the fashion ActualiAditions and with the help of a mechanical miner, mechanical user the fashion ExtraUtilities.
_Put if is the **Spigot** or **Sponge** version._  
Plataform:  spongeforge-1.10.2-2477-5.2.0-BETA-2793

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-7.3.1-b69-Universal

_Your server Minecraft version_  
Minecraft version:  1.10.2

_Issue or Suggestion?_  
What you want?: chek this video:
 https://www.youtube.com/edit?o=U&feature=vm&video_id=331PilOmOkY

**Comment by FabioZumbi12** [comment]
Dupe things and bugs with mods you need to check with the mod owners. RedProtect just cancel sponge events and mods need to check to this eventos too to check if can break/place blocks in a region controled by plugins (i am not modder to know where or what).
