### ISSUE TITLE
Unable to use /rp start

### ISSUE THREAD

**Issue by smmmadden** [FabioZumbi12/RedProtect#243]
Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-dfc5c4a
SpongeForge: 1.12.2-2555-7.1.0-BETA-2842
Minecraft Forge: 14.23.1.2599
Windows 10 Pro x64
Java: 1.8.0_162 x64

Mods: 
![image](https://user-images.githubusercontent.com/10309346/35194847-10ef185e-fe88-11e7-8895-07aa6812744e.png)

Issue: https://github.com/FabioZumbi12/RedProtect/wiki/(1)-How-to-use
This Wiki page provides steps that do not work (at least for my server).  I've granted the redprotect.start permission node and can type in the command, but I get an "Invalid Command" when using the steps on this page. I also could not locate any schematic file that could/would be used for the command.
I'm also an OP, granted redprotect.admin and I've granted reprotect.own.redefine as LuckPerms was saying it is undefined (not set).  That didn't work so i added redprotect.* and still no luck.  Is it possible that LuckPerms isn't supported or the document is just outdated and no longer applicable?

![image](https://user-images.githubusercontent.com/10309346/35195001-f24d46c0-fe8a-11e7-8444-c0db68a2b245.png)

Thanks - Steve

**Comment by FabioZumbi12** [comment]
As we talk on discord, is not available on Sponge for now, but is a to-do ;)
