### ISSUE TITLE
Sugestões

### ISSUE THREAD

**Issue by LordBlaZze** [FabioZumbi12/RedProtect#245]
Opa, tudo bom?

1 - Ao deletar uma tô devolver  o (ou parte do) dinheiro gasto na compra da RP.

2 - Flag de dano à animais pacíficos diferente do de dano. Ex.: Eu posso tirar leite da vaca, tosquiar ovelha ou realizar trocas com Villagers mas não posso matar eles.

**Comment by FabioZumbi12** [comment]
1 - Nop.
2 - Talvez mas não por agr.
