### ISSUE TITLE
Error console

### ISSUE THREAD

**Issue by Irineu3737** [FabioZumbi12/RedProtect#247]
Error 

Plataform: Craftbukkit 

Minecraft version_  
Minecraft version: 1.7.2 

_Issue or Suggestion?_  
 Issue /Problema

 
Description:  
When I break some block in the world or I put frame, any place whatsoever, it appears an error in the console related to the plugin.Até now I had no problem with that.But I want to know what this error means. (I do not speak English, that's why I used google translator, maybe some things have been translated wrong).See a print showing a part of the error: https://prnt.sc/i7x13g

**Comment by FabioZumbi12** [comment]
You is using the version from Overcastle... this is too too old. Update to the new versions from spigot!
