### ISSUE TITLE
All regions are gone

### ISSUE THREAD

**Issue by Theelmodog** [FabioZumbi12/RedProtect#249]
Hello!

I pasted my server files on a another server of me and the redprotect regions are all gone.
But in the backup files i have the zone, and the zones inside the file. When i make it out the backup file to the main data folder and i restart the server, than the text from the file is gone.
How can i load my regions or just simply fix it? please help!
##############################################################################
Plataform:  Spigot 1.8.8
Jar version:  RedProtect-Spigot-7.2.2-b435.jar

**Comment by FabioZumbi12** [comment]
Updating to latest version is a good way.
After update to latest and if the error still, download the dev build from our jenkins (like is on our issue template form here) and try.

After all tests, paste here your console logs with the errors.

**Comment by Theelmodog** [comment]
In log makes no errors at all, and i now tested the new version but still i don't get my regions back

**Comment by FabioZumbi12** [comment]
Then your backup is with wrong data/extension. If no errors, seems nothing wrong with redprotect. Btw, join our discord.

**Comment by Theelmodog** [comment]
The region zones in the data and in the data folder the "zones text file" has nothing in it. But in the backup folder in the "zones text file" are all zones in it. I used my server in a linux vps and on the linux vps everything was fine, i moved to a normal minecraft server and after zones not working.

**Comment by FabioZumbi12** [comment]
In resume i cant help since redprotect is working fine in one of your server. I dont have in mind what can, so i cant help :/
