### ISSUE TITLE
3 Issues with Dynamp (Shifted on flat map, shifted on surface map, no cuboids)

### ISSUE THREAD

**Issue by zippoking** [FabioZumbi12/RedProtect#251]
_Put if is the **Spigot** or **Sponge** version._  
Platform:  Spigot 1.12.2-R0.1-SNAPSHOT

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RP v7.3.0

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Issue

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  

Hey FabioZumbi 12,
i have 3 issues with your plugin, specifically with dynmap integration.

1.
Here is my region ingame: [Test region ingame](https://i.imgur.com/uC6vzop.gif)
Here is my region info: [Test region info](https://imgur.com/XuuzFP5)
The green wool blocks represent the blocks i selected with the wand tool.

This is how it looks at the flat map: [Test Region flat map](https://imgur.com/KPgSq3T)
This is how i expected it: [Test Region expectation](https://imgur.com/yrVtNFQ)

As you can see, the region does not cover the wool blocks on the right side and on the bottom.
.................................................................................................................................................................................

2.
I would like to refer to an issue that i had 2 years ago :-D
https://github.com/FabioZumbi12/RedProtect/issues/32
    
The areas on Dynmap are shifted and not at the position i expected.

Same region as above. 
This is how it look at the surface map: [Test region surface map](https://imgur.com/d4DRnkk)
This is how i expected it: [Test region expectation](https://imgur.com/L5pupJd)
This is what should happen: [Test region should move up](https://imgur.com/iLAjids)

As i said, i already hat this issue, but you fixed it. Unfortunately it is not working anymore.
.................................................................................................................................................................................

3.
I want to see cuboids on dynmap.
This is my config: [Config file](https://imgur.com/Dl39vHJ)

This is how you show in the spigot forum: [RedProtect Cuboids](https://proxy.spigotmc.org/3cb9fbde8771689db0b4fb14ecdb754f7f7607dc?url=http%3A%2F%2Fi.imgur.com%2FE75UbVX.png)
This is what i expected for my region: [Test region surface map cuboid expectation](https://imgur.com/cj8jurt)
But as shown on all other pictures, on my dynmap there are no cuboids.
.................................................................................................................................................................................

Hope you can help me fix these things!  Oh by the way: here are alll pictures together:
[Imgur Collection](https://imgur.com/a/fZOV1)
Great plugin so far, as you now i used it 2 years ago and i am still using it =)

Best regards
Zippoking

**Comment by FabioZumbi12** [comment]
1- This is because the block coordinade down not represent the center of block.
About 2 and 3, i ll fix when i can but seems something changed on Dynmap.

**Comment by zippoking** [comment]
Thanks for your reply!

About 1: 
I dont think i fully understand. Is this my problem? Or is this just the way your plugin handles the coordinates?

About 2 and 3: 
I hope the issue is easy to fix for you, because it looks way better when everything is in position ;)

Best regards
Zippoking

**Comment by FabioZumbi12** [comment]
Try the latest version from dev builds http://areaz12server.net.br:8080/job/RedProtect
I tryed to fix the region to be on the center of block, not about cubo regions

**Comment by zippoking** [comment]
I don´t know what to say except: Perfect!

Look at my areas now:
[Test Area 1](https://imgur.com/mAqtgnv.png)
[Test Area 2](https://imgur.com/NPl7i4b)

Thank you very much!

All you got to fix now is the surface map view and the cuboids :-P


Amazing work!
Best regards
Zippoking
