### ISSUE TITLE
Where does redproteect.own.claim fall under?

### ISSUE THREAD

**Issue by smmmadden** [FabioZumbi12/RedProtect#254]
In the permissions listing [here](https://github.com/FabioZumbi12/RedProtect/blob/master/RedProtect-Spigot/src/main/resources/plugin.yml), it shows the parent and child permission nodes, but this statement showing two methods to claim land, makes reference to a permission not documented (redprotect.own.claim).  Is this valid or is the redprotect.use enough?
#Method 2: Use /rp wand to get the wand tool or give the wand tool to player using your kit plugin. Hit the 2 opposite points in the region you want to protect and use the command /rp claim [nameOfRegion] [additionalOwner] to claim the region with you as owner. (need the permission redprotect.own.claim)

Where does this permission live under for the parent?

**Comment by smmmadden** [comment]
ah okay, thank you for the quick reply.  Will add all the child perms to the users.    The question was more about redprotect.own.claim as it isn't listed as a child permission node on that page showing the code of each parent/child relationship.

**Comment by FabioZumbi12** [comment]
Its because is no more needed. This is controlled via config.

**Comment by smmmadden** [comment]
okay, so this is just a documentation bug and that it should be redprotect.user not redprotect.own.claim for bukkit/spigot servers OR all redprotect.xxx child perms for Sponge servers. right?

**Comment by FabioZumbi12** [comment]
Just give `redprotect.user` to your user groups on Sponge, on Bukkit is not needed.
