### ISSUE TITLE
AreaShop & RedProtect

### ISSUE THREAD

**Issue by SchattenritterX** [FabioZumbi12/RedProtect#255]
Hey Bud!
I'm using AreaShop & WorldGuard and RedProtect cause the RedProtect Rent feature is actually in development(?) and doesn't work properly.

In my World can't Members Build so I set it in the RedProtect globalflags.yml to false. That's works fine. Buying Regions works fine Too.

But the Problem is that RedProtect overwrites the WorldGuard flags in the AreaShop defined Region, so Members can't build there. Is there a way to fix it?

Maybe some exceptions so RedProtect don't have access on this defined area?

//edit
AreaShop have the option to Blacklist some Regions like "__global__" from WG. Does RedProtect have a name for the GlobalFlags too, so i can Blacklist it?

**Comment by CloudeLecaw** [comment]
you have a globalflags.yml.....

**Comment by SchattenritterX** [comment]
Now I understood and fixed it. I've just created a non-buyable RP Region with the Flag Build: allow in the AreaShop Region with the default AS Flags (build:non-members deny etc.). Why does everything has to be so complicated xD

I hope the rent-system will be implemented soon :(

Thanks.
