### ISSUE TITLE
Suggestion: new Region Flag: Dynmap

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#256]
an Owner in Spigot needed this Feature, i looked and saw that here is no Suggestion for this, so i created it now : )

a Region flag called **dynmap**
What should this falg do?: - Show a Region a dynmap or not
Values: true / false
Info: Only works if dnymap is used on the Server ;)
Default value: true

what is it for?
Some owners dont want ALL Regions to be shown on dynmap.
This would be an easy way to blend not needed once out, or set the Default config value to false if u dont want Region automaticly in dnymap.

**Comment by zippoking** [comment]
Yeah that was me^^.

I really need the dynmap flag. I have some quests area protected with RedProtect, but the areas are visible on dynmap. That is waaaaay to easy!

Hope you consider this new flag.

Best regards
Zippoking

**Comment by FabioZumbi12** [comment]
Added on https://github.com/FabioZumbi12/RedProtect/commit/d51bf553c2b480428c399a0caa283bbc05fb93bf

Try the latest dev build.
