### ISSUE TITLE
Question about cost of claiming blocks

### ISSUE THREAD

**Issue by fsgmhoward** [FabioZumbi12/RedProtect#258]
_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Sponge

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-7.3.0-b68-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Issue

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  
In the RP's economy's config file, I have enabled claim-cost-per-block:
```
claim-cost-per-block {
    cost-per-block=1
    enable=true
    y-is-free=false
}
```
I have installed TotalEconomy (version 1.8.0) as well. When I claim blocks, the claiming process is completed without deducting money from the wallet (I check by `/money` before and after I `/sp claim`). I tried both claiming by wand and claiming by signboard and none of them works.

I didn't find the explanation in the wiki.

One more thing, is it possible to let RP only claim until a certain height? I found that for both ways to claim, the claiming region will be stretched to the upper limit of height.

**Comment by Frosthaven** [comment]
I ran into this point of confusion as well and could use some clarification!

Plataform:
 * forge-1.12.2-14.23.2.2611-universal.jar
 * spongeforge-1.12.2-2611-7.1.0-BETA-3002.jar

Minecraft:
 * 1.12.2

RedProtect:
 * RedProtect-7.3.0-b68-Universal.jar

TotalEconomy:
 * TotalEconomy-1.8.0.jar

**Comment by FabioZumbi12** [comment]
Economy whas removed from new redprotect versions.
