### ISSUE TITLE
Repeating Error: "Could not pass InteractBlockEvent$Secondary$MainHand$Impl to Plugin{id=redprotect..."

### ISSUE THREAD

**Issue by Sora101Ven** [FabioZumbi12/RedProtect#259]
Platform:  Sponge - Version: spongeforge-1.12.2-2611-7.1.0-BETA-2990.jar

Jar version:  RedProtect-7.30-b68-Universal.jar (Sponge)

Minecraft version:  1.12.2

What you want?:  Issue:

"Could not pass InteractBlockEvent$Secondary$MainHand$Impl to Plugin{id=redprotect, name=RedProtect, version=7.3.0, description=Complete antigrief plugin, authors=[FabioZumbi12], source=\mods\RedProtect-7.3.0-b68-Universal.jar}"

Description:  Hey, I'm part of staff running a Pixelmon Server (Latest version being Version 1.12.2-6.2.3) and we're looking far and wide for a protection plugin for both admin regions, and player claims. Your mod is amazing, solid stuff... but there's this issue, that eventually leads to the server chopping up and eventually breaking

The "Could not pass..." message gets spammed in our console, and as soon as it's thrown the server experiences choppy connection and minor blocklag, eventually breaking entirely with massive amounts of sponge failures which cause the server to fail.

If you could have a look at this, I'd greatly appreciate it! I'd love to continue using this mod as much as possible. Contact me if you need info like configs or modpack info.

Here is the pastebin for the repeating error: https://pastebin.com/zW2JvnsG

**Comment by FabioZumbi12** [comment]
This is already fixed on latest dev builds! 
Download from our jenkins: http://areaz12server.net.br:8080/job/RedProtect
