### ISSUE TITLE
When I promote people to high ranks in a region, it does not change their allow-place, allow-break  flags

### ISSUE THREAD

**Issue by coolcat93** [FabioZumbi12/RedProtect#26]
On your wiki, it states: 

Member: Can build, break blocks, place blocks, open chests and other inventory blocks, interact with all redstones, doors, buttons and armor stands and interact with all animals.

It is a little buggy, I had some trouble trying to allow members to be able to break it. I think you should make naming the region unnecessary, and have it automatically do it for you, so you dont run into errors

**Comment by FabioZumbi12** [comment]
Sorry but i dont mean what you say. The problem is the player cant build/break with flags allow-place, allow-break set or in general? Promoting player dont allow this players to build?

**Comment by FabioZumbi12** [comment]
Have you tryed the latest versions? Still the problem?

**Comment by FabioZumbi12** [comment]
Closing... if still, reopen the issue.
