### ISSUE TITLE
Spammed server-enter-command

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#260]
In the latesst redprotect i saw when i setup a flag server-enter-command and move inside the region then the command got spammed to the player: this means currently u just can use  "Siltencommands" there.

This is the command i used: **/rp flag server-enter-command cmi walkspeed {player} 0.5**
Result when moving inside the Region:
![image](https://user-images.githubusercontent.com/12080017/38386923-9b159b5c-3916-11e8-9842-1c50bba1d3dd.png)

So pls try to find a solution for this :3

**Comment by FabioZumbi12** [comment]
Post updates on that topic.
