### ISSUE TITLE
Pixelmon Infinite Berry/Apricot Blocks in protected regions

### ISSUE THREAD

**Issue by Sora101Ven** [FabioZumbi12/RedProtect#261]
Platform: Sponge - Version: spongeforge-1.12.2-2611-7.1.0-BETA-2990.jar

Jar version: RedProtect-7.40-b81-Universal.jar (Sponge)

Minecraft version: 1.12.2

What you want?: Issue:

Normal players who collect berries or apricots will recieve a 'Can't build here!' message while interacting with the plants-- however, they will recieve the item they collect when doing so, despite the plant being restored back to full growth-- thus creating an infinite collection bug.

It's a block placement issue, so I was wondering if there was a whitelist I can possibly access to handle these items? It's definitely not an easy fix, and I'm terribly sorry about this being a separate-mod issue. 

Thank you for your help!

**Comment by FabioZumbi12** [comment]
This is a Pixelmon issue and is happening with other antigrief plugins too. Will be fiexd on next pixelmon build.
As for now, you can allow players to break only berries on wilderness adding the list of berris blocks on `globalflag.conf`, on `if-build-false > allow-break`, or something like this:

```
if-build-false {
        break-blocks=[
            "pixelmon:poke_chest",
            "pixelmon:berrytree_[a-z_]+"
        ]
        place-blocks=[]
    }
```

**Comment by Sora101Ven** [comment]
I'm glad to hear it, thank you. I'll look into donating soon because of you're incredibly fast replies and feedback. Your plugin has helped out insanely with our server, given the lack of plugins nearly as polished as yours. Thanks again for your support bud!

**Comment by Sora101Ven** [comment]
Ah crap, still didn't work, people are able to constantly click on the berry bushes still and farm infinite berries.

I have the pastebin here: https://pastebin.com/DX00bX7p

I'm trying my hardest to understand the reason why this config ain't working but I'm drawing a blank. I'll post here one more time in hopes of a fix being figured out but I understand if I'm pushing your patience. Thanks again!

**Comment by FabioZumbi12** [comment]
This config will only work if you set the flag `build` to false. 

You is using `need-claim-to-build` config?

**Comment by Sora101Ven** [comment]
No players are allowed to build without claim (build in the wilderness) is that the only way of fixing the problem is setting it so claims are needed for building?

**Comment by Sora101Ven** [comment]
**I FIXED IT!** I'm so sorry sir for being full potato! I fixed it by setting "if-build-false" to "if-build-true" for my settings!

**THANK YOU** again for giving me your support!!! I'll donate as soon as possible!

**Comment by FabioZumbi12** [comment]
Cheers!
I will close this issue as we need to wait Pixelmon to fix this at all.
