### ISSUE TITLE
"Could not pass MoveEntityEvent$Impl to Plugin{id=redprotect...

### ISSUE THREAD

**Issue by Sora101Ven** [FabioZumbi12/RedProtect#262]
**BEFORE** I say anything, you have been a seriously great help, and just wanted to say I have done what I said before, and donated to you for your help, along with making the wonderful plugin. Name being L***n Ju***j (hidden on purpose here)

Platform: Sponge - Version: spongeforge-1.12.2-2611-7.1.0-BETA-2990.jar

Jar version: RedProtect-7.40-b81-Universal.jar (Sponge)

Minecraft version: 1.12.2

What you want?: Issue:

A repeating error is going through the console, similar to an issue I had before with the previous iteration of redprotect, but for a different reason.

"Could not pass MoveEntityEvent$Impl to Plugin {redprotect..." "...INFO java.util.ConcurrentModificationException: null"

It's hard to track down the cause or reason, but I should mention once more we are running a pixelmon server, and it's unsure if it's something on our side as far as configs.

Once again, thanks for your help!

Pastebin Here: https://pastebin.com/Y2w9UhGj

**Comment by FabioZumbi12** [comment]
Thank you so much man!!

Try the latest dev build. I didnt have tested but aims to fix this issue.

**Comment by Sora101Ven** [comment]
Awesome! Will give it a shot!

**Comment by Sora101Ven** [comment]
Mmk, unfortunately not, still getting the error, as logged here:

[Sponge]: Could not pass ChangeBlockEvent$Break$Impl to Plugin{id=redprotect, name=RedProtect, version=7.4.0, description=Complete antigrief plugin, authors=[FabioZumbi12], source=/mods/**RedProtect-7.4.0-b84-Universal.jar}** 15.04 03:21:28 [Server] INFO java.util.ConcurrentModificationException: null
