### ISSUE TITLE
RP name with special char or not a STRING char can cause an error on the data yml.

### ISSUE THREAD

**Issue by DrOreo002** [FabioZumbi12/RedProtect#264]
Plataform:  Spigot 1.12.2

Jar version:  Latest version from spigot page

Minecraft version:  1.12.2

What you want?:  Please fix this ASAP!

Description:  Any RP that has this special char (not a String)

Deff++
CC+
==:
;v
_______________: 
---------H : 

Will cause an error. Don't ask me any other question, cus I've reported this to the dev earlier and he ask me to open an issue on github so he won't forget to fix it.

Ty

**Comment by FabioZumbi12** [comment]
Done!
