### ISSUE TITLE
Permissions player

### ISSUE THREAD

**Issue by TimingsFix** [FabioZumbi12/RedProtect#265]
I want to give a player permission to fly on his region
but what this permissions ?
please help

**Comment by CloudeLecaw** [comment]
try to give them       - redprotect.bypass.world

i know it sounds strange but this permission was Blocking the flying in the regions where i wanted it to tallow for them

**Comment by FabioZumbi12** [comment]
On `rp  flag` theres the `fly` flag, just enable and the player will be allowed to fly.
