### ISSUE TITLE
API documentation & API methods too RedProtect specific

### ISSUE THREAD

**Issue by MisterFixx** [FabioZumbi12/RedProtect#268]
Hello, iv'e had problems working with the RP API basing my knowledge from the API wiki, a lot of the API methods are not documented at all and those which are documented aren't documented well.

Also i would like to create RP regions with the RP API without RedProtect sending messages to the player, as far as i see there's currently no way to do this with the API. 
What i would suggest is either removing the messages completely from the API methods or have a boolean with the API methods that would send messages only if true. 

Thank you.

**Comment by FabioZumbi12** [comment]
Hi,

You can create the region with the construtctor `new Region(...)` and add this region to db with `RedProtect.rm.AddRegion (Region, World)`

**Comment by VaiTon** [comment]
Can you explain why do you think that the `new Region(...)` is inconvenient?

**Comment by MisterFixx** [comment]
I hope you realize it's been _over 8 months_ since i opened this issue, i don't even remember what i was working on.

**Comment by VaiTon** [comment]
Yes I do, but I was scrolling through the issue list to see which issues could be closed. So please close the issue if you don't consider this as an issue anymore.
