### ISSUE TITLE
ERROR Could not pass event SignChangeEvent to RedProtect v7.4.0

### ISSUE THREAD

**Issue by DrOreo002** [FabioZumbi12/RedProtect#269]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: spigot 1.12.2 (Latest)

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-Spigot-7.4.0-b90.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Fix this

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  https://pastebin.com/mjQnYFbv

**Comment by FabioZumbi12** [comment]
Fixed on latest dev build
