### ISSUE TITLE
Spamming Error Message to Players (Help)

### ISSUE THREAD

**Issue by EnderGamingFilms** [FabioZumbi12/RedProtect#270]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Sponge 1.12.2 - 2655

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-Spigot-7.0.3.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Issue

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  Chat/Player is being spammed with "You Cannot hurt passive mobs" (or whatever the error message is) and I don't know how to stop this? (It is happening without them doing anything)

https://imgur.com/Rgpw0Lt.png

**Comment by CloudeLecaw** [comment]
to be honest..7.0.3 is a loong outdated version...
[we are currently on 7.4. build 98 please test this one with your spigot 1.12.2](http://areaz12server.net.br:8080/job/RedProtect/98/)

**Comment by EnderGamingFilms** [comment]
That has fixed the problem... Also I meant to say I was using 7.3.0, my bad.
