### ISSUE TITLE
Region name cant be a chinese string

### ISSUE THREAD

**Issue by PorPit** [FabioZumbi12/RedProtect#273]
Plataform: sponge

Jar version: RedProtect-7.4.1-b101

Minecraft version: 1.12.2

What you want?: Issue

Description:

region name cant be a chinese string

(that is feasible in old version)

(common chinese words unicode range: \u4e00-\u9fa5)

**Comment by FabioZumbi12** [comment]
I think i fixed this (didnt tested) on latest dev build: http://areaz12server.net.br:8080/job/RedProtect/

**Comment by PorPit** [comment]
fixed~
there is a new issues #274
