### ISSUE TITLE
[imp!] claim override issues

### ISSUE THREAD

**Issue by PorPit** [FabioZumbi12/RedProtect#274]
Plataform: sponge

Jar version: RedProtect-7.4.1-b102

Minecraft version: 1.12.2

What you want?: Issue

Description:
For example：
when a player "PorPit" cliam a region call “myregion”
after if other player cliam a region and use same name"myregion"

the PorPit's region:"myregion" will be override and removed!

**Comment by FabioZumbi12** [comment]
Check #273 for update!

**Comment by FabioZumbi12** [comment]
I sayd that because you mentioned the build 101. I'll check ✅

**Comment by FabioZumbi12** [comment]
Fixed on latest dev builds
