### ISSUE TITLE
Add flag godmode

### ISSUE THREAD

**Issue by Fiks75** [FabioZumbi12/RedProtect#279]
Please add flag region godmode on or off. Exampe /rp flag godmode [true/false].

RedProtect 7.3.0

Server version: Spigot 1.12.2-R0.1-SNAPSHOT
CraftBukkit version git-Spigot-2086bb0-8cc5a7e

**Comment by FabioZumbi12** [comment]
Probally i will add (when i have time).

**Comment by CloudeLecaw** [comment]
why a godmode flag? doesnt godmode dont du anything else then let you taking no damge?there is a flag for that  player-Damage that can be set true/false

**Comment by FabioZumbi12** [comment]
Or using the command flag too!
