### ISSUE TITLE
[Request] More interaction with Dynmap

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#281]
A spigot user "starnos" asked for some extansion of the dynmap-feature.

He asked if it is possible to add color and icon support for the regions shown in dynmap.

it would be nice if "server"-regions and user-regions would have its own in config definable defaultcolor and defaultsymbol if none Special is set

so would this be possible to add?

**Comment by supertin** [comment]
Extending on that thought, a region flag for the dynmap colour would be nice in some circumstances. Would make for a nice perk for donors, for example. Or allow admins to colour code different zone types for whatever reason.

**Comment by FabioZumbi12** [comment]
Its possible, but not for now.

**Comment by FabioZumbi12** [comment]
@thomas-worm on #383 

It would be great if the dynmap interaction can be extended. We would like to set the colors of the area markers and categorize the areas, so for example have blue areas for server zones, red areas for user zone and yellow area for special infrastructure zones like railroad lines. Would be great if these categories are extra layers for dynmap so the user can choose which layers to view.

**Comment by FabioZumbi12** [comment]
Added some options on latest dev build, but not all of your suggestions!
