### ISSUE TITLE
[Request] RegionFlage for Vine and Mycell

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#283]
When setting up a region with and designing it with mycell and vine ist a bit annoying
when the vine haning Kilometers after a while and the grass is converted to mycell completly after while
so two RegionFlags (also for Players Maybe) would be needed:
Since 1.13 a extra flag (or integration) would be nice to be able to stop seagras growing.. Currently they grow allways up to the top of the water where ever they grow ;*

**mycelium-spread** -  state: true/false - Whether mycelium will spread
**vine-growth** - state: true/false - Whether vines will grow
Since 1.13:
**seagras-growth** - state true/false - let seagras grow ir not

**Comment by FabioZumbi12** [comment]
Probally will add, but not for now.

**Comment by aurel85** [comment]
For vines this could just be added in **can-growth**.

**Comment by FabioZumbi12** [comment]
Added vines and seagrass to can-grow, mycelium depends of chunk. try the latest build.
