### ISSUE TITLE
Claimed houses getting unclaimed sometimes after some time or restart

### ISSUE THREAD

**Issue by YumaYamamoto** [FabioZumbi12/RedProtect#285]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: spongeforge-1.12.2-2705-7.1.0-BETA-3206

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-7.3.0-b68-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12

_Issue or Suggestion?_  
What you want?:  Issue help

Description:  Sometimes after my members claimed there house everything works fine but after some hours or after a server restart its not claimed anymore.

**Comment by CloudeLecaw** [comment]
Pls try Version RedProtect_7.4.1-Build111.jar and tell us if the issues still exists

**Comment by FabioZumbi12** [comment]
Too old build. You probally have crashes and erros on your logs but unnusable if you still using an outdated version.
