### ISSUE TITLE
RedProtect and GraveStone Mod problem

### ISSUE THREAD

**Issue by Goju-Sulfam** [FabioZumbi12/RedProtect#288]
_Put if is the **Spigot** or **Sponge** version._  
Platform: Sponge

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version: RedProtect-7.4.1-b108-Universal.jar

_Your server Minecraft version_  
Minecraft version: 1.12.2 (forge version 1.12.2-14.23.4.2705 / Sponge version 2705-7.1.0)

_Issue or Suggestion?_  
What you want?: Issue

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  

I have a modded forge server with Sponge and RedProtect, with the "GraveStone Mod" installed.

The grave appears in the wilderness at a player's death as expected, but not in a region. In this case, RedProtect cancels the build of the grave and say player don't have the permission to build in that region in the chat. In fact, RedProtect works totally as expected, but it's not what myself and my players need in that particular case.

I think the most easy way to make the grave work everywhere is a list of block ignored by RedProtect anti-build feature in the configuration file. In this case I will just have to add the grave block in the configuration and we have no longer a problem. It's possible to add that ?

**Comment by FabioZumbi12** [comment]
Probally yes, but not for now.

**Comment by FabioZumbi12** [comment]
Oh, i think i added a wrong asnwer before. Redprotect will not interact with other mods because is a plugin. Mods need to check for correct events from forge/sponge.
