### ISSUE TITLE
/rp cancelbuy does not exist anymore

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#293]
Hi,

Spigot 69774b3-e3c21de
RedProtect-7.4.1-b111-Universal
Minecraft 1.13
Issue

The /rp cancelbuy command no longer exists in this version, so it is impossible to cancel the sale of its claim. Is this normal ?

Thank you in advance.

**Comment by FabioZumbi12** [comment]
All things about region sell/buy was removed
