### ISSUE TITLE
Sponge Crash

### ISSUE THREAD

**Issue by GershonR** [FabioZumbi12/RedProtect#295]
Platform: spongeforge-1.12.2-2705-7.1.0-BETA-3374

Jar version:  RedProtect-7.4.1-b111-Universal.jar

Minecraft version:  1.12.2

What you want?:  Plugin causes server crash

Description:  Crash Report https://hastebin.com/iqewofazaj.pl

**Comment by FabioZumbi12** [comment]
Your servers crashed probally because other reason. redProtect is on logs because is trying to get the region from database until the cresh is not responding.
