### ISSUE TITLE
/rp sell and /rp buy with 7.5.0

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#296]
Hi,

Spigot 1.13
RedProtect-7.5.0-b112-Universal.jar
Minecraft 1.13
Issue

As told in #293 the claim sale has been removed from RedProtect but we can still do /rp buy and /rp sell while in /rp help these orders are no longer present.

And concerning the claims already on sale during the passage in 7.5.0 what will happen to them ? They will remain for sale without possibility to buy them or something else will happen ?

**Comment by Darkilen** [comment]
Btw, commands for buy or sell are still here in 7.5.0 :

 - `/rp buy` : https://github.com/FabioZumbi12/RedProtect/blob/edfa47dc4dc480b366eadb8f66c21cef837100c0/RedProtect-Spigot/src/main/java/br/net/fabiozumbi12/RedProtect/Bukkit/listeners/RPCommands.java#L1846
 - `/rp sell` : https://github.com/FabioZumbi12/RedProtect/blob/edfa47dc4dc480b366eadb8f66c21cef837100c0/RedProtect-Spigot/src/main/java/br/net/fabiozumbi12/RedProtect/Bukkit/listeners/RPCommands.java#L1867
 - version : https://github.com/FabioZumbi12/RedProtect/blob/edfa47dc4dc480b366eadb8f66c21cef837100c0/RedProtect-Spigot/pom.xml#L6

**Comment by aurel85** [comment]
Ok !
