### ISSUE TITLE
worldedit integration

### ISSUE THREAD

**Issue by Pa4ok** [FabioZumbi12/RedProtect#297]
please add a worldedit integration, when players can create regions with 
wooden ax (now if i set it in config, your plugin cancel blockcreakevent early than worldedit and there is no visual border) and have borders from wecui
also maybe see borders of region from wecui by /rp border command
sorry for my english)
I think that the current system with borders of regions through the light-stone is a bit strange

wecui forgeeddition:
https://minecraft.curseforge.com/projects/worldeditcui-forge-edition-2

worldedit sponge plugin:
https://ore.spongepowered.org/EngineHub/WorldEdit/versions

**Comment by CloudeLecaw** [comment]
we just have 16 issues open...so pls close this one an add ypour Suggestion here too:
https://github.com/FabioZumbi12/RedProtect/issues/282

**Comment by CloudeLecaw** [comment]
_Copy&paste_

> I never heared of WorldEditCUI but i can understand that u want One Tool that is uses by all Plugins, WorldEdit and RedProtect and may others too..personaly i dont think this is a so good idea..but everyone has an other opinion about that.
> i can understand you, but the problem is if u allow your players using the RedProtectwand for RegionCreation then you would also allow them to use the WorldEditWand that may could be missused.
> So pls Fabio, If u should think about adding the WorldEditWand as a selectiontool for RedProtect pls make it just optional.
> Else WorldEdit would be a HardDepency then and may not all servers wanne use WorldEdit even if it one of the may most used and well known Plugins :-p, Ist also not nice to say "You have no WorldEdit? then u cant use the seletiontool"...
