### ISSUE TITLE
erors on sponge

### ISSUE THREAD

**Issue by Pa4ok** [FabioZumbi12/RedProtect#298]
first:
https://gist.github.com/Pa4ok/6b4b01e5cf1952de92faa5a5960126c4

second:
https://gist.github.com/Pa4ok/273c35c03799255898ca2b6130792b47

third:
limits for rg blocks by permissions on luckyperms dont work
plugin contining see in config limit

fourth:
what is the max distans beetwen magicclaim point (1200), players can't create big regions and i can't find it in config

Minecraft : 1.12.2                                                                                                                                                                                          
SpongeAPI : 7.1.0-SNAPSHOT-7105dfc                                                                                                                                                                          SpongeForge : 1.12.2-2705-7.1.0-BETA-3371                                                                                                                                                                    
Minecraft Forge : 14.23.4.2739

**Comment by FabioZumbi12** [comment]
Try the latest version: https://ore.spongepowered.org/FabioZumbi12/RedProtect/versions

**Comment by Pa4ok** [comment]
https://gist.github.com/Pa4ok/bd8817feb62a3cccbda73035ee3b27b3
not work

**Comment by lewisclement** [comment]
I'm having the same problem: " java.lang.NumberFormatException: For input string: "750-b115" "

**Comment by FabioZumbi12** [comment]
For now open the jar with winrar or zip and edit mcmoc.info on notepad and remove the -b115

**Comment by lewisclement** [comment]
That doesn't seem to have any effect

**Comment by FabioZumbi12** [comment]
Then return to v 7.4.1 ultil i am on my home and fix

**Comment by FabioZumbi12** [comment]
Updated to work with api 7 again. Download from sponge ore.

**Comment by Pa4ok** [comment]
server started normaly)

**Comment by Pa4ok** [comment]
the same error with itemdropevent
https://gist.github.com/Pa4ok/aa3fc0ba1b62ac5e3537adf6a315d846

**Comment by FabioZumbi12** [comment]
Fixed on latest public build
