### ISSUE TITLE
/rp buy Error Testing

### ISSUE THREAD

**Issue by RogueCmdr** [FabioZumbi12/RedProtect#3]
When a user on my server does /rp buy it says invalid command but my admins and I are able to use the /rp buy. Also when you sell a region or buy a region is auto renames it to your name ex RogueCmdr_0

**Comment by FabioZumbi12** [comment]
The rename is purposeful, but i can add an option on economy.yml to let the old name if you want. You give ther permission "redprotect.eco.use" for your players? I've tested and worked too!

**Comment by FabioZumbi12** [comment]
I think this is fixed!
