### ISSUE TITLE
Can't set pos1 and pos2 using the wand

### ISSUE THREAD

**Issue by tastiestemperor** [FabioZumbi12/RedProtect#300]
**Versions**
Platform: **SpongeForge: 1.12.2-2705-7.1.0-BETA-3361**
RedProtect: **RedProtect-7.5.0-b114-Universal**
LuckPerms: **LuckPerms-Sponge-4.2.17**
Minecraft version:  **1.12.2**

**Problem**
When using the wand can't set Pos1 or Pos2, generates error in console.

**Errorlog**
Link: [Log](https://hastebin.com/sagomobiju.rb)

**What I changed**
I added the *redprotect.user* and the *redprotect.magicwand* permissions to the group (for /rp wand and the default perms) and made the following changes to the *config.conf*
`   world-types {
            DIM-1=WAND
            DIM-222=WAND
            DIM1=WAND
            DIM2=WAND
            world=WAND
    }`

**Comment by FabioZumbi12** [comment]
Try the build 115 
https://ore.spongepowered.org/FabioZumbi12/RedProtect/versions

**Comment by FabioZumbi12** [comment]
Fixed on latest public builds.
