### ISSUE TITLE
[Bug] - Smart Door flag

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#302]
if the smartdoor flag is enaled then it often habens that the doors get a wrong Position after open and plates opens them

![image](https://user-images.githubusercontent.com/12080017/43831236-c0c0cc06-9b03-11e8-986a-9aa7ce9dbc43.png)

**Comment by FabioZumbi12** [comment]
Yeah, very weird. Looking for a fix!

**Comment by FabioZumbi12** [comment]
Fixed on latest dev bilds.
