### ISSUE TITLE
ic2 integration and chisel fix

### ISSUE THREAD

**Issue by Pa4ok** [FabioZumbi12/RedProtect#305]
please add ic2 integration for mining laser
it can destroy blocks in regions by all players

and for chisel:
chisel can't change blocks from Chisel mode in regions by all players
but sometimes it can change some vanila blocks like stome bricks

PS: sorry for my english and add wecui integration)

**Comment by CloudeLecaw** [comment]
a mineing laser...what the...where is the time of the good old picaxe? 🗡 

If your mininglaser destorys blocks of other Players it mean that your Plugin irgnore all other simply replace or destorys a block. this laser is no Player so i dont think it can be blocked. u Need to ask the dev of the mininglaserplugin to hook redprotect.

Also this Problem Sound like it will also happen with all other type of protection Plugin, worldgaurd,griefprevention,etc,,,

**Comment by FabioZumbi12** [comment]
Correct, the mod need to check the sponge events about break/placeblocks. redprotect just cancel the place/break block events from sponge. Is not RP fault (as a plugin is not a mod).
