### ISSUE TITLE
Existe alguma forma de fazer uma area não protegivel por RP?

### ISSUE THREAD

**Issue by TiNTin0TAG** [FabioZumbi12/RedProtect#307]
Eu fiz o Spawn do meu server no mesmo mundo que os players fazem suas RP's e protegi essa área usando o worldguard, porem os players começaram a fazer RP's coladas na linha do Spawn, tem como colocar uma distancia mínima para RP's? eu quero que eles consigam construir perto do Spawn, so não quero eles fazendo RP's.

**Comment by FabioZumbi12** [comment]
Faz a area do spawn com uma região do redprotect!

**Comment by TiNTin0TAG** [comment]
![image](https://user-images.githubusercontent.com/32472199/44006179-07ebe6b0-9e56-11e8-9eae-069ea17f6fd9.png)

**Comment by FabioZumbi12** [comment]
Isso eh configuração. Aument o valor na config "max-scan"

**Comment by TiNTin0TAG** [comment]
mas isso vai liberar para os players fazerem também não?

**Comment by TiNTin0TAG** [comment]
só quero blockar os players de fazerem RP's perto do Spawn, eu quero que eles consigam destruir os blocos ainda

**Comment by FabioZumbi12** [comment]
Faz a rp grande e liga a flag `/rp flag build true`
