### ISSUE TITLE
Can´t open flag

### ISSUE THREAD

**Issue by SirLuckey1** [FabioZumbi12/RedProtect#308]
==> Click on PREVIEW tab!

## Fill all info below to help us to find the problem are you having or with your suggestion:
If I define a new region or I if I stand in an old region. I can´t open the flag. The plugin say´s to me "An internal error occured while attemting to perform this command. Also I have a problem with double doors. They do not open synchron. That means every time one is opened and the other is closed. They also change there positions.
### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.
RedProtect-7.5.2-b116-Universal.jar
_Put if is the **Spigot** or **Sponge** version._  
Platform:
Spigot
_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  
8
_Your server Minecraft version_  
Minecraft version:  
1.13
_Issue or Suggestion?_  
What you want?:  

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:

**Comment by FabioZumbi12** [comment]
Update your guiconfig.yml with new item names: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

(or delete the guiconfig.yml and let rp to create a new one)
