### ISSUE TITLE
Still problem with doors

### ISSUE THREAD

**Issue by SirLuckey1** [FabioZumbi12/RedProtect#309]
==> Click on PREVIEW tab!

## Fill all info below to help us to find the problem are you having or with your suggestion:
After I´ve installed the new GUI-config.yml I can use the flag. But I still have the problem with the doors, which change their positions. I can also place no new blocks from version 1.13 ( not only in regions, on the whole world).
### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.
RedProtect-7.5.2-b116-Universal.jar
_Put if is the **Spigot** or **Sponge** version._  
Platform:
Spigot
_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  
8
_Your server Minecraft version_  
Minecraft version:  
1.13
_Issue or Suggestion?_  
What you want?:  

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:

**Comment by CloudeLecaw** [comment]
come one.. we a just havinbg 16 issues..ist not hard to see on one page that there is allready a thread for the door Problem with 1.13 and the latest versions.

https://github.com/FabioZumbi12/RedProtect/issues/302

**Comment by FabioZumbi12** [comment]
I cant reproduce the problem with non placeable blocks on worlds, probally a wrong configuration. And yes, the door problem can be followed on this thread #302
