### ISSUE TITLE
[bug] Permission redprotect.limit.claim. não limitando

### ISSUE THREAD

**Issue by eltonnikecasa** [FabioZumbi12/RedProtect#310]
Platform: Debian 9
Java 8
Mysql

Jar version: RedProtect-7.5.2-b116-Universal.jar

Minecraft version: Spigot 1.13

Problema com a permissão para limitar a quantidade de rps redprotect.limit.claim.

Eu somente uso o método de criação com cerca e placa, ele não mostra nada no console somente cria quantas o jogador fizer.

**Comment by FabioZumbi12** [comment]
Printa a said sdo comando `/rp limit` e `/rp cl`

**Comment by eltonnikecasa** [comment]
![sem titulo](https://user-images.githubusercontent.com/16653029/44008259-bbe2c42e-9e77-11e8-9729-ce1974f3db22.png)

**Comment by eltonnikecasa** [comment]
esse é meu user de teste ele não é op e já tem 5 rps

**Comment by FabioZumbi12** [comment]
Não tenho esse erro no meu server 1.13 que ta em produção. Se nao aparece que ele tem 5 rps nesses comandos, então nao tem mesmo. Talvez seja em um mundo que não esta carregado ou o mundo que ele nao esta. Se ele for Admin da rp tbm não conta no `/rp cl`.

**Comment by eltonnikecasa** [comment]
mais no db aparece
![sem titulo](https://user-images.githubusercontent.com/16653029/44008407-a8ea2a18-9e79-11e8-8191-5b4733839b65.png)

**Comment by eltonnikecasa** [comment]
ele não é admin eh um usuário normal sem vip

**Comment by eltonnikecasa** [comment]
Boa tarde, você está usando mysql?

**Comment by eltonnikecasa** [comment]
permissão:
redprotect.limit.claim.1
redprotect.limit.blocks.4096
comando /rp limit de um jogador com 4 RPs.
![limit](https://user-images.githubusercontent.com/16653029/44245956-fe263400-a1b1-11e8-927e-dd7269520a8d.png)
comando /rp cl
![limit](https://user-images.githubusercontent.com/16653029/44245977-231aa700-a1b2-11e8-8e88-0c4df42acb24.png)
comando /rp list
![limit](https://user-images.githubusercontent.com/16653029/44246011-46455680-a1b2-11e8-97c4-06c303a62a5b.png)

**Comment by eltonnikecasa** [comment]
Você poderia verificar quando o RP carrega os dados do DB, as quantidades que ja estão usadas pelos players.
