### ISSUE TITLE
Bug！Bug！Startled Bug！Help me！

### ISSUE THREAD

**Issue by qq1604902534** [FabioZumbi12/RedProtect#312]
When I was playing on my server, a player circled the ground in front of me, and then I dug up his territory on that draft, and I had no authority! But dig out the same square! And the cube has not disappeared. I went to the main city to try it again, and it turned out to be the same result!

**Comment by qq1604902534** [comment]
![q ark p uov 1ta6](https://user-images.githubusercontent.com/42343520/44149666-7b5f403a-a0cf-11e8-89b3-2371ba2e1548.png)
![i lybyeo0qig f4vl3b5aj](https://user-images.githubusercontent.com/42343520/44149667-7c2e091a-a0cf-11e8-94f9-e4a650e1568f.png)
![Uploading I_G`~Q3YWT~2HCN(15MS$4R.png…]()
If the box in the player's territory is put on the billboard! Players can skip permissions and use boxes. The same is true of a burning furnace. This is too scary! My god?

**Comment by FabioZumbi12** [comment]
Its not RedProtect fault. Pixelmon need to check the block place/break events to allow player to build/breaks blocks. redprotect just cancel this events to call mods what can be break or not.

Report this to Pixelmon devs.
