### ISSUE TITLE
GriefPrevention migration command broken

### ISSUE THREAD

**Issue by AngellitoX** [FabioZumbi12/RedProtect#313]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: PaperSpigot:  git-Paper-1322 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-7.5.2-b116-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  The console command "rp gptorp" is not working properly with the most recent version of GriefPrevention. I have both GriefPrevention and RedProtect installed on my server.

This is the message I get:

 **Redprotect: [The plugin GriefPrevention is not installed or is disabled]**

In advance, thank you so much!
_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:

**Comment by FabioZumbi12** [comment]
Try the lates dev build.

**Comment by AngellitoX** [comment]
Portuguese translation:

A conversão terminou no meu banco de dados MySQL. Eu reiniciei o servidor SEM GriefPrevention para finalmente testar as regiões, e quando entrei no meu servidor para verificar, as regiões não foram reconhecidas pelo servidor, mas as regiões estão dentro da tabela de banco de dados MySQL.

Eu tentei /rp mysqltoyml  e mudei o **file-type** dentro da configuração para "yml" e, em seguida, as regiões foram reconhecidas.

Conclusão: Existe um problema com a informação reorganizada da conversão de GriefPrevention para Redprotect porque eu testei o banco de dados mysql e novas regiões são reconhecidas.

**Comment by FabioZumbi12** [comment]
The problems stills?
