### ISSUE TITLE
[Request] GlobalFlag PhantomSpawn

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#314]
On many Servers its hard to manage all to sleep over night in bed.
Just laying in bed is not enough to let phantoms not spawn and hunt you.
In many worlds specialy the once that concentrate more in survivalbuilding the phantaoms are a big reason for many to not come out on night anymore ;(

Is it possible to add a global flag that can be set by world like the other globalflags that disables the spawn of the phantoms in certain world?

**Comment by FabioZumbi12** [comment]
#316 related
