### ISSUE TITLE
About last night's Bug question

### ISSUE THREAD

**Issue by qq1604902534** [FabioZumbi12/RedProtect#315]
![l2p8sv _7bj q9l 8sh w5](https://user-images.githubusercontent.com/42343520/44202431-87237800-a17e-11e8-9e86-1c5870a28540.png)

**Comment by qq1604902534** [comment]
This problem has also appeared in the original edition. You wait first! Let me test it for you! I think this is not just a question of pixelmon!

**Comment by CloudeLecaw** [comment]
Hm someone mined a block... Horray...

**Comment by qq1604902534** [comment]
This is not authorized! Ignore the authority of the territory and dig for diamonds!

**Comment by CloudeLecaw** [comment]
Have minefarm flag be set to true?

**Comment by qq1604902534** [comment]
![ds e h a49tn6e7t15o_t](https://user-images.githubusercontent.com/42343520/44206501-9d383500-a18c-11e8-9126-c4107e67490c.png)
The cube fell! But it did not disappear.

**Comment by CloudeLecaw** [comment]
Ah i know what u mean, i had the same Problem with rp. I restarted the server and it was solved.

**Comment by qq1604902534** [comment]
It's the same thing that I restart here.If the box in the player's territory is put on the billboard! Players can skip permissions and use boxes. The same is true of a burning furnace. This is too scary!

**Comment by FabioZumbi12** [comment]
As i sayd, is not a RedProtect issue. Redprotect is cancelling all the correct events. Seems you have wrong configurations or other mods/plugins not allowing RP to work correctly.
