### ISSUE TITLE
Pls hes with setup of new Black&whitelist

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#316]
In the new Build 118 i found this line for Blacklist and whitelist Entities. I need a bit help with ubderstanding hiw to set it up correcT.

Here is what i understood how it shiould work:
The blacklist- here you enter mobs that should not spawn in the world.
The whitelist - here you ener mobs that should spawn in the world. 

Therebis no example how two set it up, so i tried a few varriant with entering mobs. None of them really worked. 
I added Creeper, Zombies, Phantoms
First i blacklisted them: I thought they would not spawn now anymore. "then i releaises they still sean to spawn"
Currently i dont know if its my setup or it still does not work correctly. 

Question1: could someone write some configexample with these three Entities for black and whiteliste?
Question2: why the whitelist exists? I want mobs to spawn - i do nothing   or   i dont want mobs to spawn - i add them to the blacklist... So what is the reason for a whitelist?
Question3: If i understood it correctly then the black and whitelisting only works for the wilderness. Is it possible to have the listed Entitie not spawning for the whole world no matter if it is a reagion or not?

**Comment by FabioZumbi12** [comment]
BlackList: Will not spawn.
Whitelist: Will spawn only this types, no others. 

Its explained on your own config section, including the link to entity types to add to list or the groups.

Its a list like this:

```
spawn-blacklist:
  - IRON_GOLEM
  - MOSNTERS
```
Will deny spawn all monsters and irongolem and
```
spawn-whitelist:
  - PASSIVES
```
Will spawn only passives, no other types of entities (as example).
Only wilderness for now.

**Comment by CloudeLecaw** [comment]
I see, so we just have a little problem for the moment. Example: the Phantom aggain, in a Region they spawn and now they "fly" Out into the wilderness and attack the player there. All us fine if the phantoms are blocked.  An owner said me "the Phantimspawn gets blockt by blocking passives spawn.... Are they passiv monster?... Sounds really strange..

**Comment by FabioZumbi12** [comment]
Added a options to allow or deny listed entities spawn on rps.

**Comment by CloudeLecaw** [comment]
Works brillant, thank you <3
