### ISSUE TITLE
Dupe Dupe Dupe!!!

### ISSUE THREAD

**Issue by tatsudev** [FabioZumbi12/RedProtect#317]
![-1](https://user-images.githubusercontent.com/6086122/44310512-4aef5200-a3e0-11e8-9e0b-533b253ca2ed.jpg)

**Server core:**
forge-1.12.2-14.23.4.2705-universal
minecraft_server.1.12.2
spongeforge-1.12.2-2705-7.1.0-BETA-3361
RedProtect-7.5.2-b116-Universal

**Other plugins installed:**
Dynmap-Nucleus-0.1
LangSwitch
LuckPerms-Sponge-4.1.7
NPCs-3.0.0-MC1.12.2
Nucleus-1.5.2-S7.0-MC1.12.2-plugin
Pieconomy-0.6.0
PlaceholderAPI-4.4
TabManager-2.1.2-S7.0-MC1.12.2
twentyticks
VillagerShops
worldedit-sponge-6.1.9-SNAPSHOT-dist

**How it working**
I just put bukkit with water, entered in region and many click LEFT mouse key. Duped buttons, railroads, levers, wires, etc.

RedProtect it cool design mod, i loved it with first second. I want install you mod on my server, but i can\t install this while items can duped so easy

**Comment by tatsudev** [comment]
![2018-08-19_19 00 35](https://user-images.githubusercontent.com/6086122/44310634-475cca80-a3e2-11e8-81e6-067dc4729e1c.png)

**Comment by FabioZumbi12** [comment]
Dupe is not redprotect (and any of sppnge plugins). Check on sponge forge channel.

**Comment by tatsudev** [comment]
You misunderstood me and hastened to close issue. I'm talking about the fact, that it's your pluging that provokes the appearance of the dupe. For example, in such plug-ins as GrifPrevention or FoxGuard, there is no problem.
More than sure that your plug-in intercepts events too late or does not intercept them. I'm talking about events such as pouring water and putting a block.

**Comment by tatsudev** [comment]
Please create a test private area for the player User1, just like in the screenshot, and try to use the player User2 to pour the water.
