### ISSUE TITLE
PlayerInteractEvent to RedProtect v7.5.3

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#318]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Spigot

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  
RedProtect-7.5.3-b122-Universal.jar
_Your server Minecraft version_  
Minecraft version:  1.13    ### Spigot-fe3ab0d-bfb9131 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT

_Issue or Suggestion?_  
What you want?:  
The console is written full the whole time with an error related to RedProtect. More details in the Consolen report.

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  https://pastebin.com/fJ2Te4Vq

**Comment by FabioZumbi12** [comment]
java.lang.NoClassDefFoundError: com/sk89q/worldedit/LocalWorld

You need to use the latest master build of worldedit or disable it on config in `hooks` section.

**Comment by Blueeyestar** [comment]
worldedit:
  # Use WorldEdit to paste newbie home-schematics (/rp start)? *RedProtect already can paste schematics without WorldEdit, but dont support NBT tags like chest contents and sign messages.
  use-for-schematics: **false**

is that correct??

**Comment by CloudeLecaw** [comment]
May it help http://builds.enginehub.org/job/worldedit?branch=master

Last WE version i see here is the Build 3848

**Comment by Blueeyestar** [comment]
I have both false and yet the console is spamming me with Red Protect messages about Worldedit.

 worldedit:
  # Use WorldEdit to paste newbie home-schematics (/rp start)? *RedProtect already can paste schematics without WorldEdit, but dont support NBT tags like chest contents and sign messages.
  use-for-schematics: **false**
 asyncworldedit:
  # Use AsyncWorldEdit for regen regions? (need WorldEdit).
  use-for-regen: **false**

https://pastebin.com/8hNuhnGu

**Comment by Blueeyestar** [comment]
https://dev.enginehub.org/youtrack/issue/WORLDEDIT-3713

**Comment by FabioZumbi12** [comment]
Updated and removed wrong worldedit versions.
