### ISSUE TITLE
Fish can be stolen 

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#319]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Spigot

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-7.5.3-b122-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.13

_Issue or Suggestion?_  
What you want?:  

**Fish can be stolen from their own zone even if everything is secure !!!
You only need a bucket and everyone can take the fish without rights**

**Comment by FabioZumbi12** [comment]
Try the latest dev build from jenkins.

**Comment by VaiTon** [comment]
Is this still an issue?

**Comment by FabioZumbi12** [comment]
Its fixed!
