### ISSUE TITLE
Areas on Dynmap are shifted/moved

### ISSUE THREAD

**Issue by zippoking** [FabioZumbi12/RedProtect#32]
Hey FabioZumbi12,

on my Server this is how it looks on Dynmap:
[Area on Dynmap](http://s27.postimg.org/gqbbqcvlv/Red_Protect_Dynmap_Area.jpg)

The correct area would cover the fences. So what i expected is this:
[Area on Dynmap moved](http://s24.postimg.org/qmdttfted/Red_Protect_Dynmap_Area_fixed.jpg)

Is this my mistake or on your side?
Thanks alot and btw: awesome plugin!!!!

Best regards
Zippolino

**Comment by FabioZumbi12** [comment]
The apperas like this because you is using the perpective angle, change to uper vision on dynmap and you will see the correct location. 

On truth, your regions need to appear like this: 
Perspective: http://i.imgur.com/E75UbVX.png
Top: http://i.imgur.com/WfXeW0o.png

**Comment by zippoking** [comment]
Thanks for the quick respone. 
Flat-view is clear, i understood that : [Spawn from Flat-view](http://s21.postimg.org/uzi7dfa2f/Area_topview.jpgl)


But I don´t think i fully understand the rest.

Lets talk about the surface view. Is surface view = perspective view = view from the side ?!? :-D
I still only see the flat line and not from bedrock to sky? Did i miss an option?
[Area from surface view](http://s15.postimg.org/87v2ucm5n/Area_perspective.jpg)

But once again, i thought the correct area would look like this:
[Area from survace view expected](http://s14.postimg.org/oq9tho11t/Area_perspective_new.jpg)

So the red area is exakt above the fence.

Maybe i am just overthinking it :-D

**Comment by FabioZumbi12** [comment]
Please, use /rp info inside this region and see the SizeY info and see if the MaxY is 256 and MinY is 0.

In surface view need to show like this image: http://i.imgur.com/E75UbVX.png. 
If not, i think theres a problem.

**Comment by zippoking** [comment]
Here is the output of /rp info: [Area Info](http://s18.postimg.org/xf1k2po2x/Area_Range.jpg)
For me it looks correct. It says fom 0 - 256.

Any change someone else can test it? Just create a new area and have a look on Dynmap.

Thank you FabioZumbi12!

**Comment by FabioZumbi12** [comment]
Try this version:

[RedProtect-6.5-SNAPSHOT.jar.zip](https://github.com/FabioZumbi12/RedProtect/files/214630/RedProtect-6.5-SNAPSHOT.jar.zip)

**Comment by zippoking** [comment]
Bro, you are amazing!
Look at that beautiful area: [Perfect Area](http://s23.postimg.org/8awx4kf17/Area_Perfect.jpg)

You did it with 100% perfection!
Thank you very much!

**Comment by FabioZumbi12** [comment]
Yay, good to see working as spected ^^
Thanks to report!
