### ISSUE TITLE
Frames in the regions are destroyed with a bow.

### ISSUE THREAD

**Issue by Vitoldik** [FabioZumbi12/RedProtect#320]
Platform: Sponge

Jar version:  RedProtect-7.5.3-b123-Universal.jar

Minecraft version:  1.12.2

Frames in the regions are destroyed with a bow.

Description:  Please, fix it.

**Comment by FabioZumbi12** [comment]
If i cant build, i cant remove!
Tested with Paintings and ItemFrames
![image](https://user-images.githubusercontent.com/5833818/47697339-5d101c80-dbe9-11e8-89a9-fddec91b6489.png)
