### ISSUE TITLE
/rp wand not selecting

### ISSUE THREAD

**Issue by asanari** [FabioZumbi12/RedProtect#321]
For non-admin players who are given access to the /rp wand command, left clicking and right clicking does nothing, and they are unable to claim land using the wand tool.

**Comment by CloudeLecaw** [comment]
They need permission to claim and you may need to give them the we-select permission too

**Comment by FabioZumbi12** [comment]
On config, see on claim-world the type. See comments on config.yml for available options. To use wand you dont need to setup additional perms, just change this option.
