### ISSUE TITLE
Animals aren't spawning with spawning egg

### ISSUE THREAD

**Issue by Ewallee** [FabioZumbi12/RedProtect#323]
Passive mobs aren't spawning when you try to spawn them with spawning egg.
While breeding no new animals can be created either.

RedProtect-7.5.3-b123-Universal.jar
spongeforge-1.12.2-2705-7.1.0-BETA-3422.jar
1.12.2-forge1.12.2-14.23.4.2739

**Comment by Dhannyjsb** [comment]
same issue . 
Redprotect: [RPGlobalListener - Cancelled spawn of Animal chicken]

**Comment by FridtjofDE** [comment]
Same issue with "spongevanilla-1.12.2-7.1.0-BETA-116"

**Comment by CloudeLecaw** [comment]
Well u know about the new whitelist and blacklist?

**Comment by oldBrowze** [comment]
I have the same problem.

**Comment by FabioZumbi12** [comment]
Trying to reproduce and i can spawn any mob using spawn eggs. Enter on our discord and download the latest version from latest-dev-build channel.
https://discord.gg/bfJYeca

What i tryed: 
- Using the default globalflags.config configuration with build: true
- Spawned a chicken using spawn egg on wilderness.

**Comment by FabioZumbi12** [comment]
Fixed on latest dev build.
