### ISSUE TITLE
[Request]  Better interacting with Itemframes on regions

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#326]
Currently we have the problem on our Server, that we wanted to work with itemframes where players can rightclick the item in it but not break or place or take it out of the frame. 

Problem we have here:

1. currenlty players cant interact with items in frames without build permision on this region

2. Even if they could, we would need a list where we could blacklist or whitelist items inside the feames for players without buildpermission. Else specialy trolls woukd start to change direction of maps or others that are moarly placed in frames too.

Is there any chance to create a framemanagement for the regions like this?

**Comment by FabioZumbi12** [comment]
Only to rotate and drop/put the items on frames? I think i ll not add :S

**Comment by CloudeLecaw** [comment]
Ever heard f the Redstone signal power given by diffent direction of the item, out f the frame?

this is used in manybuilings for secret doors an others
