### ISSUE TITLE
I'm kicked off the server when I enter the zone (1.13)

### ISSUE THREAD

**Issue by Soupjektiv** [FabioZumbi12/RedProtect#328]
Hello,

on my server (Spigot 1.13) I am kicked from the server, after I entered the secured area.
"Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ArryIndexOutOfBoundsException: 6" is displayed to me after I was kicked

Please help me,
Luca

**Comment by FabioZumbi12** [comment]
This is not because redprotect. Btw, not using the template, no versions and redprotect logs :/
