### ISSUE TITLE
Pixelmon

### ISSUE THREAD

**Issue by shanklm** [FabioZumbi12/RedProtect#329]
Platform: Sponge

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-7.5.3-b123-Universal

_Your server Minecraft version_  
Minecraft version:  1.12.2

After installation, you cannot generate'Pixelmon'!

I don't know what it is because of it!

I delete it and resume work!!
-----------------------------------------------------------------------
-------------------------------------------------------------------

**Comment by Darkilen** [comment]
Wrong version, please use 7.4.1 for minecraft 1.12.2.
Version 7.5.3 is for minecraft 1.13.

**Comment by FabioZumbi12** [comment]
Probally configurations. Other servers using this plugin dont have this problem (including my server)

**Comment by FabioZumbi12** [comment]
Fixed on latest dev builds.
