### ISSUE TITLE
Pressure Plate flag and removing Fire flag

### ISSUE THREAD

**Issue by Arcane-Bunny** [FabioZumbi12/RedProtect#330]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Spigot

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version: RedProtect-7.5.3-b123-Universal

_Your server Minecraft version_  
Minecraft version: 1.13

_Issue or Suggestion?_  
What you want?: Flag for pressure plates and denying people access to removing fire from blocks

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description: There currently is no way to set permissions to allow the use of pressure plates on the server. Along with this, players can remove fire when they aren't supposed to. I recommend getting all the flags WorldGuard had before it stopped working. I'll make sure to check Spigot for an update! Both of these issues are only in protected zones, and we'd need this fixed since we run a questing/rpg/dungeon delving server that has a heavy use on pressure plates and fire for traps!

**Comment by FabioZumbi12** [comment]
Both fixed on latest dev version: https://host.areaz12server.net.br:8080/job/RedProtect
