### ISSUE TITLE
How to update the Gui config

### ISSUE THREAD

**Issue by SirLuckey1** [FabioZumbi12/RedProtect#333]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Spigot

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-7.5.3-b123-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.13.1

_Issue or Suggestion?_  
What you want?:  

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  How can I change the gui config. I am sorry but I dont know how to change the gui config. Wich informations I have to put in there

**Comment by FabioZumbi12** [comment]
Just chage all the string for what you want. If you want more help about this read our wiki, but the guiconfig is already an good example.
