### ISSUE TITLE
Yaw and Pitch are Reset when reconnecting

### ISSUE THREAD

**Issue by KyroOW** [FabioZumbi12/RedProtect#335]
Platform: Spigot
Jar version:  RedProtect-7.4.1-b110-Universal
Minecraft version:  1.12.2
What you want?:  Issue

Description:  When reconnecting, the player looses it's previous camera position (yaw and pitch) making him facing south everytime he reconnect to the server.

**Comment by FabioZumbi12** [comment]
Fixed on latest dev build: https://host.areaz12server.net.br:8080/job/RedProtect/
