### ISSUE TITLE
Rp Flag Bug

### ISSUE THREAD

**Issue by TeamMage** [FabioZumbi12/RedProtect#336]
_Put if is the **Spigot** or **Sponge** version._  
Platform: Spigot

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-7.4.1-b110-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Issue

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  https://pastebin.com/vc3pAkAz This is what happened after doing /rp flag, java 8

**Comment by Darkilen** [comment]
There seems to be an error on the `gui-separator` that you defined in the` guiconfig.yml`.
Could you provide us or check your `guiconfig.yml` ?

**Comment by FabioZumbi12** [comment]
Cant reproduce, btw, try the latest dev build from our discord channel.
