### ISSUE TITLE
Animal no spawning

### ISSUE THREAD

**Issue by WareZ57** [FabioZumbi12/RedProtect#338]
Hello

Hello
I currently have a problem with the plugin, it blocks the spawn of animals in the whole map when I create regions with flags (with or without flags) and I do not see how to solve this problem knowing that the Animal lay configuration is activated!

I do not know if you will understand the problem?

Overall, when I create a region no matter the place, the flags put on this region after a reboot or any other events the animals do not spawn anymore!

Redprotect lasted version
SpongeAPI 7.1.0-FF990DF
Sponge Forge 1.12.2-2705-7.1.0-BETA-3448

Thanks.

**Comment by Siavel** [comment]
Goes hand in hand with this issue, I'm experiencing both problems.
https://github.com/FabioZumbi12/RedProtect/issues/323

**Comment by FabioZumbi12** [comment]
Follow #323
