### ISSUE TITLE
Towny Compatibility

### ISSUE THREAD

**Issue by Blackyvk** [FabioZumbi12/RedProtect#34]
Can you hook into towny ?

Deny claiming inside town, near towns ? and deny towny claiming RedProtect claims ?

or convert from towny to redprotect

**Comment by DraksterAU** [comment]
Hi There
I'm actually developing a plugin that will support this!

It is designed to prevent different grief prevention plugins from overlapping.

It will be ready by the weekend :) will post here when it is released.

**Comment by FabioZumbi12** [comment]
I can deny RP to be created inside towny but not towny inside RP... I recommend only one claim plugin.

**Comment by DraksterAU** [comment]
Towns should throw a claim event you can cancel ?
Factions does

**Comment by FabioZumbi12** [comment]
I will take a look ;)

**Comment by FabioZumbi12** [comment]
I think Towny and redprotect are two plugins to make the same work and its not recommened to work together. I will not add compatibility with towny now. Anyway, towny can hook into redprotect if want.

**Comment by Bysokar** [comment]
Tbh id have a list of plugins and prompt a warning to ops on login if they have conflicting plugins installed 

That way you provide a list of plugins not to contact you about ;)
