### ISSUE TITLE
"java.util.NoSuchElementException: No value present" error on startup(1.12.2, Sponge)

### ISSUE THREAD

**Issue by BlackjackMKV** [FabioZumbi12/RedProtect#341]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Sponge

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-7.5.3-b123-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  RedProtect won't load when the server starts, and disables itself.

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  
Consistently refuses to load on bootup. It hasn't ever worked, and this is the 7th or 8th time I've tried to get it to load without it working. I can't make heads nor tails of the 'No value present'. Anyone know what is going on or if it is at least a known issue? My best guess is that something is missing from the config, but regenerating it from scratch still won't fix it.

https://pastebin.com/1ydhNiXV

**Comment by BlackjackMKV** [comment]
Now using the RedProtect-7.5.5-b129-Universal.jar, but still hitting the same error. It seems to be the latest as far as I can tell. Any ideas?

**Comment by FabioZumbi12** [comment]
Try again from jenkins... and the error stills, whats the output of `/version` command?

**Comment by BlackjackMKV** [comment]
Typing just `version` into the console just errors claiming the command wasn't found. I AM running SpongeForge, if that might be related.

**Comment by FabioZumbi12** [comment]
Then you have something wrong: 
![image](https://user-images.githubusercontent.com/5833818/47632053-38ec0700-db27-11e8-96e7-1f895ef89f78.png)

**Comment by FabioZumbi12** [comment]
Its `sponge version`

**Comment by BlackjackMKV** [comment]
Ha, I should have guessed Sponge would have their own special command for it. Why actually follow the existing standards?

`[00:09:54] [Server thread/INFO] [minecraft/DedicatedServer]: SpongeForge
    Minecraft: 1.12.2
    SpongeAPI: UNKNOWN
    SpongeForge: UNKNOWN
    Minecraft Forge: 14.23.4.2765`

**Comment by FabioZumbi12** [comment]
Your `UNKNOWN` values mean something...

Mine is like this:

```
SpongeForge
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-ff990df
    SpongeForge: 1.12.2-2705-7.1.0-BETA-3481
    Minecraft Forge: 14.23.4.2705
```
Ask on Sponge forums and paste your sponge version output on it to someone help you!
