### ISSUE TITLE
RedProtect Inventory Client Kick

### ISSUE THREAD

**Issue by Yanniclord** [FabioZumbi12/RedProtect#35]
When i sometimes shift click and item in the creative inventory to delete it, i get kicked. Here the log: http://pastebin.com/tBYUWJBB

**Comment by FabioZumbi12** [comment]
We are on version 6.5.6 and still suporting 1.7 server. Update to this version and test again.

*IMPORTANT: Make a backup of your regions because theres a lot of changes since 6.4.4

**Comment by Yanniclord** [comment]
Ok will do.
