### ISSUE TITLE
Could not pass event BlockSpreadEvent to RedProtect v7.5.5

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#350]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform:
**Spigot-2474d93-3697ec7 (MC: 1.13.2)**

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  

**RedProtect-7.5.5-b139-Universal.jar**

_Your server Minecraft version_  
Minecraft version:  
**1.13.2**

_Issue or Suggestion?_  
What you want?:  

This error message comes in the console as a continuous loop

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  

https://pastebin.com/nHJaX3Xr

**Is it perhaps because of the plugin?:**

https://www.spigotmc.org/resources/worldeditcui-visualize-your-selection.60726/

**If so, it would be a pity. This is how the users could see which zone they had pulled before claiming.**
**or can you change something that no longer reports errors in the console?**

**Comment by FabioZumbi12** [comment]
Nop, a mistake from my part. Try the latest build

**Comment by Blueeyestar** [comment]
It works now. Thank you for doing the great job
