### ISSUE TITLE
Hook with WorldEditCUI does not work correct? or do they?

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#351]
Well i tested Redprotect Build 140 (so lttest) today with the WECUi 1.2.2 that was also made for Spigot 1.13.2

my Problem the WECUI Effect on seting the regionsize seems not to move…even when the borders allready gone...is this wanted or a bug?

![image](https://user-images.githubusercontent.com/12080017/48355369-1ebc3800-e694-11e8-95f8-7f4266cdc332.png)

**Comment by FabioZumbi12** [comment]
I really dont know what you mean...

**Comment by CloudeLecaw** [comment]
you see the Selection? this is the WorldEditCUI hook from RP
My Problem is that i still see the seletcion when the normal seen borders (glowstone blocks) disapear.
then the animated border from WorldEditCUI is still shown. my Question was. if this is wanted or not? 🥉

**Comment by FabioZumbi12** [comment]
It is. You disable with "/rp b" again

**Comment by CloudeLecaw** [comment]
Well i didnt know that this is the way how it works :§
is there any Change to add an optional timer and when enabled and it run out then it disapears?

i want my Payers to use as less commands as possible :3 but this is a great Feature for them to see their Region while try to get the claimsize of their Region :)

**Comment by FabioZumbi12** [comment]
Only using the commands for now!
