### ISSUE TITLE
Error no console, quando mata MOBS

### ISSUE THREAD

**Issue by johnbrasil** [FabioZumbi12/RedProtect#352]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Spigot e Paper

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-7.5.5-b139-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.32.2

_Issue or Suggestion?_  
What you want?:  Error when we kill any mob on mapa, insite protection or outsite protection, and console NEVER stops giving this error.

Você é Brasileiro ne... então mano, é o tempo todo dando esse erro no console, so por matar qualquer tipo de mob entendeu.. e o console não para.. é o tempo todo dando esse erro, mesmo sem matar nenhum bixo, só depois que matou o primeiro mob, pronto, esse erro o tempo todo.

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  https://pastebin.com/H4EunbQE

**Comment by FabioZumbi12** [comment]
Isso ja foi arrumado na build 140. Baixa do nosso jenkins.
