### ISSUE TITLE
Critical error caused by "flag-mobs-spawn"

### ISSUE THREAD

**Issue by Ewallee** [FabioZumbi12/RedProtect#353]
Sponge: spongeforge-1.12.2-2705-7.1.0-BETA-3446.jar
Minecraft: 1.12.2
Forge: 1.12.2 - 14.23.5.2768
Mode: none

Hello!
Found two issues so far:

1.In private region the mobs aren't burning.Makes it difficult for players to survive.
2.If you place the flag "spawn mobs=false" in private region , you get places where it is not possible to place blocks.If you switch the "allow spawn mobs=true" it appears that the places where you couldn't place blocks were overpopulated with mobs.The server starts lagging when you are near that region because of several hundreds of invisible mobs.It looks like they were spawning but have been kept invisible  on the spawning areas. After set flag to true, reload chunks they will  all break out and run all over the place.I had  yesterday ca 1000 mobs on a small area.

**Comment by FabioZumbi12** [comment]
1. I will check
2. There no flag `spawn mobs` for regions and only `passives`, or `rp flag passives true/false`. Check if you is really using redprotect and put the rp version, like is on issue template!

**Comment by Ewallee** [comment]
RedProtect-7.5.5-b130-Universal.jar

1.If you try to pick up lava with bucket in a private region(privated by other person), by quickly clicking  with empty bucket on lava- you get lava bucket dupes.

2.If you set /rp flag "Spawn monsters" =true you will get not moving monsters and you cannot kill them.
The only ways to solve this issue is to reload chunks then all monsters will be deleted.

**Comment by FabioZumbi12** [comment]
About dupe, this is a spigot problems, redprotect just cancels the event, if spigot get the returns or not, we can do nothing :/
