### ISSUE TITLE
Bypass protection using rails

### ISSUE THREAD

**Issue by Lachney** [FabioZumbi12/RedProtect#357]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Sponge

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-7.5.5-b130-Universal.jar

_Your server Minecraft version_  
Minecraft version:  Minecraft 1.12.2

_Issue or Suggestion?_  
What you want?:  You can bypass protection, specifically placement by spamming rails. It will place a rail but not remove it from the inventory and you are able to duplicate them. Here's a video: https://i.xjon.me/cvNuSz.mp4

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  https://pastebin.com/z2xFD7U6

**Comment by FabioZumbi12** [comment]
This is not a RedProtect issue. Duplication and similars need to be reported on Sponge foruns!
