### ISSUE TITLE
Item frames and Paintings aren't breakable

### ISSUE THREAD

**Issue by Geekmakes** [FabioZumbi12/RedProtect#358]
Platform: PaperSpigot Ver: Snapshot 452

Jar version:  RedProtect-7.5.5-b129-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.13.2

What you want?:  Item frames and painting to be breakable in unprotected areas.

Description:  Item frames and painting are only breakable in protected areas. I don't get any errors in console.

**Comment by Geekmakes** [comment]
Same with sugar cane can't break that either...

**Comment by FabioZumbi12** [comment]
Fixed on latest dev builds (soon on spigot page)
