### ISSUE TITLE
Color on custom welcome message

### ISSUE THREAD

**Issue by Darkilen** [FabioZumbi12/RedProtect#359]
### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Spigot (PaperSpigot)

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-7.5.5-b140-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.13.2

_Issue or Suggestion?_  
What you want?:  Issue

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  Custom welcome message on claim are gold (&4) by default, they should be white

On 7.5.5-b140 :
![2018-12-08_16 51 25](https://user-images.githubusercontent.com/22028659/49687855-bc771b80-fb09-11e8-9a62-9e86f9b3558f.png)

Before :
![2018-12-08_16 52 25](https://user-images.githubusercontent.com/22028659/49687858-ce58be80-fb09-11e8-9f41-4ecda4511315.png)

**Comment by VaiTon** [comment]
I think that you can change the color of the message just by editing the properties file in the plugin folder.

**Comment by Darkilen** [comment]
@VaiTon Where and in which file ?

**Comment by VaiTon** [comment]
@Darkilen the `langFR.properties` file or

**Comment by Darkilen** [comment]
I already check. Maybe, i miss the specific line to fix that. Could you send me the key ?

**Comment by FabioZumbi12** [comment]
Yep, you can change on lang file.

**Comment by Darkilen** [comment]
@FabioZumbi12 Could you tell me the key in lang file ?

**Comment by Darkilen** [comment]
Fixed with https://github.com/FabioZumbi12/RedProtect/commit/272141d9f5b40306e13103ef8ba9e12c3dd3e394.

Now use this key in lang files to change default formatting (text and color) for a region with a custom welcome message : `playerlistener.region.welcome`
