### ISSUE TITLE
Integration query 

### ISSUE THREAD

**Issue by DraksterAU** [FabioZumbi12/RedProtect#36]
Hi mate,

I'm looking to integrate your plugin with Regenerator, my land regeneration plugin as per a request from several people on SpigotMc.

If you have a second could you explain the best way to detect what claims are in a chunk, as well as who owns them?

Sorry to be a bother! I'll look through your code shortly just hoping you can save me some time :P

**Comment by FabioZumbi12** [comment]
Shure! You need to get the Region and the owners right? If helps, you can take a look on RedProtectAPI. This will give the region, and with region you can get the leaders. 

More info here too: https://github.com/FabioZumbi12/RedProtect/wiki/RedProtect-API

But if you want specific info i can help you ;)

**Comment by DraksterAU** [comment]
That's perfect!!!
Thanks man!

Curious, do you have ranks within regions other than owner?
Do you have a quick way to query for all regions in a chunk?

My plugin works on chunks, so if a region exists in a chunk? Looks like I would have to query every block coordinate?

**Comment by FabioZumbi12** [comment]
Yes, theres three ranks: Leader, Admin and Member, you can read the description for each rank [here](https://github.com/FabioZumbi12/RedProtect/wiki/Player-Ranks).

I dont need to get the region per chunk for players, then i dont have a method to this. But i can see what can i do... probally i need to loop into all blocks on chunk to get the region. The RP regions can be customized with max y and min y too like worldguard.

I dont know other way to get the region on chunks. If you know a better way you can share with me ^^

**Comment by DraksterAU** [comment]
Will do :)

Perhaps if I make the method, you can make it available in your API for other plugins that use chunks?

**Comment by FabioZumbi12** [comment]
Shure! Seem to be a good way to get the regions in a chunk instead to get by block locations ^^

I need to sleep now but you can join the gitter chat to we talk later https://gitter.im/FabioZumbi12/RedProtect?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by DraksterAU** [comment]
Hi @FabioZumbi12 

I've come up with this... it is VERY inefficient though.

Perhaps you can create something similar, but query the DB for positions instead?

Or Maybe you can have a getAllRegions() in the API and I can iterate through the x, y, z and world arrays and find out if the coordinates match with the chunk?


    public List<Region> getRegionsForChunk(Chunk chunk) {
        int x;
        int y;
        int z;
        List<Region> regions = new ArrayList<Region>();
        for (y = (0); y <= chunk.getWorld().getMaxHeight(); y = y+1) {
            for (x = ((chunk.getX()*16)-8); x <= ((chunk.getX()*16) + 8); x = x+1) {
                for (z = ((chunk.getZ()*16)-8); z <= ((chunk.getZ()*16) + 8); z = z+1) {
                    Location location = new Location(chunk.getWorld(), x, y , z);
                    if (RedProtectAPI.getRegion(location) != null) {
                        regions.add(RedProtectAPI.getRegion(location));
                    }
                }
            }
        }
        return regions;        
    }

**Comment by FabioZumbi12** [comment]
Cool, i have added this code on API and added getAllRegions too ^^

For players i use getTopRegion(Location) to get the high priority region, but in our case, you need to get all region on the same location if exists.

Then i added getGroupRegions(Location) to get all possible regions on the same location of other region.

Your code will be:

```
public Set<Region> getRegionsForChunk(Chunk chunk) {
        int x;
        int y;
        int z;
        Set<Region> regions = new HashSet<Region>();
        for (y = (0); y <= chunk.getWorld().getMaxHeight(); y++) {
            for (x = ((chunk.getX()*16)-8); x <= ((chunk.getX()*16) + 8); x++) {
                for (z = ((chunk.getZ()*16)-8); z <= ((chunk.getZ()*16) + 8); z++) {
                    Location location = new Location(chunk.getWorld(), x, y , z);
                    if (getGroupRegion(location).size() > 0) {
                        regions.addAll(getGroupRegion(location).values());
                    }
                }
            }
        }
        return regions;        
    }
```

A question about your plugin: Your plugin regens the world wheres no regions or plots? The regeneration is like //regen of worldedit making trees and ores back to first gen of chunk??

**Comment by DraksterAU** [comment]
Yes that's right....except my plugin does automatic regen.

You can also grant rights to players to regen certain areas too.

**Comment by FabioZumbi12** [comment]
I've updated the plugin with new API methods: https://www.spigotmc.org/resources/redprotect-1-7-1-8-1-9-anti-grief-server-protection.15841/update?update=83498

;)

Another thinks: How your plugin regen the regions? Is async like AsynWorldEdit? For now i am hooking into worldedit and AsynWorldEdit to regen the regions for away players in a configured time. Its possible to i hook into your plugin to regen only the regions instead to use worldedit+AWE?

Thanks!

**Comment by Pokechu22** [comment]
Wouldn't it be much faster to, rather than iterate through all blocks in a chunk which then iterates through all regions for each block, instead iterate through all regions and look for ones which are in a chunk?

Maybe something like this?

```java
public Set<Region> getRegionsForChunk(Chunk chunk) {
    Set<Region> regions = new HashSet<Region>();
    for (Region region : RedProtect.rm.getRegionsByWorld(chunk.getWorld())) {
        int minChunkX = (int)Math.ceil(region.getMinMbrX() / 16f);
        int maxChunkX = (int)Math.ceil(region.getMaxMbrX() / 16f);
        int minChunkZ = (int)Math.ceil(region.getMinMbrZ() / 16f);
        int maxChunkZ = (int)Math.ceil(region.getMaxMbrZ() / 16f);
        
        if (chunk.getX() >= minChunkX && chunk.getX() <= maxChunkX && chunk.getZ() >= minChunkZ && chunk.getZ() <= maxChunkZ) {
            regions.add(region);
        }
    }
    return regions;
}
```

**Comment by DraksterAU** [comment]
Hi https://github.com/FabioZumbi12

I'm not sure I follow what you mean?

You want to regenerate land that is owned by inactive players?

**Comment by FabioZumbi12** [comment]
But in the case, my build world is too big. How your plugin will know that region is marked to regenerate? What i mean is when the server start, my plugin will check the regions of inactive players and delete, then regen that region area.

**Comment by DraksterAU** [comment]
Ah! I understand.

With my plugin installed, if a RP region is deleted it will be added to the area that is automatically regenerated by Regenerator (unless you disable auto regen for that world) ... You don't need to do anything.

I can add a hook if you like.. So you can request regen on a chunk ... But it really isn't needed.

Yes it does look like a better way to do things. The way I suggested was a lot slower.

**Comment by DraksterAU** [comment]
To answer your question properly;

When a chunk is marked as "inactive and modified" by my plugin, it will check each of the supported plugins that are enabled to see if the land is claimed.

If the land is not claimed, it will regenerate. 
In the case of factions or world guard, if the land is claimed by wilderness or the __global__ region it will still regenerate, though.

**Comment by DraksterAU** [comment]
My plugin is not technically async at the moment - I'm focusing on compatibility with other plugins first.

It does check server TPS and pause regeneration if it drops below what is set in config, and resumes after it goes back above that though... So it does not cause lag.

**Comment by Pokechu22** [comment]
Whoops, looking at the code I made again I see I made a mistake: I used `Math.ceil` when I should have used `Math.floor`.  Chunk coordinates work with `Math.floor`, so using `Math.ceil` would give incorrect data at the edges of most regions.  (Similarly, you have to use `Math.floor` and can't just directly cast because otherwise negative numbers won't work right).

Corrected code:

```java
public Set<Region> getRegionsForChunk(Chunk chunk) {
    Set<Region> regions = new HashSet<Region>();
    for (Region region : RedProtect.rm.getRegionsByWorld(chunk.getWorld())) {
        int minChunkX = (int)Math.floor(region.getMinMbrX() / 16f);
        int maxChunkX = (int)Math.floor(region.getMaxMbrX() / 16f);
        int minChunkZ = (int)Math.floor(region.getMinMbrZ() / 16f);
        int maxChunkZ = (int)Math.floor(region.getMaxMbrZ() / 16f);

        if (chunk.getX() >= minChunkX && chunk.getX() <= maxChunkX && chunk.getZ() >= minChunkZ && chunk.getZ() <= maxChunkZ) {
            regions.add(region);
        }
    }
    return regions;
}
```

**Comment by DraksterAU** [comment]
@Pokechu22 Thanks for that :D Ive updated Regenerator in the meantime until RP is updated.

**Comment by FabioZumbi12** [comment]
I dont have idea on how to work with Chunk, on thuth never needed to manage chunks. I changed to your code and dont have tested. I leave this part to @DraksterAU :P 

I updated the API on this verion: https://github.com/FabioZumbi12/RedProtect/blob/master/release/RedProtect-6.5-SNAPSHOT.jar?raw=true

**Comment by DraksterAU** [comment]
Haha yeah regions are better @fabiozumbi12, but for regeneration purposes chunks are required.
Doing regeneration based on regions is stupidly complex

**Comment by FabioZumbi12** [comment]
No problem, i still using WE. Its working fine. When you finish put the news here ☺

**Comment by DraksterAU** [comment]
Hi Fabio, I think I'm done :)

Feel free to test out my plugin with RP - 
Players can regenerate their land based on permissions if they have them and unclaimed land is correctly auto regenerated.

**Comment by FabioZumbi12** [comment]
I will make a backup of my build world and test your plugin, so i have some questions but i will post on your plugin page ^^

Only on: Have you tested and the RP regions still 100%?

**Comment by DraksterAU** [comment]
Ive tested detection of RP regions, it seems to be 100%. 

My plugin is less than a week old.. please be careful..... there may be bugs :)

Report them and I will fix, though!

**Comment by FabioZumbi12** [comment]
Working like a charm ^^
