### ISSUE TITLE
[Feature Request] Spawn egg and /summon flag

### ISSUE THREAD

**Issue by duhadventure** [FabioZumbi12/RedProtect#360]
Platform: Sponge

Jar version:  RedProtect-7.3.0-b68-Universal.jar

Minecraft version:  1.12

Description:  A region flag that enables mob spawning but only for spawn eggs and /summon. This is for the creation of mob arenas  that you dont want mobs to spawn.

**Comment by FabioZumbi12** [comment]
We are on 7.5.5 where already have a option to define each type of mob is allowed to spawn or not.

**Comment by Darkilen** [comment]
@FabioZumbi12 he would like a flag for deny mob spawner only for natural spawning on a specific claim.

From [flags wiki](https://github.com/FabioZumbi12/RedProtect/wiki/(05)-Region-Flags) :
> **spawn-monsters:**
> Deny Monsters spawning in a protected region. **Include Monsters Spawners**.

**Comment by duhadventure** [comment]
> @FabioZumbi12 he would like a flag for deny mob spawner only for natural spawning on a specific claim.
> 
> From [flags wiki](https://github.com/FabioZumbi12/RedProtect/wiki/(05)-Region-Flags) :
> 
> > **spawn-monsters:**
> > Deny Monsters spawning in a protected region. **Include Monsters Spawners**.

Yea, I want natural spawning to be disabled, but still be able to spawn with spawneggs and /summon
