### ISSUE TITLE
[Suggestion] Mobarena flag

### ISSUE THREAD

**Issue by duhadventure** [FabioZumbi12/RedProtect#361]
What you want?:  A flag called arena or mob arena that only allows mobs to be spawned with commands or spawn eggs. 

Description:  Currently the only flags allow despawning mobs or only allowing certain ones to spawn or not spawn. I can disable all hostile mobs and passives from despawning, but I only want things to spawn in an area when they are summoned by command or egg. Mobs spawned by the world naturally should be disabled. 
in #360 you already said that you can stop certain groups from spawning. Still want them to spawn, just only when I or a command block personally does it.

**Comment by FabioZumbi12** [comment]
You can use other plugins to spawn only one type of mobs like InfernalMobs or letitrain. Normally other plugins force the spawn ignoring redprotect flags (as a plugin have high priority)
