### ISSUE TITLE
error with /rp reload in 1.13.2

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#362]
Hi,

With the last version of RedProtect (7.5.5 b140) and PaperSpigot 1.13.2 (486) there is a error when we do /rp reload : https://pastebin.com/bn4E4YVQ

**Comment by VaiTon** [comment]
You are using an yml file to store more than 10000 regions. I guess that's why it freezes. My advice is to switch to an sql system as soon as you can because it's certainly faster than a file.

**Comment by aurel85** [comment]
I tried to spend several times to mysql with RedProtect, but each time there are problems and as it is never really resolved I stay in yml...

**Comment by aurel85** [comment]
Yet Fabio himself has already told us to use yml rather than mysq... I would like to be able to switch to mysql because it gets too busy in yml but for now with RedProtect we can not, maybe one day...

**Comment by Darkilen** [comment]
@VaiTon Switch from yml to mysql doesn't work.
Region aren't recognize when they are switch from yml to mysql.
(And sorry if you misunderstood @aurel85, he's very bad with english)

**Comment by VaiTon** [comment]
Ah ok sorry, now i understand. I'll try to investigate.

**Comment by VaiTon** [comment]
@aurel85 I tried to create a dummy region in a dummy server and then tried to use the command /rp ymlTomysql and it works. If you have any different behavior feel free to post the log and tell what happened after the error.

**Comment by aurel85** [comment]
The passage from yml to mysql works I know it. The problem in mysql it's the lag when we do /rp claim (even worst that in yml).  And I don't want to hear that I have too many regions, it is not normal that we can't use properly RedProtect when we have exceeded 10,000 regions in the server. We know where the problem comes from but nothing is done : In the plugin writing, the way the regions are caculated is not good, it checks all the regions of the map.

Sorry for my bad english :p

**Comment by Darkilen** [comment]
> I would also change the issue title to something more descriptive like "Switching from yml to sql does not work"

@VaiTon it's not the principal purpose of this issue.

The principal purpose is that /rp reload cause a 10s freeze every time if you have a massive number of claims (which is current with a server with a lot of traffic and players).
And i can add that when you claim, it freeze too, because we have a massive number of claims (which is absolutely normal, I repeat again) and he check every single claim of the entire map ([here](https://github.com/FabioZumbi12/RedProtect/blob/43145acfd812f686c0284b31e7fbef176005adc0/RedProtect-Spigot/src/main/java/br/net/fabiozumbi12/RedProtect/Bukkit/actions/DefineRegionBuilder.java#L144)).

**Comment by VaiTon** [comment]
I'll try to look into that to find if there are less expensive methods in terms of performances.

**Comment by FabioZumbi12** [comment]
The @VaiTon performance aditions will be added on new redprotect version (EpicRedprotect). Btw, this message is because the time redprotect spend to load the regions... we can consider normal until we fix mysql to you use with all your regions.
