### ISSUE TITLE
Problem with flag build

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#367]
Hi,

In 1.13.2 (with PaperSpigot and 7.5.5 b140 for RedProtect) the players can not break some plantations (carrots, potatoes...) or replant them. They can break/put the other blocks as the flag permits, but not the plantings while all that worked normally in 1.12.2.

**Comment by aurel85** [comment]
There are also problems with andesite, diorite, granite this can not be posed while the flag is true...

**Comment by Darkilen** [comment]
@VaiTon It's the first flag in the wiki "[build](https://github.com/FabioZumbi12/RedProtect/wiki/(05)-Region-Flags#build)".
Please, don't answer if you don't know what you are talking about.

**Comment by FabioZumbi12** [comment]
Tryed the latest dev builds? If you is using need-claim-to-build, check the exceptions blocks too!

**Comment by Darkilen** [comment]
We use `needed-claim-to-build` for all our build worlds, but we don't use any exceptions blocks (I don't even know what is it). And yes, we tried on b141, didn't works.

**Comment by FabioZumbi12** [comment]
The flag buils still depending of other flags like interact, buils permisisons and some things like this. The flag build will be removed on Epic version!

**Comment by aurel85** [comment]
so don't expect this flag to be fixed soon if I understand correctly ?

**Comment by FabioZumbi12** [comment]
Exact!
