### ISSUE TITLE
My Redprotect Is Error!

### ISSUE THREAD

**Issue by LuckyMonos** [FabioZumbi12/RedProtect#369]
I have already claimed the land for Red Protect and I have installed the sign and written [rp] and said Done!

Well the next day, my RP is gone, the Red Protect is gone! I have to red protect again!

if like this, the player on my server will not be comfortable because their house will be griefed!

Note: this happens usually because there is a BOT entered and a rollback server! Please help

**Comment by LuckyMonos** [comment]
> Please follow issue pattern. We can't help you with so little information.

HOW ?

**Comment by Darkilen** [comment]
https://github.com/FabioZumbi12/RedProtect/blob/master/ISSUE_TEMPLATE.md

**Comment by FabioZumbi12** [comment]
No logs, not following the template, cant help :/
