### ISSUE TITLE
Eror on Movment in Version 6.5.7?

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#37]
i dont know why this happens.. sorry just can post you the errorlog i got :3

http://pastebin.com/wruPfP5n

What i can tell to create it:
- Appears on Login (Only to player not to owners or RedprotectAdmins)
- Appears on first Movings after login (Only to player not to owners or RedprotectAdmins)

**Comment by FabioZumbi12** [comment]
Its because PVPManager. I will update to the new version of PvPManager with APi implemented by NoChanceHD

**Comment by FabioZumbi12** [comment]
The same as #27
