### ISSUE TITLE
Prohibiting players from entering a region not working

### ISSUE THREAD

**Issue by talaphoenix** [FabioZumbi12/RedProtect#370]
Platform: Sponge

Jar version:  RedProtect-7.5.5-b130-Universal.jar

Minecraft version:  1.12.2

What you want?:  Problem with prohibiting certain ranks of players from entering a region.

Description:  When prohibiting certain ranks of players (using LuckPerms plugin) from entering certain locations, affected players get the message "You cannot enter this region" but aren't actually stopped from entering the region. They can still walk around in it, all while being spammed with the message. Players with the proper permission are allowed inside with no message, as intended.

**Comment by FabioZumbi12** [comment]
You is using a too old build (b130). Download our latest dev build where this is already fixed!
