### ISSUE TITLE
Problem with flag passives and news passive mobs 1.13

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#371]
Hi,

In 1.13.2 (with PaperSpigot and 7.5.5 b140 for RedProtect) all the new passive mobs (cod, salmon, pufferfish, dolphin and tropical fish) except the turtle are not taken into account in the passive flag. So everyone can hit them in a claim while the flag is on false.

**Comment by FabioZumbi12** [comment]
This is not happening on latest devs builds (i am using on my spigot servers without this problems)

**Comment by Darkilen** [comment]
We test on latest dev build, didn't work with cod, salmon, pufferfish, dolphin and tropical fish. This flag only work with turtle as 1.13 passive mob.

**Comment by aurel85** [comment]
With the version 152 the problem is always present, please re-open this issue.

**Comment by FabioZumbi12** [comment]
Fixed on latest dev build.
