### ISSUE TITLE
Problem with flag "flow" and soulsand elevator (1.13)

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#373]
Hi,

In 1.13.2 (with PaperSpigot and 7.5.5 b140 for RedProtect) the elevator soulsand break the flag "flow". By being on false there is still a small flow of water and that on these soulsand elevator.

Screen : 
![2019-01-07_18 44 25](https://user-images.githubusercontent.com/24486147/50786439-e2800f00-12b3-11e9-9565-ef31bf920646.png)

**Comment by aurel85** [comment]
It's the same problem thing with kelp : 

![2019-01-08_12_30_11 png 638928cfcaea4d1fb44c5268f244dec8](https://user-images.githubusercontent.com/24486147/50833964-18c09b80-1353-11e9-80a2-8c425f780878.png)

**Comment by FabioZumbi12** [comment]
Will be fixed on next build (Up to b144)
