### ISSUE TITLE
A very, very serious problem! Failure to repair will result in heavy losses!

### ISSUE THREAD

**Issue by shanklm** [FabioZumbi12/RedProtect#374]
flat-file:
 # Want to save the regions in your ow files?
 region-per-file: false
 auto-save-interval-seconds: 3600
 backup: true
 max-backups: 10
------------------
If'region-per-file: false' is true!

Create a territory named'Qwe'and'qwe'!

So, these two areas will all disappear!

All versions including 7.5.5 have this problem!
--------------------
Quickly fix this problem with the fastest speed!

**Comment by FabioZumbi12** [comment]
This not happens on latest jenkins builds! This an old issue from oldest versions!
