### ISSUE TITLE
Flag gui command error

### ISSUE THREAD

**Issue by Owner-Arnaw** [FabioZumbi12/RedProtect#376]
_Put if is the **Spigot** or **Sponge** version._  
Platform: Spigot

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  7.5.5

_Your server Minecraft version_  
Minecraft version:  1.13

_Issue or Suggestion?_  
What you want?:  Issue

Description:  https://hastebin.com/avihumubip.css

**Comment by FabioZumbi12** [comment]
Theres no such information to analyse, and this log is cutted. Btw, flag gui erros in 99% of cases is related to wrong item types names. Check your spigot/sponge versions and check the version javadocs.
