### ISSUE TITLE
Como criar permissão para um player!

### ISSUE THREAD

**Issue by M-Andrade** [FabioZumbi12/RedProtect#378]
Eu tenho sistema de vip no meu servidor, coloquei para vip conseguir ter 2 claims 80x80, mas só conseguem 1 de 80x80, e se eu aumento a quantidade de blocos, eles conseguem ter mais que 80x80 em um claim só! Eu queria colocar, 2 claims de 80x80 cada um! Como faço? 

Config: https://paste.gg/p/anonymous/aecdf3e17d1045b0a0e06adacac3d862

**Comment by FabioZumbi12** [comment]
Não da, o red tem permissões só de total de blocos e total de claims, nao por tamanho das claims! Ou ele usa todos blocos do seu limite de uma vez ou faz dividinho.
