### ISSUE TITLE
server console error when use /rp select-we, nothing selected

### ISSUE THREAD

**Issue by Krysinski** [FabioZumbi12/RedProtect#379]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Sponge

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-7.5.5-b140-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  I need to select region with wecui, but get error

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  https://pastebin.com/h08iURdG
client mod: WorldEdit+CUI+Forge+Edition+2-2.1.2-mf-1.12.2-14.23.5.2768
server mod: worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist

**Comment by FabioZumbi12** [comment]
RedProtect for sponge requiries Worldeditsponge.

Btwb will not work for now because rp updated to we 7.0 and sponge still on 1.12 (only supports we 6.0)

Disable wecui option for now

**Comment by Krysinski** [comment]
ok, i disable option for use wecui. Now i try to select region with lift click on first point ("first point selected" in chat), then i select second point ("first point selected" in chat, but i suppose that must be "second point"). Then i use "/rp claim regionname" command and get error: https://pastebin.com/r43hNcsg
