### ISSUE TITLE
Suggestion: Use block protection for protect a region

### ISSUE THREAD

**Issue by Zoiter7** [FabioZumbi12/RedProtect#38]
Hello, I have a suggestion, for a claim/protect a region, you can will add blocks protection with measures, and the player can buy this block and put it, and protect a X blocks.

Sorry for my bad english.

PD: If you can, you can add import regions of LibelulaProtectionBlocks

Regards.

**Comment by FabioZumbi12** [comment]
Sorry but cant. With my plugin you can claim with fences and/or wand tool.
