### ISSUE TITLE
server console error when use /rp claim

### ISSUE THREAD

**Issue by Krysinski** [FabioZumbi12/RedProtect#380]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Sponge 1.12.2-2768-7.1.5

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version: RedProtect-7.5.5-b140-Universal.jar 

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  select and claim region with "wand"

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:   i disable option for use wecui. Now i try to select region with left click on first point ("first point selected" in chat), then i select second point by right click ("first point selected" in chat, but i suppose that must be "second point"). Then i use "/rp claim regionname" command and get error: https://pastebin.com/r43hNcsg

**Comment by FabioZumbi12** [comment]
This is caused by empty lang texts. The latest dev builds should fix this.
