### ISSUE TITLE
Error console

### ISSUE THREAD

**Issue by LordRamma** [FabioZumbi12/RedProtect#382]
08.02 18:48:06 [Server] ERROR Could not pass event PlayerInteractEvent to RedProtect v7.5.5
08.02 18:48:06 [Server] INFO java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
08.02 18:48:06 [Server] INFO at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.WEListener.setSelection(WEListener.java:36) ~[?:?]
08.02 18:48:06 [Server] INFO at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.WEListener.setSelectionRP(WEListener.java:48) ~[?:?]
08.02 18:48:06 [Server] INFO at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.RPPlayerListener.onPlayerInteract(RPPlayerListener.java:165) ~[?:?]
08.02 18:48:06 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1095.execute(Unknown Source) ~[?:?]
08.02 18:48:06 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-514]
08.02 18:48:06 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-514]
08.02 18:48:06 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-514]
08.02 18:48:06 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-514]
08.02 18:48:06 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:320) ~[patched_1.13.2.jar:git-Paper-514]
08.02 18:48:06 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:466) ~[patched_1.13.2.jar:git-Paper-514]
08.02 18:48:06 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1361) ~[patched_1.13.2.jar:git-Paper-514]
08.02 18:48:06 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-514]
08.02 18:48:06 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-514]
08.02 18:48:06 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-514]
08.02 18:48:06 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_144]
08.02 18:48:06 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_144]
08.02 18:48:06 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-514]
08.02 18:48:06 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-514]
08.02 18:48:06 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-514]
08.02 18:48:06 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-514]
08.02 18:48:06 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-514]
08.02 18:48:06 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
08.02 18:48:06 [Server] ERROR Could not pass event PlayerInteractEvent to RedProtect v7.5.5
08.02 18:48:06 [Server] INFO java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
08.02 18:48:06 [Server] INFO at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.WEListener.setSelection(WEListener.java:36) ~[?:?]
08.02 18:48:06 [Server] INFO at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.WEListener.setSelectionRP(WEListener.java:48) ~[?:?]
08.02 18:48:06 [Server] INFO at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.RPPlayerListener.onPlayerInteract(RPPlayerListener.java:165) ~[?:?]
08.02 18:48:06 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1095.execute(Unknown Source) ~[?:?]

**Comment by FabioZumbi12** [comment]
Update to worldedit 7.0 or disable wecui integration on config.
