### ISSUE TITLE
Suggestion: Colors and Sets for Dynmap

### ISSUE THREAD

**Issue by thomas-worm** [FabioZumbi12/RedProtect#383]
Platform: Spigot 13.2
Jar version:  7.5.5
Minecraft version:  13.2
What you want?:  Suggestion

Description: 
It would be great if the dynmap interaction can be extended. We would like to set the colors of the area markers and categorize the areas, so for example have blue areas for server zones, red areas for user zone and yellow area for special infrastructure zones like railroad lines. Would be great if these categories are extra layers for dynmap so the user can choose which layers to view.

See also:
Parts of the suggestion can be found in issues #280 and #281

**Comment by FabioZumbi12** [comment]
Added to #281
