### ISSUE TITLE
/Rp Flag Bug

### ISSUE THREAD

**Issue by NonoxSoux** [FabioZumbi12/RedProtect#385]
_Put if is the **Spigot** or **Sponge** version._  
Platform: Spigot

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect-7.5.5-b129-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.7.10

_Issue or Suggestion?_  
What you want?:  Issue

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  When trying to execute the command I get that error in console https://pastebin.com/1EExxwyD Plz, help

**Comment by FabioZumbi12** [comment]
Chekc you GuiSeparator configuration on guiconfig if is a valid item.
