### ISSUE TITLE
Cannot hit/kill creepers in a RP area

### ISSUE THREAD

**Issue by Mathiey** [FabioZumbi12/RedProtect#386]
Cannot hit/kill creepers in a RP area. Ok with all other mobs. I can kill them outside protected area.

Platform: Forge-1.12.2-14.23.5.2814 / SpongeForge-2768-7.1.6-RC3600
Jar version: RedProtect-7.5.5-B141
Minecraft version: 1.12.2
What you want?: Kill Creeper !
Description: No console bug / error

**Comment by FabioZumbi12** [comment]
tryed to set flag fire to false? (as test)

**Comment by FabioZumbi12** [comment]
Fixed on latest dev build!
