### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by daniorio** [FabioZumbi12/RedProtect#387]
Platform: Spigot
Jar version:  7.5.5
Minecraft version:  1.7.10
Description:  Could not pass event EntityDamageByEntityEvent to Redprotect. Pls fix it.
https://hastebin.com/yoyucasifu.sql

**Comment by FabioZumbi12** [comment]
This hastebin is empty

**Comment by FabioZumbi12** [comment]
The latest dev build fix this! Download from our jenkins url.
