### ISSUE TITLE
"needed-claim-to-build" not working

### ISSUE THREAD

**Issue by supertin** [FabioZumbi12/RedProtect#389]
Platform: Spigot 1.13.2

Jar version:  RedProtect-7.5.5-b141-Universal.jar

Minecraft version:  1.13.2

Description: Setting "needed-claim-to-build" to the world names I'm using does not work. To test, I created a clean Spigot directory, and only put Redprotect in (no other plugins). No config settings were changed except for adding "world" to the "needed-claim-to-build" list.
When connecting with a normal, non-op player, all blocks are breakable, and any blocks I've picked up can be placed regardless of whether the player is in a claim or not.

Am I missing some other setting that's not obvious, or is this setting currently broken?

**Comment by supertin** [comment]
This may help narrow down where things are broken...
Spigot 1.12.2 + RP 7.4.1 b110 = works
Spigot 1.12.2 + RP 7.5.5 b141 = FAIL

Spigot 1.13.2 + RP 7.5.0 b112 = works
Spigot 1.13.2 + RP 7.5.2 b116 = works
Spigot 1.13.2 + RP 7.5.3 b123 = works
Spigot 1.13.2 + RP 7.5.5 b129 = FAIL

These are just the builds listed on the spigot resource page (under history). I've not looked for any other builds yet.

**Comment by supertin** [comment]
Last build in Jenkins that works as expected in 125. 126 is broken.

Looking at the diff, some code related to building was changed, but I don't really understand what any of it does :smile:

**Comment by FabioZumbi12** [comment]
Wow, thanks for all tests xD

All working as expected then?

**Comment by supertin** [comment]
> Wow, thanks for all tests xD
> 
> All working as expected then?

Nope. It works up until 125. 126 and later are all broken.

**Comment by FabioZumbi12** [comment]
Fixed on next build (up to b144)
