### ISSUE TITLE
Request: Block sub commands

### ISSUE THREAD

**Issue by GershonR** [FabioZumbi12/RedProtect#39]
RedProtection does not recognize sub commands when blocking but only the parent, for example if you want to prevent a person from claiming inside a region `/rp flag blocked-cmds polis unclaim` would not work. But `/rp flag blocked-cmds polis` would work, but the problem with this is that it blocks every single polis command.

**Comment by FabioZumbi12** [comment]
This is a bit complicated, but i will add...

**Comment by FabioZumbi12** [comment]
Added on latest update ;)
The usage is: /rp flag allow/deny-cmds cmd:<cmd> arg:<agumment>, ...
This allow you repeat the command and use various argumments like "cmd:polis carg:unclaim, cmd:polis agr:claim,..." etc...

**Comment by GershonR** [comment]
Thank you very much! :) Will it be updated on the Sponge version too?
