### ISSUE TITLE
No lava flow?

### ISSUE THREAD

**Issue by Coolrooswag** [FabioZumbi12/RedProtect#391]
Platform:
Sponge
_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  
RedProtect-7.5.5-b130-Universal.jar
_Your server Minecraft version_  
Minecraft version:  
1.12.2
_Issue or Suggestion?_  
What you want?:  
Lava will not flow
_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  I have edited my globalflags.conf file and enabled flow and lava flow and lava still will not flow on the server, here is my config https://pastebin.com/5AybLMdw

**Comment by Darkilen** [comment]
Hello,

Could you try with the latest dev build pls ? You can found it here : https://host.areaz12server.net.br:8080/job/RedProtect/

**Comment by Coolrooswag** [comment]
> 
> 
> Hello,
> 
> Could you try with the latest dev build pls ? You can found it here : https://host.areaz12server.net.br:8080/job/RedProtect/

Just updated and lava still will not flow

**Comment by FabioZumbi12** [comment]
Remove redprotect and try again (if you can), or rename the Redprotect folder too and see if still not flowing.

**Comment by Coolrooswag** [comment]
I have, also people are able to use buckets in my spawn region leading to people being able to flood them completely

**Comment by FabioZumbi12** [comment]
Will be fixed on next dev build (Up to b145)
