### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by baxandrei** [FabioZumbi12/RedProtect#393]
Platform: This server is running CraftBukkit version git-Spigot-3cb9dcb-8b1588e (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Jar version:  7.5.5

Minecraft version:  1.13.2

What you want?:  Click to TP to region or /rp tp region don`t work, even if I add `redprotect.own.tp` to group permissions.

Description:

**Comment by FabioZumbi12** [comment]
Theres not enough information to i help. What jar build? Errors on console?

**Comment by FabioZumbi12** [comment]
The correct perm is `redprotect.own.teleport`, btw is working fine on my tests, try the latest builds
