### ISSUE TITLE
[BUG] /rp wand error

### ISSUE THREAD

**Issue by mistek131995** [FabioZumbi12/RedProtect#396]
I use command /rp wand. select region and I have this error. 

Version Sponge: spongeforge-1.12.2-2768-7.1.5

[latest.log](https://github.com/FabioZumbi12/RedProtect/files/2980539/latest.log)

**Comment by FabioZumbi12** [comment]
Wheres the issue template? 
Disable WECUI integration on RP configuration until WorldEdit don't update for sponge: `Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.math.BlockVector3`
