### ISSUE TITLE
[BUG] "/rp info Admin List" show Admins and Members

### ISSUE THREAD

**Issue by DakirDEV** [FabioZumbi12/RedProtect#398]
Hey,
if you enter "/rp info" for the newest version, the members and the admins are displayed for admins. There is nothing for members.

**Server and plugins versions:**
 - Server: PaperSpigot 1.12.2
 - Plugin Version: RedProtect-7.5.6-b151-Universal.jar
 - Java Version: Java 1.8

**Comment by FabioZumbi12** [comment]
I dont know what you mean!

**Comment by DakirDEV** [comment]
Screen 1: http://prntscr.com/n05tq5
Screen 2: http://prntscr.com/n05suc

In screen 1 you can see the admins, members and leaders but in screen 2 you can see what is displayed when you type "/rp info".

For info, I renamed the ranks (but only in the language file):
Leader = Owner
Admin = Mod
Member = Member

**Comment by FabioZumbi12** [comment]
Now I understand, I'll see what can be!

**Comment by FabioZumbi12** [comment]
I found a wrong var on region class. Please try the latest dev build.

**Comment by aurel85** [comment]
It's ok with 153 :)

**Comment by DakirDEV** [comment]
Thanks a lot for the fast fix!
