### ISSUE TITLE
[BUG]  Dynmap+ RP

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#399]
since the update of the file RedProtect-7.5.6-b151 to the version RedProtect 7.5.6 b152 you can't see the zones on the Dynmap anymore.  How can I fix this?

http://pic.lululand.de/upload/Webseite/dynmapRP.png

**Comment by aurel85** [comment]
It's even more beautiful on my server ahah : https://media.discordapp.net/attachments/215574654050500608/557705245359210521/unknown.png?width=1239&height=610

**Comment by Blueeyestar** [comment]
It's like a laser show ^^ 
You have to downgrade Red Protect to the RedProtect-7.5.6-b151 universal then empty the browser cache then everything is normal. It is unfortunately due to the RedProtect-7.5.6-b152 Universal

**Comment by aurel85** [comment]
I will wait for it to be fixed because I need at least version 152 so that everything works normally with RedProtect on my server but thank you for info ;)

**Comment by FabioZumbi12** [comment]
Hey, you can say your players this version of dynmap its a crazy version and say to all to enjoy xD

(looking for a fix)

**Comment by aurel85** [comment]
It's fixed with 154, thank you :)

**Comment by Blueeyestar** [comment]
It's now fixed for me with the 154.
Thank you very good work.
