### ISSUE TITLE
Big ERROR

### ISSUE THREAD

**Issue by Alibabaand40voleur** [FabioZumbi12/RedProtect#40]
Look at my logs error :
http://pastebin.com/AkEgsLFT
How can u help me for this ? i can't see my logs with that big flood error ...

**Comment by FabioZumbi12** [comment]
You need to check your mcmmo version if you are running the latest version!

**Comment by Melowelei** [comment]
Yes i am usin the latest version :
http://dev.bukkit.org/bukkit-plugins/mcmmo/files/66-mc-mmo-1-5-00/

**Comment by Melowelei** [comment]
Soo ? How can i solve it

**Comment by FabioZumbi12** [comment]
I tryed to reproduce but didnt... try to use the latest dev version of mcmmo!

**Comment by Stuart74** [comment]
says in your log your running 1.8.8 but your running the 1.7 version of MCMMO you should be running the 1.5.0.4 version for 1.8 minecraft which is here 

https://www.spigotmc.org/resources/mcmmo.2445/

Maybe try that see how that goes he does have the non paywalled version for those who cannot pay. 

http://www.dirkocraft.net/mcMMO.jar
