### ISSUE TITLE
[BUG] Flag press-plate

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#400]
Hi,

With the last version (154) there are only stone pressure plates that normally work when the flag "press-plate" is activated.

I use PaperSpigot 1.13.2.

Thank you in advance !

**Comment by FabioZumbi12** [comment]
A bug with Spigot. I using `block nstanceof PressurePlate` but seems SPigot is not recognizing some types of pressure types as PressurePlate. I've changed to check the type name and all is working fine now (latest dev build).
