### ISSUE TITLE
[BUG] The op don't bypass the claims anymore

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#401]
Hi,

With the last version (154) the op don't bypass the claims anymore whereas before that was the case especially that we are well in ignore-regions-from-players in the config.

I use PaperSpigot 1.13.2.

Thank you in advance !

**Comment by FabioZumbi12** [comment]
Dont bypass in wich cases?

**Comment by aurel85** [comment]
Normally as an op can interact with all the map, claim or not claim, the players must claim to be able to build. Here it's the same for ops.

**Comment by FabioZumbi12** [comment]
The latest dev build should fix this!
