### ISSUE TITLE
Help with interact Blocks please

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#403]
Good afternoon, I'd like to ban the use of Ender Chest in the End.
I wanted to do this with the help of RP.

Now I entered the ender chest but you can still access it. What did I do wrong ? a wrong format? 

interact: false
   If interact option is false, choose what blocks or entity the player can interact.
   EntityTypes: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
  if-interact-false:
    interact-blocks:
      This items will not be allowed to interact, all other items will be.
      blacklist:
      - 'ENDER_CHEST'
       Only this items will allowed to interact, all other item will not be allowed.
       You can add this blocks to allow basic exploration (accept regex):
       "[*]_PLANT","GRASS_BLOCK", "TALL_GRASS", "POPPY", "DANDELION"
      whitelist: []

**Comment by Blueeyestar** [comment]
Doesn't anyone know how to disable enderchest in a certain world?

**Comment by FabioZumbi12** [comment]
I'll check this later.

**Comment by FabioZumbi12** [comment]
Fixed on latest dev build ;)
