### ISSUE TITLE
[BUG] Maven Repo URL outdated

### ISSUE THREAD

**Issue by BaronyCraft** [FabioZumbi12/RedProtect#404]
Not a problem with the plugin itself, but with the maven repo resp. its description in README.MD.

It seems like github changed its URLs, and the maven example:

```
<repository>  
  <id>redprotect-repo</id>  
  <url>https://raw.github.com/FabioZumbi12/RedProtect/mvn-repo/</url>  
</repository>  
```

doesn't work anymore. However, this works:

```
<repository>
  <id>redprotect-repo</id>
  <url>https://github.com/FabioZumbi12/RedProtect/raw/mvn-repo/</url>
</repository>
```

**Comment by FabioZumbi12** [comment]
Its outdated, but now i think should be `https://raw.githubusercontent.com/FabioZumbi12/RedProtect/mvn-repo/`

Fixed on readme, thanks for point that.
