### ISSUE TITLE
secure fire

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#408]
Is it possible to secure fire as well on the zone? Users still have the option to extinguish the fire on my zones. Which is annoying because you have to light it again and again. Is it possible to integrate a fire into a flag ?

**Comment by FabioZumbi12** [comment]
This breaks on every major Minecraft updates. I will later.

**Comment by FabioZumbi12** [comment]
Detected this as a paper/minecraft BUG: https://github.com/PaperMC/Paper/issues/1915

When the fire is not near fences os other transparent blocks, the player can't extinguish the fire!

**Comment by FabioZumbi12** [comment]
Tempfix bff5c90

**Comment by FabioZumbi12** [comment]
Fixed in another way on 1f200c6

**Comment by Blueeyestar** [comment]
You made it. Super work. It works. No user can extinguish fire on the Zone Deco. You can be relied on. Thank you
