### ISSUE TITLE
[BUG] Enderchest opening

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#409]
Hello Fabio, I have written because of the problem because of the Enderchest. Although I have the RP version RedProtect-7.5.6-b162-Universal now on the server, the users can open Enderchest in certain worlds. Am I still entering a wrong format?

interact: true
  if-interact-false:
    interact blocks:
      blacklist:
      - 'ENDER_CHEST'
      whitelist: []
    interact-entities:
      blacklist: []
      whitelist:
      - 'VILLAGER'

**Comment by FabioZumbi12** [comment]
If ´interact: true` this option will not take effect

**Comment by Blueeyestar** [comment]
Even if I have it on false still the users can access it   

 interact: false
  if-interact-false:
    interact-blocks:
      blacklist:
      - 'ENDER_CHEST'
      whitelist: []
    interact-entities:
      blacklist: []
      whitelist:
      - 'VILLAGER'

**Comment by Blueeyestar** [comment]
Super it works. Thank you for the quick fix. You do a great job :)
