### ISSUE TITLE
[Suggestion] /rp flag in wilderness 

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#410]
Wouldn't it be too Ideal if you had a Gui like in /rp flag for the wilderness ?  Where you can set what you can and can't do in non-drawn areas or wilderness?

Wouldn't it also be more ideal if you then also make a white and black list in the flag what is allowed and what is not ?  This could then be realized in the Gui  by simply adding spawn eggs to the list of mobs that should be on or off.

**Comment by CloudeLecaw** [comment]
a nice idea a flag gui (or other form of management) for the wilderness :).. maybe a textform management with just a "chatgui" ...or something like that

**Comment by FabioZumbi12** [comment]
Will not be added :/
