### ISSUE TITLE
[BUG] fire protection is only partially active

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#411]
RP-Version: **RedProtect-7.5.6-b162-Universal.jar**

Spigot-Version: **CraftBukkit version git-Spigot-e6eb36f-51100db (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**

I found another bug to put out fires in protected areas. 
On the picture I have 2 fires. On the right is the open fire and on the left is a built-in fire. The direct fire cannot be extinguished thanks to RP the left built-in fire can be extinguished from diagonally above by clicking. So it is no longer protected by RP. 

http://pic.lululand.de/upload/Webseite/2019_03_25_11.51.53.png

**Comment by FabioZumbi12** [comment]
This is the same problem/bug with paperclip and fence. When you hit any block through other mid blocks or transparent blocks this will happens. Follow the bug open on #408 
(and i will not add a tempix for every transparent block)
