### ISSUE TITLE
[BUG] permission settings not work

### ISSUE THREAD

**Issue by chenxuuu** [FabioZumbi12/RedProtect#412]
**Describe the bug**

I give my default group with permission:
- redprotect.user
- redprotect.flag.all
- redprotect.limit.claim.unlimited
- redprotect.limit.blocks.unlimited

but when I use `/rp wand` , it say `无效的命令`(Invalid commands)

> also not work when I give `redprotect.admin` permission

**Server and plugins versions (please complete the following information):**
 - Server: spongeforge-1.12.2-2768-7.1.6-RC3629
 - Plugin Version: RedProtect-7.5.6-b149-Universal
- permission plugin: LuckPerms-Sponge-4.3.109
 - Java Version: jdk8u202-b08-jre openjdk hotspot

**Comment by FabioZumbi12** [comment]
Your players dont need any perm to use /rp wand, you just need to change the claim type of your worlds to `WAND` or `BOTH`

**Comment by chenxuuu** [comment]
It works! thanks!
I think this should be the default setting...
