### ISSUE TITLE
[Suggestion] add multi-language support for guiconfig

### ISSUE THREAD

**Issue by chenxuuu** [FabioZumbi12/RedProtect#413]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
add multi-language support for guiconfig

**Describe alternatives you've considered**
now I only translate for my own server, but it can be more useful for others

**Additional context**
nothing

**Comment by chenxuuu** [comment]
my translation
[guiconfig.zip](https://github.com/FabioZumbi12/RedProtect/files/3026254/guiconfig.zip)

**Comment by VaiTon** [comment]
I'm sorry but I can't understand what do you mean with 'multi-language'. Is it about the number of languages currently available or about the possibility of a "fallback" language for missing strings?

**Comment by chenxuuu** [comment]
@VaiTon 'multi-language' is already exist
but the part of 'guiconfig' , it not , only can be changed in config files , not support 'multi-language'
