### ISSUE TITLE
Error when i use splash popo

### ISSUE THREAD

**Issue by Alibabaand40voleur** [FabioZumbi12/RedProtect#42]
ERROR 	[17:00:31] [Server thread/ERROR]: Could not pass event PotionSplashEvent to RedProtect v6.5.7
Caused by 	Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.meta.PotionMeta.getBasePotionData()Lorg/bukkit/potion/PotionData;

1 Popo = This error.
If u want more information say me !

**Comment by FabioZumbi12** [comment]
Whats you server version?

**Comment by Melowelei** [comment]
1.8.8 Spigot

**Comment by Melowelei** [comment]
Exactly :
CraftBukkit version git-spigot-0359393-9cd1111 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by FabioZumbi12** [comment]
Thats right, the PotionMeta is not compatible with 1.8 I will fix and upload ;)

**Comment by FabioZumbi12** [comment]
Uploaded a version with this fix (i think), download from Spigot: https://www.spigotmc.org/resources/redprotect-1-7-1-8-1-9-anti-grief-server-protection.15841/

**Comment by Melowelei** [comment]
So, All the claim of my player don't will be delete ? All claim will stay ?

**Comment by FabioZumbi12** [comment]
Will stay, but if you want to make a backup, is not a bad ideia ;)

**Comment by Melowelei** [comment]
Another probleme with ur update :
ERROR 	[11:51:48] [Server thread/ERROR]: Could not pass event FakeBrewEvent to RedProtect v6.5.8

**Comment by FabioZumbi12** [comment]
I need all error log at "cause: ...." to see wheres the class and line causing the error.

**Comment by Melowelei** [comment]
ERROR 	[19:07:22] [Server thread/ERROR]: Could not pass event FakeBrewEvent to RedProtect v6.5.8
Caused by 	Caused by: java.lang.NullPointerException

**Comment by FabioZumbi12** [comment]
No man... all error log, like reported here: #48
