### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by H3roDude** [FabioZumbi12/RedProtect#423]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

**Describe the bug**
I disabled monsters in the globalflag file but zombie kids are still spawning because of the chickens. The chickens will attack you and the zombie is invisible, but still making noise
Is there a workaround for this problem?

**To Reproduce**
1. Got to the Config
2. Disable Monsters to spawn in a choosen world
3. Chickens will spawn at night and will attack you with baby Zombie noises

**Expected behavior**
Regular Chickens spawn without attacking

**Screenshots and LOGs**
I do not have Logs for that kind of Issue

**Server and plugins versions (please complete the following information):**
 - Server: spongeforge-1.12.2-2768-7.1.5
 - Plugin Version: RedProtect-7.5.6-b149-Universal
 - Java Version: Java 1.8

**Comment by H3roDude** [comment]
edit, updated to the Build: RedProtect-7.6.0-b193-Universal and its still happening

**Comment by FabioZumbi12** [comment]
Seems you have another mob plugin like InfernalMobs or other mob manager. The mobs you have mentioned dont spawn on minecraft vanilla/naturally.
