### ISSUE TITLE
[BUG]  uuid Name Problem 

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#428]
RP-Version: **RedProtect-7.6.0-b194-Universal.jar**

Spigot-Version: **CraftBukkit version git-Spigot-e4be9b0-5736cdc (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)**

_Users are no longer displayed as names only as uuid_

![2019-04-29_08 00 24](https://user-images.githubusercontent.com/35557302/56878646-6c1b3e80-6a55-11e9-9f70-13a6e57405ce.png)

**Only if you completely remove the player from his zone and then add him again he can access his /rp flag again.**

After that the uuid is gone and the correct name is to be read. But only if you add new players to the zone.

![2019-04-29_08 20 32](https://user-images.githubusercontent.com/35557302/56879149-aede1600-6a57-11e9-9d61-bdfe824720e7.png)

**Comment by thomas-worm** [comment]
Same problem here. Is there a tool to convert the uuid to user names?

**Comment by FabioZumbi12** [comment]
Paste here one of the regions with this problems to i see how is.

**Comment by Blueeyestar** [comment]
The zones are all only with uuid time. Until you transfer the owner to the zone.

Example:
Mardelzur belongs to the zone as a leader. But in the info is only the uuid as well as in the Bossbar when entering the zone.

![2019-04-30_22 26 51](https://user-images.githubusercontent.com/35557302/56991590-4ea2bd80-6b98-11e9-93a9-5d1717e9a3f8.png)
![2019-04-30_22 28 01](https://user-images.githubusercontent.com/35557302/56991599-54000800-6b98-11e9-8fb9-4310ec44594f.png)


Now I have to remove the owner from his zone as leader. and reassign the zone as a leader then the real name is back

![2019-04-30_22 31 22](https://user-images.githubusercontent.com/35557302/56991661-7bef6b80-6b98-11e9-8351-d042b2144f02.png)

**Comment by FabioZumbi12** [comment]
I ll make a converter for this problem, easy to fix but when i am at my home.

**Comment by Blueeyestar** [comment]
Thank you :)
