### ISSUE TITLE
Inventory Lost From Chests

### ISSUE THREAD

**Issue by Stuart74** [FabioZumbi12/RedProtect#43]
I am running the following             

-  KCauldron 1.7.10-1614.201  
-  RedProtect 2.6.7

Had a player come online and all their items were in there chests then they died came back to find all the private signs blank and all the chests empty. There had been absolutely nothing that had happened to explain why this occurred. This was completely isolated to that one single player, which was unusual. The only assumption is that private signs should not be used inside the protected area, this is simply a guess that the signs conflicted with the region name possibly??

The region name of the players area is different to what they placed on the private signs if that makes any difference.

I went to check the redprotect logs and the logs are empty nothing was recorded in the logs. 

Let me know if there is any more information is needed..

**Comment by FabioZumbi12** [comment]
I dont know what can be... RedProtect dont manages the chest's inventory, only deny open dont allowing to open the inventory/chest.

Theres no errors on console?

**Comment by Stuart74** [comment]
I was fairly sure that redprotect did not handle the actual inventory and it being so isolated i found it hard to understand why. It is bizarre there was no log of any event that i could see that was the cause and it literally one person out of the current 20 players that was affected. 

Only reason I assumed it was a redprotect issue was the private signs went blank. Also the player complained that textures were not right either.

Thanks for the help I am going to close this for now if it occurs again and i can find more details i willl re open this again. 

Thanks again :+1:

**Comment by FabioZumbi12** [comment]
Shure, i am here to help :+1:
