### ISSUE TITLE
[BUG] claiming land without permission

### ISSUE THREAD

**Issue by T0MSSM0T** [FabioZumbi12/RedProtect#432]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

**Describe the bug**
No permissions have been given but a non oped user can claim land. (using wand and fences)
the wand didnt work at first but started working.
Along with this, I have tried using lucky perms to give specific permissions like redprotect.commands.near but the players still dont have permission to user this command

**To Reproduce**
1. have lucky perms
2. dont specify permissions for a non opped user
3. try to claim land with wand (might not work) claim with fence and sign [rp]

**Expected behavior**
not be able to claim land at all without permissions

**Server and plugins versions (please complete the following information):**
 - Server: Spigot 1.14
 - Plugin Version: RedProtect-7.5.6-b163-Universal
 - Java Version: 1.8

**Additional context**
i have another problem which i will make a bug report for but thes are the warning i get 
[22:27:59] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to RedProtect v7.5.6
org.bukkit.event.EventException: null
[22:27:59] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to RedProtect v7.5.6
org.bukkit.event.EventException: null

**Comment by FabioZumbi12** [comment]
Use our latest version where is already compatible with 1.14 and with a lot of bugfixes.

Btw, the player dont need permissions to claim regions, you can define this by worlds seting up the configuration for world on configs. If you change the claim type to WAND, the player wil be allowed to claim using wand tool.

**Comment by T0MSSM0T** [comment]
Can i get a link to make sure i have the latest, I thought I did. Also the config I believe says both for claim type.

Also I am not sure what you mean by setting up in the configs. which config should I look into?

**Comment by FabioZumbi12** [comment]
Its up here:

https://host.areaz12server.net.br:8080/job/RedProtect

**Comment by T0MSSM0T** [comment]
so I have:
region-settings:
  claim-type:
    worlds:
      world: 'BOTH'
      world_nether: 'BOTH'
      world_the_end: 'BOTH'

and

wands:
  adminWandID: 'GLASS_BOTTLE'
  infoWandID: 'PAPER'

I just noticed, it says admin wand... does that mean non admins cant use them?

**Comment by T0MSSM0T** [comment]
my other two problems have gone, the two errors as well as the rp flag allowing me to take items.

So those bugs are gone, so the only "bug" is the wand thing, as well as not fully getting how to edit permissions (which isn't your problem) i'll read more, but I would be able to give and take specific permissions, not sure if that is already doable and maybe I am doing it wrong?

**Comment by T0MSSM0T** [comment]
update, it seems as if old configs mix with the new configs, making me assume the new configs werent "new"
Basically I have stuff in the old configs, like teleport time being effective, but then some new configs AKA the claiming options not be in effect... so I actually didn't have "BOTH" selected, now it works!

still the permissions thing is a problem, well more a feature request.

I believe this issue can be closed, and update in the future will probably fix my issues, last thing
can you explain how I can enable or disable a command? like /rp teleport, what would i type in my permissions plugin

**Comment by FabioZumbi12** [comment]
Cool is all working now.

Each command have a permission. You can negate the permission to deny player to use. See https://github.com/FabioZumbi12/RedProtect/wiki/(04)-Permissions for the exact permissions you need and syntax.
