### ISSUE TITLE
[BUG] Claimen in the snow biome

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#434]
On our server you can claim the land with a wooden sword.
Only then you can build something. Unfortunately we have the problem in schneebiom that the users cannot claim with their wooden sword, because the snow cover makes it impossible. This is probably not recognized as a block. So you can only claim where there is no snow cover. can you do something from Red Protec ?

**Comment by FabioZumbi12** [comment]
Are you using need-claim-to-build? if yes you need to allow players to break snow.

**Comment by Blueeyestar** [comment]
Danek that was a good tip :)
