### ISSUE TITLE
[BUG] RP Border -Glowstone Problem

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#435]
Spigotversion: CraftBukkit version git-Spigot-1eece4f-09a453a (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

RP-version: 199

if you drag a zone you will no longer see Glowstone as a corner which you can see better but only white_stained_glass_pane. Although in the config Glowstone is registered. Or did I do something wrong?

border {
        material=GLOWSTONE
        time-showing=10

**Comment by FabioZumbi12** [comment]
Will be fixed on next dev build.
