### ISSUE TITLE
[BUG] Problem with RP with Deluxemenus

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#437]
Spigot-ver.CraftBukkit version git-Spigot-1eece4f-09a453a (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

RedProtec Version: 299

I have a little problem, and I hope you can help me.
I am using the DeluxeMenus 1.10.5 plugin, which allows users to control /rp flag without entering the /rp flag command each time. They just click on the house icon and the Gui opens. 

Now the problem since 1.14 is the only problem in the Gui of DeluxeMenus 1.10.5 Red Protec. If you click on the house symbol the /rp flag gui opens but the users can remove the items from the flag.  If you enter the command /rp flag in the chat you can't remove them. 

In the Config vin DeluxeMenus the setting looks like this:
material: hdb-4449
        data: 0
        amount: 1
        slot: 3
        priority: 2
        display_name: 'Open &bZones-Menu'
        lore:
        - &aClick to open the zone menu'
        left_click_commands:
        - '[player] rp flag'
        - '[close]'
        right_click_commands:
        - '[close]'

Does anyone have any advice as to why only Redprotec makes the mistakes?

**Comment by FabioZumbi12** [comment]
I dont know, probably DeluxeMenus dont allow rp to register the event to cancel the click and move events... or maybe dont support open third party gui menus... you need to check with deluxe menus the way his plugin lanches other guis or commands.

**Comment by Blueeyestar** [comment]
I have 4 other plugins that I open via deluxemenue but you can't move anything in the gui.  The programmer said that it's not his plugin because nothing has changed...  now I am unfortunately helpless..... :(

**Comment by FabioZumbi12** [comment]
And check for console errors when using deluxemenu to open the rp gui.

**Comment by Blueeyestar** [comment]
it was found out...it's an opengui problem i had to
 change the code:

Old code:
- '[player] rp flag<'
New Code
- '[player] rp flag<delay=10>'

there had to be a delay. 

So it wasn't your plugin. Still thanks for the tips :)
