### ISSUE TITLE
[BUG] private chests not private

### ISSUE THREAD

**Issue by T0MSSM0T** [FabioZumbi12/RedProtect#438]
**Describe the bug**
[private] with your name has a bug where a player can put a chest 3 blocks away with [private] their name which then allows them to access blocks 2 away, opening the private chest.

**To Reproduce**
1. find private chest you cant open.
2. Place chest 3 blocks (if its closer it will be locked by the other sign)
3. Place private sign on your chest, and double your chest closer to the private chest you are trying to get into
4. place another [private] sign on the new double chest close to the private chest you want to get into
5. get access

**Expected behavior**
signs, don't have a radius

**Screenshots and LOGs**
i am T0MSSM0T not oped but i can access captainindia's chest

**Server and plugins versions (please complete the following information):**
 - Server: Spigot 1.14
 - Plugin Version: RedProtect-7.6.0-b199-Universal.jar
 - Java Version: 8
![2019-05-04_16 01 03](https://user-images.githubusercontent.com/15080064/57184229-86ef1800-6e86-11e9-9d79-f858a2e058ee.png)

**Comment by CloudeLecaw** [comment]
we are on build...217..allready :3

**Comment by T0MSSM0T** [comment]
Ill check
