### ISSUE TITLE
Problems with the "Fly" flag

### ISSUE THREAD

**Issue by PeRFecTxTabZ** [FabioZumbi12/RedProtect#44]
Hello, when u want to change a flag u must wait 20 seconds between it. It works fine for all Flags, but not for the New where u can set that other players cant fly on your Region. Why?

**Comment by FabioZumbi12** [comment]
You mean you have configured the flag delay con configuration for all your flags and allow-fly dont respect the delay?

**Comment by PeRFecTxTabZ** [comment]
Yes exactly , that's what I mean

**Comment by PeRFecTxTabZ** [comment]
Do u think u can Fix it?

**Comment by FabioZumbi12** [comment]
I have tested and seems working fine. This is my config:

    change-flag-delay:
        enable: true
        seconds: 10
        flags:
        - pvp
        - allow-fly

This is what i have: http://prntscr.com/b1wkgx

**Comment by PeRFecTxTabZ** [comment]
Ahh, Thanks a lot. It was my mistake. Thanks for ur time :)
