### ISSUE TITLE
[BUG] on latest rp reload

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#440]
On latest Redprotect 7.6.0 Build 200 it seems like u cant reload it anymore?

![image](https://user-images.githubusercontent.com/12080017/57196206-e3bc0280-6f5a-11e9-9dae-3712f3e7a29c.png)

this is all you get in chat (and console)
same on  rp reload-config

**Comment by FabioZumbi12** [comment]
You need to use `/rp admin reload` or `/rp admin + TAB` to autocomplete all available admin commands

**Comment by CloudeLecaw** [comment]
thank you fabio i didnt noticed these commands moved to rp admin :3

**Comment by FabioZumbi12** [comment]
Yeah, i've updated the wiki with all commands
