### ISSUE TITLE
Info for 1.14 GUI - some material names changed

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#441]
like on change of 1.12 to 1.13 take a look at the material names on 1.14 in the GUI
they have not changed automaticly ;)
So all users of 1.14 pls open your GUIfile and check all Material names in it before reporting a bug with the gui ;)

Example:
before:
```
    sign {
        material=SIGN
        slot=28
    }
```
needed to be edited to:
```
    sign {
        material=OAK_SIGN
        slot=28
    }

```

thanks :-)

**Comment by EpiCanard** [comment]
Isn't it OAK_SIGN for material instead ? https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html#OAK_SIGN

**Comment by FabioZumbi12** [comment]
Like the same on 1.12 to 1.13, the server owners need to change the default materials. On next release, the default material will be 1.14 item names.
