### ISSUE TITLE
[Suggestion] bidirectional portals with a cooldown

### ISSUE THREAD

**Issue by T0MSSM0T** [FabioZumbi12/RedProtect#445]
**Describe the solution you'd like**
For the rp setportal command, a player should be able to go back through the portal to return to where they were.
Also a portal cool down so this can't be abused (that can be configed).

**Describe alternatives you've considered**
Obviously other plugins may have things like this, so that is an option.
Also I could always set another portal at/near the exit of the portal to go back, but I wonder if I put the portals on top of each other would I constantly go back and forth.

**Additional context**
Is /sethome apart of this plugin, I always get the notification when I claim land to /sethome.
This could also be used to "go back"

**Comment by FabioZumbi12** [comment]
Added portal cooldown on latest dev build and a config for the time. About /sethome, its only a suggestion, you can edit the message on lang file.
