### ISSUE TITLE
[BUG] Tree subzones problem

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#448]
Spigot: CraftBukkit version git-Spigot-8043ebc-dd99c5b (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

RP-Version:RedProtect-7.6.0-b213-Universal.jar

We found out a bug when you have 2 levels with 2 subzones and build in the lower subzone a tree like black oak and that goes over the subzone into the other one the upper part of the tree is not generated. then only the half of the tree is standing.

**Comment by FabioZumbi12** [comment]
This not a bug and yes a security thing where malicious people cant generate trees or other types of trees/blocks from one region to other regions. You can disable this on config.
