### ISSUE TITLE
[BUG] Water/lava flow

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#449]
CraftBukkit version git-Spigot-8043ebc-dd99c5b (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

/rp-Version:RedProtect-7.6.0-b214-Universal.jar

Water and lava tiles is exhibited in the /flag

but still it flows on

**Comment by FabioZumbi12** [comment]
I dont known what you mean. More info please.

**Comment by Blueeyestar** [comment]
Deny Water and Lava flows in a region. Include protection for child regions, where flow from child region dont overlaps master regions.  <<----This flag no longer works. No matter if it is on or off. water and lava are always running.

**Comment by Blueeyestar** [comment]
I hope you get what I mean. Mine users despair because lava and water flow although they have exhibited it
