### ISSUE TITLE
Console Spam after updating to 6.5.8

### ISSUE THREAD

**Issue by Stuart74** [FabioZumbi12/RedProtect#45]
Running KCauldron 1.7.10-1614.201
                Redprotect version 6.5.8

As soon as it was updated my console just gets spammed with the below errors

http://pastebin.com/wy2KeY3B

Will probably go back to 6.5.7 until this can be resolved  as it will fill my logs up quite quickly if i leave it as it is.

Thanks in advance for any help and if you need further information feel free to ask.

**Comment by FabioZumbi12** [comment]
Oh, using 1.7! Try this version if solves: https://github.com/FabioZumbi12/RedProtect/blob/master/release/RedProtect-6.5-SNAPSHOT.jar?raw=true

**Comment by Stuart74** [comment]
is this version 6.5.7 the snapshot ?? or is it bleeding edge build??

I had 6.5.7 and was working fine apart from some command arguments problems in the rp help page for showing the help commands for /rp flag /rp buy and /rp sell   see image below 

http://s32.postimg.org/n7bu3r879/rphelp.png

**Comment by FabioZumbi12** [comment]
Its because i put ".eco." on help strings the then on translation, the plugin is looking for it, but now i think fixed. flaggui is a subcommand of /rp flag and i removed from help page. Download from same link and test.

**Comment by Stuart74** [comment]
Thanks for the quick reply the console spam has gone but the help page 3 is still missing language strings  Below is an updated screenshot.

http://s32.postimg.org/gdl7e1ayt/rphelp.png

**Comment by FabioZumbi12** [comment]
Remove the above lines from your lang file:

cmdmanager.help.expandvert
cmdmanager.help.eco.sell
cmdmanager.help.eco.buy

Theres new lines added instead this "wrong" lines.

**Comment by Stuart74** [comment]
works perfectly thank you so much for the support wish all developers were as helpful and supportive of their plugin as you are. You are a credit to the community :+1:

**Comment by FabioZumbi12** [comment]
Thank you! Glad to see all working ^^
