### ISSUE TITLE
[BUG] [7.6.0-b214] [Sponge] Startup Error

### ISSUE THREAD

**Issue by CrAazZyMaN21** [FabioZumbi12/RedProtect#451]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

**Describe the bug**
java.lang.ClassNotFoundException: br.net.fabiozumbi12.RedProtect.Sponge.RPVHelper7

**To Reproduce**
1. Move Plugin in mods folder
2. Start the server

**Expected behavior**
Normal Startup

**Screenshots and LOGs**
https://hastebin.com/fokekajere.md

**Server and plugins versions (please complete the following information):**
 - Server: [Sponge 1.12.2]
 - Plugin Version: RedProtect-7.6.0-b214-Universal
 - Java Version: Java 1.8

**Additional context**

**Comment by FabioZumbi12** [comment]
The latest version should fix this!
