### ISSUE TITLE
[BUG] [7.6.0-b214] [Sponge] Wand Interact Error Primary and Secondary Hand

### ISSUE THREAD

**Issue by CrAazZyMaN21** [FabioZumbi12/RedProtect#452]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

**Describe the bug**
Could not pass InteractBlockEvent for Right and Left Hand

**To Reproduce**
1. Left or Right Click the Wand

**Expected behavior**
Set position with wand but only works with commands

**Screenshots and LOGs**
If applicable, add screenshots to help explain your problem. Upload your logs to https://hastebin.com/wihokefere.rb

**Server and plugins versions (please complete the following information):**
Server: [Sponge 1.12.2]
Plugin Version: RedProtect-7.6.0-b214-Universal
Java Version: Java 1.8

**Additional context**

**Comment by FabioZumbi12** [comment]
The latest version should fix this!
