### ISSUE TITLE
[BUG] [7.6.0-b214] [Sponge] Claim no value present

### ISSUE THREAD

**Issue by CrAazZyMaN21** [FabioZumbi12/RedProtect#453]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

**Describe the bug**
No region can be claimed (rp define is working)

**To Reproduce**
1. Enable it in config
2. Select Region with rp pos1 & 2
3. Type rp claim or rp claim test
4. Error: no value present

**Expected behavior**
RP should claim the region

**Screenshots and LOGs**
If applicable, add screenshots to help explain your problem. Upload your logs to https://hastebin.com/ahecodekel.rb

**Server and plugins versions (please complete the following information):**
- Server: [Sponge 1.12.2]
- Plugin Version: RedProtect-7.6.0-b214-Universal
- Java Version: Java 1.8

**Additional context**

**Comment by FabioZumbi12** [comment]
The latest version should fix this!
