### ISSUE TITLE
Problems with Negating Permissions for GUI in latest Version

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#454]
Spigot 1.14.1
PermissionsEx_1.23.4
RedProtect_7.6.0-Build214

Problem: When negating Permissions for hidng some flags in the GUI for users then it does nt work.
Currently all Players can see all party of the GUI no matter if they have Permission for it or not

![image](https://user-images.githubusercontent.com/12080017/57955288-c2153080-78f5-11e9-96c6-03fd15077892.png)
In The Picture u can see all my used GUI flags. the last two rows are Admins flags that players normaly should not see.
Also i negates the flag permission redprotect.flag.door to to try to hide the door gui element.

This negating of permissions to hide GUI elements was working fine before the "new" GUI was splitted into two parts... hm maybe u did some other changes too? :3

**Comment by FabioZumbi12** [comment]
Yeah, i've removed the ` enabled flags` configuration (and i need to remove from config) and now we need to ad the flags to default flags values on config. for admin perms will be all on permissions, but yeah, i think i need to remove the existing permisions from gui if the player dont have the permission.

**Comment by FabioZumbi12** [comment]
The latest version should fix this!

**Comment by CloudeLecaw** [comment]
i will test it today and report or close the issues after test :)

**Comment by CloudeLecaw** [comment]
fixed
