### ISSUE TITLE
[BUG]  /rp setmaxy + miny do not go

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#455]
CraftBukkit version git-Spigot-8043ebc-9bda413 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

RP-Version 216

i can't set the zone height anymore with /rp setrminy and /rp setmaxy then comes always: you can't use this. Even as an owner I am not allowed to set the zone height!

**Comment by CloudeLecaw** [comment]
After a bit of testing around i found out that problem exist allways if you are not listed as leader of a zone. Not even op or admin can change it if someone else or the Server is the leader of the zone.

if you have the permission and you are the leader of a zone then you can change the setmini and setmaxy.

May this helps to trigger out where the problem accours

**Comment by FabioZumbi12** [comment]
Build 217 should fix this
