### ISSUE TITLE
Fly Bypass for Mods

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#456]
We use a Regionflag called. allow-fly
when this flag is disabled then our Mods cant fly

The only change to let them fly is to give them the permission: "redprotect.command.admin"
Normally this flag should be no permission for flags?.....

Is there a way to creat bypass for flags? like "redprotect.flag.flagname.bypass" for  all flags?
the solution cant be to give the mod - redprotect.command.admin...

**Comment by Blueeyestar** [comment]
I also have the problem on the server....

**Comment by Blueeyestar** [comment]
Isn't there a solution?

**Comment by FabioZumbi12** [comment]
You already can add admin flag permissions to your mods, but i've added some not present on 218, now on 219

**Comment by Blueeyestar** [comment]
If the mods now have the permission redprotect.admin.flag.allow-fly. And when you get to a zone where these flags are set up, they fly down like stones.  The flag redprotect.admin.flag.allow-fly doesn't entitle you to fly permanently whether in a zone Fly is on or off.

**Comment by FabioZumbi12** [comment]
The correct is `redprotect.flag.admin.allow-fly`

**Comment by Blueeyestar** [comment]
Super it worked. As always a super work from you
