### ISSUE TITLE
Economy And Armor Stand

### ISSUE THREAD

**Issue by netherarts** [FabioZumbi12/RedProtect#46]
Hello I have two problems with Red Protect.

1. Firstly, I can't place Armor Stand a place where protected with Red Protect. I configured the flag allow-place like this 'allow-place : armor_stand' but it doesn't work.

2. User can buy and sell their place, but the vault doesn't transfer properly.

**Comment by FabioZumbi12** [comment]
1. I will test;
2. I think is not a RedProtect problem because we hook into latest vault. And only the leaders receive the money. You are using what plugins to economy?

**Comment by netherarts** [comment]
Only Vault for Economy.

**Comment by Stuart74** [comment]
Do you have essentials installed as that has its own inbuilt economy which hooks into Vault. Vault on its own wont actually give you currency it simply the middle man basically between one plugin to your plugin that actually distributes the coin, dollars or whatever you use.

So the main economy plugins are 
Essentials Economy 
Iconomy

I believe that is what FabioZumbi is asking.

**Comment by FabioZumbi12** [comment]
I think this the same as #50 

And Vault does work alone, its only a Bridge! You need a economy plugin like Essentials, iconomy, etc. Can you confirm if you are using a Economy plugin or Only Vault?
