### ISSUE TITLE
Warns no console durante a inicialização em um spigot 1.14.1

### ISSUE THREAD

**Issue by comonier** [FabioZumbi12/RedProtect#460]
Versão do servidor: Spigot 03bd4b0-c45c0a9 (MC: 1.14.1)
Versão do RP: RedProtect-7.6.0-b213-Universal.jar
https://paste.ofcode.org/eKRdWgdGd5quGZ337jPPhF
Só para saber se eu devo me preocupar ou ignora
De qualquer forma estou atualizando a ultima build do jekins
Não deu pra entrar no servidor nessa build do Spigot
Vou tentar o Paper ou voltar a versão da Build anterior do Spigot q eu construi com o buildtools.
Abraços.

**Comment by comonier** [comment]
no paper build 39:
https://paste.ofcode.org/gL5BLsxJeL3nCA56NDrdDb

**Comment by comonier** [comment]
https://paste.ofcode.org/mcY22ChztnhmDGHeQxdPDF
Versão do servidor: Spigot 03bd4b0-c45c0a9 (MC: 1.14.1)
RedProtect-7.6.0-b219-Universal

**Comment by FabioZumbi12** [comment]
Deleta o arquivo `economy.conf` e deixa gerar um novo
