### ISSUE TITLE
[Suggestion] Return money or part occupied in the claim

### ISSUE THREAD

**Issue by NonoxSoux** [FabioZumbi12/RedProtect#461]
Something that occupies griefprevention, are the claimeo blocks that when removing the claim are recovered, here in redprotect the money is used and many of my users get angry at not being able to move the claim since to be able to move the claim (With / rp redefine naneofclaim) Charges them as if it were a new claim or by removing the claim they lose the money invested.
Tip: A command to move the claim and have a small penalty in cost (To be defined by admin)
To be able to customize the return of the money or part of the money to the user when removing the claim.

I'm sorry if my English is not very good I only speak Spanish.

Pd: My users have lag when activating the deny-build-near option
I use cauldron and I have RedProtect-7.5.6-b163-Universal.jar

Thank you! :+1:

**Comment by FabioZumbi12** [comment]
Try the latest dev build.

**Comment by NonoxSoux** [comment]
I've tried it, the plugin loads correctly but the ingame commands do not respond.

**Comment by comonier** [comment]
permissions:
    - redprotect.own.redefine [old]
    - redprotect.command.redefine [new]
check permissions
