### ISSUE TITLE
só reportando erro no console

### ISSUE THREAD

**Issue by comonier** [FabioZumbi12/RedProtect#462]
link do erro: https://paste.ofcode.org/353qc3zQgEKUXN5Ljv5ewDc
rp verion: RedProtect-7.6.0-b221-Universal.jar
[Sat, 25. May 2019 23:00:24 EDT INFO] CONSOLE issued server command: /ess version
[Sat, 25. May 2019 23:00:24 EDT INFO] Server version: 1.14.1-R0.1-SNAPSHOT git-Spigot-03bd4b0-17da342 (MC: 1.14.1)
[Sat, 25. May 2019 23:00:24 EDT INFO] EssentialsX version: 2.16.1.180-mc114-b95
[Sat, 25. May 2019 23:00:24 EDT INFO] PermissionsEx version: 1.23.4
[Sat, 25. May 2019 23:00:24 EDT INFO] Vault version: 1.7.2-b107
[Sat, 25. May 2019 23:00:24 EDT INFO] EssentialsXChat version: 2.16.1.180-mc114-b95
[Sat, 25. May 2019 23:00:24 EDT INFO] EssentialsXGeoIP version: 2.16.1.180-mc114-b95
[Sat, 25. May 2019 23:00:24 EDT INFO] EssentialsXSpawn version: 2.16.1.180-mc114-b95

**Comment by FabioZumbi12** [comment]
Versão e build do redprotect?

**Comment by comonier** [comment]
blz tu é muito rapido já sai + 2 rs

**Comment by comonier** [comment]
eu acho super estranho que sempre q tu lança uma build nova começa a dar erro nas build antigas
tipo automático em tempo real - coisa que não daria antes de tu lançar a nova.

**Comment by comonier** [comment]
tem 1 alerta na inicialização
https://paste.ofcode.org/KbW9EHRysBnb2vDhrRYVTa
e o servidor ta travado ninguém consegue logar
mas não sei se é culpa do rp

**Comment by comonier** [comment]
![image](https://user-images.githubusercontent.com/19571541/58376860-a986c500-7f4a-11e9-9b51-207a7ee33e8b.png)

**Comment by comonier** [comment]
https://paste.ofcode.org/jZi2Pjf3PHGkSUhBWfhEFa
é de pau não sei o que é poderia me dar 1 dica ?

**Comment by comonier** [comment]
erro no console, após iniciar o servidor, fica travado e ninguém loga. =/
será culpa do rp - ou outro plugin ?
https://paste.ofcode.org/A4GmFMCmgnd8ddt3CzCSnq

**Comment by comonier** [comment]
hoje de manha eu liguei o servidor sem erro nenhum vai ver era tudo culpa do host, vlw.
