### ISSUE TITLE
[BUG] WorldEditCUI + RP Problem 

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#466]
Hello, I'd like the users to see the line when drawing zones. So I put the plugin WorldEditCUI on it. I also gave them the permission redprotect.select-we. But all this does not work! To move the users have to take a wooden sword. That is set with us. 

Now the users with the wooden sword pull the zone to each corner point. They still don't see any particles. Now they have to hit the floor with a wooden axe and the particles appear all at once.

But that doesn't last long. Then you can re-select and there will be no particles so you have to hit the floor with the axe again to make it work for a few minutes. Then comes the selection particles are no longer displayed, because you didn't change it for a while."

Isn't it somehow possible that the particles come without taking a woodenaxe? 

I first thought about exchanging the axe for a wooden sword in Worldedit, but then I get problems as an owner if I want to work on zones with Worldedit.

Does anyone know any advice on how to use WorldEditCUI without axe that it works with RP?

**Comment by FabioZumbi12** [comment]
It worked on previous versions? Seems worldedit/WeCui is not 100% compatible with 1.14.2 for now.

**Comment by FabioZumbi12** [comment]
Use the own border system.
