### ISSUE TITLE
[BUG] Chat SPAM when on presureplate

### ISSUE THREAD

**Issue by baxandrei** [FabioZumbi12/RedProtect#468]
**Describe the bug**
When you step on a pressure plate and you are not a member in the region, chat is being spammed. http://prntscr.com/nwk7x9

**To Reproduce**
Stay on a pressure plate in a region.

**Expected behavior**
When you step on a pressure plate and you are not a member in the region, chat is being spammed.

**Screenshots and LOGs**
http://prntscr.com/nwk7x9

**Server and plugins versions (please complete the following information):**
 - Server: This server is running Paper version git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
 - Plugin Version: RedProtect-7.5.5-b141-Universal
 - Java Version: openjdk version "1.8.0_212" OpenJDK Runtime Environment (build 1.8.0_212-b04) OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

**Additional context**

**Comment by FabioZumbi12** [comment]
You is using a too old version. Update to latest dev build and try again! We are on 7.6.0 b233 and i cant support outdated versions.

**Comment by baxandrei** [comment]
WIll work on 1.13.2?
