### ISSUE TITLE
[BUG] Misplaced GUI Icons

### ISSUE THREAD

**Issue by DARG367** [FabioZumbi12/RedProtect#469]
**Describe the bug**
1. The GUI on the main spigot website provides a GUI for `/rp flag` with properly placed window dividers. But on version RedProtect-7.6.0-b233-Universal.jar the GUI looks like this instead. ![Misplaced GUI Icons](https://i.imgur.com/sAHzaKv.png)
2. Missing GUI icons as show here in the picture. ![Missing GUI Icons](https://i.imgur.com/FthjOTo.png)

**To Reproduce**
1. Type `/rp flag` while in your owned region.
2. Misplaced GUI icons and wrong icon names.

**Expected behavior**
To have the GUI looking like the one on the main spigot page listed here...
![Proper GUI Icons](https://proxy.spigotmc.org/da22e405d753eafd9b553ca4da71419168461d0e?url=http%3A%2F%2Fi.imgur.com%2F0uEb07h.png)

**Server and plugins versions (please complete the following information):**
 - Server: Paper (Version paper-65)
 - Plugin Version: RedProtect-7.6.0-b233-Universal.jar
 - Java Version: Java 1.8

**Comment by DARG367** [comment]
To fix the missing icons for number 2 issue. Use this if you have just installed the version I am using RedProtect-7.6.0-b233-Universal.jar

https://gist.github.com/DARG367/92bfa1b35a5dee84baebc2dee19ec343

**Comment by FabioZumbi12** [comment]
You just need to adjust your item GUIs on `guiconfig.conf` to your minecraft version, as example, if on 1.14, `WODDEN_BUTTON` should be `OAK_WODDEN_BUTTON` (or something like, i dont remember exactly).

As you see on message, you need to adjust that flag item names.
