### ISSUE TITLE
FakePlayers Not Able To Interact

### ISSUE THREAD

**Issue by Stuart74** [FabioZumbi12/RedProtect#47]
I am wondering about fakeplayers as my players are unable to use BC Fillers etc I had asked them to add the below Fakeplayers to their trust with /rp am 

This is the list of fakeplayers that i know of 

[Mekanism] - Mekanism
[BuildCraft] - BuildCraft
[Forestry] - Forestry 
ComputerCraft - ComputerCraft
[OpenComputers] - Open Computers
[Stevescart] - Steve's Carts
[MineFactory] - MineFactoryReloaded
[CoFH] - Autonomous Activator
[SFM_PLAYER] - Steve's Factory Manager
[EioFarmer] - Ender IO Farmer
FakeThaumcraftGolem - Thaumcraft Golems
FakeThaumcraftBore - Thaumcraft Arcane Bore
[EioKillera] - Ender IO KillerJoe
[Minecraft] - Extra Utilities

Is there something i am missing or do you have a list of fakeplayers that would work and allow my members machines to build.and interact with their stuff. 

I did OP these fakeplayers and when i added them to the worlds __Global__region it prevented anybody interacting in there regions so that is not going to work just hoping you had an idea.

**Comment by FabioZumbi12** [comment]
You mean fakePlayer by mentioned MODs right? I really dont know how to work mod fakeplayers, but i think if you add the fakeplayer by Nick on region this fakeplayer will be able to build on RPs. My plugin only lister to players... if this mods send your this fakeplayers as player, its supposed to work.

**Comment by Stuart74** [comment]
Greifprevention does it the same way and thats how i have done it on your plugin but i think its a deeper issue as the items such as fillers, autonomous activers and the such that are known fakeplayers wont work in non protected area i am attempting to write a small fakeplayer fix plugin for this.

**Comment by Stuart74** [comment]
Issue is not a redprotect issue so i am closing it thanks for all the support you have given me and will defiantly be sending you a donation in the next week. Fakeplayers are always a pain when it comes to protection plugins be it this one or GP or WG keep up the great work.
