### ISSUE TITLE
[BUG] with Alow place or break spawners

### ISSUE THREAD

**Issue by baxandrei** [FabioZumbi12/RedProtect#470]
**Describe the bug**
After i set "Alow place or break spawners" to true, non-members can place spawner, can`t break spawners back.

**To Reproduce**
1. /rp flag
2. Set Alow place or break spawners to true
3. Let a non-member of region to place spawners
4. Now they can`t get spawners back.

**Expected behavior**
From what I read from the description of the flag, it had to allow them to put spawners and break them, but I can only put them.

**Screenshots and LOGs**
https://youtu.be/6FexdYvYR-0

**Server and plugins versions (please complete the following information):**
 - Server: This server is running Paper version git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
 - Plugin Version: RedProtect-7.6.0-b233-Universal
 - Java Version: openjdk version "1.8.0_212" OpenJDK Runtime Environment (build 1.8.0_212-b04) OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

**Additional context**
Sometimes they can not even put them, but eventually they will work.

**Comment by FabioZumbi12** [comment]
Fixed on latest dev build.
