### ISSUE TITLE
[Suggestion] WESV + RedProtec?

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#472]
I'm still looking for something that makes the zone boundary visible, pulling the zone and me /rp Border.  Would the plugin be useful for that?

Can I use RedProtec together with the WESV to see the zones? Is it possible to establish a connection?

https://www.spigotmc.org/resources/worldeditselectionvisualizer-1-7-1-14.17311/

**Comment by Blueeyestar** [comment]
I have tested it now and with it you can see where you have set the claim points. It would be great if RedProtec can set it up like WECUI.

**Comment by FabioZumbi12** [comment]
Ill add an own system on redprotect based on that plugin ;)

**Comment by Blueeyestar** [comment]
Super that would be mega great because that's really missing. especially for users who are a little weak in the head ^^ 

You're doing a great job.

**Comment by Blueeyestar** [comment]
I've seen you insert out of something like this with flames. How does it work? sometimes you don't see them sometimes. Do you only see them at /rp border or even if you set the claim points. But I think it's great that something like this is finally introduced :)

**Comment by Blueeyestar** [comment]
The new border looks great with the particles. The users are thrilled. Super work you did again
