### ISSUE TITLE
[Suggestion] setminy + setmaxy for User

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#473]
I would like the users to be able to adjust the subzone heights on their own zone. Is that possible?  Or is that rather difficult to set up?  I don't want to give the admin the right to set the height.  Otherwise there would only be problems. They should only be able to set it up themselves.

**Comment by FabioZumbi12** [comment]
Just give the permissions `redprotect.command.setminy` and `setmaxy`

**Comment by Blueeyestar** [comment]
Thank you
