### ISSUE TITLE
[Suggestion] Border selection

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#475]
We think it's great now that you can see your zones border through the new border. It would be great if the owner had the possibility to choose between 2 systems.

When I zoom in or out it was practical to see the corners with Glowstone. 

Can't you make 2 systems?

**1. system /rp Border1 = flame**

**2System /rp border2 = Glowstone**

That'd be great if you could handle it.

**Comment by FabioZumbi12** [comment]
No way, the block border was totally removed, btw i've added options for particles like intensity of amount of particles.
