### ISSUE TITLE
[BUG] double door on 1.13.2

### ISSUE THREAD

**Issue by baxandrei** [FabioZumbi12/RedProtect#478]
**Describe the bug**
When I open the right door, it goes wrong.

**To Reproduce**
Watch video.

**Expected behavior**
When I open the right door, it goes wrong.

**Screenshots and LOGs**
https://youtu.be/as3B9J4Mpa0

**Server and plugins versions (please complete the following information):**
Server: This server is running Paper version git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Plugin Version: RedProtect-7.6.0-b240-Universal.jar
Java Version: openjdk version "1.8.0_212" OpenJDK Runtime Environment (build 1.8.0_212-b04) OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

**Additional context**
-

**Comment by FabioZumbi12** [comment]
I cant reproduce this. Tryied to place doors in all sides and locations in a block and didnt get that result. Probabbly its an old chunk, and breaking and placing the door again should fix.

**Comment by baxandrei** [comment]
I tried to break them and I was just the same. I see the problem only occurs when I use the right door. If you want, I can leave you the server address to see.

**Comment by baxandrei** [comment]
Any news?

**Comment by MorokMC** [comment]
This bug occurs when the flag "Open Double and Iron Doors" is enabled.
It works on the version RedProtect-7.6.1-b242-Universal.jar.

**Comment by baxandrei** [comment]
On `git-Paper-97 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)` problem seems solved.

**Comment by baxandrei** [comment]
I forgot to mention that problem is solved only on 1.14.2, on 1.13.2 is still here.

**Comment by CloudeLecaw** [comment]
Well, they you know what you should do baxandrei ;)..Update the server *g*

**Comment by baxandrei** [comment]
I can`t. I have a server for 1.13.2 and another for 1.14.4...

**Comment by CloudeLecaw** [comment]
why dont use an other version of RedProtect on the older 1.13.2 Server?.... most simple solutionin that case :3

**Comment by baxandrei** [comment]
My players have informed me that the problem has disappeared since the last updates.
