### ISSUE TITLE
[BUG] Destroy Armor Stand 

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#479]
Spigot:CraftBukkit version git-Spigot-df0eb25-411609d (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)

RP:RedProtect-7.6.0-b240-Universal.jar

In the 240 version of RedProtec you can dismantle armor stands in secured zones !!! 

Please fix !!!

**Comment by FabioZumbi12** [comment]
I didn't reproduced this bug.

Tryied to break and get items from armor stands and its fully ptotected:
![image](https://user-images.githubusercontent.com/5833818/59242000-46e72780-8be0-11e9-8d31-4245b13c8f47.png)

(The message is in portuguese but means deny actions! Check your region flags and other plugins, and for errors on console.
