### ISSUE TITLE
[BUG] WARN at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.removeMark

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#480]
Spigot:CraftBukkit version git-Spigot-df0eb25-411609d (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)

RP:RedProtect-7.6.0-b240-Universal.jar

You can no longer delete zones from the dynmap, only after a restart are the zones removed.

10.06 22:44:53 [Server] Server thread/INFO [RedProtect] cmd1: rp delete XPSpinnenFarm
10.06 22:44:53 [Server] Server thread/WARN java.lang.NullPointerException
10.06 22:44:53 [Server] Server thread/WARN at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.removeMark(DynmapHook.java:90)
10.06 22:44:53 [Server] Server thread/WARN at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.remove(RegionManager.java:243)
10.06 22:44:53 [Server] Server thread/WARN at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandlers.handleDeleteName(CommandHandlers.java:386)
10.06 22:44:53 [Server] Server thread/WARN at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.DeleteCommand.onCommand(DeleteCommand.java:59)
10.06 22:44:53 [Server] Server thread/WARN at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:285)
10.06 22:44:53 [Server] Server thread/WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
10.06 22:44:53 [Server] Server thread/WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
10.06 22:44:53 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707)
10.06 22:44:53 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670)
10.06 22:44:53 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510)
10.06 22:44:53 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
10.06 22:44:53 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
10.06 22:44:53 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13)
10.06 22:44:53 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
10.06 22:44:53 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135)
10.06 22:44:53 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
10.06 22:44:53 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114)
10.06 22:44:53 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895)
10.06 22:44:53 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888)
10.06 22:44:53 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99)
10.06 22:44:53 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871)
10.06 22:44:53 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805)
10.06 22:44:53 [Server] Server thread/WARN at java.lang.Thread.run(Thread.java:748)
10.06 22:44:53 [Server] Server thread/INFO [RedProtect] Problems when remove marks to Dynmap. Is Dynmap updated?

**Comment by FabioZumbi12** [comment]
Its working fine here using the latest paperclip build 80 and Dynmap-3.0-SNAPSHOT!

I've deleted and created regions with success.
