### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by RaceVan** [FabioZumbi12/RedProtect#481]
**Describe the bug**
Protection does not cover armor stands.

**To Reproduce**
1. Place an armor stand in a protected area.
2. Get another player with no permision to break it.
3. He is able to break it and to obtain any armor or tools on it.

**Expected behavior**
Armor stands shouldn't be able to be broken in a protected area.

**Screenshots and LOGs**
----

**Server and plugins versions (please complete the following information):**
- Server: This server is running Paper version git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
- Plugin Version: RedProtect-7.6.0-b242-Universal.jar
- Java Version: openjdk version "1.8.0_212" OpenJDK Runtime Environment (build 1.8.0_212-b04) OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

**Additional context**
In a multiplayer server it would be very frustrating to lose your items simply by someone stealing them like this.

**Comment by FabioZumbi12** [comment]
On my server and on tests with other verisons its protected! Use the latest version available on Spigot and try again.

**Comment by baxandrei** [comment]
Server is using latest version 7.6.0 (build #242)

**Comment by RaceVan** [comment]
The problem has been solved, thank you.
