### ISSUE TITLE
[BUG] Which permissions needs to create player`s regions? 

### ISSUE THREAD

**Issue by SashaShtal** [FabioZumbi12/RedProtect#482]
Hello! Couldd you help me? I am creating server on Sponge for 1.10.2, RP version 7.3.0 andd i want players to create their own regions using magic wand)
![image](https://user-images.githubusercontent.com/51839212/59542511-f426ac00-8f0e-11e9-8905-6299d535f0a0.png)

**Comment by FabioZumbi12** [comment]
7.3.0 its too old. Update to latest available on Sponge Ore.

**Comment by SashaShtal** [comment]
Ok, i just seted up 7.6.1: Players have next permissions: 
![image](https://user-images.githubusercontent.com/51839212/59551928-9d11ed00-8f89-11e9-9d33-1b5fdb88f19a.png)

But i cant execute /rp wand command (it gives empry feedback), when i use /rp pos1 and /rp pos2 commands, then /rp claim there is error: 
![image](https://user-images.githubusercontent.com/51839212/59551951-d4809980-8f89-11e9-9156-1c91d5578021.png)

**Comment by FabioZumbi12** [comment]
You need to change the claim-type on config to `wand` or `both`
