### ISSUE TITLE
[BUG] Ender Chest Access Needs Chest Access

### ISSUE THREAD

**Issue by RageYT** [FabioZumbi12/RedProtect#483]
**Describe the bug**
Non-members of a region need access to the chests flag but also need access to the ender chests flag to have access to ender chests.

**To Reproduce**
1. Disable chest access within a region and enable ender chest access
2. Without having a person as a member, have them try accessing the ender chest

**Expected behavior**
Should not need chest access flag to use ender chest access flag.

**Server and plugins versions (please complete the following information):**
 - Server: Sponge 1.12.2-7.1.6
 - Plugin Version: RedProtect-7.6.1-b242-Universal.jar
 - Java Version: 1.8

**Comment by FabioZumbi12** [comment]
Fixed on latest dev build on https://github.com/FabioZumbi12/RedProtect/commit/ba50c9cfd2cb38b958eaca3cb2ebec2ce4431bcc
