### ISSUE TITLE
Crop Trample protection not working [BUG] 

### ISSUE THREAD

**Issue by PopcornMadness** [FabioZumbi12/RedProtect#484]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

**Describe the bug**
In the global flags file, crop-trample is set to false, yet crops can still be trampled.
**To Reproduce**
1. Jump on crops
2. Crops will be trampled

**Expected behavior**
I expected the crops to not be trampled

**Server and plugins versions (please complete the following information):**
 - Server: Spigot 1.14.2
 - Plugin Version: RedProtect-7.6.1-b242-Universal.jar

**Comment by FabioZumbi12** [comment]
Tested here and crops are protected on RedProtect on 1.14! Tested on latest 1.14.3 and latest dev build of redprotect! Check for errors on console, player permissions on region and for other plugins conflicts!
