### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by anatoliy99** [FabioZumbi12/RedProtect#485]
I got a bug on the server with invisible players / mobs that were now visible, then invisible. After I removed the redprotect this bug was gone. I tried to install different versions of the plugin, it did not help. Also sometimes noticed bugs with lighting in hell (maybe a client)
The version of SpongeForge is the latest for the moment. Forge is the last one for 1.12.2 (I didn’t notice this bug on the older Forge and Sponge mods assembly, and I don’t have it in single player)

mods:
ic2
advanced mashines
advanced solars panels
buildcraft
Jei
Foresty
Code chiken lib
commpact solars arrays
custom npc
ender core
ender io
gravity suit
hide names
infernal mobs
iron chest
modern warfare
omlib
openmodularturrets
railcraft
spartan shields
spartan modony
trapcraft
varied commodities

plagins:
nucleus (tried to install any version)
redprotect (tried to install any version)
Luckperms

**Comment by anatoliy99** [comment]
Sorry for my bad english

**Comment by anatoliy99** [comment]
java version - 1.8
sponge forge version - latest
the redprotect version is the latest

**Comment by FabioZumbi12** [comment]
I cant reproduce. If you is having this on any version seems to be related to your sponge version or conflicts with your client mods.
