### ISSUE TITLE
Error occurred while enabling RedProtect v7.6.1 (Is it up to date?)

### ISSUE THREAD

**Issue by Rikoyts** [FabioZumbi12/RedProtect#486]
Hi! I have a problem trying to install redprotect 7.6.1/7.6.0 in my cauldron 2.1403.1.54 server (1.7.10) (Java 8). 
Image:
[https://imgur.com/KMzfuRf](url)
I trying jenkins version and others (7.1.x, 7.2.x, 7.4.x, 7.5.x) but they didn't work.
Just let me use RedProtect v7.1 and older versions and I don't know where the old permit list is.
Could you take a look at my problem? Or if not send me the list of old permissions please.
I really like this plugin and it's a shame not to be able to use it. 
Thank you very much for your time!

**Comment by FabioZumbi12** [comment]
The problem in your print its related to a bad download! redownload or try to download manually and put the jar on plugin/mods folder manually too.
