### ISSUE TITLE
[BUG] Red protect does not load on my server correctly 

### ISSUE THREAD

**Issue by NonoxSoux** [FabioZumbi12/RedProtect#487]
**Describe the bug**
Red protect does not load on my server correctly 

**To Reproduce**
I simply put it in plugins, I prend the server and the plugin even if it appears in the list of loaded plugins does not work, when wanting to use the command "/ rp?" I get the following message "Error, use '/ rp?' to see the commands. " The rest of the commands do not work.

**Expected behavior**
I hope it has a solution, since I need to update the plugin and this prevents me from doing so.

**Screenshots and LOGs**
Console log: https://pastebin.com/PJ1pDM6c

**Server and plugins versions (please complete the following information):**
 - Server: Cauldron version 1.7.10-1614.58
 - Plugin Version: RedProtect-7.6.1-b242-Universal.jar
 - Java Version: 1.8.0_201

**Comment by FabioZumbi12** [comment]
Theres no RedProtect logs on your pasted logs! Try to find redprotect looking with ctrl+f first and then post the logs here.

**Comment by NonoxSoux** [comment]
Sorry for the delay, I'm using the latest published version of the plugin and I had to restart twice until it came out on the console.

- Plugin Version: RedProtect-7.6.2-b245-Universal.jar

**Comment by FabioZumbi12** [comment]
I see redprotect, but you have a big problema because as the redprotect generated a war, all yout other mods plugins has the same message... its not a problem with redprotect

**Comment by NonoxSoux** [comment]
I've been doing tests on a server only of thermos without my mods or plugins and even red protect has failed to load ...
I need to update the plugin and be able to find the solution to the problem please :c 
https://pastebin.com/LbPaHavR

**Comment by NonoxSoux** [comment]
@FabioZumbi12 Forgive my insistence help please :c

**Comment by FabioZumbi12** [comment]
You server version dont have a dependency where is present on other server versions and on recent minecraft versions. I cant fix this now and i need to check what deps i need to add on jar to work with your version.

**Comment by FabioZumbi12** [comment]
Try the latest dev build 255

**Comment by NonoxSoux** [comment]
"ERROR Error occurred while enabling RedProtect v7.6.2 (Is it up to date?)"
Log: https://pastebin.com/4kYQHjqb
U_U

**Comment by daniorio** [comment]
![изображение](https://user-images.githubusercontent.com/42574494/61788981-c721bf00-ae13-11e9-9f5c-21cfcb93eb1d.png)
Latest 256 build

**Comment by NonoxSoux** [comment]
Sorry for bothering you, I know you're busy but there's no news? @FabioZumbi12 U_U

**Comment by FabioZumbi12** [comment]
Will not work on 1.17.10 :/

The libs conflicts with the java classes from 1.7. You will need to use this version: https://www.spigotmc.org/resources/redprotect-anti-grief-server-protection-region-management-1-7-1-14.15841/download?version=266312
