### ISSUE TITLE
[BUG] Mysql Support (Flags)

### ISSUE THREAD

**Issue by ShiroeSama** [FabioZumbi12/RedProtect#489]
Hi FabioZumbi12 ! 
It's already me x)

### **Version**
RedProtect-7.6.2-b247-Universal

### **BUG**
Claim a region after selected zone with wand tool.

### **Log**

[17:58:12] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RedProtect.Sponge.database.WorldMySQLRegionManager:addLiveRegion:199]: 	at java.lang.Thread.run(Thread.java:748)
[17:58:12] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.sql.SQLException: Data too long for column 'flags' at row 1
Query is: INSERT INTO `redprotect_RepubliCraft_1.6.4` (name,leaders,admins,members,maxMbrX,minMbrX,maxMbrZ,minMbrZ,minY,maxY,centerX,centerZ,date,wel,prior,world,value,tppoint,candelete,flags) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?), parameters ['ShiroeS_Test','b5d39042-cb0a-402c-bea9-7d153fe73c1d@ShiroeS','','',-10,-22,191,179,0,255,-16,185,'05/07/2019','',0,'RepubliCraft_1.6.4',0,'',1,'can-grow:true,leaves-decay:true,allow-effects:true,door:false,teleport:true,allow-spawner:false,mob-loot:true,button:false,player-damage:false,fire:false,flow:true,iceform-player:true,allow-home:false,chest:false,iceform-world:true,smart-door:false,fishing:false,use-potions:true,lever:false,pvp:false,spawn-animals:true,passives:true,press-plate:false,minecart:false,ender-chest:false,build:false,allow-fly:true,gravity:true,flow-damage:false,spawn-monsters:false,allow-potions:true']
[17:58:12] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
[17:58:12] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:223)
[17:58:12] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:212)
[17:58:12] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 28 more

### **To Reproduce**
1. Connect to the server (With Mysql Support Enable)
2. Get the wand
3. Select Region/Zone
4. Claim it
5. Normaly you see an error in console and if you enter /rp list you couldn't see any region in the chat

### **To Solve them**

I think you can make more largest the flags column. Actually, the column has 200 characters, but the string have 483 characters.
Maybe you can try change the flags column into a 'LONGTEXT' mysql type.

_**Mysql Table Description**_ 
```
CREATE TABLE `Test`(
    NAME VARCHAR(20) PRIMARY KEY NOT NULL,
    leaders LONGTEXT,
    admins LONGTEXT,
    members LONGTEXT,
    maxMbrX INT,
    minMbrX INT,
    maxMbrZ INT,
    minMbrZ INT,
    centerX INT,
    centerZ INT,
    minY INT,
    maxY INT,
    DATE VARCHAR(10),
    wel LONGTEXT,
    prior INT,
    world VARCHAR(100),
    world_value INT NOT NULL,
    tppoint MEDIUMTEXT,
    flags LONGTEXT,
    candelete TINYINT(1)
) CHARACTER SET utf8 COLLATE utf8_general_ci
```

_**Code Implementation (WorldMySQLRegionManager.java)**_ 
```
st = con.prepareStatement("CREATE TABLE `" + tableName + "` " + "(NAME VARCHAR(20) PRIMARY KEY NOT NULL, leaders LONGTEXT, admins LONGTEXT, members LONGTEXT, maxMbrX INT, minMbrX INT, maxMbrZ INT, minMbrZ INT, centerX INT, centerZ INT, minY INT, maxY INT, DATE VARCHAR(10), wel LONGTEXT, prior INT, world VARCHAR(100), world_value INT NOT NULL, tppoint MEDIUMTEXT, flags LONGTEXT, candelete TINYINT(1)) CHARACTER SET utf8 COLLATE utf8_general_ci");
```

### **Server and plugins versions**
- Server : Sponge Forge 1.12.2 7.1.5.2768
- Plugins Version : RedProtect-7.6.2-b247-Universal
- Java Version : 1.8

**Comment by ShiroeSama** [comment]
AH !

Take care of the 'value' column, I don't know what is the usage of this field but I renamed it in 'world_value'.

Why I rename it ? 
Because in MYSQL the 'value' world in a protected keyword and if you use it as column name, you can have some error because of this.

**Comment by FabioZumbi12** [comment]
Hi Shiroe, try to change the type of flag column like you did on leaders. I ve changed to varchar on latest dev build, but only for new installations.

**Comment by ShiroeSama** [comment]
Yes that what I do for the moment ;)

Normaly with this new creation thank to my create table command we will be fine for MySQL ;)

I tried this befire :)

**Comment by ShiroeSama** [comment]
Yes that what I do for the moment ;)

Normaly with this new creation thank to my create table command we will be fine for MySQL ;)

I tried this befire :)

**Comment by ShiroeSama** [comment]
I have also an other request.

 I think that will better to set name in varchar(100) or varcahr(200) Just for more characters to named our region.

Tell me when you have made fix for flags. And maybe if you are okey to made more characters for name column.

At this moment, I have changed the database structure like I send before and it's working as well.

**Comment by FabioZumbi12** [comment]
I already did some changes on dev builds. You can see the code here: https://github.com/FabioZumbi12/RedProtect/blob/master/RedProtect-Sponge-56/src/main/java/br/net/fabiozumbi12/RedProtect/Sponge/database/WorldMySQLRegionManager.java#L77

If you have more suggestions, ill like to check ;)

**Comment by ShiroeSama** [comment]
Ok ok ! 
Thanks ;)

Otherwise, use the mysql table structure that I sent before to fix the mysql tables. I remake my database like rhis and it's working correctly ;)

**Comment by ShiroeSama** [comment]
Hi FabioZumbi12 ! 

Did you change the database creation string in the next build ?
