### ISSUE TITLE
deny-cmds

### ISSUE THREAD

**Issue by netherarts** [FabioZumbi12/RedProtect#49]
Thanks for your update! 

But, I can't use the flag deny-cmds after update.

it keep displays 'usage : blah blah'

i typed '/rp flag deny-cmds spawn,tpa,tpaccept

**Comment by FabioZumbi12** [comment]
This update includes this changes: https://github.com/FabioZumbi12/RedProtect/issues/39

**Comment by netherarts** [comment]
Can i use this command without argument like this deny-cmds spawn,tpa,tpahere ... ?

**Comment by FabioZumbi12** [comment]
Yes, you need to change to deny-cmds cmd:spawn,cmd:tpa,cmd:tpahere ...you can usa only cmd: Or only arg:

**Comment by netherarts** [comment]
greatly appreciate for your quick help! i will donate!!
