### ISSUE TITLE
[BUG] CREATEPORTAL

### ISSUE THREAD

**Issue by Express5** [FabioZumbi12/RedProtect#490]
WHEN I TRY TO CREATE A PORTAL, THE PLUGIN SAYS "YOU DONT HAVE PERMISSIONS".
WHAT? I AM OP. WHAT IS WRONG WITH IT? I EVEN TRIED TO GIVE ME ADMIN IN THE REGION BUT STILL HAVE THE SAME ISSUE. PLS HELP.

**Comment by FabioZumbi12** [comment]
Whats the server version, sponge, spigot...? What Redprotect jar version (jar name)? Help me to help you :/

**Comment by Express5** [comment]
Spigot 1.14.2, the RedProtect version is the last one.

**Comment by Express5** [comment]
Sorry caps lol ,didn't realise I wrote in caps xD

**Comment by FabioZumbi12** [comment]
Fixed on latest dev build available on ou jenkins
