### ISSUE TITLE
[BUG] Wrong calculation magic wand

### ISSUE THREAD

**Issue by MorokMC** [FabioZumbi12/RedProtect#491]
**Describe the bug**
When using wand from WorldEdit 48 * 48 blocks, 2304 blocks are obtained.
When you use wand from RedProtect the same 48 * 48 blocks, for some reason it turns out 4418 blocks.

**Expected behavior**
It would be desirable when using wand from RedProtect to count blocks on a plane.

**Screenshots and LOGs**
![Безымянный](https://user-images.githubusercontent.com/2644698/60792141-32159980-a176-11e9-9054-319b33a95037.png)

**Server and plugins versions:**
 - Server: Sponge 1.12.2
 - Plugin Version: RedProtect-7.6.2-b247-Universal.jar
 - Java Version: Java 1.8

**Comment by FabioZumbi12** [comment]
This the size of the `x + y * 2`, set on max-scan on config file. Is not the region area, its the amount of blocks will be scanned on claim the region.
