### ISSUE TITLE
[Problema] Não cobra valor por bloco de área em novas RPs

### ISSUE THREAD

**Issue by eltonnikecasa** [FabioZumbi12/RedProtect#493]
Ola, uso seu plugin a muito tempo e desde a 1.14 o plugin não esta cobrando a área das RPs.
Ja testei varias Versões de Java, e Tambem Spigot e Paper. Testei o Vault estável e o de teste.

Ja resetei todo plugin, apaguei tudo refiz e não consegui. Talvez você tenha alguma dica.

Ou mesmo seja um bug.

Não consegui fazer funcionar

Caso tenha alguma nova mudança que eu não vi na Wiki por favor desconsidere.

Estou usando
Vault Estável
Paper #127
Java 8 testei 7 8 e 11

**Comment by FabioZumbi12** [comment]
Arrumado na ultima dev build(https://github.com/FabioZumbi12/RedProtect/commit/95c2e3b09fdbb29d230e2601f063dd7c1ac173da)
