### ISSUE TITLE
Redstone Crashes Server

### ISSUE THREAD

**Issue by Salty-Cheese** [FabioZumbi12/RedProtect#496]
Hi, my server crashes when redstone is activated. It's seems inconsistent thought.

Server: spongeforge-1.12.2-2825-7.1.6.jar
Plugin Version: RedProtect-7.6.1-b242-Universal.jar
Java Version: (build 1.8.0_151-b12)

Plugins:

AurionVoteListener-2.4.2-S7.1.0.jar
BiomesOPlenty-1.12.2-7.-.1.2425-universal.jar
CarrotShop-1.19-S7.1-MC1.12.2.jar
CatClearLag-0.9.0.jar
EcoBridge-1.12.2-2.0.7.jar
EvenMorePixelmonCommands-1.12.2-5.1.0.jar
holograms-3.1.5.jar
LuckPerms-Sponge-4.4.26.jar
MeltanFixer-1.12.1-S7.1-Mc1.12.2-plugin.jar
Nucleus-1.12.1.S7.1-MC1.12.2-plugin.jar
nuvotifier-2.5.3.jar
PixelExtras-1.12.2-2.4.8-universal.jar
Pixelmon-1.12.2-7.0.6-server.jar
PixelmonBroadcasts-1.12.2-0.4.1.jar
RedProtect-7.6.1-b242-Universal.jar
SimpleDexRewards-1.0-RELEASE.jar
spongeapi-7.1.0-shaded.jar
spongeforge-1.12.2-2825-7.1.6.jar
TotalEconomy-1.8.1.jar
TrainerCommands-1.12.2-2.5.0-universal.jar
WonderTrade-1.12.2-4.6.2-universal.jar
worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar

I posted this on the sponge forums and they referenced this line in the crash report. Said I should come here for a fix.

br.net.fabiozumbi12.RedProtect.Sponge.region.RegionManager.getTopRegion(RegionManager.java:264)

Thanks

**Comment by FabioZumbi12** [comment]
Ok but i need the console erros about redprotect too. Check if you is using the latest DEV build too from our discord.

**Comment by Salty-Cheese** [comment]
> Ok but i need the console erros about redprotect too. Check if you is using the latest DEV build too from our discord.

https://github.com/Salty-Cheese/Log-and-crash.git

Pardon me, I made the repository but forgot to post it.

I didn't know there were builds on discord.

**Comment by FabioZumbi12** [comment]
You is using a too old version of redprotect. We are on 7.6.2 build 252. Btw seems your server s is requesting a lot of regions at same time, probably an big region or a large system (based on your error log)

**Comment by CloudeLecaw** [comment]
> You is using a too old version of redprotect. We are on 7.6.2 build 252. Btw seems your server s is requesting a lot of regions at same time, probably an big region or a large system (based on your error log)  7.6.2 build 255 now :D

**Comment by Salty-Cheese** [comment]
I've updated the version and it has not has given this crash since thank you.
