### ISSUE TITLE
[BUG] PLugin don't work

### ISSUE THREAD

**Issue by daniorio** [FabioZumbi12/RedProtect#497]
**Describe the bug**
Plugin don't starting with error

**Screenshots and LOGs**
https://gist.github.com/daniorio/04191be131a5bd1f7744db29b69e2c14

**Server and plugins versions**
 - Server: Kcauldron/Thermos/Ultramine 1.7.10
 - Plugin Version: RedProtect-7.6.2-b247-Universal
 - Java Version: Java 8

**Comment by FabioZumbi12** [comment]
Seems some dep is not present on this server version. I ll look if theres a fix for thid!

**Comment by FabioZumbi12** [comment]
Will be solved on #487 with the same problem!
