### ISSUE TITLE
[BUG] can-projectile flag does not work

### ISSUE THREAD

**Issue by Salty-Cheese** [FabioZumbi12/RedProtect#500]
**Before open an issue, checkout this steps:**
I have been running this plugin for a while now.
I have the latest RP version off of the discord server RedProtect-7.6.2-b256-Universal.jar

I have the region flag "can-projectiles" set to "false" but i'm still able to shoot my bow in the air. I'm not able to use my bow when I am using it on a block though. I turned off my admin bypass as well as made sure I was not a member on these regions.

**To Reproduce**
Set region flag "can-projectiles" to false
Face no blocks and shoot bow.
No console errors.

**Expected behavior**
Not to be able to shoot my bow or throw out my pokeballs

**Screenshots and LOGs**
can-projectiles is false
![2019-07-24_17 59 54](https://user-images.githubusercontent.com/52469868/61835297-b9cef980-ae40-11e9-84cb-607efd6ef5d5.png)

My bypass perms are false and I can ready the bow
![2019-07-24_18 00 16](https://user-images.githubusercontent.com/52469868/61835330-d66b3180-ae40-11e9-94c3-7534568fb524.png)

I can shoot the bow multiple times
![2019-07-24_18 07 52](https://user-images.githubusercontent.com/52469868/61835341-e08d3000-ae40-11e9-93eb-96659f9fd20e.png)

I can't use the bow while looking at block
![2019-07-24_18 00 25](https://user-images.githubusercontent.com/52469868/61835350-ec78f200-ae40-11e9-98e0-7d87925b9c46.png)

I am also able to throw out pokeballs
![2019-07-24_18 00 31](https://user-images.githubusercontent.com/52469868/61835357-f7cc1d80-ae40-11e9-8a35-14030ffe576a.png)

**Server and plugins versions (please complete the following information):**
 - Server: forge-1.12.2-14.23.5.2838-universal.jar
 - Plugin Version: RedProtect-7.6.2-b256-Universal.jar
 - Java Version: build 1.8.0_151-b12

Is there a flag I can toggle in a region to not be able to spawn each individual entity or said entity to not interact with anything? I.E. pokeballs with NPC trainers? Or throwing pokeballs a part of the can-projectiles flag?

Thanks

**Comment by FabioZumbi12** [comment]
Tested and its working fine. Tryed to shoot looking for blocks, to air and looking up, all blocked by `can-projectiles` on `false`.
