### ISSUE TITLE
[BUG] Spawn blacklist in the map

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#502]
Hi,

I use PaperSpigot 1.14.4 and the last version of this plugin (258).

I have always had ghosts in the blacklist of some cards, but with the update of my server in 1.14.4, they still appear.

In globalflags.conf : 
![Capture](https://user-images.githubusercontent.com/24486147/61998475-01f45300-b0b1-11e9-852c-cef8e7e0f3cc.PNG)

**Comment by FabioZumbi12** [comment]
This is a bug related with minecraft/spigot still alowing phanton spawn until cancelled. And the other thing is the phanton spawn near the player, sometimes out of a region and then came inside. Btw, if the player sleeps, the Phantons will not spawn for a long time xD

**Comment by Darkilen** [comment]
Hello, what if players are not allowed to sleep ? We have to deal with Phantoms ?
We have this issue in a global scope. We can't deny Phantoms from spawning in a map, regardless if we are in claims or not, even if the map don't allow players to claim on it.
