### ISSUE TITLE
[Suggestion] Lectern interaction for non-added member in a claim

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#504]
Hi,

For 1.14 could we have the possibility that non-added members of a claim could interact with lecterns ? It would take a new flag or integrate it into an already existing flag (not that of the chests!).

Thank you in advance.

**Comment by FabioZumbi12** [comment]
Only one flag for this item and only on 1.14, no for now. Use the chest (add the item name to config for chest flag interaction)

**Comment by aurel85** [comment]
Too bad because with this flag players can take it :/
