### ISSUE TITLE
[BUG]claim limit

### ISSUE THREAD

**Issue by INMADE666** [FabioZumbi12/RedProtect#505]
Hi there! i have a problem.
claim limits doesnt work, its always unlimited for every group in luckyperms
Here is my
config.conf
# Declare here the permissions you want to use for your players and groups.
permissions-limits {
    blocks=[
        "redprotect.limits.blocks.8000"
    ]
    claims=[
        "redprotect.limits.claim.5"
    ]
Im using LuckyPerms and this command doesnt work too
redprotect.limits.claim.5

**Comment by FabioZumbi12** [comment]
Redprotect dont give ilimited to player by default. In somewhere you have added the permissions `*` or ilimited to your players or group. This is not a bug.
