### ISSUE TITLE
[BUG] Auto-complete with player names

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#506]
Hi,

Since 1.14 the tab-complete for player names no longer work with RedProtect commands, it's very annoying.

I use the last version of this plugin (build 258) and PaperSpigot 1.14.4.

Thank you in advance.

**Comment by FabioZumbi12** [comment]
For what commands? I have solved this some build ago.

**Comment by aurel85** [comment]
/rp list, /rp addmember, /rp blocklimit... I think all.

**Comment by FabioZumbi12** [comment]
Fixed on https://github.com/FabioZumbi12/RedProtect/commit/12d5c0af907cc093e7b5ff745db12ec6351ddecc

**Comment by aurel85** [comment]
Thank you, but it's a shame that it differentiates capital letters and tiny letters... With other plugins there is no problem. If I type an "a" they suggest me the nicks that have a tiny letter "a" as a capital letter "A".

**Comment by FabioZumbi12** [comment]
Easy to fix, already on latest dev build.
