### ISSUE TITLE
[Suggestion] More wand configuration

### ISSUE THREAD

**Issue by DevSrSouza** [FabioZumbi12/RedProtect#508]
**Is your feature request related to a problem? Please describe.**
- The wand items can't break blocks, if is a shovel you will never use her like a shovel.
- If is axe, shovel or any tool Item, will always spam in chat that you are selecting new position for claim.
- Keep right mouse button pressed spam the selection, like worldedit, make show the selection one time if the block/location is selected.

**Describe the solution you'd like**
- Add an option to config for enable break blocks with the wand items (admin and info)
- Add an option to config for use just one type of click to select the two places (right click)
- Make a check if the block is not already selected before send the message

**Comment by FabioZumbi12** [comment]
Em br mesmo... são ajustes bem finos que eu não considero tão importante pra serem implementados. E tambem, se o player não tiver a permissão pra usar a wand, tudo funciona normalmente, então só por o wand pra um item "inutil" como a vareta, ou algo assim.
