### ISSUE TITLE
Suggestion: Adding Claim Blocks Via Admin/Console Command

### ISSUE THREAD

**Issue by ghost** [FabioZumbi12/RedProtect#51]
I would love to see and option where through console or admin the ability to increase the blocks players are allowed to claim. Especially being able to have claim sizes determined by rank also. 

I use a playtime reward system and be nice to say after x amount of hours you will be rewarded x amount of claim blocks on top of what the member alreadys has, or they can purchase more claim blocks or claims using the playtime points or by using an economy plugin. 

Maybe also the ability claim blocks increase over time to a maximum allowed, 

If any of the above is already implented especially the different amount of claims per permission rank i am unsure how this works.

**Comment by 7h3ev1l** [comment]
U can use permissions 
```  
redprotect.limit.blocks.10000
redprotect.limit.claim.200
```

**Comment by Stuart74** [comment]
Thanks 7h3evi1l that helps me with the ranks getting certain amount of claims and blocks but still there is no way to add more blocks to peoples current claims unless an admin manually changes the protection area. 

Still be good to have it like its done on the griefprevention plugin where you earn extra claim blocks or purchase extra claim blocks either via loyalty points / ingame currency or the from packages on buycraft store.

**Comment by FabioZumbi12** [comment]
I will add a command to add blocks to players. But for this i will need to create additional files for each player. But i will add soon ;)

**Comment by lafaipopo** [comment]
Yes, very cool feature.

**Comment by FabioZumbi12** [comment]
Permissions still the best solution.
