### ISSUE TITLE
[BUG] Zone claim is limited to 600 block

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#511]
I have a problem on the server. The users can no longer draw 12 000 block zones. It always comes -->> **Your selection exceeds the max distance between your two selected points. Limit: 600 - Your selection: 4620.0**

This was not the case in the past. Has anything changed?

_My settings in the Config:_

    # Time in seconds the request to be a leader of a region will expire.
    leadership-request-time=20
    # The default total of blocks a player can claim. 
    # The permission "redprotect.limits.blocks.<amount>" overrides this setting.
    limit-amount=**12000**
    # If using blocks for claim, this is the max blocks the plugin will scan before claim a region.
    max-scan=600

**Comment by Blueeyestar** [comment]
Does no one know a solution??

**Comment by aurel85** [comment]
Hi,

I'm not sure I understood everything but by increasing the max-scan that not solve your problem ?

**Comment by Blueeyestar** [comment]
I have now enlarged max-scan now you can claim as normal zones. Thanks for the hint
