### ISSUE TITLE
[BUG] Region update at startup

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#512]
Hi, 

Normal that every reboot there is 30 sec of that since 1.14.4 ? Someone has the same thing ?

https://pastebin.com/vEX26CJQ

This is done with each reboot since the 1.14.4 update and we can find several times the same regions...

I use PaperSpigot 1.14.4 and the last version of this plugin.

**Comment by FabioZumbi12** [comment]
This is not exactly a bug, but probably this players have changed their nicks, and redprotect cant find their online accnounts. You can fix the regions mentioned by editting manually.

**Comment by aurel85** [comment]
The problem is that it is not necessarily players who have changed their nickname. In my pastebin there is theodu and this player has never changed his nickname : https://fr.namemc.com/search?q=theodu

**Comment by aurel85** [comment]
Sometimes I have that too that appears in the console after what I sent above : https://pastebin.com/qHjwjRB6

Thanks for doing what's needed

**Comment by FabioZumbi12** [comment]
A solution should you do a search on regions files and if this players are not player in your server, you remove him from regions. What RP try to do is convert this player uuid to nicknames, i think this the cause of your startup time problems

**Comment by aurel85** [comment]
I'll start by removing these errors manually hoping there are not too many otherwise it'll be long...

**Comment by aurel85** [comment]
When the bug is at the owner level my only solution is to delete the region because I have this error : https://pastebin.com/XXunHdzZ

When he is a member no problem.
