### ISSUE TITLE
[Request] Update mvn-repo with v7.6.2

### ISSUE THREAD

**Issue by EpiCanard** [FabioZumbi12/RedProtect#514]
You made some changes inside RedProtect-API in 7.6.2 that do breaking changes compared to old API version 7.6.0.

My request is simple, can you update the branch mvn-repo with last 7.6.2 version to continue to work with last versions of the API ?

Thank you for your answer

**Comment by FabioZumbi12** [comment]
Updated! try again.

**Comment by EpiCanard** [comment]
Perfect, thank you.
