### ISSUE TITLE
[BUG] The arrows destroy the entities in the claims

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#516]
Hi,

When you shoot an arrow with a bow or a crossbow you can destroy some blocks in a claim without being added. I was able to test fruit choruses, boats and tnt.

I use PaperSpigot 1.14.4 and the last version of this plugin (263)

**Comment by FabioZumbi12** [comment]
People already cant break boats and minecarts and other blocks (tested). I've fixed only chorus fruits on https://github.com/FabioZumbi12/RedProtect/commit/4d4d3486c69c31834777a2dbca1c3fadb9ac99a6

**Comment by aurel85** [comment]
I tested and it's ok, thank you !
