### ISSUE TITLE
/rp Info breaks when adding Fakeplayers

### ISSUE THREAD

**Issue by Stuart74** [FabioZumbi12/RedProtect#52]
hey sorry to be a pain seems add forge mods fakeplayers to the protections will screw up the /rp info command due to the UUID changing on the fakeplayer when the server restarts i was under the impression the UUID never changed.

http://pastebin.com/ZtCKN98g

Seems that the UUID for the buildcraft mods fakeplayer changed and causes internal errors when doing /rp i   not sure if this is the case for the rest of the forge mod fakeplayers though. 

Once i had remove [BuildCraft] from the region /rp i worked fine.

**Comment by FabioZumbi12** [comment]
On truth, running in online mode my plugin only know UUIDs, and your fakeplayers are sending [BuildCraft] as uuid, but i think i fixed, try this version: https://github.com/FabioZumbi12/RedProtect/blob/master/release/RedProtect-6.5-SNAPSHOT.jar?raw=true

**Comment by Stuart74** [comment]
Seems to have fixed it and also fixed some of the fake player protection issues i was getting now its only one mod thats not being recognised thats open blocks block placer I cant find the fakeplayer name it uses. 

But the rp info works fine with the fakeplayers added thanks again :)

**Comment by FabioZumbi12** [comment]
The name is always [BuildCraft]? I think is the mod way to send the fakeplayer identification.

**Comment by Stuart74** [comment]
Yes indeed  Below is a list of fakeplayer names and there respective mod this is all that i can find 

[Mekanism] - Mekanism
[BuildCraft] - BuildCraft
[Forestry] - Forestry
ComputerCraft - ComputerCraft
[OpenComputers] - Open Computers
[Stevescart] - Steve's Carts
[MineFactory] - MineFactoryReloaded
[CoFH] - Autonomous Activator
[SFM_PLAYER] - Steve's Factory Manager
[EioFarmer] - Ender IO Farmer
FakeThaumcraftGolem - Thaumcraft Golems
FakeThaumcraftBore - Thaumcraft Arcane Bore
[EioKillera] - Ender IO KillerJoe
[Minecraft] - Extra Utilities
