### ISSUE TITLE
[Problema] 

### ISSUE THREAD

**Issue by TiNTin0TAG** [FabioZumbi12/RedProtect#520]
A água nao quebra as sementes, quando coloco água sobre ou ao lado das sementes(Trigo, Cenoura e Batata)elas nao são destruídas, alguns players utilizavam desse método para colher e agora nao conseguem mais, estou na versão 7.6.2-b247 espero que voce possa me ajudar, antes pensei que fosse alguma flag mas não achei nenhuma parecida com isso.
![image](https://user-images.githubusercontent.com/32472199/64050294-f1bb1200-cb4d-11e9-8c8e-155cdc7794d5.png)

**Comment by FabioZumbi12** [comment]
Habilita a flag `flow-damage` para true, ou no `/rp flag` clica no balde de lava.
