### ISSUE TITLE
[BUG] Plugin not Start On Mohist

### ISSUE THREAD

**Issue by Dhannyjsb** [FabioZumbi12/RedProtect#523]
Describe the bug
Plugin not start and give error message

Log 
https://pastebin.com/8GaPT0jt

Server and plugins versions

    Server: Mohist 1.12.2 https://github.com/Mohist-Community/Mohist
    Plugin Version: Latest version RedProtect-7.6.3-b270-Universal.jar
    Java Version: Java 8

**Comment by FabioZumbi12** [comment]
I dont know what type of server is this and never heard about. Cant you use spigot/paper? The seems to be related with some lib not found.

**Comment by FabioZumbi12** [comment]
Btw, seems to be a interesting server type... bukkit plugin + mods and updated! I'll take a look and do some tests!

**Comment by FabioZumbi12** [comment]
This can be fixed now!

> Yeah, i can confirm this! Sponge uses the version 1.3.1 and for Spigot the version 1.3.1 its shaded on Redprotect jar. If Mohist updates to 1.3.1 will fix, but for now, if you go to libraries folder and remove the folder 1.2.1 inside com\typesafe\config Redprotect will load!

https://github.com/Mohist-Community/Mohist/issues/8
