### ISSUE TITLE
[BUG] Pretty high performance impact on BlockListener (EntitySpawnEvent)

### ISSUE THREAD

**Issue by Kiryu144** [FabioZumbi12/RedProtect#524]
**Version: RedProtect-7.6.2-b247-Universal.jar**

**Describe the bug**
We're running a Freebuild server with a lot of regions, and logging the performance results in a lot of overhead from your plugin.

**Screenshots and LOGs**
https://i.imgur.com/IQpNlOx.png

**Server and plugins versions (please complete the following information):**
We're running one of the newest builds of PaperSpigot.

**Comment by FabioZumbi12** [comment]
I cant do nothing about this. This vary on server, mob spawn config and a lot of things! As example on my server with ~ 30 players we have no lags caused by RP. As an antigrief plugin, will listen for all spawned mobs (of all types).
