### ISSUE TITLE
[BUG] Permissions are not working correctly

### ISSUE THREAD

**Issue by GermanY1337** [FabioZumbi12/RedProtect#526]
**Describe the bug**
I set all the permissions and I still can't use /rp define. It's telling me that i dont have the Permissions for it. I'm using Luckperms as permission plugin

**Server and plugins versions (please complete the following information):**
 - Server: [spongeforge-1.12.2-2838-7.1.7-RC3903]
 - Plugin Version: [RedProtect-7.6.1-b242-Universal]
- LuckPerm Version: [LuckPerms-Sponge-4.3.75]
 - Java Version: [Java 1.8]

**Comment by FabioZumbi12** [comment]
You is using a too old version. Actually we are on 7.6.3. And to allow define commands, you need to set the `claim-type` in your config to `wand` or `both`. Its not needed permissions.
