### ISSUE TITLE
Flag for-sale

### ISSUE THREAD

**Issue by yerbuky** [FabioZumbi12/RedProtect#527]
**Server and plugins versions (please complete the following information):**
 - Server: [e.g. Sponge 1.12.2, sponge-2825]
 - Plugin Version: [e.g. RedProtect-7.6.3-b270-Universal.jar]
 - Java Version: [e.g. Java 1.8]

i would like know what can i do with the flag for-sale? i tried buy region created with /rp wand. its says last value 6420$ but i cant claim zone

**Comment by FabioZumbi12** [comment]
This flag was removed, prob i forgot to remove this from other places on plugin. Use the plugin recommended on discord, on announcements channel to buy/sell regions
