### ISSUE TITLE
[BUG] Enchanting table for non-members of claim

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#528]
Hi,

Usually with the flag chest, can allow the non members of the claim to interact with the enchanting table. Currently with flags enderchest, redstone, build and chest on true does not allow access to enchanting table for non-members of this claim.
Before 7.6.3 there was no problem.

I use PaperSpigot 1.14.4 and the last version of this plugin (version 271).

**Comment by FabioZumbi12** [comment]
Cant reproduce this. On my test server, enabled just chest, and one of each  flag you have mentioned and i can interact with enchanting table. Check if on private list is `ENCHANTING_TABLE`, not `ENCHANT_TABLE`

**Comment by aurel85** [comment]
Effectively it was well linked to a wrong name in the config (Enchantement_Table) and we must put Enchanting_Table.
