### ISSUE TITLE
[BUG] / rp flag cropsfarm   it does not work.

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#529]
RP-Version: 271
Spigot :CraftBukkit version git-Spigot-94af569-a3fdef8 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

I want to plant the users in the garden and harvest.
Unfortunately it does not work with / rp flag cropsfarm true

Also with the commands: / rp flag allow-break, / rp flag allow-place

It does not work that you can reap or plant. it always comes: You can not build here.

**Comment by FabioZumbi12** [comment]
Fixed on latest dev builds
