### ISSUE TITLE
[Bug] Economy issue?

### ISSUE THREAD

**Issue by lafaipopo** [FabioZumbi12/RedProtect#53]
We got issues using your pluggin,
1st problem: when we sell a claim, we fix the price, but when we purchase, no money is transferred, the economics links seem to be broken, we tried it on standard and op mode
2nd problem, when we buy a region, the seller doesn’t get any message, but the buyer does.
https://www.dropbox.com/s/5ej2ul6vyo9xc2v/Capture%20d%27%C3%A9cran%202016-05-13%2013.01.48.png?dl=0

The version tried is the last one Protection 6.5.81, 
- Tried on spigot 1.9.2 and 1.9.4, paper spigot
- Latest vault version and craftconomy
- Tried with only vault, and your pluggin without anything
- On production server we are using Craftconomy vault and Essentials
The test were made on your original version, without any change in translation and configuration we are using craftcononmy
We can provide you a French translation of the pluggin we will made for our server

**Comment by zedentox** [comment]
Hi,

I made some debug and it appears that the leaders who receive the message are not sellers but buyers. The bug is due to the fact that leaders list is retrieved after call to RPEconomy.BuyRegion. RPEconomy. I will create a PR soon.

**Comment by FabioZumbi12** [comment]
Thanks for help @zedentox - I've changed some thinks too. @lafaipopo download the latest release and try again:  https://github.com/FabioZumbi12/RedProtect/blob/master/release/RedProtect-6.5.82-b658.jar?raw=true

**Comment by lafaipopo** [comment]
Thank you, it's fixed!
