### ISSUE TITLE
Region Not Working[BUG] 

### ISSUE THREAD

**Issue by BarcodeGIT** [FabioZumbi12/RedProtect#530]
**Describe the bug**
I create the region for the Spawn. Set the flags so people cannot build nor destroy. But people are able to destroy but not build. and they cant destroy signs oddly enough.
**To Reproduce**
1. Create region
2. Turn off building
3. turn off destroying
4. People can destroy everything except signs

**Expected behavior**
People cant build or destroy anything

**Server and plugins versions (please complete the following information):**
 - Server: spongeforge-1.12.2-2838-7.1.7-RC3924.jar
 - RedProtect-7.6.3-b270-Universal.jar
 - Java Version: 1.12.2

**Additional context**
I originally thought the /setworldspawn default protection system was the issue causing weird interactions but i chnage it to /setfirstspawn and moved the /worldspawn somewhere else, and even moved the entire spawn area to see if that fixed it but still the same problem. I also tried to change the priority of the region but when it asked for confirmation i type /rp yes and it just kept bringing up the /rp help options and doing nothing. So idk

**Comment by FabioZumbi12** [comment]
This problem has been solved on b269 and >. Check if you is using the right build (latest 271) and if yes, check your console for some errors.
