### ISSUE TITLE
[Problema] Redprotect não consegue dar load

### ISSUE THREAD

**Issue by Opex1227** [FabioZumbi12/RedProtect#531]
**Descreva o bug**
Esta manhã eu fui abrir o meu server da aternos para jogar e notei que ninguem entrou, foi ai que eu abri meu discord e todos me falaram que não conseguiam entrar, eram barrados pela "Whitelist".
Depois de checar varias vezes a whitelist do server, eu me apercebi que foi o plugin redprotect que colocou uma whitelist e kickou/continua kickando todos do servidor.
Eu ja tentei reinstalar o redprotect e até já tenho a versão b270, tentei dar reload varias vezes, desisnstalei um plugin que tinha instalado antes do erro occorrer, e mesmo assim o erro continua.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Ir até a aba "servidor" em aternos
2. Clicar em iniciar
3. Jogar

**Comportamento esperado**
Eu esperave que conseguisse jogar com os meus amigos, em vez disso todos menos OP's estão barrados de entrar.
Regiões também não funcionam.

**Capturas de tela e registros**
[https://i.imgur.com/dIHbjEA.png](url)
[https://i.imgur.com/1dH6QYt.png](url)

**Versões de servidor e plug-ins (preencha as seguintes informações):**
 - Servidor: [Spigot 1.9]
 - Versão do plug-in: [RedProtect-7.6.3-270-Universal.jar]
 - Versão do Java: [Java 8]

**Contexto adicional**
Em aternos, os plugins funcionam na nuvem, por isso a minha versão java pode não ser tão util.

**Comment by FabioZumbi12** [comment]
Testa a versão dev que ta no Discord que deve arrumar. Isso acontece pq o RP encontrou um erro e bloqueou o server pra impedir de players entrarem sem o plugin de proteção.

**Comment by Opex1227** [comment]
Mas como eu testo a versão que esta no discord? Eu uso o server da aternos, nenhum plugin é do meu pc, é tudo da nuvem.

**Comment by FabioZumbi12** [comment]
Enviado pro bukkitdev/spigot, quando aprovar vc vai conseguir baixar pelo seu painel de controle da sua host.
