### ISSUE TITLE
[BUG] Ghost protected zones

### ISSUE THREAD

**Issue by KyroOW** [FabioZumbi12/RedProtect#534]
**Describe the bug**
There are some "ghost" zones where players can't do anything, even opening enderchests, there is no claims or anything.

**To Reproduce**
I don't know how this problem could be reproduced.

**Expected behavior**
Those ghost zones shouldn't exist and players should be able to build here.

**Screenshots and LOGs**
https://i.imgur.com/yIqcA3V.png

**Server and plugins versions (please complete the following information):**
 - Server: 1.12.2 PAPER
 - Plugin Version: RedProtect-7.6.2-b270-Universal.jar
 - Java Version: 1.8

**Additional context**
You can come on my server to investigate the ghost zones if you want, the address is mc.plakivado.fr, i located two zones for the moment, both of them are in separate worlds, there might be more of them but i haven't discovered them yet.

Also, no message are showing up at all on the chests that the player can't open.

**Comment by FabioZumbi12** [comment]
This only happens if the region is near Spawn, and the spawn-protection is more than 0 on server.properties. You can additionally look for server start logs and see if theres some errors.

**Comment by KyroOW** [comment]
That was correct, those areas disappeared once i set "spawn-protection" to 0, i don't know if that behavior was intended as it wasn't happening before and couldn't find anything related to it in the config files, but at least, it's fixed, thanks.

Also there was no errors in the console, just in case.

**Comment by FabioZumbi12** [comment]
May have errors in case spawn-protection is already on 0, btw, problem fixed ^^
