### ISSUE TITLE
[Suggestion] Action bar messeages

### ISSUE THREAD

**Issue by Bartek200219** [FabioZumbi12/RedProtect#535]
**Is your feature request related to a problem? Please describe.**
Add action bar as messeage on eneter, exit or welcome messeages 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/37016424/65851541-87b3a980-e353-11e9-8ab5-1739b4377429.png)

**Comment by FabioZumbi12** [comment]
Added on latest dev builds
