### ISSUE TITLE
[Suggestion] Tax System

### ISSUE THREAD

**Issue by Ash10744** [FabioZumbi12/RedProtect#536]
**Is your feature request related to a problem? Please describe.** I don't have a problem :S

**Describe the solution you'd like**  A taxes feature! Where an admin can set the tax rate for someone owning a region.. And the owner of said region can tax the members in their region!

So admins can keep control over regions! This can obviously be disabled but can be a feature for those who want it.

Also you are able to set when the taxes come out so monthly etc.

Summary:  [Be able to tax people for owning a region] --- [And Region owner is able to tax their members]

**Comment by FabioZumbi12** [comment]
Is there alreadu a plugin for rent regions w/redprotect support: https://www.spigotmc.org/resources/buyregion-1-13.60189/

**Comment by aenaveen** [comment]
But that buyregion does not provide a method to tax people for owning a region, it is more like upkeep from towny. Could really use an addon plugin at least. Love RedProtect btw.
