### ISSUE TITLE
[BUG] Chest_Minecart problem

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#538]
RP-Version: 297

Although I have banned in the config that you can access in Chest_minecart ... users can still grab in the boxes. The normal boxes are secured.

https://pastebin.com/YGXkYbPU

**Comment by FabioZumbi12** [comment]
Chest Minecart its an entity, add this on entity list, not block

**Comment by Blueeyestar** [comment]
I tried it in different variants. In the yml. Format I've got it still. but in the new conf. Format because I do not know which format I should enter.
can you give an example?

interact-entities {
                # Only this entities will not be allowed to interact.
                blacklist=[
                    "TNT_MINECART"
                ]
                # Only this entities will be allowed to interact, all others no.
                whitelist=[
                    HORSE,
                    MINECART
                ]
            }

**Comment by FabioZumbi12** [comment]
```
        if-interact-false {
            # Allow player interactions with monsters?
            entity-monsters=true
            # Allow player interactions with passives?
            entity-passives=true
            interact-blocks {
                # This items will not be allowed to interact, all other items will be.
                blacklist=[]
                # Only this items will allowed to interact, all other item will not be allowed.
                # You can add this blocks to allow basic exploration (accept regex):
                # "minecraft:grass", "minecraft:tallgrass", "minecraft:red_flower", "minecraft:chest"
                whitelist=[]
            }
            interact-entities {
                # Only this entities will not be allowed to interact.
                blacklist=[
                    MINECART,
                    "MINECART_CHEST"
                ]
                # Only this entities will be allowed to interact, all others no.
                whitelist=[
                    VILLAGER
                ]
            }
        }
        # Allow player interactions, with all entities or blocks?
        interact=false
```
It works with this config!
