### ISSUE TITLE
[BUG] Harvest problem

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#539]
Rp-Version: 280

Hello, you can now harvest wheat with / rp cropsfarm.

Unfortunately, it is still not possible to harvest carrots and beetroot potatoes and put them back as a guest.

Can you protect something in Red that you can also harvest potatoes, beetroot and carrots? and again plants?

**Comment by FabioZumbi12** [comment]
Try the latest dev build
