### ISSUE TITLE
Question about the camp deny-item-usage

### ISSUE THREAD

**Issue by yerbuky** [FabioZumbi12/RedProtect#540]
- Sponge 1.12.2,
 - Plugin Version: [e.g. RedProtect-X.X.X-b280-Universal.jar]
 - Java Version: [e.g. Java 1.8]

My question is, how do i make this flag?

        # Control what items the player can use.
        deny-item-usage {
            allow-on-claimed-rps=true
            allow-on-wilderness=false
            # The item names is like you see holding "F3" and pressing "H".
            items=[]
        }

it should be...

        # Control what items the player can use.
        deny-item-usage {
            allow-on-claimed-rps=true
            allow-on-wilderness=false
            # The item names is like you see holding "F3" and pressing "H".
            items=
            ic2:mining_laser
        }

Español: no se como rellenar ese campo... podrias hacerlo para que yo solo haga copy paste?

**Comment by FabioZumbi12** [comment]
Theres two ways:
```
items=[ic2:mining_laser1, ic2:mining_laser2]
```
or
```
items=[
  ic2:mining_laser1, 
  ic2:mining_laser2
]
```
