### ISSUE TITLE
[BUG] Deny-Cmds flag incorrect usage?

### ISSUE THREAD

**Issue by BarcodeGIT** [FabioZumbi12/RedProtect#541]
Using RedProtect -7.6.3 -b270-Universal with latest Spigot in (1.14.4)

**Describe the bug**
Trying to type in "/rp flag deny-cmds cmd:tpa " to deny tpa in the area
but says im using it wrong "Usage /rp flag deny-cmds cmd:<command>"

Im in the region and have all the perms, im assuming its syntax but i can't see where Im doing it wrong based off the template it gives me.

**Comment by Meme-Daddy** [comment]
I'm having the same exact issue. Really need it fixed to get my server up and running :(. I can't allow players to be able to claim a town at spawn

**Comment by FabioZumbi12** [comment]
Fixed on latest dev build
