### ISSUE TITLE
[Question] RedProtect disabled Whitelist ?

### ISSUE THREAD

**Issue by GermanY1337** [FabioZumbi12/RedProtect#542]
Hey, while i started my Server i saw the message [RedProtect] Whitelist disabled!
Does that mean that the Whitelist from the Server is disabled by the Plugin or is it a Plugin intern Whitelist ? Because i use a whitelist on my Server and everytime i start my Server the whitelist is turned off. If the Plugin changes my Whitelist status how can i disable it or turn the Whitelist on in the Plugin ?
I searched through some of the config files but cant seem to find anything close to Whitelist for the Server.

Best regards
GermanY2k

**Comment by PinkFloyd1213** [comment]
Hello,
Same issue for me. Do you find any solution ?

Regards
PinkFloyd1213

**Comment by FabioZumbi12** [comment]
Disable whitelist on regen options. Just search for "whitelist" on config file

**Comment by Lolzkarry** [comment]
Just wondering, this didn't solve the problem at all, and the redprotect plugin still automatically turns it off. do you know why?

**Comment by FabioZumbi12** [comment]
If this option is `false` this wont happens:
![image](https://user-images.githubusercontent.com/5833818/73800526-c6d98780-4797-11ea-88a3-400111c9090a.png)

**Comment by Lolzkarry** [comment]
oh. You're right. The console just didn't reset so I thought that it was still disabling the whitelist. Thanks a bunch for the quick response.
