### ISSUE TITLE
[BUG] Server crashes (ServerHangWatchdog detected)

### ISSUE THREAD

**Issue by GermanY1337** [FabioZumbi12/RedProtect#543]
**Describe the bug**
The Server crashes after some time, there is no exact time its happening random.

**To Reproduce**
Its just happening randomlyn there is no way for me to produce it.

**Screenshots and LOGs**
https://gist.github.com/GermanY1337/05d0c0493a92177c97f04ff2b729b2d7

**Server and plugins versions (please complete the following information):**
 - Server: spongeforge-1.12.2-2838-7.1.7-RC3928
 - Plugin Version: RedProtect-7.6.4-b280-Universal
 - Java Version: Java 1.8.0_232

**Comment by FabioZumbi12** [comment]
Probably a too big region, not a redprotect error or bug!
