### ISSUE TITLE
RedProtect Sponge API compatibility

### ISSUE THREAD

**Issue by petrnowak** [FabioZumbi12/RedProtect#544]
What version of RP may I use for MC1.10.2 SpongeForge1.10.2-2477-5.2.0 ?

Only RedProtect-Sponge-5.2.0-7.2.2-b145 ?

Or RedProtect-7.6.1-b242-Universal is possible ? Will it work on Sponge 5.2.0 ?

**Comment by FabioZumbi12** [comment]
The latest builds will work. Its an universal build.

**Comment by petrnowak** [comment]
Great! Thanks Fabio...
