### ISSUE TITLE
[Suggestion] Sponge Forge 7.1 Support 

### ISSUE THREAD

**Issue by Karlighter** [FabioZumbi12/RedProtect#545]
Currently, this perfect sponge plugin unfortunately doesn't work with sponge forge 7.1.

I recently upgraded my server to 1.12.2 at the expense of towny... as Thermos only supports 1.7.10.

Much to my dismay, sponge is lacking in the "towny" department and I'm currently forced to keep my server whitelisted until I can get a plugin that doesn't just claim chunks, doesn't just act like towny, but is better than towny. RedProtect fits this quota and after hours of desperate research, here I am for the first time asking someone on github to update their mod. 

Fabio, I'm at the point where I would even support you if it would mean that Sponge Forge gets 5.2, 6.1, AND 7.1 support. Hopefully, this request finds you well, cause on paper, this mod/plugin looks great and I'd hate to settle for less than what you're offering!

**Comment by FabioZumbi12** [comment]
But what is not working, having errors on try to install? Redprotect already supports the latest 7.2.0 and 7.1.0 stable

**Comment by Karlighter** [comment]
Fabio, you're a life saver! I'm very surprised that I never saw Mohist when I was looking for a Thermos replacement. The only options I had were Kettle (which didn't work at all ) and SpongeForge (which I have hated from the start since you're at the mercy of plugin authors who make "ports")!

Thanks a lot for pointing me in the right direction and now my server is up and running without sponge, I couldn't be happier!

Now, regarding your mod not working on my server when it was using spongeforge. I do not have a error report on clipboard and I'd rather not gut my server for the sake of getting spongeforge to work again just to display errors. However, to anyone who actually likes sponge, and to help you out, I still remember that right before the server was ready to accept login requests I did get errors.

So I distinctively remember getting an error "java.lang.IllegalAccessError: -tried to access method-" followed by a wall of red text on the console. The server would start up properly and I could still log in, but when i typed the "/rp <>" commands, I kept getting the "unknown command type /help for a list of commands." So from what i could see, no matter what version of spongeforge 1.12.2 i tried, redprotect would never initialize, even with b#280 - b#270. Maybe it's just a mod conflict on my end but again, thanks to you, these sponge problems are no longer my problem. 

Maybe you can use this information for the benefit of others, but I'm not touching sponge with a ten foot pole.

**Comment by FabioZumbi12** [comment]
I'm glad that everything worked with Mohist. If the Mohist project goes on the way it is, I soon think it will no longer support Sponge, given the hard work of keeping two APIs up to date.

Thanks for the feedback about errors in Sponge !!
