### ISSUE TITLE
[BUG] Dissapear players and entity items

### ISSUE THREAD

**Issue by JMBargueno** [FabioZumbi12/RedProtect#547]
**Describe the bug**
Entity items and players invisible on regions

**Expected behavior**
Sometimes entity items and players dissapears on regions

**Server and plugins versions (please complete the following information):**
 - Server: spongeforge-1.12.2-2825-7.1.6
 - Plugin Version: [RedProtect-7.6.1-b242-Universal.jar]
 - Java Version: 8

**Comment by FabioZumbi12** [comment]
Redprotect dont do nothing related to this. This may be a mod incompatibility or an Sponge error in general.
