### ISSUE TITLE
[BUG] Flag name missing for FISHING

### ISSUE THREAD

**Issue by aenaveen** [FabioZumbi12/RedProtect#550]
The name for the flag Fishing in the GUI menu for "/rp flag" is not set so it just displays Flag Name, it confuses players and they ask staff again and again about it.
I have been meaning to report this tiny fix for months now, you could include with your next 1.15 update.
Thanks for the good plugin.

**Comment by yerbuky** [comment]
it a tiny error translation, you can fix it manually. add this to your gui.conf, for example my gui.conf its called guiES-ES then, you paste this.

gui.flags.fishing.description=&6Descripción\: &aPermitir pescar a/n&amiembros y no miembros./n
gui.flags.fishing.name=&e\=> Permitir pescar

it will be fixed. :)
