### ISSUE TITLE
stand armor

### ISSUE THREAD

**Issue by yerbuky** [FabioZumbi12/RedProtect#551]
- Server: sponge 1.12.2-2838
 - Plugin Version: RedProtect-7.6.4-b280-Universal.jar
 - Java Version: Java 1.8

I'm having problem with stand armor in protected zone. User not member can interact with stand amor of minecraft, but stand amor of buildcraft they cant interact. Could it be a issue of plugin or my config??

**Comment by FabioZumbi12** [comment]
If its a mod, we cant do nothing. Normal armor stands are protected in all versions

**Comment by yerbuky** [comment]
Portugues: Meu problema é com o suporte de armadura do minecraft e não com o suporte de armadura do bibliocraft. Minha área protegida, um usuário não-membro, pode interagir com a armadura do minecraft. No sinalizador / rp, tenho tudo negado.

Español: mi problema es con la stand armor de minecraft y no con la stand armor de bibliocraft. mi zona protegida un user no miembro puede interactuar con stand armor de minecraft. en /rp flag tengo todo denegado.
