### ISSUE TITLE
[Problema] Erro ao quebrar gramas

### ISSUE THREAD

**Issue by skyman478** [FabioZumbi12/RedProtect#552]
Oi, todas as vezes que alguem do meu servidor quebra um bloco de grama aparece isso no console:

ERROR Could not pass event PlayerInteractEvent to RedProtect v7.6.5
26.12 23:30:09 [Server] INFO java.lang.NoSuchFieldError: CARROTS
26.12 23:30:09 [Server] INFO at br.net.fabiozumbi12.RedProtect.Bukkit.listeners.BlockListener.onPlayerInteract(BlockListener.java:326) ~[?:?]
26.12 23:30:09 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor740.execute(Unknown Source) ~[?:?]
26.12 23:30:09 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[Paper.jar:git-Paper-1608]
26.12 23:30:09 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[Paper.jar:git-Paper-1608]
26.12 23:30:09 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Paper.jar:git-Paper-1608]
26.12 23:30:09 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[Paper.jar:git-Paper-1608]

**Comment by FabioZumbi12** [comment]
Ja foi arrumado nas ultimas dev builds.
