### ISSUE TITLE
[BUG] /rp expand-vert ignores permissions, usable by any player on any region

### ISSUE THREAD

**Issue by ShadowFlare** [FabioZumbi12/RedProtect#554]
**Server and plugins versions (please complete the following information):**
 - Server: Paper 1.14.4 build 238
 - Plugin Version: RedProtect-7.6.5-b289-Universal.jar
 - Java Version: Java 1.8

**Additional context**
I've tested the command /rp expand-vert on a region I do not own, making sure someone else owns it and I'm not any part of it (while no longer having op on the server), and I can still use it and it does actually change the min y and max y of the region.  Other commands seem to be denied as expected.  Looking through the code, I'm not 100% sure, but it seems to be missing a permission check maybe?  Also seems it probably doesn't log the change either like setmaxy and setminy do.

**Comment by FabioZumbi12** [comment]
Fixed in https://github.com/FabioZumbi12/RedProtect/commit/7193af1c3985dd0b912330f8831a26709f6f6886 on latest dev build.

**Comment by ShadowFlare** [comment]
The permissions issue seems to be fixed. Thanks
