### ISSUE TITLE
[ProblemCould not pass event SignChangeEvent to RedProtect v7.6.5a

### ISSUE THREAD

**Issue by upanikbr** [FabioZumbi12/RedProtect#557]
**Antes de abrir um problema, verifique estas etapas:**
* Se você estiver executando o plug-in na primeira vez, tente executar novamente para ver se o problema persiste.
* Verifique se a sua compilação é a mais recente do nosso Jenkins. Clique aqui: <https://host.areaz12server.net.br:8080/job/RedProtect>
* É importante você incluir o nome do jar do plug-in, porque as informações de versão e construção estão nele.

**Descreva o bug**
Tentativa de proteger um baú, porém nada acontece.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Proteja um baú com uma placa
2. Olhe no console
3. Veja o erro

**Comportamento esperado**
Proteção do baú

**Capturas de tela e registros**
https://pastebin.com/W7FCNEe5

**Versões de servidor e plug-ins (preencha as seguintes informações):**
 - Servidor: CatServer-a8d129c-universal
 - Versão do plug-in: RedProtect-7.6.5-b289-Universal
 - Versão do Java: build 1.8.0_231-b11

**Comment by yefersonojeda2** [comment]
Obrigado Eu no falo moito o português mas eu vi o problema

**Comment by FabioZumbi12** [comment]
Fixed in https://github.com/FabioZumbi12/RedProtect/commit/bdfe169359821b07e61a801fc56c9542b317a390 available on latest dev build
