### ISSUE TITLE
[BUG] I comandi non funzionano correttamente

### ISSUE THREAD

**Issue by Xm4g1kZzXj0k3** [FabioZumbi12/RedProtect#558]
Buona sera,
ho parlato poco fa con un aiutante (yIncisi) e mi ha detto di segnalare qui il mio problema e di scrivere in italiano perche' in inglese non me la cavo molto bene.

Dettagli tecnici:
- Server version: Spigot 1.14.4-R0.1-SNAPSHOT (L'ultima build disponibile compilata tramite Git)
- Plugin version: RedProtect 7.6.5
                           LuckPerms 5.0.52
- Java version: build 1.8.0_232-b09

Il problema nasce quando vengono dati i permessi al giocatore.
Alcuni comandi non funzionano, come nel caso di "/rp pos1".
Avendo l' * come permesso, tutto funziona correttamente, nel momento in cui do all'utente i singoli permessi, non tutto funziona correttamente, in particolare nel caso di "/rp pos1", non appare niente in chat, e neanche nessun errore in console.

Ho notato pero' dando il permesso "redprotect.command.admin.*" (come richiesto dall'aiutante), che il comando "/rp pos1" dava un errore per la mancanza del permesso, il comando "/rp claim" dava un classico errore, essendo la region non selezionata (quindi dovrebbe funzionare correttamente), mentre il comando "/rp wand" non dava nessuna risposta in chat e nessun item nell'inventario.

Video url: https://www.youtube.com/watch?v=iUj14tCm6TE&feature=youtu.be

**Comment by FabioZumbi12** [comment]
As i see in your video, you dont need any permission, just change on configuration file, on `claim -> world-types` from `FENCE` to `WAND`

**Comment by Xm4g1kZzXj0k3** [comment]
Ok, but command do not work the same

**Comment by FabioZumbi12** [comment]
Tryied to give the permissions `redprotect.command.pos1` and `redprotect.command.pos2`? The instructions its on wiki and it worked here for me.

**Comment by Xm4g1kZzXj0k3** [comment]
Don't work the same giving the permissions

**Comment by FabioZumbi12** [comment]
No problems here (tested again):
As first, no permission and `redprotect.command.pos1 / pos2` not set:
![image](https://user-images.githubusercontent.com/5833818/72571551-b02dc800-389e-11ea-8cf3-b0049c327df4.png)

Then, on LP, added this two perms:
![image](https://user-images.githubusercontent.com/5833818/72571573-c63b8880-389e-11ea-9935-f1fbad92c7e3.png)
And then, ingame, i can use the both commands (that two in blue):
![image](https://user-images.githubusercontent.com/5833818/72571614-deaba300-389e-11ea-8d76-6d646febb397.png)

This is on config for my worlds:
![image](https://user-images.githubusercontent.com/5833818/72571706-161a4f80-389f-11ea-921e-bb22f5a2246e.png)


Theres NO problem with this commands!!
