### ISSUE TITLE
[BUG] Missing dependencies from org.spongepowered

### ISSUE THREAD

**Issue by TheBusyBiscuit** [FabioZumbi12/RedProtect#560]
**Describe the bug**
One of my repositories hooks into RedProtect-Core and RedProtect-Spigot.
After an automated dependency-update to version 7.6.5 of both dependencies, the project now fails to compile, as it cannot find:

"org.spongepowered:configurate-yaml"
"org.spongepowered:configurate-core"

After digging through RedProtect-Core's pom.xml, I noticed that the repository found there doesn't contain these dependencies either.

For reference, this is the pom.xml of my project:
https://github.com/TheBusyBiscuit/CS-CoreLib2/blob/master/pom.xml

**To Reproduce**
1. Build a project with RedProtect-Core as a dependency
2. See it not compile

**Expected behavior**
Expected to resolve the dependencies correctly and compile that dependency.

**Screenshots and LOGs**
Not applicable, but you can find a log of the maven compilation here:
https://github.com/TheBusyBiscuit/CS-CoreLib2/commit/7364bcca80808c65cdc8c76b4e7df13004f4ae34/checks?check_suite_id=386463548

**Comment by FabioZumbi12** [comment]
Humm. I ll'check!

**Comment by TheBusyBiscuit** [comment]
For additional context:

The repository you specified in RedProtect-Core/pom.xml is jcenter.bintray.com
https://jcenter.bintray.com/org/spongepowered/

This directory however does not contain the dependencies your pom.xml demands.

**Comment by FabioZumbi12** [comment]
On clean i got the error. Should be fixed now!

**Comment by TheBusyBiscuit** [comment]
Can confirm that it is fixed.
Thanks :)
