### ISSUE TITLE
[BUG] player pseudo displayed by the claim

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#561]
Hi,

I noticed recently that despite the change of the player's pseudo the claim still remains in its old pseudo, it does not pose a problem in terms of use but there are some versions there was not this concern.
I'm talking about the name of the owner which is displayed with /rp info, not the name of the claim
Example : 
![Capture](https://user-images.githubusercontent.com/24486147/72074497-505d7d00-32f2-11ea-884d-1a1dcd3906dc.PNG)
and
https://fr.namemc.com/profile/JTeikyo.1

Thank you in advance.

**Comment by FabioZumbi12** [comment]
You need to set `online-mode: true` on config if you want redprotect to use uuids and update the names on every mojang name change by players (make a db backup first if you change this config)
