### ISSUE TITLE
[BUG] Block Break or Place Error

### ISSUE THREAD

**Issue by LeePC** [FabioZumbi12/RedProtect#562]
[latest.log](https://github.com/FabioZumbi12/RedProtect/files/4071011/latest.log)

**Server and plugins versions (please complete the following information):**
 - Server: spigot 1.12.2
 - Plugin Version: latest version
 - Java Version: java 8

**Additional context**

**Comment by FabioZumbi12** [comment]
Its already fixed on latedt dev builds. Check this github home page for jenkins dev builds.
