### ISSUE TITLE
[BUG] /rp claim doesn't work after //regen

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#565]
Hi, 

the /rp claim sometimes deactivates for no reason, maybe after a //regen from WorldEdit but I'm not sure... Something should be done because it's annoying to have to reboot my server for claim (the other commands work).
I use the latest version of the plugin (295) and the latest version of PaperSpigot 1.15.1 (51).
Error in the console : https://pastebin.com/aYS4AYQa

**Comment by aurel85** [comment]
I confirm it's good after a //regen that the bug occurs.
I use Paper 1.15.2, the latest version of the plugin and the latest dev version of WorldEdit.

**Comment by aurel85** [comment]
With /rp reload everything is ok after the //regen.
But please resolve this bug anymay.

**Comment by FabioZumbi12** [comment]
I cant know whats wrong since the cause its the //regen command. Btw, the error on log its when i loop on worlds... seems after a regen some world its returning ans null... the dev build should avoid this (after build 300)

**Comment by aurel85** [comment]
On 5 attempts the bug appeared only once (with version 302), I consider that it is solved. Thank you !
