### ISSUE TITLE
setmaxy setminy dont work

### ISSUE THREAD

**Issue by R4f4Lc** [FabioZumbi12/RedProtect#566]
The setmaxy and setminy options do not work. They do not throw any error. When it runs directly skip the help of RedProtect.

 - Server: SpongeForge 1.12.2
 - Plugin Version: RedProtect-7.6.5-b295-Universal.jar
 - Java Version: Java 1.8

**Comment by FabioZumbi12** [comment]
Will be fixed on next dev build, check the changelogs
