### ISSUE TITLE
[BUG] server crash (ServerHangWatchdog)

### ISSUE THREAD

**Issue by chenxuuu** [FabioZumbi12/RedProtect#569]
**Describe the bug**
server no response, and it stopped by watchdog after 600 seconds

**To Reproduce**
one player say that crash after `/rp tp xxx` command
but I checked my server log, no this command in log files

**Expected behavior**
server shouldn't be no response

**Screenshots and LOGs**
https://gist.github.com/chenxuuu/d15058943a04f1f90d5e5aeba7e72c5f
3 crash logs

**Server and plugins versions (please complete the following information):**
 - Server: spongeforge-1.12.2-2838-7.1.7
 - Plugin Version: RedProtect-7.6.3-b270-Universal.jar
 - Java Version: 1.8.0_202, Eclipse OpenJ9
 - Operating System: Windows Server 2016 (amd64) version 10.0

**Comment by chenxuuu** [comment]
may be it's a bug of `botania` mod?

**Comment by FabioZumbi12** [comment]
This is not caused by redprotect. In this case your server was already frozen and redprotect just tryied to get the region from db in this time.

Maybe on generating new chunk after a tp, or for some other reason.

**Comment by chenxuuu** [comment]
@FabioZumbi12 
so, maybe it wait too long?
I found that all other threads are in `TIMED_WAITING` status, 
but redprotect threads are in `RUNNABLE` status.

here's another crash report:[crash-2020-02-02_13.58.47-server.txt](https://github.com/FabioZumbi12/RedProtect/files/4143597/crash-2020-02-02_13.58.47-server.txt)

just a guess🤔, if I'm wrong, sorry about it

**Comment by chenxuuu** [comment]
timings for 1 hour
https://timings.aikar.co/?id=6015ca04b60b407f82ba389d57d9de2c
![图片](https://user-images.githubusercontent.com/10357394/73604691-beceeb80-45cf-11ea-9e84-93d4a29aaa66.png)

**Comment by chenxuuu** [comment]
It's be ok after I disable rp plugin, no crash, no lag

last log: [latest.log](https://github.com/FabioZumbi12/RedProtect/files/4157235/latest.log)

heapdump files: [7z file](https://1drv.ms/u/s!Asz6jM0Kmex1qvNsfZmvtSyvs6nDNw?e=leMXCX)

no crash report because not enable watchdog
