### ISSUE TITLE
[Suggestion] /home command

### ISSUE THREAD

**Issue by PeRFecTxTabZ** [FabioZumbi12/RedProtect#57]
Hello, can u ad an Function, where the user is able to set a home only on his protected area with /sethome not with /rp sethome, and where u can set in the Confi the Maximum y block high. When the user is mining i will not that he can use the /home command. Only when he is out of the Mine. When he is in the Mine and when he use /home than i want that i can customise an error message which gets displayed then. sry for my bad english :/

**Comment by CloudeLecaw** [comment]
a good idea. 

i think your talking about preventing for chickenrunners that run away with /home so save their full inventory what is aggainst the Survival Server Rules.
This is also one of the reasons why i have no /home
/home is like a cheat to save your ass for a survval server.
if u add somethign like this in redprotect pls let there be an option to enable/disbale it :)

**Comment by FabioZumbi12** [comment]
In this case, enabling teleport cooldown on Essentials (or on your teleport plugins) dont solve this? As example, on my server i set a cooldnow of 3 seconds to teleport, if the player move or interact with a block or entity, or get damage, the teleport is cancelled.

**Comment by PeRFecTxTabZ** [comment]
> set a home only on his protected area with /sethome not with /rp sethome, and where u can set in the Confi the Maximum y block high. When the user is mining i will not that he can use the /home command. Only when he is out of the Mine. When he is in the Mine and when he use /home than i want that i can customise an error message which gets displayed then.

Sry but this is not working with Essentials, i i asked so much PEople before i wrote this. I dont know how i can do this with other Plugins so i suggested it here ^^

**Comment by FabioZumbi12** [comment]
Will de added on 6.7.0
https://github.com/FabioZumbi12/RedProtect/wiki/Region-Flags#command-ranges
