### ISSUE TITLE
[Suggestion] Ability to remove some of the admin flags

### ISSUE THREAD

**Issue by Smiggle** [FabioZumbi12/RedProtect#570]
On i-survival, we are trying to come up with a way that the admins (me included) can have access to the admin flag but not be able to set the flags "server-command-enter" and "server-command-exit"

An option to remove these flags would be nice to have in the config file or possibly a branch with these flags removed. Another option could be a third class that is called Mod or something and wouldn't have access to these flags.

I personally have tried looking through the source code to find where the flags are stored and delete these two but I'm kinda garbage at coding and couldn't find it. Right now all admins on the server are treated like normal players on claims to prevent any further abuse of this flag.

**Comment by FabioZumbi12** [comment]
You can limit flags to your admin removing the permission `redprotect.admin` and then giving the permissions only to what flags you want to use. Check the specific perms on wiki.
