### ISSUE TITLE
[Problema] funil se quebrando ao mover item

### ISSUE THREAD

**Issue by llronaldoll** [FabioZumbi12/RedProtect#571]
**Antes de abrir um problema, verifique estas etapas:**
* Se você estiver executando o plug-in na primeira vez, tente executar novamente para ver se o problema persiste.
* Verifique se a sua compilação é a mais recente do nosso Jenkins. Clique aqui: <https://host.areaz12server.net.br:8080/job/RedProtect>
* É importante você incluir o nome do jar do plug-in, porque as informações de versão e construção estão nele.

**Descreva o bug**
Uma descrição clara e concisa do que é o bug.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Veja o erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

**Capturas de tela e registros**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema. Envie seus registros para https://gist.github.com/

**Versões de servidor e plug-ins (preencha as seguintes informações):**
 - Servidor: [por exemplo Sponge 1.12.2, Spigot 1.13.2]
 - Versão do plug-in: [por exemplo RedProtect-7.5.6-b151-Universal.jar]
 - Versão do Java: [por exemplo Java 1.8]

**Contexto adicional**
Adicione qualquer outro contexto sobre o problema aqui.

tenho um problema onde apenas dentro de alguma RP, se eu tentar colocar um item dentro de um funil que esteja conectado a outro, ele se quebra imediatamente, o mesmo acontece se tentar colocar item em um baú que tenha 2 funis a baixo, o primeiro funil se quebra ! 

spigot 1.15.2

rRedProtect-7.6.5-b295-Universal

**Comment by FabioZumbi12** [comment]
Não consigo te ajudar, o redprotect não causa esses problemas, provavelmente é outro plugin ou alguma incompatibilidade. Se tiver erros do redprotect nos logs eu posso analisar, caso contrario nada a fazer.
