### ISSUE TITLE
[BUG] Couple of bugs related to /rp start

### ISSUE THREAD

**Issue by TheReverend403** [FabioZumbi12/RedProtect#577]
**Describe the bug**
* `/rp start` claims you have to type `/rp start` again to confirm. This is wrong, it's `/rp start confirm`.
* After a confirmed `/rp start`, the plugin shows a success message about creating the region and pasting the schematic, but no region or schematic is created.

**Server and plugins versions (please complete the following information):**
 - Server: Paper version git-Paper-102
 - Plugin Version: RedProtect-7.6.5-b297
 - Java Version: 11

```
Plugins (27): AsyncWorldEdit, ChatControl, CombatLogX, DiscordSRV, Essentials, HolographicDisplays, LiteBans, LuckPerms, Matrix, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, NametagEdit*, PlaceholderAPI, PlotSquared, PremiumVanish, ProtocolLib, RedProtect, ServerListPlus, SSHD*, Vault, ViaBackwards, ViaVersion, VoidSpawn, WorldBorder, WorldEdit, WorldEditSUI
```

**Comment by FabioZumbi12** [comment]
Its not working because some worldedit hook prolems, and probably will be removed from redprotect :/

**Comment by lostINParadies** [comment]
You will fix this problem otherwise? Maybe without worldedit?

**Comment by TheReverend403** [comment]
Yeah, this is a pretty major unique feature and is one of the main reasons I installed the plugin in the first place rather than GriefPrevention. It would be a huge mistake removing this because then there's hardly any reason to use RedProtect over other plugins that offer the same features.
