### ISSUE TITLE
[Question] Block the opening of the chests in wilderness ?

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#578]
Hi,

On my server, the players must claim an area to build on it, yet outside this area (non claimed region) they can open chests. Do you know if a way to prevent this exists ? I have already checked into the ʺglobalflagsʺ file but I didn’t found anything which works.

I use the last version of this plugin (297) and Paper 1.15.2.

Thank you in advance for  your help.

**Comment by Skinde** [comment]
On RedProtect/config.conf
search for:
# Allow player to create private container outside regions? (on wilderness)
    allow-outside=false

**Comment by aurel85** [comment]
In effect this is not what I am looking for.
I did tests with the interact-blocks in globalflags but it doesn't seem to work or I do not do it well...

**Comment by FabioZumbi12** [comment]
Will be added on next dev build
