### ISSUE TITLE
[BUG] Use of bone meal in wilderness

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#579]
Hi,

On my server, the players must claim an area to build on it, however they can use ʺbone mealʺ on non claimed areas (in wilderness). Is this due to a problem from the plugin or is it the way that it's supposed to work ?﻿

I use the last version of this plugin (297) and Paper 1.15.2.

Thank you in advance.

**Comment by FabioZumbi12** [comment]
Will be fixed on next build
