### ISSUE TITLE
[Suggestion] No build without claim

### ISSUE THREAD

**Issue by lafaipopo** [FabioZumbi12/RedProtect#58]
Before I used Griefprevention and proposed a feature that is missing on RedProtect: Not being able to build if we do not claim the land with the magic wand.
This prevents everyone can build anywhere and keep a clean map.

**Comment by FabioZumbi12** [comment]
Good idea, i will add this!!

**Comment by FabioZumbi12** [comment]
Thanks @zedentox  i will take a look on your pull request and add after some tests ^^

**Comment by FabioZumbi12** [comment]
#76
