### ISSUE TITLE
[BUG] Use of bone meal on flowers in a claim

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#580]
Hi,

I have another problem since a while : members of a claim area can’t interact with double flowers (2 blocks tall) whereas it is normally working with simple flower (1 block tall). There is no problem for the claimed area’s owner, it happens only for players that are just member of the claim. Could you have a look on this ?

I use the last version of this plugin (297) and Paper 1.15.2.

Thank you in advance.

**Comment by FabioZumbi12** [comment]
Tested here and i can interact with both blocks normally...

**Comment by aurel85** [comment]
I use on my server a personal plugin called FlowerMeal which allows you to duplicate all flowers with bone meal. I think there is a problem between it and RedProtect because when I actually remove it I have no problem duplicating the double flowers.
We will look on our side in the plugin to see if we can fix the problem ourselves.

**Comment by aurel85** [comment]
Ok it's good everything is settled by modifying things in our plugin !
