### ISSUE TITLE
[Suggestion] Prevent Crazy-Enchantments damage while pvp deny.

### ISSUE THREAD

**Issue by baxandrei** [FabioZumbi12/RedProtect#581]
**Is your feature request related to a problem? Please describe.**
Players can be attacked using these enchantments, even if they are in a protection that prevents pvp.

**Describe the solution you'd like**
[1] https://github.com/badbones69/Crazy-Enchantments/wiki/Enchantment-Information
The enchantments of crazy enchants (like radiant) can give damage to the players in the protections. It would be useful if p

**Describe alternatives you've considered**
Honestly, I do not know.

**Additional context**
nothing, tank you!

**Comment by FabioZumbi12** [comment]
You can deny enchantments and potions on pvp regions too. Its better to you talk to the owner of that plugin to hook into redprotect if you want a specific enchantment to do not fire on non pv regions
