### ISSUE TITLE
[Suggestion] Region rent and tax

### ISSUE THREAD

**Issue by Nosneross** [FabioZumbi12/RedProtect#582]
**Is your feature request related to a problem? Please describe.**
I have not any problems more so trying to have the ability of giving the player more control off of red protected claims it would be great to have them be able to tax sell and rent land claims,  
 
**Describe the solution you'd like**

I want the structured economy for selling land plots to either other players or a single player looking to expand personal property. it would be great to be able to set a land cost. rent, taxes what have ya, 
**Describe alternatives you've considered**
 have not found any plugins that would fill that particular void

**Comment by FabioZumbi12** [comment]
You can enable region cost on config to debit from your players when claim. Theres a plugin for rent/sell regions with redprotect. Check the spigot page for more info.
