### ISSUE TITLE
[Suggestion] New flag for concrete powder

### ISSUE THREAD

**Issue by Melvout** [FabioZumbi12/RedProtect#584]
Hello !

**The problem :**
Some people would like to use concrete powder as a way to create diversified beaches ( like a colored sand ) however they can't due to the reaction of concrete powder with water.

**A solution :**
The suggestion is to add a new flag to prevent the concrete powder from solidification when in contact with water.

Thanks in advance and keep up the good work ! :)

**Comment by FabioZumbi12** [comment]
Added the flag `block-transform` on latest release. Note that will be a visual bug when placing concrete powder near water, its only visual.

**Comment by aurel85** [comment]
Is there any way to avoid this visual bug ?
