### ISSUE TITLE
[BUG] Kelp growth

### ISSUE THREAD

**Issue by Melvout** [FabioZumbi12/RedProtect#585]
**Bug description**
The flag to prevent plants growth doesn't prevent the growth of kelp.

**Expected behavior**
Kelp's growth should be stopped by using this flag.

**Server** : Paper 1.15.2
**Plugin** : Lastest version (297)

**Comment by FabioZumbi12** [comment]
Should be fixed on https://github.com/FabioZumbi12/RedProtect/commit/0a1373cec5190956e74a75634c185b6748345f43
Download the latest dev build
