### ISSUE TITLE
[BUG] Signs Bug

### ISSUE THREAD

**Issue by NovaPixell** [FabioZumbi12/RedProtect#586]
Report a Bug: with this plugin you can make the signs disappear by clicking on them. Not only in claim areas but also in global areas. Try to solve because it is more serious than expected.
I use Paper 1.15.2 and Plugins like ChatControl Pro.
LATEST RedProtect version.
Waiting for feedback.

**Comment by FabioZumbi12** [comment]
Cant reproduce this and i have shure redprotect dont causes this. Check your other plugins, and this normally happens just as visually bug.
