### ISSUE TITLE
[BUG] Missing language string for...

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#587]
Hi,

Some elements are missing from the translation file. if i add them manually it doesn't work.
After /rp near :
![Capture2 PNG 078d5950ca3ed9304ae20c040032a597](https://user-images.githubusercontent.com/24486147/76167808-d61e6d00-6169-11ea-915b-e99cef3f7b01.png)

I checked here it is not present :  
https://github.com/FabioZumbi12/RedProtect/blob/master/RedProtect-Core/src/main/resources/assets/redprotect/langEN-US.properties

I use the latest version (302) and Paper 1.15.2.

Thank you in advance.

**Comment by FabioZumbi12** [comment]
You can add to en-us language first as a temp fix, and then add to your language file. En us is the base language

**Comment by aurel85** [comment]
When i try to add the missing lines to the langEN-US.properties file they disappear as soon as I reload the plugin or I reboot the server.

**Comment by FabioZumbi12** [comment]
Fixed on latest dev build
