### ISSUE TITLE
[BUG] Redprotec Dynmap Probleme

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#588]
RP-Version: 303

Dynmap-Version: Dynmap-3.0-beta-10-spigot.jar

paper-version: Paper version git-Paper-131 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

Unfortunately, since the many updates up to version 303, I always have problems when I enlarge or reduce the zone. Then there are conflicts with the Dynmap. You can only see the enlargement or reduction of the zone after a server restart

>.... [18:48:11 WARN]: java.lang.NullPointerException
>.... [18:48:11 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.removeMark(DynmapHook.java:90)
>.... [18:48:11 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.remove(RegionManager.java:258)
>.... [18:48:11 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.actions.RedefineRegionBuilder.<init>(RedefineRegionBuilder.java:161)
>.... [18:48:11 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.RedefineCommand.onCommand(RedefineCommand.java:66)
>.... [18:48:11 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:354)
>.... [18:48:11 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [18:48:11 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [18:48:11 WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1172)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
>.... [18:48:11 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [18:48:11 INFO]: [RedProtect] Problems when remove marks to Dynmap. Is Dynmap updated?
>.... [18:48:11 WARN]: java.lang.NullPointerException
>.... [18:48:11 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.addMark(DynmapHook.java:101)
>.... [18:48:11 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.region.RegionManager.add(RegionManager.java:239)
>.... [18:48:11 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.RedefineCommand.onCommand(RedefineCommand.java:70)
>.... [18:48:11 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:354)
>.... [18:48:11 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [18:48:11 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [18:48:11 WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1172)
>.... [18:48:11 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
>.... [18:48:11 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [18:48:11 INFO]: [RedProtect] Problems when add marks to Dynmap. Dynmap is updated?

**Comment by FabioZumbi12** [comment]
Cant reproduce here. Tryied to reproduce using:

RP-Version: 303
Dynmap-Version: Dynmap-3.0-beta-10-spigot.jar

No errors and the region is updated in realtime on map
