### ISSUE TITLE
[BUG] Placing signs on the wall is not possible

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#589]
I wanted to put a pin board on my server. Where users can put signs on and remove them. so I wanted to add the signs with / rp flag allow-place. You can now put signs on the ground in the zone but not on the wall. Can you still fix this or is it not possible?

**Comment by FabioZumbi12** [comment]
You need to check if the wall sign has other name than only "sign" to add on place flag. Maybe "wall_sign" or "wooden_wall_sign", something like that.

**Comment by Blueeyestar** [comment]
I used the gui. / rp flag allow-place or / rp allow-break. I just put a sign in the slot. since it should be automatically included in the file. but i can only put and dismantle signs on the floor. Do I have to enter this as a command without using the gui?

**Comment by FabioZumbi12** [comment]
Give a try. Will help to debug the problem.

**Comment by Blueeyestar** [comment]
ok i have now tested it. if you do it manually without the gui you just have to do it / rp flag allow-place spruce_wall_sign

I would be happy if you could add the option. but if it doesn't work it's not too bad.

Great that you are always there for us. Stay healthy :)

**Comment by FabioZumbi12** [comment]
No way as we cant specify the sign type in gui. Good to see working on command.
