### ISSUE TITLE
[BUG] - Home Flag not working correctly

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#590]
We noticed on our Server, that the allow-home flag seems not to work correctly?

What we a trying to do:
People come to a big zone where no **_/sethome_** or **_/sethome Name_** should be allowed
In some subzone the allow-home flage is enabled to people can setup this point this subzone as home (like a save spot)
currently then can set a homepoint no matter if the allow-home flag is true or false.
whats wrong here?

We havent used the flag for longer time so we dont know correctly when this flag stoped it's work?

We are using: PaperSpigot 1.15.2
RedProtect-7.6.5-b303-Universal.jar
Plugin for Managing homes: [CMI](https://www.spigotmc.org/resources/cmi-270-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/)

Info: We also tried to do /rp flag deny-cmd cmd:sethome 
we got a flag in the zone but people can still set homes in the zone...

**Comment by Blueeyestar** [comment]
With many different flags, this also applies as an example:
/rp flag player-damage 

unfortunately, this also applies to many other flags. As an owner you have no authorization

**Comment by FabioZumbi12** [comment]
Redprotect handles Essentials home commands. If that other plugin uses other commands or aliases or, is some cases, the commands handler fires after redprotect (or in the same priority), its not an issue with redprotect.

Btw, home flag its working fine on my server.

**Comment by Blueeyestar** [comment]
I have now set up a test server on a single player, where I am the only one who has all rights. As an OP, I still have no rights to change the admin flags. It is the same with the public server.

**Comment by FabioZumbi12** [comment]
Seems you have some other problem or bad configuration, maybe on permissions.yml? I am using (and testing) the latest build and all is running ok, with deop i have player default permissions and as op, all permissions.

**Comment by CloudeLecaw** [comment]
If the allow-home flag is active and the players do /sethome, /sethome name, /home /home name
then all works fine and they cant set home or use the selected home

But if the players use /cmi sethome, /cmi sethome name, /cmi home /cmi home name
then this went over the flags and allow's the players to set homes or went to this homes.

The /sethome and /home command are aliases for /cmi home and /cmi sethome from CMI in our case. The interesting part is that the flag works for the /sethome an /home....

So is there any chance that Redprotect can also check for /cmi home and /cmi sethome like it can for /sethome and /home? 

Maybe a hook or something like this or a list where owners can setup there regular home and sethome commands,
I think there are a lot of plugins that can set homes and homes with other commands like just /sethome and /home

**Comment by FabioZumbi12** [comment]
I cant a hook for a specific plugins like this way... Y can allow players only use the /sethome or /home and i have added a check for `/cmi:sethome` (`/<plugin name>:home or sethome`) too.
