### ISSUE TITLE
[BUG] Region name gives NullPointerException

### ISSUE THREAD

**Issue by Dmunch04** [FabioZumbi12/RedProtect#592]
**Describe the bug**
In the `CreateRegionEvent`, the regions name returns a `NullPointerException`

**To Reproduce**
```java
@EventHandler
public void onRegionCreated(CreateRegionEvent e) {
   String name = e.getRegion().getName();
}
```
Error:
```
java.lang.NullPointerException: null
```

**Expected behavior**
It should return the regions actual name (The one that's also on the region sign)

**Server and plugins versions (please complete the following information):**
 - Server: `Paper 1.15.2`
 - Plugin Version: `RedProtect-7.6.5-b289-Universal`
 - Java Version: `Java 8`

**Comment by Dmunch04** [comment]
Bump

**Comment by FabioZumbi12** [comment]
Already fixed on latest dev build (b303+)

**Comment by Dmunch04** [comment]
How would I important that API version with Maven?
