### ISSUE TITLE
[BUG] Error on maven pom 

### ISSUE THREAD

**Issue by Darkool** [FabioZumbi12/RedProtect#593]
Hello there, I got this error using your plugin as dependency:

        <dependency>
            <groupId>br.net.fabiozumbi12.RedProtect</groupId>
            <artifactId>RedProtect-Core</artifactId>
            <version>7.6.5</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>br.net.fabiozumbi12.RedProtect</groupId>
            <artifactId>RedProtect-Spigot-1.13</artifactId>
            <version>7.6.5</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.spigotmc</groupId>
                    <artifactId>spigot-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <repository>
            <id>redprotect-repo</id>
            <url>https://raw.githubusercontent.com/FabioZumbi12/RedProtect/mvn-repo/</url>
        </repository>

[WARNING] The POM for org.flywaydb:flyway-core:jar:3.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for br.net.fabiozumbi12.RedProtect:RedProtect-Spigot:jar:7.6.5 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

Any idea? 

Thank you.

Regards.

**Comment by FabioZumbi12** [comment]
Use the version for latest mc version like for 1.15.2 and later.
