### ISSUE TITLE
People can't use Nether Portal

### ISSUE THREAD

**Issue by ravenmyrrdin** [FabioZumbi12/RedProtect#594]
When I claim an area, others can't use the nether portal on the domain

Also people can't use a Lectern

**Comment by CloudeLecaw** [comment]
you know that this is a flag in redprotect? If you wish your strngers can use the nether portal then u need to enable this flags?

Take a look here

**allow-create-portal**
| This flag deny/allow creation of portals in player regions. This flag deny portal creation if the player is teleporting from nether>overworld too | /rp flag allow-create-portal [true/false]

**portal-enter**
| Deny/allow player to enter on portal | /rp flag portal-enter [true/false]

**portal-exit** 
| Deny/allow player to across between portal if the region in other side of portal have this flag | /rp flag portal-exit [true/false]

**Comment by ravenmyrrdin** [comment]
I tried this but it still doesn't work. Is there any other way those can be locked

I also wonder if it is possible to add an excisting group to a claim instead of individual players

**Comment by FabioZumbi12** [comment]
Redprotect dont handle nether portals if that flat is not in use. Theres no way to use groups on regions.

**Comment by eelaniles** [comment]
Hi, so sorry but I've been having this same problem, and I have tried using the rp flag portal-enter true and rp flag portal exit tru commands already
