### ISSUE TITLE
[BUG] People can steal books + Potty items

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#595]
We a running a 1.15.2 Server
with RedProtect-7.6.5-b303-Universal

in this Version strangers can steal books from book stands in other players region.
We assume that this a bug?

Here how to produce the bug:

1. go to a stranger one where someone placed a book stand with a book
![Snag_343a470](https://user-images.githubusercontent.com/12080017/77372749-b2147b80-6d66-11ea-9f4d-45eedcfbd141.png)

2. click on the book stand the book to read it
![Snag_3443b22](https://user-images.githubusercontent.com/12080017/77372779-c8bad280-6d66-11ea-97df-5c4b2867e4fa.png)

3. klick the button - take it
![Snag_344a536](https://user-images.githubusercontent.com/12080017/77372799-d8d2b200-6d66-11ea-8922-bb78a8abd538.png)

Result: u stole the book

**Edit:**
We noticed also player can steal the item you put on a putty in protected region 🥉

**Comment by FabioZumbi12** [comment]
Tryied to reprocude and strangers cant interact with book stand, making to get the book impossible...

**Comment by CloudeLecaw** [comment]
We are using latest Version of Paperspigot and Build 303 of Redprotect.

Is there a special flag for Pots and the book stands? or something that allows interacting with it?

**Comment by FabioZumbi12** [comment]
This blocks are protect with chest flag. If you remove him from private-blocks list or enable this flag, will allow the access for all.
