### ISSUE TITLE
[Suggestion] Explosion only from blocks inside the protection

### ISSUE THREAD

**Issue by KiralyCraft** [FabioZumbi12/RedProtect#596]
**Is your feature request related to a problem? Please describe.**
I want my players to have the full experience of Minecraft, including fire and explosions. I'm running RedProtect on Spongeforge, and here modded machines can explode, and I want them to feel the consequences. 

**Describe the solution you'd like**
I would like to forbid explosions from blocks coming outside the protection. If a TNT was placed just outside the protection, it will not damage the inside. If the TNT was placed inside the protection, it will do damage. The same analogy for machines exploding, Nuke from IndustrialCraft, EFLN from Tinker's Construct, etc.

The same could be applied for fires. If the fire started *inside* the protection, it will spread. Otherwise not.

**Describe alternatives you've considered**
Allowing fire, which and leaves players vulnerable to grief.

**Additional context**

**Comment by CloudeLecaw** [comment]
you know you can do this allready? you have a worldprotection file where you can forbit explodedmg from creepers and you can add them to a default region as set true

the global flag entity-block-damage
 - Deny explosive entities to damage blocks in this world - need to be true
and for the region the Fire Flag needs to be set false by default
also you player should not be allowed to change it (deny the permission)

**Comment by KiralyCraft** [comment]
While this is indeed a possibility, it is not the desired behavior.  I would like to have everything break everything, fire to spread everywhere, so basically just like without a protection, but with some restrictions:
1. Fire started inside a player's protection will spread to the wilderness.
2. TNT/Nuke/Explosions of any kind started inside a player's protection will damage the wilderness too
3. Fire started **outside** a player's protection (in the wilderness) will **NOT** enter the protection, but only to blocks in the wilderness
4. TNT/Nuke/Explosions of any kind (creepers, ghasts, etc) will **NOT** enter or damage any blocks inside the protection, but only blocks that are in the wilderness

**Comment by CloudeLecaw** [comment]
you dont want allow mobs to enter hm? ;)
This is currently not possible, if they have build no walls they will come inside from outside.

and yes this will be a problem with the fire and spreading start at the border of a zone 🥉 

i dont know if Redprotect can follow your special wishes here ;3

Maybe in a farer further version? :)

If mobs from outside cant come inside you will see players will start to use their regions like save spots. - zombie come - run to zone - save..  

Well i dont like this chicken behavior of many players, but if this option will come once into Redprotect i hope it can be disabled too to have a normal behavior like we have it now (monster can coem inside from outside if you have no wall)

You said you wanne give your players the "full expierience" this does include monster that can come to your home from the wilderness ;)

**Comment by KiralyCraft** [comment]
This has absolutely nothing to do with mobs, but with explosions caused by exploding Nuclear Reactors, Nukes, EFLN, Industrialcraft Machines powered with the wrong voltage, Tinker's Construct smelteries, factories that run on lava and so on, as I've written in the first post. I'm talking about the Sponge version of RedProtect that seems to handle Forge mods pretty well.

**Comment by CloudeLecaw** [comment]
this jsut means your plugin/mod that is doing al this things has to hook with RedProtect and Prevent this

i would close this thread. (or your doing this with the Vanilla SpongeForge?

if your plugin has no hook with Redprotect that your wished will not come true. Its not Fanios Job to handle this.
You should ask your "exploding Nuclear Reactors, Nukes, EFLN, Industrialcraft Machines powered with the wrong voltage,-developer"..really

**Comment by KiralyCraft** [comment]
I've just tested having "fire=false" flag in config.json. It does seem like mod-specific explosions are not blocked, or are not seen by the plugin as being explosions. It does work however for Vanilla explosion sources. So even if RedProtect would implement my "wish", it would still not detect mod explosions. I'm not entirely familiar with Sponge, as I am coming from the Spigot world. I would not close this thread just yet, as the fact that mod explosions bypass the "fire=false" flag is a bug in itself (given the fact that Sponge is officially supported by the RedProtect team), vanilla or not.

**Comment by CloudeLecaw** [comment]
Feel free to Do what you think ;-)
Was just a tip why this will not be implemened.

**Comment by KiralyCraft** [comment]
So even though Sponge is supported, RedProtect will not interact with mods, never ever?

**Comment by CloudeLecaw** [comment]
hm i never would say never. But Redprotect is also supported by Spigot, so i would say yes..never ever..

But. Hey finaly this is the desscion of the dev. If he feel like he wants to have this extra work that he can do this. But then he may cant combine a plugin for Sponge & Spigot anymore in a universal jar... then Redprotect will split into two versions aggain like we had this some years ago allready :3

**Comment by FabioZumbi12** [comment]
Redprotect handles spongevents, not mod events (and its the same with all `plugins` for sponge. If the mod call sponge events, redprotect will handle.

Btw, i am stopping to support sponge since we have now Mohist supporting mods + bukkit plugins!
