### ISSUE TITLE
/rp start - can't find schematic 

### ISSUE THREAD

**Issue by lostINParadies** [FabioZumbi12/RedProtect#599]
Hello,

I tried to use the plugin with the start command /rp start to place a startregion for the users. I don't know why, but it doesn't works. I can't see any settings for this in config.yml. I use the newest version with spigot 1.14.4. Please help! Thanks

**Comment by FabioZumbi12** [comment]
Its not owrking as depends of worldedit, and will be removed from plugin soon.
