### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by Kirstiana** [FabioZumbi12/RedProtect#60]
Hello! I'm getting this issue on my console that's spamming a lot whenever someone moves. Not sure if it's caused by this plugin or not, so let me know!

`15.05 19:33:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_1.9_latest.jar:git-Spigot-4af49dc-e22506f]
15.05 19:33:14 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
15.05 19:33:14 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
15.05 19:33:14 [Server] INFO at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source) ~[?:?]
15.05 19:33:14 [Server] INFO at br.net.fabiozumbi12.RedProtect.listeners.RPGlobalListener.onPlayerMove(RPGlobalListener.java:125) ~[?:?]
15.05 19:33:14 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_9_R1/entity/CraftPlayer
15.05 19:33:14 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
15.05 19:33:14 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot_1.9_latest.jar:git-Spigot-4af49dc-e22506f]
15.05 19:33:14 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot_1.9_latest.jar:git-Spigot-4af49dc-e22506f]
15.05 19:33:14 [Server] INFO at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot_1.9_latest.jar:git-Spigot-4af49dc-e22506f]
15.05 19:33:14 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot_1.9_latest.jar:git-Spigot-4af49dc-e22506f]
15.05 19:33:14 [Server] INFO at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot_1.9_latest.jar:git-Spigot-4af49dc-e22506f]
15.05 19:33:14 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_77]
15.05 19:33:14 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_77]
15.05 19:33:14 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_1.9_latest.jar:git-Spigot-4af49dc-e22506f]
15.05 19:33:14 [Server] INFO at net.minecraft.server.v1_9_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot_1.9_latest.jar:git-Spigot-4af49dc-e22506f]
15.05 19:33:14 [Server] INFO at net.minecraft.server.v1_9_R2.PacketPlayInFlying.a(SourceFile:126) [spigot_1.9_latest.jar:git-Spigot-4af49dc-e22506f]
15.05 19:33:14 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:607) [spigot_1.9_latest.jar:git-Spigot-4af49dc-e22506f]
15.05 19:33:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_1.9_latest.jar:git-Spigot-4af49dc-e22506f]
15.05 19:33:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_1.9_latest.jar:git-Spigot-4af49dc-e22506f]
15.05 19:33:14 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.9_latest.jar:git-Spigot-4af49dc-e22506f]
15.05 19:33:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_1.9_latest.jar:git-Spigot-4af49dc-e22506f]
15.05 19:33:14 [Server] INFO org.bukkit.event.EventException
15.05 19:33:14 [Server] ERROR Could not pass event PlayerMoveEvent to RedProtect v6.5.81
15.05 19:33:14 [Server] INFO ... 15 more`

**Comment by FabioZumbi12** [comment]
I think is fixed on: https://www.spigotmc.org/resources/redprotect-1-7-1-8-1-9-2-anti-grief-server-protection.15841/update?update=92086
