### ISSUE TITLE
[Suggestion] Snow & Ice

### ISSUE THREAD

**Issue by Melvout** [FabioZumbi12/RedProtect#601]
Hi !

**A new suggestion for the plugin if it is possible :** Add a new flag **or** modify the ice flag to prevent snow covering the ground when it's snowing.

**[EDIT] Adding a new idea from someone :** Is it possible to add a flag to prevent the melting of ice because of a near light source ?

Thanks, have a nice day.

**Comment by FabioZumbi12** [comment]
For the second idea you can use the new flag `block-transform`. For the first, this already possible with the flag `iceform-world`. Check all flag on wiki https://github.com/FabioZumbi12/RedProtect/wiki/(05)-Region-Flags

**Comment by aurel85** [comment]
For ice that does not melt with block-transform it does not work.

**Comment by FabioZumbi12** [comment]
Check the latest build. I forgot to add an event for blocktransform flag.

**Comment by aurel85** [comment]
Now it's ok thank you !
