### ISSUE TITLE
 - What is wrong with the RP--Jenkins? :3

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#604]
![image](https://user-images.githubusercontent.com/12080017/78262861-7bc2c300-7501-11ea-94fb-dc0c1b0c1525.png)

Since a few days i just get this when i try to get to the Redprotect jenkins to see if ther may is a new build. Something is wrong with the site? :3

**Comment by Krosta8** [comment]
It is working, just with another port :D
http://host.areaz12server.net.br:8081/job/RedProtect/

**Comment by FabioZumbi12** [comment]
Sorry for no notice about this. My isp just blocked the port 8080 (for no reason), then now all are under 8081
