### ISSUE TITLE
[Suggestion] A chat for claim

### ISSUE THREAD

**Issue by Melvout** [FabioZumbi12/RedProtect#605]
Hi again !

A player from the server I'm playing has a suggestion : 

Is it technically possible to add a chat on a claim to talk with others players by using a command like /rp chat <message> for example ? If you have any ideas on how to set up that.
( Furthermore do you think the chat could be expanded to adjacent claims of the same owner ? )

It could be great when 3+ peoples are working on a the same claim and want to discuss without spamming the global chat.

Have a good day and I hope you're fine during these days.

**Comment by FabioZumbi12** [comment]
Added on https://github.com/FabioZumbi12/RedProtect/commit/dd1e77246612283c1a97a36687ea3478d6c1d5a3
