### ISSUE TITLE
[BUG] Portal removal

### ISSUE THREAD

**Issue by OscarleBG** [FabioZumbi12/RedProtect#606]
When I try to remove a portal, I have to be in the portal area so it teleport me. I'm not able to remove my portal

**Comment by OscarleBG** [comment]
Just found a way to do it, you have to stop the server, edit plugins/RedProtect/data/<Your world>.yml and remove the line set-portal

**Comment by FabioZumbi12** [comment]
You have two ways to do this without restart your server: https://github.com/FabioZumbi12/RedProtect/wiki/(08)-Portal-Creation#remove-the-portal
