### ISSUE TITLE
[BUG] RedProtect build 300+ won't load on Mohist 1.12.2 

### ISSUE THREAD

**Issue by Krosta8** [FabioZumbi12/RedProtect#607]
**Describe the bug**
With version build 300+, RedProtect won't start, just an error on startup.

**To Reproduce**
1. Run 1.12.2 server with RedProtect and build 300+
2. RedProtect won't load.
4. Error

**Screenshots and LOGs**
https://gist.github.com/Krosta8/8c6908a8ae47ed80e5b00bff79e9d6ac

**Server and plugins versions (please complete the following information):**
 - Server: Mohist version 6408ec0 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2847)
 - Plugin Version: RedProtect-7.6.5-b299-Universal.jar
 - Java Version: Java 1.8

**Comment by FabioZumbi12** [comment]
Fixed on next dev build 304+

**Comment by Krosta8** [comment]
I tried this with latest dev 304 and it was not working either. Got the same error :/

**Comment by FabioZumbi12** [comment]
Will be, is not fixed now

**Comment by Krosta8** [comment]
Oh, sorry, ok. Thank you and sorry, I got your message wrong :D

**Comment by Krosta8** [comment]
Today I tried the new build 305 and it is the same error on startup like before (tried also with resh new config and only with RedProtect)
https://gist.github.com/Krosta8/64836d8f416267412445064c8bf4a0d5
