### ISSUE TITLE
[Suggestion] Server protection - deny-build-in-worlds

### ISSUE THREAD

**Issue by Krosta8** [FabioZumbi12/RedProtect#608]
Hello,

I have a modded Minecraft server with IndustrialCraft.
I would love the option to set "blacklist" of items, that can't be placed in specific world.
Example:
```
    # Deny build of specific block in specific world.
    deny-build-in-worlds {
        world=[
            ic2:te:80 (example, Advanced Miner)
        ]
        DIM-1=[
            ic2:te:12 (example, Chunk Loader)
        ]
    }
```
I think, that this is described enough :D 
Would be also nice, to be able to set custom message for each blocked item.
Example:
```
    # Deny build of specific block in specific world.
    deny-build-in-worlds {
        world=[
            ic2:te:80, "&cYou cant build this here, you can mine only in Mineworld!"
        ]
        DIM-1=[
            ic2:te:12, "&cChunk Loader is only possible to be build in Mineworld to let you use Advanced Miner without being in Mineworld."
        ]
    }
```

**Comment by FabioZumbi12** [comment]
You already can do this on globalflags.conf:
```
        # Control what items the player can use.
        deny-item-usage {
            allow-on-claimed-rps=true
            allow-on-wilderness=false
            # The item names is like you see holding "F3" and pressing "H".
            items=[]
        }
```
Use the new command `/rp debug-item` with the item in your hand to get the material name for use on config ( the same for issue #610 )

**Comment by Krosta8** [comment]
Yeah, sorry, didn't get this config part correctly.
I tried to use it, but unfortunatelly it is imposissble to use with a bunch of modded items. 
I tried to use /rp debug-item to know, how correctly use it for (example) Generator from IndustrialCraft2, the name is ic2:te:3, via debug-item command it is IC2_TE, which means, that every machine from IC2 is not allowed.
Can you make it possible to use "the full address to the block"?
Not just "IC2_TE" but also with 3? "IC2_TE:3"?

**Comment by FabioZumbi12** [comment]
Well, redprotect can know the item material name if its not passed from modded to Mohist... In this case, its not possible

**Comment by Krosta8** [comment]
Okay, thanks, I will try to communicate this with Mohist developers.
