### ISSUE TITLE
[Suggestion] Build Flags

### ISSUE THREAD

**Issue by Kirstiana** [FabioZumbi12/RedProtect#61]
Hello! I love your plugin, but I'm really needing the ability to control whether or not users can place blocks or break blocks (separately).

RP Flag 1 - Toggle if a user can place a block
RP Flag 2 - Toggle if a user can break blocks

**Comment by FabioZumbi12** [comment]
Hello. You already can do this. Just use the flags allow-block-place or allow-block-break ;)

**Comment by Kirstiana** [comment]
Oh I'm dumb. I forgot to read the Admin Flag section on the wiki! THANK YOU SO MUCH!

Problem fixed :)
