### ISSUE TITLE
[Suggestion] Wand set to modded item

### ISSUE THREAD

**Issue by Krosta8** [FabioZumbi12/RedProtect#610]
It would be nice to be able to set wand item to modded item. 
I made item in my mod called "Region Maker" and wanted to use it just for region creation, but I found out, that it is not possible to set the item in config. 
I tried modid:itemname, "ID" and just ItemName, but it was not working.
Is it possible to add this option?

**Comment by FabioZumbi12** [comment]
Use the new command `/rp debug-item` with the item in your hand to get the material name.
