### ISSUE TITLE
[BUG] Missing cmdmanager files

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#611]
RP-Version: 7.6.6

If you drag a new zone you will get messages about missing language files.
As an an example:
cmdManager.newRegion.priority.set0

I thought they were only forgotten in the German version. that's why I had icvh created in English, but you can't find them there either.

Can you please write in the lines here that you have to add that the error message no longer comes.

Thanks a lot

![2020-04-06_20 36 12](https://user-images.githubusercontent.com/35557302/78594547-cf5a4700-7848-11ea-8abf-3a8016af6c18.png)

**Comment by FabioZumbi12** [comment]
The IDE renamed the string together my var with the same name. Fixed on latest dev build.
