### ISSUE TITLE
[Suggestion] Non-member Teleport flag

### ISSUE THREAD

**Issue by InfinitySnapz** [FabioZumbi12/RedProtect#612]
Hello!
In the server that I've been playing in, I run a public farm- however I need to add people who are interested as members first, which gives them certain unwanted permissions, and it also ends up being a hassle to have to manually accept users. 
While there is the ability to set homes, it requires getting to the claim in the first place.
As a result, I feel that there should be a flag to allow players who aren't a member of a claim to use the /rp teleport command.

**Comment by FabioZumbi12** [comment]
You can make portals to one region to other, this way people dont need to use the command: https://github.com/FabioZumbi12/RedProtect/wiki/(08)-Portal-Creation
