### ISSUE TITLE
[Suggestion] Global blocklimit and blocklimit per world?

### ISSUE THREAD

**Issue by Krosta8** [FabioZumbi12/RedProtect#613]
Blocklimit to set per world.
I can set blocklimit per world via LuckPerms, but if I create claim in world, where I set 10000 limit and wanted to have max. 2000 blocklimit in nether, it will show me: Used 10000/2000 and I can't do the claim. It would be nice to have it internally in RedProtect config.
Maybe to set in config.cfg global blocklimit (example 12000) and in globalconfig.cfg per world set the limits like:

- world 10000
- nether 3000
- end 3000

Player can decide, how the player wants to use the max possible limit of 12000 blocks (the biggest in world, but only 2000 for nether and end, etc..)

**Comment by FabioZumbi12** [comment]
Theres a config section on redprotect to select if the blocklimit will be per world or global with a minimum value

**Comment by Krosta8** [comment]
Yeah, I know, but I'm not able to set different blocklimits for each world, or I just can't see the option for it.

**Comment by FabioZumbi12** [comment]
Added vault permissions to check for world permissions, try the latest dev build.

**Comment by Krosta8** [comment]
Blocklimit is correct, but it is using the "already used limit" together.
Example:
redprotect.limits.blocks.1000 world=world
redprotect.limits.blocks.500 world=dim-1
In world I used 950 blocks
In nether (dim-1) I cannot do claim 950/500

Would be nice to have it like this:
I am in nether and set 500 blocks limit, used already 950 in world.
/rp blocklimit
"Already used 0/500, globally 950/1500 (1000+500)"
But I think, that global block limit is not very needed and I think, that it cannot be done, unless with block limit set in global-flags per world, right?
