### ISSUE TITLE
[BUG] /rp debug-item, block-transform with mods

### ISSUE THREAD

**Issue by Krosta8** [FabioZumbi12/RedProtect#617]
I wrote this in a comment of already closed issue, so, just to make sure, that you notice this:
The new command `/rp debug-item` doesn't do anything, if you don't have permission. (I mean like without message "You don't have permission to do this")

And found out, that if you don't have flag `block-transform` set to true in claim, you can't place anything from mods.

Happened with RedProtect build 310 and Mohist build 439

**Comment by FabioZumbi12** [comment]
Its all spected. As a debug command, the players should not see this command and will show the help info instead. `block-transform` handles all blocks transformations, then can handle a lot of things and need to be used with caution. If the mod itens are treated as block transformations, its not a redprotect issue. This flag handles `BlockFadeEvent`
