### ISSUE TITLE
[BUG] MySQL - server lag every block placed/broken

### ISSUE THREAD

**Issue by Krosta8** [FabioZumbi12/RedProtect#618]
**Describe the bug**
If you connect RedProtect to MySQL and try to break/place block - server lag. RedProtect do around 13k requests to MySQL (in 5 sec) and after these requests server is going back to normal.
This can't be reproduced, if you are using file save instead of MySQL.

**To Reproduce**
1. Connect RedProtect to MySQL
2. Try to break/place block - server lag
3. RedProtect did around 13k requests to MySQL
4. After this - server is going back to normal

**Screenshots and LOGs**
https://media.discordapp.net/attachments/692360033857568788/697748114626576404/unknown.png

Happened with RedProtect build 310 and Mohist build 439, Minecraft version 1.12.2

EDIT://
Also found out, that the server got lag with claim creating (don't know, if its related). 
With the test I made claim size of 19k blocks.

**Comment by FabioZumbi12** [comment]
This still?

**Comment by Krosta8** [comment]
I am not sure, will test it next week and let you know

**Comment by Qkzoh** [comment]
This is happening to my server. Redprotect is hardly laggin my server 

it's also taking me back or delaying when i use the shovel to mine dirt or sand it takes me back

![image](https://user-images.githubusercontent.com/67622253/88263398-fcb3ef00-cc97-11ea-86b5-97db5eb7a999.png)

**Comment by FabioZumbi12** [comment]
On claim creation a have added a async thread to do not lag the server. This avoid lag on both db types.
