### ISSUE TITLE
[BUG] flag "block-transform"

### ISSUE THREAD

**Issue by Melvout** [FabioZumbi12/RedProtect#619]
Hi !

I am here to report various problems with the new flag "block-transform" on the lastest version of the plugin and a server using Paper 1.15.2 :

**First problem :**

If you set the flag to "false" and place a door you get that :

![image](https://user-images.githubusercontent.com/39627267/78902710-6f4ae700-7a7a-11ea-831d-adfe25178a8e.png)

and if you try to open it :

![image](https://user-images.githubusercontent.com/39627267/78902753-7ffb5d00-7a7a-11ea-9441-f65b3f1dc8db.png)

Now if you set again to "true" the flag there are 2 cases :

- If you try to open the door : it brokes it and you get 2 doors.

- If you want to break it ( with an axe eff V for example ), the door completely disappear.

**Second problem :**

If you set the flag to "false" and try to place a trapdoor on the half-top of a block, it will be placed on the bottom-half.

**Third problem :**

If you set the flag to "false" and you want to place fences, chests, trapdoors, stairs, anvils or furnaces ( at first glance all blocks that can be oriented ) every of these blocks will be facing north, no matter the way you placed them.

Thanks in advance if you can fix theses issues.

_( I will edit this issue if I am informed of any other problems )_

**Comment by FabioZumbi12** [comment]
Try the latest dev build... the event of this flags handles should handle only blocks transformations, but seems spigot deliver more than this to this event.

**Comment by aurel85** [comment]
1 - If the block is placed before the modification of the flag it works more or less but if we place the block after the modification of the flag, it is always bug.
2 - Not corrected
3 - Not corrected

I use the last version (313) and Paper 1.15.2
