### ISSUE TITLE
[BUG] Spams my console with error and force shutdown it

### ISSUE THREAD

**Issue by Ex-Infinityy** [FabioZumbi12/RedProtect#620]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
still error
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/RedProtect>
404 not found
* Its important to you include the plugin jar name, because version and build info.
RedProtect-7.6.6-b307-Universal.jar

**Describe the bug**
im trying to create my own survival mod but somehow when i start my server it just shutdown itself and spams my console with error, when i remove this plugin, my server starts working fine again
any ideas?

**To Reproduce**
1. start server
2. error

**Expected behavior**
umm i dont reeally care about error, but this time it force shutdown my server.

**Screenshots and LOGs**
https://gist.github.com/Ex-Infinityy/45a246f155b2bf88835a2a55d9dcdfed

**Server and plugins versions (please complete the following information):**
 - Server: Mohist-9f12580-server
 - Plugin Version: RedProtect-7.6.6-b307-Universal.jar
 - Java Version: Java 1.8

**Additional context**
forgive if i do something wrong on this report, tbh this is my first bug report issue, also sorry for my bad grammar, thankyouu^^

**Comment by FabioZumbi12** [comment]
Try the latest dev build: https://host.areaz12server.net.br:8081/job/RedProtect

This is already fixed

**Comment by Ex-Infinityy** [comment]
why i always get ERR_SSL_PROTOCOL_ERROR whenever i tried to access that site?
@FabioZumbi12

**Comment by FabioZumbi12** [comment]
Its http not https, i gave you wrong url.
