### ISSUE TITLE
[BUG] [MOHIST] Block-transform false = can't use flint and steel

### ISSUE THREAD

**Issue by Krosta8** [FabioZumbi12/RedProtect#621]
Hello,
I found out, that with your changes I don't need to allow block-transform for players to allow them place blocks from mods, but problem is with fire. 
https://imgur.com/a/us6q43c
The "generated" block is with ID "ic2:te:0" if this can help.
I can't even activate nether portal.

**How to reproduce**
1. Start Mohist server
2. Install (for example) Industrialcraft 2
3. Create region
4. Set block-transform in region to false
5. Try to use flint and steel in that region

Happened with RedProtect build 315 and Mohist build 453, Minecraft version 1.12.2

**Comment by FabioZumbi12** [comment]
The build 317 + should fix the fire problem.
