### ISSUE TITLE
[Suggestion] Explosion-damage as seperate region flag

### ISSUE THREAD

**Issue by Krosta8** [FabioZumbi12/RedProtect#622]
It would be nice to have explosion-damage like seperate region flag.
I won't allow players to spread fire in their regions (possible lags), but still have it more like "vanilla", which means, that they still need to be afraid of explosion from creepers/tnt.

As I saw on wiki, there is only one flag now, which is "fire" and it can toggle fire spread and explosion damage at once.

**Comment by CloudeLecaw** [comment]
and you dont wanne use the gamerule for the whole world right? :3

`doFireTick | Whether fire should spread and naturally extinguish`

**Comment by Krosta8** [comment]
Hm, maybe I will use it like this, thanks :D

**Comment by FabioZumbi12** [comment]
If you dont want fire spread, use that gamerule as Cloud suggested. Dont wort a new flags only for explosions.
