### ISSUE TITLE
[BUG] Flag "block-transform" and "smart-door"

### ISSUE THREAD

**Issue by Melvout** [FabioZumbi12/RedProtect#624]
Hi !

Firstly, thanks for the fixes already made on this flag. Yet there is a new bug ( using the latest version of the plugin and server on Paper 1.15.2 ) :

If you set to "**false**" the **block-transform** flag and to "true" the **smart-door** flag.
The doors aren't opening simultaneously correctly and it results in something like this :

![image](https://user-images.githubusercontent.com/39627267/79067376-0902d600-7cbf-11ea-8856-715d5b57409b.png)

It's not only a visual bug because you can't go through the doors. 

Is this problem can be fixed ?

**Comment by aurel85** [comment]
And flag press-plate used with a door it's the same... :/

**Comment by FabioZumbi12** [comment]
Both on 1.15.2? Because on 1.16.2/3 i dont have this problem, probably fixed on latest minecraft versions!

**Comment by aurel85** [comment]
Now it's ok, thank you !
