### ISSUE TITLE
[BUG] Flag "block-transform"

### ISSUE THREAD

**Issue by Melvout** [FabioZumbi12/RedProtect#625]
Hi,

A new problem has been spotted. If you set to "**false**" the "**block-transform**" flag and you want to place a coral out of the water, a source of water appears on the same block.
As you can see on this screenshot :

![image](https://user-images.githubusercontent.com/39627267/79156293-e6fa7800-7dd2-11ea-9d3b-496e712ea3bb.png)

Thanks.

**Comment by aurel85** [comment]
And the kelp : 

![2020-04-27_20 02 22](https://user-images.githubusercontent.com/24486147/80404972-41f79900-88c2-11ea-9836-dd77fc20cc83.png)

**Comment by CloudeLecaw** [comment]
well i have a question i didnt really got whaz interactions are counted as "blocktransform"?

What about mycel (the earth arround) or  wines?
what about clay where water flows over?....
What about Cleanstone and Cobblestone generators?

these all are some kind of blocktransformations or arent they? arent they?

**Comment by EpiCanard** [comment]
Is it possible to add a config parameter to define yourself the type of block affected by the transformation and use this limitation in all type of event affected (BlockFadeEvent, BlockPhysicsEvent, BlockPlaceEvent) ?

Because for now the limitation you added only affects BlockPlaceEvent.

**Comment by Melvout** [comment]
Hi !

We are wondering about several things that can happen while using this **"block-transform"** flag and we would have a confirmation that it's something that can happen with the flag on **"false"** or it is buggy ?

- You can display only the "piston-head" of a piston.
- You can plant flowers on another blocs than grass.
- Cultures can be placed on another blocs than farmland.
- You can display only the bottom half of a 2 blocs tall flower.
- Ladders can stay without a block to hang on.
- You can have a "full block" of scaffolding with only 1 scaffolding.
- You can have a snowy grass/podzol/mycelium block without snow on top of it.

Here is a screenshot which regroup everythings listed above :

![image](https://user-images.githubusercontent.com/39627267/80926209-0c592100-8d96-11ea-97b0-39fe564882f3.png)

**Comment by aurel85** [comment]
Apparently there have been changes with the latest updates, can we be kept informed of what has been decided for this flag ?

**Comment by aurel85** [comment]
up...

**Comment by aurel85** [comment]
Thank you !
