### ISSUE TITLE
[BUG] [MOHIST] PlayerInteractEvent error - opening doors, gates, ...

### ISSUE THREAD

**Issue by Krosta8** [FabioZumbi12/RedProtect#626]
**Describe the bug**
Every click on door, fence gate, etc.. Error in console - PlayerInteractEvent
Error not appears if you are trying it in wilderness (outside of any claim)

**To Reproduce**
1. Create claim
2. Try to open/close door or gate in claim
3. Error appears in console

**Screenshots and LOGs**
https://gist.github.com/Krosta8/05f00b02fee066428378e225038f1fe2

**Server and plugins versions (please complete the following information):**
 - Server: Mohist 1.12.2 build 466
 - Plugin Version: RedProtect-7.6.6-b357-Universal.jar
 - Java Version: Java 1.8

**Comment by FabioZumbi12** [comment]
Its seems you removed the flag `smart-door` from flags configuration...

**Comment by Krosta8** [comment]
Oh, sorry, didn't know, that this should caused this. I disable this, because I have mod in-game for this feature and I was not sure about compatibility between your plugin and the mod (MalisisDoors)
It looks like, it is working. Thanks :)
