### ISSUE TITLE
[Suggestion] Spectator mode in a claim

### ISSUE THREAD

**Issue by Melvout** [FabioZumbi12/RedProtect#629]
Hi !

**Here is a new suggestion :**

Add a functionnality to allow the owner of a claim ( + admins ? ) change his gamemode from survival to spectator ( and vice-versa ).
The spectator mode should be restricted to his claim only, the owner can't leave his claim while in spectator mode **or** his gamemode is automatically updated to survival if he tries to go outside.

The functionnality could be accessible from the **/rp flag** menu.

**Thanks !**

**Comment by CloudeLecaw** [comment]
actually u can chane the gamemode of a claim...
or u can use Enter and Leave reagion commands


**player-enter-command** | Execute a command as player when a player enter in a Region | /rp flag player-enter-command [cmd1], [cmd2], 

**player-exit-command** | Execute a command as player when a player exit a Region

You can work with this:
Step 1: Enterring gives him the permissions for GM3 (permiison command)
Step 2: Leaving steams him the permission (Permisison command) + Sets him to gamemode 0

Well this would not help to not allow him to leav in gamemode 3.. but is a first idea xD

Pls apsect that the user could run out of his region while he is inside some blocks or in the air...
try to clear that with your players.. that they should not do this ;)

**Comment by FabioZumbi12** [comment]
Its already allow using the flag `gamemode`: https://github.com/FabioZumbi12/RedProtect/wiki/(05)-Region-Flags#admin-flags
