### ISSUE TITLE
Internal Exceptions when i use /rp info

### ISSUE THREAD

**Issue by Stuart74** [FabioZumbi12/RedProtect#63]
I keep getting the below error when i use the /rp info command. It still shows me the players region but gives me the internal exception in red in chat.    

Running Kcauldron 1.7.10 Build 201
Redprotect  6.5.8

Error 

http://pastebin.com/10b1bgbc

**Comment by FabioZumbi12** [comment]
Probally the player world is not listed on "region-settings.world-colors.worldName" in configuration, but i will add a default value for this cases.

**Comment by Stuart74** [comment]
The original issue has been fixed but now has caused console spam believe its due to  a missing or broken class. 

error is here  http://pastebin.com/ZpqSZbsx

**Comment by FabioZumbi12** [comment]
Oh, something wrong on my code. The server are looking for armor stand on your 1.7 ...

I will dix tomorrow, ☺

**Comment by Stuart74** [comment]
Any word on this fix

**Comment by FabioZumbi12** [comment]
Yup! I working on offline mode for the other issue, but try this version: https://github.com/FabioZumbi12/RedProtect/blob/master/release/RedProtect-6.5.9-b671.jar?raw=true

**Comment by Stuart74** [comment]
Will let you know shortly

**Comment by Stuart74** [comment]
Seems to be working all as intended with no consoloe spam thanks for the help on this again wish all devs were as helpful as you.
