### ISSUE TITLE
Userpermision redprotect.user broke with vault[BUG] 

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#631]
In the latest build Version 318 of Redprotect we notices all our players have empty Flag-GUIs
and cant use many commands.

after a bit of testing arround with the permissions, we found out that
the parrent permission **redprotect.user** does not work.

This is including all permisions for commands and flags of it.
![image](https://user-images.githubusercontent.com/12080017/79980108-e16ff280-84a2-11ea-9cef-2af897b72825.png)

![image](https://user-images.githubusercontent.com/12080017/79979376-b6d16a00-84a1-11ea-8a75-f150a1023c2a.png)
- we added the direct permissions to add the flag gui
in the Flag-GUI you see 3 icons. these flag where added extra with direct permission

we added redproct.flag.defaults
![image](https://user-images.githubusercontent.com/12080017/79979572-0152e680-84a2-11ea-9e60-fdf9554ac141.png)
it looks normal now.

The interesting point is: if we test it on the server WITHOUT Vault plugin
then all works fine and also the redprotect.user is recognized correctly
So this issues just appears with Vault on the Server (and maybe also only with Pex?)

**Server:** Spigot 1.15.2
**Redprotect Version:**  RedProtect-7.6.6-b318-Universal
**other Plugins:** Vault_1.7.2, Multiverse-Core-4.1.1-SNAPSHOT, PermissionsEx-1.23.4

**Comment by Blueeyestar** [comment]
I have the same problem.

**Comment by FabioZumbi12** [comment]
You can disable vault permissions on config. Use vault only you need to control redprotect permissions per world.

I'll investigate this issue.

**Comment by Blueeyestar** [comment]
I only found the line in the list that indicates Vault.
Is the line misspelled?

     **use-valtapi = true**

If this is True, the users under / rp flag have no flags to select.

If I now set this to false, you have no authorization to use this command even though the zones are owned.

**Comment by Blueeyestar** [comment]
I may have an idea.
can't you make it easier as a server owner in the world?
For example, give / rp guizone WOLRD. Then the server owner gets all flags displayed in the gui that exist in the world. Now the server owner can activate and deactivate which flags are displayed to the user under / rp zone.

Is that doable?

**Comment by CloudeLecaw** [comment]
For the moment we design it fitting to the vault permissions.
The problem isself not solved but for it that way

For our server it does because we are using the way vault handles it now - so with the per world permissions.

we also notriced in the plugin.yml the redprotect.user does not exists anymore so we are using the other partent permissions now related to plugin.yml

If you want, you can close this issues.

**Comment by CloudeLecaw** [comment]
Well ok, we accepted the new way permissions are handled
