### ISSUE TITLE
[BUG] Premision Chest

### ISSUE THREAD

**Issue by JavyKrono** [FabioZumbi12/RedProtect#633]
Hello, I am having problems with some permissions, some users of my server, creating regions and when you try to put a chest inside them, it tells you that you do not have permissions to open the chest.

Also, users cannot interact with objects (Pixelmon healer) on the map.

 - Server: [Sponge 1.12.2]
 - Plugin Version: [RedProtect-7.6.4-b280-Universal.jar]
 - Java Version: [Java 1.8]

**Comment by CloudeLecaw** [comment]
Only the Owner and members of a region are allowed to open  Chests
if you wanne change this you have to set the chest flag to false.

**Comment by FabioZumbi12** [comment]
Solved on discord: Chest problams was caused by conflicts with Universer Guard 2

Pixelmon  npc and machines can be accessible using the flag `allow-mods`
