### ISSUE TITLE
[BUG] Unable to break leaves

### ISSUE THREAD

**Issue by Shadow32055** [FabioZumbi12/RedProtect#635]
**Describe the bug**
I have it setup so players are able to break any blocks in the world (excluding bedrock to use the break blacklist) and they are not allowed to place any (excluding chests to use the place whitelist). This seems to work with every block but leaves. Players are unable to break leaves with default permissions, however, operators are able to break them. Leaves still decay properly over time after the wood is removed.

I have removed all other mods (excluding SpongeForge) and plugins to verify this is indeed an issue related to Red Protect.

**Steps to reproduce the behavior:**
1. Adjust globalflags.conf to the below settings for over world (see attached config)
        a. Set build=false
        b. Set break-blocks blacklist to "minecraft:bedrock"
        c. Set place-blocks whitelist to "minecraft:chest"
        d. Save
2. Start server
3. Join server
4. Attempt to break leaves

**Expected behavior**
Leaves should be able to be broken by players with default permissions.

**Screenshots and LOGs**
globalflags.conf - https://gist.github.com/Shadow32055/5b9238ca7ea6dbc924bb1cc32c251aa6

**Server and plugins versions (please complete the following information):**
 - Server: spongeforge-1.12.2-2838-7.2.1.jar
 - Plugin Version: RedProtect-7.6.6-b318-Universal.jar
 - Java Version: 1.8
 - Forge: forge-1.12.2-14.23.5.2838-universal.jar

**Comment by CloudeLecaw** [comment]
Why you havent set leaves to whitelist?
