### ISSUE TITLE
[Suggestion] Manage the weather in a claimed area

### ISSUE THREAD

**Issue by Melvout** [FabioZumbi12/RedProtect#639]
Hi !

Here is a new suggestion : 

Adding the possibility to set the weather in a claim area using either of these methods :
- the **/rp flag** menu 
- a cmd like **/rp weather <sun|rain|...>**

Thanks.

**Comment by FabioZumbi12** [comment]
Its possible, as the weather is set at same time for whole world and not by chunk/region :/
