### ISSUE TITLE
rp error 

### ISSUE THREAD

**Issue by FyFou57** [FabioZumbi12/RedProtect#64]
Si un joueur pose un panneau sans rien marquer dessus alors le panneau indiquera RP error, mon serveur est un pvp faction et j'utilise redprotect juste pour protéger le spawner et la warzone donc je ne veux pas que les gens crées des zones ou autres.

**Comment by FabioZumbi12** [comment]
Vous pouvez écrire en portugais ou en anglais s'il vous plaît ?

**Comment by FyFou57** [comment]
google translate 

If a player raises a panel without any score above then the panel will indicate RP error , my server is a pvp faction and I use redprotect just to protect the spawn and the warzone so I do not want people adds or other areas .

**Comment by FabioZumbi12** [comment]
If i get what you mean, you need disable players claim in all your words on confie, in allowed world claims optipn.

**Comment by FyFou57** [comment]
I want to create areas in the main world, for the spawn and the warzone except I do not want people to create zones ( why it's good people can not) however when people ask a panel anywhere in the world there will be marked "RP error" on the panel.

**Comment by FabioZumbi12** [comment]
Yes, this is proposital, and this will followed with a message sayng the player cant claim in that world.

**Comment by FyFou57** [comment]
google translate english 

Problem Solved thank you , I have a few suggestions.

We can not allow a lot of block with the command /rp flag allow-break minecraft chat
is Limited and can not be added directly in the config

it will be very intérressant Power authorize example , in Quebec the zone X on May ask
All blocks Unless some ( current is the opposite , the two options put be Very well)

it 'll be very interresant of WorldEdit Have Some basic commands
//cut and //set , 
because for some things We Are forced to use WorldEdit and
worldguard
