### ISSUE TITLE
[Suggestion] Chunk selection, outset & inset

### ISSUE THREAD

**Issue by adfg4af4** [FabioZumbi12/RedProtect#640]
Minecraft 1.12.2 + Sponge

With the help of WorldEdit in the past, it was possible to create regions based on chunks. Because of WorldGuard supports WorldEdit it is possible to select chunk using WE command //chunk, then //outset -h 16 so the region is now 3x3 chunks and the whole world regions are based on chunks. I tried to implement something like this using RedProtect, using CommandUtils (command aliases) but RP doesn't work with WE selection tool (wand). Please think about WE selection tool support or implementing commands such as //chunk, //outset and //inset.

**Comment by CloudeLecaw** [comment]
UseF3+H..

**Comment by FabioZumbi12** [comment]
Added on https://github.com/FabioZumbi12/RedProtect/commit/dd3dac69d954c4e5ccb02eaeb07dd1c998edc5d6
