### ISSUE TITLE
[BUG] Mohist - If you try to block monster spawn -> Huge lags

### ISSUE THREAD

**Issue by Krosta8** [FabioZumbi12/RedProtect#641]
**Describe the bug**
If you block monster spawn in region, the server will get TPS drop and massive lags (tested in night)

**To Reproduce**
1. Create region
2. Block monster spawn via flag
3. Lags incoming

**Server and plugins versions (please complete the following information):**
 - Server: Mohist 1.12.2 (build 532)
 - Plugin Version: RedProtect-7.6.6-b324-Universal.jar
 - Java Version: Java 1.8

**Comment by FabioZumbi12** [comment]
Its seems the server its trying to spawn monsters intensively when the event is cancelled, more like, instead to wait to try to spawn again, its trying on every cancelled event. RedProtect have just few 20 lines of code to handle mob spawning.

**Comment by Krosta8** [comment]
Okay, understand. Should I try to report this to Mohist? You think, that this is problem with Mohist, right?
Because on spigot, it looks like without any problem
