### ISSUE TITLE
[Suggestion]  Add Slimes to the Monster category

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#642]
Many users keep asking me why the annoying slimes are still coming even though they have switched off monsters. I cannot answer the question. You can only switch off the slimes if you deactivate the peaceful animal spawn. But then there are no more peaceful animals. or you have to create a subzone. that is very cumbersome. Can you assign the slimes to the monsters? that would help us a lot. Or create a list in the config where you can sort which ones are neutral and which monsters are on the server

**Comment by FabioZumbi12** [comment]
The server it wont consider slime as a monster. What i do its just check for the mains mob class like here: https://github.com/FabioZumbi12/RedProtect/blob/dbe474248e83e679347c996d10fb842df16e929a/RedProtect-Spigot/src/main/java/br/net/fabiozumbi12/RedProtect/Bukkit/Region.java#L1116

I dont check mobs types individually.

**Comment by Blueeyestar** [comment]
do you have the opportunity to add the slimes to the category of evil monsters? or that you can create your own list in the config where you decide which peaceful or aggressive mobs are in the flags? or is it getting too complicated?

**Comment by CloudeLecaw** [comment]
I can understand this problem, its really annoing that you cant block slimes that way

Slimes may are not monster for minecraft but they are seens as monster by the players

So the Region.java sees them as regular monsters.
maybe there is  way to create a list?

We have a flag for monster and neutral.

If we could define a list like groups in the config?

```
monster {
    entityname1
    entityname2
    etc..
}
neutral {
    entityname3
    entityname4
    etc..
}
```

then everyone could setup what he defines as a monster and what as neutral mob

The neutral flag would take care of all entities in the neutral list
the  monster flag would take care of all entities in the monster list.

**Comment by Blueeyestar** [comment]
I just see you actually made it !!!! there is now a gui where you can set which good and which monster spawnwn are allowed on the zone.m This is mega hammer well done. I think this is a big update which offers a lot of new possibilities.
