### ISSUE TITLE
[BUG] Does not allow to interact with the world

### ISSUE THREAD

**Issue by ChrisTVH** [FabioZumbi12/RedProtect#645]
**
I use Paper 1.12.2 and the version of the RedProtect-7.6.7-b327-Universal.jar plugin brings the following problem shown in the image, it does not allow anyone to interact with anything for that reason, I have been holding the BONE_MEAL bug in the earlier version.
**
![image](https://user-images.githubusercontent.com/58376852/83317510-441f8100-a1fb-11ea-9490-512a405c80cc.png)

**Comment by FabioZumbi12** [comment]
I can't reproduce this!

Check your configuration looking for `need-claim-to-build`. If this is true, players cant build outside your regions and can put only protection blocks.

**Comment by ChrisTVH** [comment]
That didn't work but upgrade to another dev version and it fixed

**Comment by FabioZumbi12** [comment]
Cool. Don't forget to check and update your review on RP's page.
