### ISSUE TITLE
Translation for [Mobs Names in the new Monster-GUI

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#648]
We are running a german server. You can aspecet that most player there dont the names of the german mobs. 
Example: most german dont know what a SALMON is.
![Snag_12410769](https://user-images.githubusercontent.com/12080017/83362993-1753a100-a396-11ea-8342-d4e7f4f25f11.png)

Is there a way to create a list where we could translate the names of the Mobs for the eggs?

An other methode may would be to use the clients used language for the mobs this would
be the most effficent way because then it would not matter in what language the client does play.

**Comment by FabioZumbi12** [comment]
Use my other plugin: https://www.spigotmc.org/resources/translationapi.70692/
