### ISSUE TITLE
[BUG] /rp reload has disappeared

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#649]
Hi,

The /rp reload command is no longer recognized by the plugin at all, it returns in the /rp help
It's a shame because it is very useful especially the recent /rp reload-config

I use the last version of this plugin (RedProtect 7.6.7 b#333) and Paper 1.15.2.

Thank you in advance.

**Comment by FabioZumbi12** [comment]
`rp reload` still working normal, theres no modification!

![image](https://user-images.githubusercontent.com/5833818/83409388-b2766600-a3ea-11ea-8a3f-0cd14de86c67.png)
Check your console for errors

**Comment by aurel85** [comment]
today I have it but yesterday it didn't work, really strange
