### ISSUE TITLE
[Suggestion] Custom GUI flag spawn-animals/monsters

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#650]
Hi,

Would it be possible to configure the GUI of the flag spawn-animals and spawn-monsters directly or at least to put the eggs of each mob rather than the same item ? This would be much simpler for the users.

**Comment by FabioZumbi12** [comment]
The gui need to be compatible from 1.8 to 1.15.2. This is why cant customize too much the gui, and to make a customizable gui, it will consume to much work.
