### ISSUE TITLE
Can randoms has see book?

### ISSUE THREAD

**Issue by Hebgbs** [FabioZumbi12/RedProtect#651]
**Is your feature request related to a problem? Please describe.**
I have a claim with lecterns I would like for random players to read, even though they can't possibly take the book or have the capability to build.

**Describe the solution you'd like**
A flag which allows for the capability to interact with lecterns, or an existing flag to have its functionality enhanced so books can be used in a claim where people otheriwise have no permissions to interact with anything.

**Describe alternatives you've considered**
Signs wouldn't work for my use case. Placing the book outside is likely to have it stolen by randoms.

**Additional context**
This would be fantastic for shops and displays on servers, or for admins who want to RP an area but not use holotext to have words for users to read.

**Comment by FabioZumbi12** [comment]
This is already possible on latest release

**Comment by Hebgbs** [comment]
What is this flag called?

**Comment by FabioZumbi12** [comment]
Theres no flag, any player can already read the book, but only member of the region can get the book.
