### ISSUE TITLE
[BUG] [MOHIST] Creeper can destroy ArmorStand with fire on false

### ISSUE THREAD

**Issue by Krosta8** [FabioZumbi12/RedProtect#652]
**Describe the bug**
In region with fire flag on false, Creeper (maybe TNT too) can destroy ArmorStand. This looks like problem specifically in Mohist. Don't know, if it is possible to repair from your side or Mohist.
On Bukkit it is without any problem.

**To Reproduce**
1. Create region
2. Set fire flag on false
3. Let Creeper explode in this region near to ArmorStand
4. Armorstand will be destroyed by this explosion

**Server and plugins versions (please complete the following information):**
 - Server: Mohist 1.12.2 build 539
 - Plugin Version: RedProtect-7.5.7-b333-Universal.jar
 - Java Version: Java 1.8

**Comment by FabioZumbi12** [comment]
I think need to be checked on Mohist if dont is happening on Bukkit version

**Comment by FabioZumbi12** [comment]
I cant reproduce this on bukkit version. Really need to be checked with mohist devs.
