### ISSUE TITLE
[Sugestão] Venda/Compra de Terreno

### ISSUE THREAD

**Issue by michaelmatteus** [FabioZumbi12/RedProtect#653]
**Sua solicitação de recurso está relacionada a um problema? Por favor descreva.**

Atualmente o RP está atrelado ao plugin BuyRegion para fazer vendas e alugueis de Terrenos porém ele não tem atualizações deste de agosto de 2019...

**Descreva a solução que você gostaria**

Não sei o qual difícil é a programação deste recurso, porém acho que seria ideal a criação comandos que execute a mesma função do plugin BuyRegion porém isto dentro do próprio RP.
Segue abaixo detalhadamente o funcionamento da nova função se implementada

*Compra e Venda de Terrenos---------------(Auto-explicativo)
```
/rp sell [RegionName] [Value] #Confirmação de /rp yes
/rp vender [NomeDoTerreno] [Valor] #Alias
/rp buy [RegionName] #Confirmação de /rp yes
/rp comprar [Terreno] #Alias
```

*Aluguel de Terrenos---------------

```
/rp rental [RegionName] [Value] [Days] #Confirmação de /rp yes
/rp alugase [NomeDoTerreno] [Valor] [Dias] #Alias
#Coloca uma RP disponível para ser alugada (somente Lider pode fazer isso)
/rp unrental [RegionName] #Confirmação de /rp yes
/rp naoalugar [NomeDoTerreno] #Alias
#Desativa um RP disponível para ser alugada (somente Lider poder fazer isso, sujeito a penalidade podendo ser definida o valor ou comandos no arquivo config do RP)
#O uso deste comando não irá despejar o jogador que estiver alugando porém deverá impedir que próximos alugueis possam ser realizados ou renovados.
#Poderá ocorrer um bug quando a pessoa colocar para alugar e depois desalugar para mudar o preço ou dias do aluguel...não sei qual seria a solução para evitar conflito no RP....
/rp rent [RegionName] #Confirmação de /rp yes
/rp alugar [NomeDoTerreno] #Alias
#Permite o jogador alugar o terreno em questão, ao digitar o /rp rent aparece para ele o valor total e o numero de dias que será alugado.
```
Novas strings sugeridas (PT-BR): #Tomei como base o modelo lang já existente do RP

```
cmdmanager.region.sell= '&bVocê colocou &6{region}&b a venda por &2{value}&b!'
cmdmanager.region.sell.error= '&6{region}&b não existe!'
cmdmanager.region.sell.owner= '&bVocê não é o dono desta região!'
cmdmanager.region.sell.already= '&bEste terreno ja está a venda!'
cmdmanager.region.sell.syntax= '&bUso correto: /rp sell [RegionName] [Value]'
cmdmanager.region.buy= '&bVocê comprou &6{region}&b por &2{value}&b!'
cmdmanager.region.buy.fail='&6{region}&b não existe!
cmdmanager.region.buy.owner='&bVocê não pode comprar seu próprio terreno!'
cmdmanager.region.buy.syntax= '&bUso correto: /rp buy [RegionName]'
cmdmanager.region.rental='&6{region}&b foi definida para alugar &4{days} por &2{value}'
cmdmanager.region.rental.error='&6{region}&b não existe!
cmdmanager.region.rental.owner= '&bVocê não é o dono desta região!'
cmdmanager.region.rental.syntax= '&bUso correto: /rp rental [RegionName] [Value]'
cmdmanager.region.unrental='&6{region}&b não pode ser mais alugada ou renovada!'
cmdmanager.region.rent='&bVocê está alugando &6{region}&b por &2{value}&ba cada &4{days}!'
cmdmanager.region.rent.error='&bNão é possível alugar este terreno!'
cmdmanager.region.rent.owner= '&bVocê não pode alugar a própria região!'
cmdmanager.region.rent.syntax= '&bUso correto: /rp rent [RegionName]'
```

**Considerações e Contexto adicional**
1- O jogador seria setado como membro da região em questão quando alugar ela porém se o mesmo comprar uma região ele é setado como lider desta região e o antigo dono é removido de todas as atribuições relacionadas aquele RP
2 - Seria ideal que um .yaml fosse criado como um registro das regiões em aluguel e regiões, funcionaria da seguinte forma: caso fosse colocada para alugar, ao ser alugada seria colocar o nome {player} no "RegionEco.yaml" e caso a pessoa vende-se a região ela simplesmente seria apagada do mesmo yaml assim impedindo que esta fosse comprada novamente.
3 - Assim como o RP atual a função deve fazer hook com o Vault

Bom, essa atualização seria algo grande, porém creio que muitas funções poderiam ser re-aproveitadas do BuyRegion e implementadas dentro deste sistema com a devida autorização é claro...
OBS: Não compreendo muito bem a programação Java de plugins para o minecraft portanto esta ideia foi escrita com base nos conhecimentos que absorvi administrando meu próprio servidor.

Meu discord para demais esclarecimentos: MechOrange!#7156

**Comment by FabioZumbi12** [comment]
Foi criado o Add-on `BuyRentRegion`: https://github.com/FabioZumbi12/RedProtect/tree/master/add-ons
