### ISSUE TITLE
outdated regions on Dynmap with own color + informer

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#655]
Redprotect allready has a nice feature to regconie when the last owner, leader of a region was visting the region and aso when this time has passted over an defined amount of time - the pruge feature. When a defined amount of time is passed there its an option to automatcly purge this region.
Some servers like our's dont want automaticly purging of outdated regions. We wanne decide itself if the region should be removed or not.

As Staffmembers we have no options to see regions that are already passed the time limit.
(you cant visit all regions just to see if its "too old" or not...)
So we made some thoughts and collected ideas about a nice new feature for RedProtect
combined with allready existing features.

The marking of outdated Regions in a different color on dynmap and an chatinformer for staffmembers.

**This would be the possible option to show outdated regions in a different color on the dynmap**.

_This is how it looks at the moment at the dynmap_
![Dyn1](https://user-images.githubusercontent.com/12080017/84131981-9b1c2600-aa45-11ea-8c25-51d56399c529.jpg)

_this is how it could look on the dynmap_
![Dyn2](https://user-images.githubusercontent.com/12080017/84132042-aa9b6f00-aa45-11ea-967a-a0efbdc73676.jpg)

The (in this case) purple color shows that the region was not visted by a region owner or leader since the time defined for purge.
The Stuff now just needs to take a look on the dynmap what regions all have the purple color
and delet them if wanted.
May there is a chance to add a blacklist for regionnames that should not become purple.

**Optional the Staffmember should be informed on login or with  a command**
a list should get printed out in chat with all "outdated" (only not the once from the blacklist like in the first idea) when clicking on the region names the staffmember should be able to get teleported there if wanted.

Both things should be able to release because we allready have a "listener" for the pruge feature that is asking if the region owner, leader was there for x days.
Currently if the time passted it deldets the region.
with the new feature the options should be to define the region with a different color (defined in cnfig) and adding the regionname to the list for the staff.

**Comment by CloudeLecaw** [comment]
What kind of Revision you need?
We are using latest 7.2.2 Build362 of Redprotect and also the latest version of Dynmap, on a PaperMc 1.16.1 Build 101 Server
This there something else you might need? :)

**Comment by FabioZumbi12** [comment]
What i need is time to work on xD

**Comment by FabioZumbi12** [comment]
Fixed on https://github.com/FabioZumbi12/RedProtect/commit/209c97b214f11d02f288c9b997d089a80e8d348a

**Comment by CloudeLecaw** [comment]
It does not work correct

Before Updating:
![Snag_8c52ce4](https://user-images.githubusercontent.com/12080017/88493113-b28c7f80-cfaf-11ea-9e60-45fbb1307fb3.png)

After Updating:
![Snag_8c5a1f5](https://user-images.githubusercontent.com/12080017/88493125-c46e2280-cfaf-11ea-9da5-bd21a95b1508.png)
