### ISSUE TITLE
[Suggestion] Rework of region naming

### ISSUE THREAD

**Issue by Jason505** [FabioZumbi12/RedProtect#657]
It would be great to allow longer region names, because as far as I know, the limit is 16 characters.
Also, is it possible to include higher priority region name to the lower priority one?
For example: I have a region "City", and there are two lands: "Land1" and "Land2". Then the full names of the lands would be "City.Land1" and "City.Land2".

Thanks.

**Comment by aurel85** [comment]
For the first part : #615 

If the second part of the suggestion is accepted, please put it as optional because for my server this would not interest me.

**Comment by FabioZumbi12** [comment]
I think not viable too many rework just to show regions names based on priority, btw thanks for suggestion.
