### ISSUE TITLE
[BUG] Small detail with the spawn-animals flag

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#658]
Hi,

The bee head is in x2 :  
![Capture](https://user-images.githubusercontent.com/24486147/84833464-9f40d880-b02f-11ea-9047-a189916ca401.PNG)

I use the last version of this plugin (341) and Paper 1.15.2

**Comment by FabioZumbi12** [comment]
This is not an issue, its intentional to know what flag is true or false as heads don't glow like enchanted items!

**Comment by aurel85** [comment]
Ahhhhhhh, ok !
