### ISSUE TITLE
Player can use X-RAY with Pistons and Composter

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#665]
We saw how this works here 
https://www.youtube.com/watch?v=MtCMu5XiHEs
and can agree that this glitch is working

To prevent this we thought about blocking pistons in the wanted worlds.
Problem: If we set any block to the place  blacklist (what would mean all other blocks can be placed) then the block is blocked but then players cant get Lava and water with the bucket.

We see two kinds of solutions here:

Way one: Redprotect fixes it that when building is false in global and some item are on the place blacklist that players can take Lava and Water with buckets...

Way two: A List in the config to disbale pistons and sticky pistons in choosen worlds.

Way tree: A list in config where we can setup disable pistons workage in defined worlds

**Comment by FabioZumbi12** [comment]
You can use the plugin "IllegalStacking" where already fix some of the Minecraft bugs, dupes and more (including this), or wait Minecraft fix this at all.

**Comment by JustBooom** [comment]
> You can use the plugin "IllegalStacking" where already fix some of the Minecraft bugs, dupes and more (including this), or wait Minecraft fix this at all.

"IllegalStacking"  fixes glitch with composter and trapdoor, but composter + piston still works, and i havent found plugin to fix this
