### ISSUE TITLE
Allow Non-member tp Flag (Revisited)

### ISSUE THREAD

**Issue by SirReal314** [FabioZumbi12/RedProtect#667]
I understand that this has been suggested before, but not all servers allow portals to be made. Even if the tp portal were made, the nonmembers would still need access to the claim that had the entrance portal—defeating the purpose of allowing nonmembers to tp without adding them all individually.

**Comment by FabioZumbi12** [comment]
The `portal` flag already allow non member to tp from/tp regions. Use this flag instead.
