### ISSUE TITLE
Killer Projektile[BUG] 

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#669]
When Killer Prokectile is turned on it takes the righ massive damge we set up.
But stops at 2 hearts. 
We wanne setup a Snowballarena but the snowballs do no damage anymore after the player reaches 2 hears health....
can this be changed? We want that the player also can die for the game.

When the player got hitted by the Killerball we see no animation like when you normaly  got hit with a snowball..

We are using the 7.2.2 build 360 together with the KillerProjectile addon.

**Comment by FabioZumbi12** [comment]
You is using percentage or direct damage on config?

**Comment by CloudeLecaw** [comment]
We are using the direkt dmg a value of 4

**Comment by FabioZumbi12** [comment]
I cant reproduce this here. The player always die. prob you have other plugin that deny player to die.

**Comment by CloudeLecaw** [comment]
Strengh, but ok, i will investigate more testing time and reopen the issue if i can reproduce this with just Redprotect and permissionsystem on a testserver.
