### ISSUE TITLE
[BUG] Data too long for Mysql "tppoint"

### ISSUE THREAD

**Issue by Akr-on** [FabioZumbi12/RedProtect#670]
exception:  com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'tppoint' at row 1
Sometime tppoint is too long that it cannot save to mysql, size of mysql field "tppoint" is 20 when table created,
I solved it by modify  to 255

**Comment by FabioZumbi12** [comment]
Fixed on https://github.com/FabioZumbi12/RedProtect/commit/ef0a1171a02a90797fb08ad926f24be52e6b99ca
