### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Jorgegiral** [FabioZumbi12/RedProtect#671]
I have a problem, I am trying to give more limits to a player, but it does not work for me, I give it permission redprotect.limits.blocks.750 but it still has 200 which is the default, this permission is added with luckperms with the lp group command sold permission set redprotect.limits.blocks.750 true, sold is the group that would increase this limit.

I'm on a server, sponge forge, on 1.12.2
with Sponge 7.2.0 and RedProtect-7.6.4-b280-Universal

**Comment by FabioZumbi12** [comment]
For sponge, you need to add the same permissions on config.conf, on `permissions` path.

**Comment by Jorgegiral** [comment]
but, if I want, to put limits, for different groups, because I can't find that part in the config.

**Comment by FabioZumbi12** [comment]
You still need to give the permissions to your users, the permissions just to be declared on config to redprotect know about perm nodes.

Look for this:
```
# Declare here the permissions you want to use for your players and groups.
permissions-limits {
    blocks=[
        "redprotect.limits.blocks.8000"
    ]
    claims=[
        "redprotect.limits.claim.20"
    ]
}
```

**Comment by Jorgegiral** [comment]
But there is then I must change something, because what I did was configure here the initial limit:

     # The permission "redprotect.limits.blocks. <amount>" overrides this setting.
     limit-amount = 200

That is, so that the players had a limit of 200, and then create several ranges,
One of them had 750, but the user still has the same 200 limit blocks, and there is where you send me, if I change any value I find no effect, or, I have to add something different for each group.

**Comment by Jorgegiral** [comment]
because I thought that adding in luckperms the permission redprotect.limits.blocks.750 in true, for a corresponding group, then the user could already have that limit

**Comment by Jorgegiral** [comment]
A, it was like this:

# [Sponge Only] Declare here the permissions you want to use for your players and groups.
permissions-limits {
     blocks = [
         "redprotect.limits.blocks.500",
         "redprotect.limits.blocks.750"
     ]
     claims = [
         "redprotect.limits.claim.2",
         "redprotect.limits.claim.3"
     ]
}

In other words, for each group, I must place their corresponding permission here

**Comment by FabioZumbi12** [comment]
Exact, this is the point ;)
