### ISSUE TITLE
[Problema] Pixelmon

### ISSUE THREAD

**Issue by vinasxz** [FabioZumbi12/RedProtect#673]
Ola, 

Estou com um problema de spawn de pixelmon nas areas protegidas, coloquei para nao spawnar nada dentro das areas mas isso acaba por ferrar o breeding, como o servidor tem algumas pessoas desconhecidas preferimos proteger tudo, como eu consigo desviar desse problema? Sem ver o pokemon no daycare fica dificil saber se estao gostando do terreno, e tambem te forca a usar o teleport/fly sempre fora de casa.

Estou usando a versao do sponge/1.12.2

**Comment by FabioZumbi12** [comment]
Nao tem o que faezr pq o mod que tem que registrar os eventos corretamente, o plugin só obedece o que lhe é enviado. Então o plugin nao sabe distinguir o que eh um spawn de um breed. O certo eh vc criar um mundo só pra construirem e permitir so player criarem suas proteções e liberar o acesso a essas flags por conta deles.
