### ISSUE TITLE
[Pergunta] Acesso em region para quem tem certa permissão/grupo

### ISSUE THREAD

**Issue by RoinujNosde** [FabioZumbi12/RedProtect#674]
É possível dar acesso em uma region para quem tem uma certa permissão ou está em um grupo (vault)?
Ex.:
/region flag build allow <permission/group>

Procurei na wiki, porém não encontrei algo assim.

Isso seria para ter uma integração nesse estilo: https://github.com/RoinujNosde/SimpleClans/wiki/Giving-clan-members-access-to-GriefPrevention-lands

**Comment by FabioZumbi12** [comment]
Vc pode usar a permissão `redprotect.region-enter.(nomeDaRegion)`, e setar a flag `rp flag enter false`, assim so quem tem a perm consegue entrar. Mais info: https://github.com/FabioZumbi12/RedProtect/wiki/(05)-Region-Flags#admin-flags

**Comment by RoinujNosde** [comment]
O que tenho em mente é uma permissão custom.
Ex.: O SimpleClans dá a permissão group.TAG_DO_CLA, então players poderiam dar acesso a regions usando essa permissão.
