### ISSUE TITLE
[BUG] Players getting to spawn?

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#675]
Some players tolduse they getting teleported to spawn and they dont see the reson

The console tell us the following:

```
.... [18:18:58 INFO]: [RedProtect] Player Famous_Guy damaged by CUSTOM - Running command:
- Command: spawn Famous_Guy
```

papermc: 1.16.1  Build 115
Redprotect: RedProtect_7.7.2-Build362

**Comment by FabioZumbi12** [comment]
Look for `command-on-damage` on globalflags.conf and remove the `CUSTOM` damage from this list
