### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Mythrain** [FabioZumbi12/RedProtect#676]
You can dupe sign by just breaking fence under "error" sign. Create 2x2 fence and place one extra under one of signs to make rp give error , and then break fence under error sign to make it dupe.

**Comment by CloudeLecaw** [comment]
Error means no region is created. Redprotect does nothing until you place a new sign. The error is because your created region is to slow. This kind if duplicate bug would also apear with any sign and fences on your server.

**Comment by FabioZumbi12** [comment]
When you interact qith the error sign, it already disapear instead break and drop.
