### ISSUE TITLE
pls add  new weeping_vines and twisting_vines to can-grow flag

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#680]
We noticed the two new 1.16.1 vines are not able to control with the redprotect flag can-grow

in extansion to this old thread
https://github.com/FabioZumbi12/RedProtect/issues/283
where you allready added the normal vines. please also add the new
weeping_vines and twisting_vines

![Snag_b289bf](https://user-images.githubusercontent.com/12080017/88858338-2325dd00-d1f8-11ea-8df4-89dab5eac6b9.png)

**Comment by FabioZumbi12** [comment]
Added on latest dev build!
