### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by CAWBxMercy420** [FabioZumbi12/RedProtect#682]
**Describe the bug**
The bug is as follows. When I try to type /rp list on my server it will not list the regions of that player but instead shows this:
-------------------------------------------------------------------
[RedProtect] Regions created by: (player name)
-----
World havenmc[1-1/1]:

HavenMC is my world name, it is showing the world name instead of the region names. Please help.

**To Reproduce**
1. Type /rp list
2. For me it shows:
-------------------------------------------------------------------
[RedProtect] Regions created by: (player name)
-----
World havenmc[1-1/1]:
3. It should show my region names but instead it shows the world name and those numbers, if I create multiple regions the numbers change at the end, for example if i had to regions it would show:
-------------------------------------------------------------------
[RedProtect] Regions created by: (player name)
-----
World havenmc[1-2/2]:

**Server and plugins versions (please complete the following information):**
 - Server: paper_1.16.1.jar
 - Plugin Version: RedProtect-7.6.6-b307-Universal.jar
 - Java Version: Java 8

**Additional context**
Is there a way to fix this issue?

**Comment by FabioZumbi12** [comment]
You version is too old. The spigot and dev builds are on 7.7.2! Please, download the latest version and try again: http://host.areaz12server.net.br:8081/job/RedProtect/
