### ISSUE TITLE
[BUG] Private sign problem

### ISSUE THREAD

**Issue by NanoxGG** [FabioZumbi12/RedProtect#683]
**Describe the bug**
A person who has permissions on a RP is able to put another sign to double private a chest.

**Screenshots and LOGs**
![2020-08-15_19 41 10](https://user-images.githubusercontent.com/68035959/90324708-66d65180-df2f-11ea-9eb8-dacad4ef3cb6.png)

**Server and plugins versions (please complete the following information):**
 - Server: PaperSpigot 1.16.1 (dev 115)
 - Plugin Version: RP-7.7.2-b362-Universal 
 - Java Version: Java 1.8

**Comment by NanoxGG** [comment]
**More details:**
To make this happens, apperantly it needs a redstone activator, such a redstone torch.

**Comment by CloudeLecaw** [comment]
Hm you may noticea one of the signs is a fake?
On it you see PRivate on the other there is private.. Look in your config to see which one of them is the fake one. Well the fake one will have no effect
