### ISSUE TITLE
[BUG] Spawning flag

### ISSUE THREAD

**Issue by Melvout** [FabioZumbi12/RedProtect#685]
Hi !

Here's a problem with the mob-spawning flag :

If I set to **"true"** only one value like this

![image](https://user-images.githubusercontent.com/39627267/90822607-04b58c00-e335-11ea-86d4-4f325f32e5d2.png)

Then I leave the GUI and come back on it, I can't set this value to **"false"** by cliking on it. If I do that and leave the GUI the value stay on **"true"**

The only way to reset the value is to use the "redstone block" button.

( Same problem for both passive and aggressive animals )

---

The issue seems to be on this file : https://github.com/FabioZumbi12/RedProtect/blob/master/RedProtect-Spigot/src/main/java/br/net/fabiozumbi12/RedProtect/Bukkit/guis/MobFlagGui.java#L133

On the condition at the line 134, if the string is empty you assign the old value.

---

It is not a huge problem but it seems not to work correctly.

Thanks for your help !

**Comment by CloudeLecaw** [comment]
This bug ia fixed allready. Could you close it?

**Comment by Melvout** [comment]
I am pretty sure that the bug is still relevant. Although if Fabio thinks that the bug is fixed he can close the issue by himself.

**Comment by CloudeLecaw** [comment]
Have you never tried with latest version from jenkins?

**Comment by Melvout** [comment]
Yes we're using the latest version of RedProtect.

Do you correctly understand the issue that I'm talking about ? As I said it's not a big deal but it's not working the way it should be.

**Comment by CloudeLecaw** [comment]
I tried it the exact way u wrote and it works fine without any problem here
