### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Stevenjose25** [FabioZumbi12/RedProtect#689]
Hello friend, install the plugin on a server that I have with some friends and it does not work correctly, the game detects it and some functions are correct, but most do not, for example the pvp and private chests do not work, I play in version 1.8 with it redprotect 7.6.2 b 245

**Comment by CloudeLecaw** [comment]
May u nitices that we had a lot of Version passes allready we are on Version 7.7.2 to ols try the latest dev build
