### ISSUE TITLE
Extending Claims  Feature request

### ISSUE THREAD

**Issue by Stuart74** [FabioZumbi12/RedProtect#69]
I do realise there is a functon that an admin can extend claims using a certain material but there is none for the normal members. The biggest complaint i get is it is too much work to redo their region when their base expands. 

Would be nice to have a expand feature where a player can use say a golden axe or shovel to expand the claim themselves without requiring an admin to do it.

**Comment by FabioZumbi12** [comment]
I changed the permissions to allow server owners to give "redprotect.own.redefine" to allow players to mark first and second points (with wand tool) and use /rp redefine <region-name>

I didnt tested, and only Leaders can redefine the regions:
https://github.com/FabioZumbi12/RedProtect/blob/master/release/RedProtect-6.5.9-b694.jar?raw=true

**Comment by Stuart74** [comment]
Tested and works perfectly thank you

**Comment by FabioZumbi12** [comment]
Added!
