### ISSUE TITLE
[BUG] Horses can destroy fields

### ISSUE THREAD

**Issue by DakirDev** [FabioZumbi12/RedProtect#692]
**Describe the bug**
If you jump with a horse on a field from a foreign claim the seed is destroyed.

**Server and plugins versions (please complete the following information):**
 - Server: 1.14.4-b243 Paper
 - Plugin Version: RedProtect-7.7.2-b376-Universal.jar
 - Java Version: Java 1.8

**Comment by Bartek200219** [comment]
I have the same problem https://gofile.io/d/30dH3r
