### ISSUE TITLE
[BUG on sponge server] command problem

### ISSUE THREAD

**Issue by Chazzie** [FabioZumbi12/RedProtect#693]
hello
when i do "/rp setminy" or "/rp setmaxy" then the help pages is showed up and the command itself does nothing...
im trying to make the area from MinY 11 to MaxY 67... but even after changing it in the world.conf data file it stays on MaxY 255 and MinY 0... i didnt do "/rp expand-vert" when creating that area... so i have no idea what is causing this problem.

the plugin version is: RedProtect-7.6.4-b280-Universal.jar

**Comment by FabioZumbi12** [comment]
Try the dev build (link available on header of this page when openning the issue :/ )We are on 7.7.2 and probably this is already fixed.
