### ISSUE TITLE
EntityDamageByBlockEvent

### ISSUE THREAD

**Issue by Mrcoco29** [FabioZumbi12/RedProtect#7]
Hey, when I start the plugin, I get this  : 

29.10 09:42:33 [Server] INFO ... 28 more
29.10 09:42:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:33 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
29.10 09:42:33 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
29.10 09:42:33 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
29.10 09:42:33 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
29.10 09:42:33 [Server] INFO at br.net.fabiozumbi12.RedProtect.RPEntityListener.onEntityDamage(RPEntityListener.java:93) ~[?:?]
29.10 09:42:33 [Multicraft] Skipped 179 lines due to rate limit (30/s)
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.EntityZombie.t_(EntityZombie.java:221) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.EntityMonster.t_(EntityMonster.java:24) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.java:193) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1447) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.Entity.t_(Entity.java:246) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.EntityInsentient.K(EntityInsentient.java:149) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.K(EntityLiving.java:169) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.Entity.K(Entity.java:321) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.Entity.burnFromLava(Entity.java:343) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.EntityZombie.damageEntity(EntityZombie.java:167) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:733) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1101) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:584) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:473) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:86) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[OpenMod-Prov2.jar:git-Spigot-fdc1440-53fac9f]
29.10 09:42:32 [Server] INFO org.bukkit.event.EventException
29.10 09:42:32 [Server] ERROR Could not pass event EntityDamageByBlockEvent to RedProtect v5.9.0

**Comment by Mrcoco29** [comment]
And the MySQL is not working : 

29.10 11:36:27 [Server] WARN com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user user'@'%' to database 'dbname_world'

User it's ok, dbname is okey but why the world is here ?

**Comment by Mrcoco29** [comment]
It seems the problem is not solved even with the last update :/

**Comment by FabioZumbi12** [comment]
Solved?
