### ISSUE TITLE
Redprotect ListGUI

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#700]
could you add a chest GUI for the /rp list

Problem we got: we allow players to use /rp list in one world.
Its printet out the chat and they can teleport to a region.

Now they enter a region where they are not allowed to teleport..
they scroll in chat to the old /rp list and click on the names...and get teleportet...

to prevent this we would ne a chest GUI where player see their zones and can TP to when they click it.
Then after TP the chestGUI would be closed. and if the target is in a an other world then you can negate the permission for the chestGUI there.

This would bevent the cheating from the chatlist gui.
 because player can teleport allways when they have option to do /rp list

**Comment by FabioZumbi12** [comment]
I think is not a feature to be added, as you can setup the cooldown to teleport, or remove the permissions to teleport.
