### ISSUE TITLE
Old permission format reference

### ISSUE THREAD

**Issue by CanusLupus** [FabioZumbi12/RedProtect#701]
Hi,

I am operating 2 1.7.10 Thermos server at the moment which are using RedProtect. Both are running the
the suggested version 7.5.6 and i thought i have set all permission and limits correctly till i get complains 
from players that they have not the right claim limits fitting to there ranks. A short look on the change logs
of the versions after 7.5.6 told me that with version 7.6.0 the permissions for commands and limit"s" have 
changed. Unfortunately the wiki reflects only the new version/format of the permissions. Maybe, when 
possible, it would be a good idea to add a small reference to the old format in to the wiki for all which still
operate server with older modpacks.

Something like:

_Example:_
- _redprotect.limits.blocks.10000_
- _redprotect.limits.claim.200_

_For 7.5.6 (KCauldron/Thermos) use permission below_
- _redprotect.limit.blocks.10000_
- _redprotect.limit.claim.200_

Took me a bit to find the correct permission by searching the change logs on github between Mar 27. and May 5. 2019.

Thanks for the good work/plugin and i hope this will help others with the same problem.

**Comment by FabioZumbi12** [comment]
You can see the plugin.yml to get permissions reference. I think i have added a vip permission group with blocks and claims example perms on that version.

**Comment by CanusLupus** [comment]
You are right. I totally forgot about the plugin.yml in the jar file itself i used the wiki for the initial setup and the permission references.

Looked right now and yes its inside.

**Comment by CloudeLecaw** [comment]
but some permissions are not found in theplugin.yml even they are may sometimes important

example: the flag bypass permission  _**redprotect.flag.bypass.(flagname)**_

**Comment by CloudeLecaw** [comment]
So this can be closed?
