### ISSUE TITLE
[BUG] No claim greeting with an entity

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#703]
Hi !

Whenever you are on an entity ( minecart, boat, horse, pig and pet from other plugin ) the welcoming message when entering a claim is not displayed in the chat.

I'm saying that here because I think it is related to this issue.

I use the last version of this plugin and Paper 1.16.3.

Thanks.

**Comment by FabioZumbi12** [comment]
Its caused by server wont send the event... i've tryed to fix this but cant, as a server limitation :/
