### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Qkzoh** [FabioZumbi12/RedProtect#705]
Hi. There is a bugg. Players can steal player_heads, armorstands, itemframes from other players protections. 

I'm running Paper-1.16.3-b253 with latest dev build RedProtect #380

The thing is that you can place water/lava using your second hand even if you are non-member of the protection. 

![image](https://user-images.githubusercontent.com/67622253/97836800-d13f9800-1cbb-11eb-8cc7-3b25d5fe4447.png)
If you put water on farthest pixel block you can break heads/armorstands/itemframes, so that way players can easily steal items from others players protections

Players can also generate stone and obsidian using their second hand by fast placing water and lava.

**Comment by FabioZumbi12** [comment]
I cant reproduce this on my tests. Also check for errors on console.

**Comment by Bartek200219** [comment]
> I cant reproduce this on my tests. Also check for errors on console.

Place item frame on chest and try with shift
