### ISSUE TITLE
[BUG] API event EnterExitRegionEvent bug

### ISSUE THREAD

**Issue by cool9850311** [FabioZumbi12/RedProtect#708]
take the stair
stand on shulkerbox and open it
ride on anything
those 3 things will call the api event EnterExitRegionEvent
even when player still in the region

**Comment by FabioZumbi12** [comment]
No versions :/ 
Btw this is caused by server events sending wrong info to plugins. Is not redprotect problems.

**Comment by cool9850311** [comment]
1.16.4 papermc
btw i rewrote the event in my plugin via redprotect api
and it worked perfectly on the same server 
so i don’t think it is server’s problem?
