### ISSUE TITLE
Actionbar in enter, exit and welcome messages

### ISSUE THREAD

**Issue by Kjettinge** [FabioZumbi12/RedProtect#709]
although it does not say "ACTIONBAR" is available, it does work, except it does not show ENTER messages, only WELCOME and EXIT messages shows
```
notify {
    # Available: "BOSSBAR", "OFF" or "CHAT"
    region-enter-mode=ACTIONBAR
    # Notify on exit region? (in most cases will be wilderness)
    region-exit=true
    # Available: "BOSSBAR", "OFF" or "CHAT"
    welcome-mode=ACTIONBAR
}
```

**Comment by CloudeLecaw** [comment]
ACTIONBAR is not supported have u written the note aboive? ;)
    # Available: "BOSSBAR", "OFF" or "CHAT"
