### ISSUE TITLE
some errors with new function

### ISSUE THREAD

**Issue by netherarts** [FabioZumbi12/RedProtect#71]
thanks for your uuid update!!!! you are good developer!!

there's some problem with new uuid function.

i got those errors.

and it brings old nickname not latest one.

http://pastebin.com/yBxTcuSQ

**Comment by FabioZumbi12** [comment]
I found the problem, now is fixed: https://github.com/FabioZumbi12/RedProtect/blob/master/release/RedProtect-6.5.10-b708.jar?raw=true

**Comment by netherarts** [comment]
@FabioZumbi12 perfectly works for now! thanks for your support. but it still brings old nickname. can you fix it?

**Comment by FabioZumbi12** [comment]
Old nickname is returning the UUIDs again (not converting) right? The conversion will be done only if the UUID is present on Mojang Servers. On my tests, i have added a lot of uuids as leaders of my regions, and then change the server mode to offline mode. The legacy uuids has converted, only not legacy still as UUIDs.

**Comment by netherarts** [comment]
i've changed my nickname hold_mybeer to dubu in mojang profile. so when i used /rp info it displays hold_mybeer. that's what i mean.

**Comment by FabioZumbi12** [comment]
Thats ok, now i get what you mean and fixed. Its a little setting on UUID Fetcher. I tested with your UUID/Name and worked: http://prntscr.com/bbqhy3

Download from here: https://github.com/FabioZumbi12/RedProtect/blob/master/release/RedProtect-6.5.10-b710.jar?raw=true
