### ISSUE TITLE
[Problema] RedProtect com IndustrialForegoing [Console Flood]

### ISSUE THREAD

**Issue by TheMartinfer22** [FabioZumbi12/RedProtect#710]
Olá, achei um problema que floda o console, não sei se pode ser grave porém, ocorre com máquinas do IndustrialForegoing, onde por exemplo, se é colocado uma máquina "Block Placer ou Block Breaker" e a determinada função é reproduzida gera um erro imenso que fica por minutos!

Reprodução:

1. Vá em qualquer área protegida/desprotegida.
2. Pegue um BlockPlacer do IndustrialForegoing.
3. Dê energia a ele e coloque algum bloco dentro para o mesmo colocar.
4. O erro é mostrado no console em seguida: https://prnt.sc/vkb96m

O erro não é super grave porém, atrapalha na visualização do console limpo mas não vi algumas possíveis falhas graves que pode gerar, mas estou aqui reportando!

Outra print além da reprodução, na qual pouca diferença.
https://prnt.sc/vkbebk

Versão do Minecraft: 1.12.2
Plataforma de servidor: Mohist- Última release Build 104
Versão do RedProtect: Build 380

Plugins utilizados: Vault, Luckperms, RedProtect
Mods utilizados: Mekanism(EnergyCube), IndustrialForegoing

**Comment by FabioZumbi12** [comment]
Então, infelizmente é algum problema com o mod não estar enviando alguma informação pro server e consequentemente pros plugins.
