### ISSUE TITLE
[BUG] Considerable performance issue - PlayerMoveEvent

### ISSUE THREAD

**Issue by antisoma** [FabioZumbi12/RedProtect#711]
**Describe the bug**
RedProtect causes considerable server lag - timings report PlayerMoveEvent as being 153% of the tick with 5 players on a good dedicated box.

May be caused by player flying over claims.  disable-onPlayerMoveEvent-handler is set true in config.conf.  Problem persists.

**Screenshot**
Timings png - https://blocklife.org/other/rp.png

**Server and plugins versions (please complete the following information):**
 - Server: Paper 282
 - Plugin Version: RedProtect-7.7.2-b380-Universal
 - Java Version: 
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

**Comment by FabioZumbi12** [comment]
This is normal as an antigrief plugin! I can't do nothing related with performance. What i can say to you do is reduce this option to 0 or 1:

```
    # Deny player to build/break blocks near x block of a region.
    deny-build-near=2
```

**Comment by antisoma** [comment]
I don't think it is normal - either with your plugin or other antigrief.

I've been running your plugin for more than a year with no major issues.  So it's new.  Also, why is there still a PlayerMoveEvent issue when that is disabled in the config?
