### ISSUE TITLE
[Bug] Pixelmon, duplication of clear bell and Tidal bell

### ISSUE THREAD

**Issue by baptistedavid** [FabioZumbi12/RedProtect#712]
I have a bug with Red Protect and the mods Pixelmon. 
In fact, if a player try to destroy the block above the item tidal bell, or clear bell,  on a claim that isn't his claim, the item will be duplicate.

**Comment by baptistedavid** [comment]
In a normal time (so without claim), if you destroy the block, the bell will be destroyed too and the bell will drop at the ground
But, in a claim, the block cant be destroy, so the bell will not be destroyed too, and the bell will drop at the ground
And it's really problematic because this item is used to spawn Lugia  ( a legendary Pokemon)
It's on Sponge by the way
And i'm in the version7.6.7
![image](https://user-images.githubusercontent.com/36503085/99882100-5dd7d900-2c1e-11eb-980a-517e0d88a83e.png)

**Comment by FabioZumbi12** [comment]
Duplication bugs is not related with plugin (in general), but with server/minecraft/mods bugs, as plugins just cancel server events to prevent grief. Maybe the mod is not listening for the events correctly.
