### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by EvanDrakes** [FabioZumbi12/RedProtect#714]
I've been wanting to know, in the pixelmon mod how do I add the pixelmon blocks into the plugins so I can give flag perms to use those blocks in the protected area's, things like npc's pc's and healer. I can't find any where on how to do it and I can't figure it out.

**Comment by FabioZumbi12** [comment]
The flag is `/rp flag allow-mod true` to allow interact with mod itens

**Comment by EvanDrakes** [comment]
I tried to put in into the console and it didn't work then I went and looked in the config file to find it but couldn't, where can I edit that?

**Comment by FabioZumbi12** [comment]
Use this command inside a created region to allow players to interact with healers, PC and etc...

**Comment by EvanDrakes** [comment]
ahh yeah thank you, I realized whatever I did in the config bugged out the plugin and removed it, I got it all working now thanks so much.
