### ISSUE TITLE
[Problema] Máquinas IndsutrialForegoing e ExtraUtilities no terreno com função Breaker

### ISSUE THREAD

**Issue by TheMartinfer22** [FabioZumbi12/RedProtect#715]
Olá boa tarde, eu novamente para atucanar em issue mas vou tomar atitude e reportar, os jogadores estão reportando uma coisa que foi prevista no plugin GriefDefender também, é sobre o funcionamento de máquinas como (Mechanical Miner, Block Breaker) todas na função de quebrar aparentemente o fake player das mesmas, somente a função de placer está funcionando.

Pode ser a mesma causa do #710 reproduzir tal erro por incompatível, se você puder responder um mod funcional para a função de quebrar blocos vou agradecer!

Etapas para reproduzir o comportamento:
1. Fazer um terreno protegido.
2. Colocar um block breaker ( Extra Utilities, IndustrialForegoing)
3. Não reproduzirá a ação de quebrar blocos.

Versão do Minecraft: 1.12.2
Plataforma de servidor: Mohist- Última release Build 104
Versão do RedProtect: Build 380

Plugins utilizados: Vault, Luckperms, RedProtect
Mods utilizados: Mekanism(EnergyCube), IndustrialForegoing, ExtraUtilities2

**Comment by TheMartinfer22** [comment]
Atualizando, o Plant Sower que têm a função de BlockPlacer está com o mesmo problema (IndustrialForegoing)

**Comment by FabioZumbi12** [comment]
Infelizmente depende dos Modders fazer com que o MOD deles acione eventos do minecraft/forge, para assim o Sponge repassar esses eventos pros plugins. Não ha nada que eu possa fazer como plugin :/
