### ISSUE TITLE
[BUG] not so much a bug, but i cant access discord. How do i change my wand from the glass bottle to something else 1.16 version of minecraft

### ISSUE THREAD

**Issue by Jimmay1** [FabioZumbi12/RedProtect#718]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://host.areaz12server.net.br:8081/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots and LOGs**
If applicable, add screenshots to help explain your problem. Upload your logs to https://gist.github.com/

**Server and plugins versions (please complete the following information):**
 - Server: [e.g. Sponge 1.12.2, Spigot 1.13.2]
 - Plugin Version: [e.g. RedProtect-7.5.6-b151-Universal.jar]
 - Java Version: [e.g. Java 1.8]

**Additional context**

**Comment by JaayTheLoft** [comment]
There is a section in your **config.conf** file to change the **/rp wand** item. By default, it should look like this:

```
wands {
    # Its used to define regions and for players to claim regions.
    adminWandID="GLASS_BOTTLE"
    # Checks the clicked block with this on hand to see if there's a region on that block.
    infoWandID=PAPER
}
```

You can change the materials there, and then reload the plugin to activate the changes.
