### ISSUE TITLE
/rp flag problem.

### ISSUE THREAD

**Issue by netherarts** [FabioZumbi12/RedProtect#72]
there's problem with flag gui. when i click the item it disappears.

**Comment by FabioZumbi12** [comment]
I get this on my server too... investigating this too...

**Comment by netherarts** [comment]
@FabioZumbi12 Thanks for your quick response. In my case.. if the area name is too long or have special characters in their name, gui icons are disappear when they clicked.

**Comment by FabioZumbi12** [comment]
Fixed, download the latest version.
