### ISSUE TITLE
[BUG] Alias with /rp wand & /rp welcome

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#722]
Hi, we noticed that there is a conflict between two commands wich have the same alias. 
 /rp wand and /rp welcome  have the same alias in the /rp help menu. This alias is /rp w  and  it seem to be  working only for the /rp wand command. 
Would it be possible to have a dffirent alias for for one of rhose commands ? (/rp wc for instance, or /rp wa) 

I use the last version of this plugin (7.7.2 b384) and Paper 1.16.4.

Thanks in advance.

**Comment by FabioZumbi12** [comment]
Change this in your language file. Its already fixed on default lang files to wel and w.
