### ISSUE TITLE
Quebrar cana de açúcar fora da RP

### ISSUE THREAD

**Issue by comonier** [FabioZumbi12/RedProtect#723]
Paper 259
RP 384
Java 15
Problema: os jogadores não conseguem quebrar somente a cana de açúcar fora da RP.

Teste realizado: desliguei o servidor. Removi o plugin do RP e liguei o servidor sem o plugin, e foi possível quebrar a caba de açúcar. Porém como esse problema aparentemente só aconteceu ineditamente comigo, suspeito que possa ser algum outro plugin em condlito com o redprotect. Ou o fato de eu já usar java 15.

**Comment by FabioZumbi12** [comment]
Pode ser outro plugin. Não consegui reproduzir o problema tanto colocando quanto quebrando.
