### ISSUE TITLE
rp redefine own (player)  [Sugestão] 

### ISSUE THREAD

**Issue by comonier** [FabioZumbi12/RedProtect#724]
Você uma vez criou a permissão redefine:

Referência: https://github.com/FabioZumbi12/RedProtect/issues/69
Referência2: https://www.spigotmc.org/resources/redprotect-anti-grief-server-protection-region-management-1-7-1-16.15841/update?update=94505

a permissão seria **redprotect.own.redefine** que vc mesmo criou conforme pode ver no link acima...

Depois da atualização de permissões onde foi adicionando command nas permissões
eu não consegui encontrar no plugin.yml a permissão para o jogador usar o comadno /rp redefine
para redimencionar o tamanho da própria rp com a wand.

Nova permissão apenas para admin (redimencionar qualquer rp)
**redprotect.command.admin.redefine**

ela não existe dentro do plugin.yml dentro do jar do rp da versão RedProtect-7.7.2-b384-Universal:

name: RedProtect
main: br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect
version: 7.7.2
api-version: 1.13

Eu lembro que já havia comentado isso contigo em uma versão muito antiga logo que vc criou o config.conf e mudou as permissões ter esquecido de re-adicionar o redefine.command.own.redefine (ou redefine.own) pro player. E vc me deu uma solução provisória na época (do mine 1.14.4) mas pelo que parece voltou a esquecer (ou optou por não liberar) de adicionar essa permissão nas releases futuras...

A Sugestão é que volte ela, obrigado.

**Comment by FabioZumbi12** [comment]
A perm é `redprotect.command.redefine` porem não é dada por padrão não é normal permitir isso aos players, visto que isso libera o wand tool automaticamente.

Como referencia, na pagina na wiki tem um exemplo dizendo que comandos normais são sempre **redprotect.command. <nome do comando>**
https://github.com/FabioZumbi12/RedProtect/wiki/Permissions
