### ISSUE TITLE
Admin Infowand

### ISSUE THREAD

**Issue by Mawobi** [FabioZumbi12/RedProtect#726]
**Describe the bug**
If normal players have:
        - redprotect.command.info
        - redprotect.command.admin.info
        - redprotect.command.infowand
        - redprotect.command.admin.infowand
the Infowand works on regions, where they arent added, but also gives the errormessage for no permission to interact.

**Expected behavior**
No Errormessage for interaction.

**Server and plugins versions (please complete the following information):**
 - Server: Spigot 1.16.4
 - Plugin Version: RedProtect-7.7.2-b384-Universal.jar
 - Java Version: Java 1.8

Greetings
~Mawobi

**Comment by FabioZumbi12** [comment]
Its because `- redprotect.command.admin.infowand`, and the message its natural for right click.
