### ISSUE TITLE
[BUG] CarryOn Mod Block Duplication

### ISSUE THREAD

**Issue by MCUmbrella** [FabioZumbi12/RedProtect#727]
**Describe the bug**
A bug that allows a player to steal things in other players' region without breaking any block.<br>Carrying blocks in RedProtect's region(denies block break) will empty their storage and the block will also appear in your hand with the things in it.

**To Reproduce**
1. Enter a region that denies player to break block
2. Carry a block use the mod
3. See error

**Expected behavior**
Block the operation

**Screenshots and LOGs**
There is a video to show the bug but it's too large so I uploaded it to YouTube: 
https://www.youtube.com/watch?v=7SLP5TY4y8g

**Server and plugins versions (please complete the following information):**
 - Server: Sponge 1.12.2
 - Plugin Version: 7.7.2-b384
 - Java Version: 1.8

**Additional context**
null

**Comment by FabioZumbi12** [comment]
The mod need to send all eventos to forge first, and then, Sponge will send to plugins. I cant do nothing on plugin side :/
