### ISSUE TITLE
Crash Server

### ISSUE THREAD

**Issue by needwalter** [FabioZumbi12/RedProtect#73]
Hi , i'm the founder of a french minecraft server , so as you guess i'm french!
I would like to lell you that i encounter a recent probleme with the plugin...
I update my serveur( Spigot 1.9.4) 72H  ago with no probleme and the last version of the plugin ( 6.5.12) But since 20 PM my serveur refuse to start , during the initialysing.
I try many times and it finally restart with this log : pastebin.com/mMCSxksr 
I would like to know how i can solve my problems and if you can give me advice to do it !

I moove from Mychunk To redprotect since i discover your plugin, It's a very usefull ressources for the minecraft community and now i can't administrate correctly my server without it !
Thanks for your response and for what you do for our community.

Walter.

**Comment by FabioZumbi12** [comment]
The name of player is with "[]" on name, not allowing RedProtect to convert from name to UUID.

You is running in online mode right?

**Comment by FabioZumbi12** [comment]
Try this version: https://github.com/FabioZumbi12/RedProtect/blob/master/release/RedProtect-6.5.13-b718.jar?raw=true

I added a method to remove the "[]" from player names.

**Comment by needwalter** [comment]
Thanks you for you quick answer and for the version you recommend me !
It works perfectly fine !
You done a great job fabio, keep it up !

walt'

**Comment by FabioZumbi12** [comment]
Good to see working ^^
