### ISSUE TITLE
[BUG] Claim and block limit can be bypassed by adding leaders on creation with sign

### ISSUE THREAD

**Issue by Olexorus** [FabioZumbi12/RedProtect#730]
**Description**
By using two accounts, it is possible to bypass the claim and block limit.

**To Reproduce**
1. have two accounts
2. create claim on account A and add account B as leader by putting them on the 3rd/4th line of the sign
3. remove account A which means it can create a new one
4. continue at step 2

**Expected behavior**
RP should check the block and claim limit for all leaders, not just the person creating the claim. This is already done when using /addleader, so it should be fairly easy to add here too (and imo it's pretty important).

**Server and plugins versions:**
 - Server: Tuinity 1.16.4 (git-Tuinity-"f06591a)
 - Plugin Version: RedProtect-7.7.2-b357-Universal.jar
 - Java Version: openjdk version "11.0.9.1" 2020-11-04

**Additional context**
I noticed that it seems to be possible to have more than one leader. How are claim limits calculated then? Do they count for everyone? Wouldn't it make more sense to only allow one leader per claim?

**Comment by Olexorus** [comment]
Hm, I just checked the code and saw that there already seems to be a check to prevent it? Maybe I misunderstood something, I'll ask the person who reported it and make sure that this is actually true...

**Comment by Olexorus** [comment]
Ok yeah they added leaders by putting them on the sign when creating a claim and not by using /addleader, I edited the main post accordingly.

**Comment by Bartek200219** [comment]
I have the same issue except that players are adding other people as leader by command.
