### ISSUE TITLE
Multiverse-Core. 

### ISSUE THREAD

**Issue by WolfyRed** [FabioZumbi12/RedProtect#731]
**Describe the bug**
Multiverse-Core "/mv create world", with RedProtect plugin.

**To Reproduce**
1. /mv create WORLD world_type
2. Wait for it to say "Creating world..."
3. Go to the server console, and wait for it to spam THIS!!!
4. Yeah, the server crashes mid-way the world generation.

**Expected behavior**
RedProtect to protect my new worlds! :'(

**Screenshots and LOGs**
![image](https://user-images.githubusercontent.com/66114400/104120892-5cff2180-5308-11eb-8f6c-e2757f46d7e4.png)

**Server and plugins versions (please complete the following information):**
 - Server: Spigot 1.11
 - Plugin Version: RedProtect-7.7.2-b357-Universal.jar
 - Java Version: Java 1.8. Yes.

**Additional context**
RedProtect has given me the best experience, out of all the WorldProtect plugins.
So I would like to continue using it, whilst using my Server-side world changing plugin (Multiverse-Core plugin).

**Comment by WolfyRed** [comment]
[Link to the same issue, with more context](https://github.com/Multiverse/Multiverse-Core/issues/2530#issue-782786213)

**Comment by CloudeLecaw** [comment]
Hm spigot 1.11
The Version 1.11 is not really Supported by most.
Also your Redprotect Version is a bit out of date
The latest Redprotect Version is 384
http://host.areaz12server.net.br:8081/job/RedProtect/

**Comment by FabioZumbi12** [comment]
Already asked on https://github.com/Multiverse/Multiverse-Core/issues/2530#issue-782786213 and the same for RedProtect. Btw, try with latest versions of redprotect.
