### ISSUE TITLE
[BUG] No impact of flag "allow-potions"

### ISSUE THREAD

**Issue by Mawobi** [FabioZumbi12/RedProtect#740]
**Describe the bug**
There is a "use-potions" and a "allow-effects" Flag.
But what does the flag "allow-potions" do? Tested it and noticed no impact of this flag.

**Server and plugins versions (please complete the following information):**
Server: Spigot 1.16.5
Plugin Version: RedProtect-7.7.2-b384-Universal.jar
Java Version: Java 1.8

Greetings
~Mawobi

**Comment by FabioZumbi12** [comment]
Working here as is, check for errors in your server.
![image](https://user-images.githubusercontent.com/5833818/231362524-6aacc12a-6d50-4c5c-95cb-18488e02cc99.png)
