### ISSUE TITLE
[BUG] Mob Spawning in Nether even if all mobs are disabled (via region flag)

### ISSUE THREAD

**Issue by FruitLabCBR** [FabioZumbi12/RedProtect#741]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://host.areaz12server.net.br:8081/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

**Describe the bug**
I currently have a player with a bigger region in the nether.. he disallowed ALL Mobs via the Flags.. but there are still mobs spawning like Strider, Hoglins, Magma Cubes and Ghasts
Those Mobs are not even in the GUI of the RP mob Gui

**To Reproduce**
1. Go to nether
2. Click on disable all mobs
3. See error

**Expected behavior**
all mobs diabled in the rp region

**Server and plugins versions (please complete the following information):**
Server Version: 1.16.5
Java: 11
Plugin Version: RedProtect-7.7.2-b385-Universal

**Comment by TheOpalium** [comment]
I am encountering a similar problem in my v1.12.2 SpongeForge server (with Java 8). RedProtect 7.6.7 from Ore.
I claimed the spawn area using a RP region, disabled all mob spawn flags, but they keep spawning as if nothing was done.

**Comment by FruitLabCBR** [comment]
push

**Comment by FruitLabCBR** [comment]
push

**Comment by CloudeLecaw** [comment]
They are! You need to choose them innthe Gui under Animals
