### ISSUE TITLE
[BUG] Fishing npc

### ISSUE THREAD

**Issue by MikaCookies** [FabioZumbi12/RedProtect#743]
**Describe the bug**
When I protect an area as an administrator, users can use the minecraft pole to "fish" the NPCs and move them around.
How can i fix it? Is in 1.12.2 Pixelmon server

- Plugin Version: [e.g. RedProtect-773-b393

**Comment by FabioZumbi12** [comment]
I think Sponge dont let to deny this feature, but additionally i stopped to develop to sponge, i just fixing some bugs, and i dont remeber a way to deny this. Sorry :/

**Comment by MikaCookies** [comment]
Oh no :(  There is no way that users cannot use the rod in a protected area?

**Comment by FabioZumbi12** [comment]
Try to add a flag to disable damage. Unfortunately it's not easy to work with sponge, so I don't develop for him anymore.

**Comment by MikaCookies** [comment]
The damage is disable :( but there has to be some way that it will not let you enter an area if you are carrying a certain item

**Comment by FabioZumbi12** [comment]
I think i found the event. Try this version http://host.areaz12server.net.br:8081/job/RedProtect/394/

**Comment by MikaCookies** [comment]
I have installed that version of the plugin and reloaded the server, but users can still "fish" the NPCs ...

**Comment by MikaCookies** [comment]
Help me please, the bug is not fixing yet :(
