### ISSUE TITLE
[Suggestion] Support float number in cost-per-block

### ISSUE THREAD

**Issue by MCUmbrella** [FabioZumbi12/RedProtect#744]
**Is your feature request related to a problem? Please describe.**
I tried to set cost-per-block to 0.25 but when the server is started it has been changed to 0 so I considered RP only support using integer as cost but I really need to use float numbers now

**Describe the solution you'd like**
Keep the correct number and use it on claiming

**Describe alternatives you've considered**
None

**Additional context**
RP version: 7.7.2-b384-Universal

**Comment by FabioZumbi12** [comment]
Changed on latest dev build!
