### ISSUE TITLE
Flag command Not working

### ISSUE THREAD

**Issue by WolfyRed** [FabioZumbi12/RedProtect#748]
**Describe the bug**
The RedProtect command `/rp flag` does not work.

**To Reproduce**
1. Go on a server
2. Download RedProtect on it
3. Type `/rp flag` and press enter
4. **An internal error occurred while attempting to perform this command**

**Expected behavior**
The RedProtect command `/rp help` giving me a menu of selectable protecting options for any region I'm in

**Screenshots**
![2021-02-19_04 40 02](https://user-images.githubusercontent.com/66114400/108487847-b21a4580-726d-11eb-8d02-723d3870f131.png)

**Server and plugins versions (please complete the following information):**
 - Spigot 1.12.2-R0.1-SNAPSHOT
 - Plugin Version: RedProtect-7.5.6-b164-Universal.jar
 - Java Version: java version "11.0.10" 2021-01-19 LTS

**Additional context**
*I used the command in existing regions, so the problem doesn't lie upon executing the command in unclaimed areas.*

**Comment by WolfyRed** [comment]
I wonder if there's a way to bump this, lol

**Comment by CloudeLecaw** [comment]
Looks like you have a currpted gui. Try to add all gui elements. Check you GUI is defined big enough and also all inserted blocks a vaild

**Comment by WolfyRed** [comment]
> Looks like you have a currpted gui. Try to add all gui elements. Check you GUI is defined big enough and also all inserted blocks a vaild

How do I add Gui elements?

**Comment by WolfyRed** [comment]
> > Looks like you have a currpted gui. Try to add all gui elements. Check you GUI is defined big enough and also all inserted blocks a vaild
> 
> How do I add Gui elements?

**NEVERMIND I FIGURED IT OUT!!!!!!!!! THANKS!!!!!**
