### ISSUE TITLE
[ISSUE] Enable Wilderness TNT

### ISSUE THREAD

**Issue by WolfyRed** [FabioZumbi12/RedProtect#749]
**Describe the bug**
I cannot explode TNT within the Wilderness region.

**To Reproduce**
1. Make sure you're outside of any claimed regions
2. Place down one/multiple block(s) of TNT
3. Light the TNT
4. No blocks explode, or any other nearby TNT block.

**Expected behavior**
The TNT to explode in non-claimed areas, as that would make a lot of sense.

**Screenshots and Videos**

https://user-images.githubusercontent.com/66114400/108489368-7bddc580-726f-11eb-8bd1-595c12217a63.mp4

**Server and plugins versions (please complete the following information):**
 - Server: Spigot 1.12.2-R0.1-SNAPSHOT
 - Plugin Version: RedProtect-7.5.6-b164-Universal.jar
 - Java Version: java version "11.0.10" 2021-01-19 LTS

**Additional context**
*I assumed the option would be in the* `config.yml` *file, hidden or buried, but it was found nowhere.*

**Comment by CloudeLecaw** [comment]
if u want this then u need to enable explosion in the  wilderness
therefor you have your globalflags.conf
