### ISSUE TITLE
Vault found, but cannot be used [Issue] 

### ISSUE THREAD

**Issue by WolfyRed** [FabioZumbi12/RedProtect#750]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://host.areaz12server.net.br:8081/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

**Describe the bug**
*`Vault found, but for some reason cannot be used with RedProtect.`*

**Expected behavior**
Vault to work with Redprotect, I downloaded many of the listed older versions of Vault too and RedProtect didn't budge.

**Screenshots and LOGs**
![image](https://user-images.githubusercontent.com/66114400/108624253-cb5bf700-7411-11eb-9a57-ea9066389fbf.png)

**Server and plugins versions (please complete the following information):**
 - Server: Spigot 1.12.2-R0.1-SNAPSHOT
 - Plugin Version: RedProtect-7.5.6-b164-Universal.jar
 - Java Version: java version "11.0.10" 2021-01-19 LTS

**Additional context**
*I have no idea what Vault is used for in RedProtect, this is more of a question issue.*

**Comment by selcukwashere** [comment]
Did you download an economy plugin with Vault? Vault can't be hooked unless it has a economy plugin hooked to.

**Comment by WolfyRed** [comment]
> Did you download an economy plugin with Vault? Vault can't be hooked unless it has a economy plugin hooked to.

No, I did not, but did you see my other issue post?

**Comment by FabioZumbi12** [comment]
Your version its too old. We are on 7.7.3 and can be downloaded from here: http://host.areaz12server.net.br:8081/job/RedProtect

Btw, this message just says that vault cant be used because theres no economy lugins available to work with vault.
