### ISSUE TITLE
[BUG] proteções do usuário são removidas

### ISSUE THREAD

**Issue by MikaCookies** [FabioZumbi12/RedProtect#751]
Por favor, preciso de ajuda imediatamente. Quando o servidor é desligado, as proteções do usuário são removidas.

**Comment by FabioZumbi12** [comment]
Voce tem que ver no seu console se tem algum erro acontecendo. Esse problema definitivamente não acontece se é a ultima versão do plugin e a ultima versão do minecraft. Se tiver erros no console, me mande os logs.

**Comment by MikaCookies** [comment]
This is the log https://pastebin.com/Zk2X68CM

**Comment by FabioZumbi12** [comment]
This is not related with RedProtect, in any way. RedProtect is not mentioned there and this seems to be a problem with your server network or server crash.
