### ISSUE TITLE
[BUG] Wrong saving of non expand-vert region

### ISSUE THREAD

**Issue by Jason505Cze** [FabioZumbi12/RedProtect#753]
Hello there,
I would like to report a simple, yet gamebraking bug. When you create with a wand a region with limited Y, the minY value is set as maxY and maxY value as minY in the data file.
As a result, these regions are not working at all.
I'm including two files, one with the "not swaped" values, that I've had to make manually, and the second, wrong one.

Looking forward to a fix.

Note: This bug has been there for a while (half a year I guess?)

[files.zip](https://github.com/FabioZumbi12/RedProtect/files/6077134/files.zip)

**Comment by CloudeLecaw** [comment]
Have you uses claim command? If yes then 1 to 250 is protectet.
If you want your choosen area just use rp define.

**Comment by ThatPerkel** [comment]
I'm afraid both claim and define are broken.
`Have you uses claim command? If yes then 1 to 250 is protectet.`
That's not our case as we have set **autoexpandvert-ondefine=false** in the config.

**Comment by CloudeLecaw** [comment]
On define! Not on claim...

**Comment by CloudeLecaw** [comment]
i took a look on your wrong and right files..

why your ymin is smaller then ymax?
was this done manually by you?
i never saw this behave before :3

**Comment by CloudeLecaw** [comment]
We tried this too and it size where set correcly...  Strengh behave...

**Comment by CloudeLecaw** [comment]
We are running a PaperMC Build server too on 1.16.5 (build 508)

here is our config may it helps <3

[config.zip](https://github.com/FabioZumbi12/RedProtect/files/6107719/config.zip)
