### ISSUE TITLE
[BUG] Region flag explosion-block-damage doesn't seem to exist

### ISSUE THREAD

**Issue by Olexorus** [FabioZumbi12/RedProtect#754]
**Describe the bug**
According to https://github.com/FabioZumbi12/RedProtect/wiki/Region-Flags#global-flags RP should have a flag `explosion-block-damage` to toggle explosion block damage. However this flag doesn't seem to exist for me, even after regenerating the config. It seems to have been replaced by `explosion-entity-damage`.

**To Reproduce**
Open globalflags.conf and check if you can find the flag.

**Expected behavior**
The config contains the flag

**Server and plugins versions (please complete the following information):**
 - Server: git-Tuinity-"c303521" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
 - Plugin Version: RedProtect-7.7.2-b357-Universal.jar
 - Java Version: openjdk 11.0.10 2021-01-19

**Comment by FabioZumbi12** [comment]
I have changed to `fire-block-damage`. Thanks for the tip.
