### ISSUE TITLE
[BUG] RP LIST kicked out for Bungeecord string output limitation

### ISSUE THREAD

**Issue by EfexTo** [FabioZumbi12/RedProtect#756]
I'm on RedProtect 7.7.2 b357

When I do /rp list, after that I added a lot of claims I get kicked for a Bungeecord string output limitation and can’t teleport to claim by using the list. I asked for this error some times ago without any fix. I was thinking that the only way could be to split the claims list in different part

**To Reproduce**
1. Execute /rp list with plenty existing claims on a Bungeecord Server

**Expected behavior**
I was thinking if It's possible to fix this by splitting the RP LIST in different strings output

**Screenshots and LOGs**
If applicable, add screenshots to help explain your problem. Upload your logs to https://gist.github.com/

**Server and plugins versions (please complete the following information):**
 - Server: Purpur 1.16.5
 - Plugin Version: RedProtect 7.7.2 b357
 - Java Version: Latest probably

**Comment by FabioZumbi12** [comment]
This is already fixed on latest version of redprotect available on http://host.areaz12server.net.br:8081/job/RedProtect/
