### ISSUE TITLE
RedProtect está lagando meu servidor completamente [Problema] 

### ISSUE THREAD

**Issue by Zaureon** [FabioZumbi12/RedProtect#759]
Olá Fabio, eu uso o seu plug-in a anos, só que eu estou tendo problema de lag com o mesmo, ele está ficando responsável por 200% do tick do servidor, estou usando a versão mais atualizada

https://prnt.sc/1100o65

**Comment by Zaureon** [comment]
Pedi agora que os players parassem, e não quebrassem/colocassem blocos e o TPS subiu

**Comment by FabioZumbi12** [comment]
Voce deve ter mexido na config `build-near` (ou algo assim, da um ctrl+f na config)

Diminui essa config pra 2 ou 1

**Comment by Zaureon** [comment]
Exatamente, vou abaixar e lhe deixo informado, btw que suporte rápido em

**Comment by Zaureon** [comment]
O servidor agora está perfeitamente estabilizado, agradeço muito pelo rápido suporte.
