### ISSUE TITLE
Unallowed players can claim inside a claim

### ISSUE THREAD

**Issue by zedentox** [FabioZumbi12/RedProtect#76]
Hi,

Some peoples reported that when somebody try to claim a one line wide claim inside another claim, it works, even if the player is not allowed.

**Comment by FabioZumbi12** [comment]
But with fences or wand tool?

**Comment by zedentox** [comment]
We use only wand tool.

**Comment by FabioZumbi12** [comment]
I think is fixed on latest version 6.6.3, please download again from Spigot/Bukkit.

**Comment by zedentox** [comment]
Thank you ! But we can't upgrade before you integrate PR #59. :confused:

**Comment by FabioZumbi12** [comment]
I added your suggestion on your PR but in other way, to allor player to use only protection blocks(can be disabled on configs). Try this version: https://github.com/FabioZumbi12/RedProtect/blob/master/release/RedProtect-6.6.3-b833.jar?raw=true

**Comment by zedentox** [comment]
OK, it seems to work fine ! BUT can you add a red message when you try to break a block in a not allowed area ? It will be perfect after that. :simple_smile:

**Comment by FabioZumbi12** [comment]
What you mean? Only dont show the message if the globalflag "build" is false, othewise show a red message.

**Comment by zedentox** [comment]
Actually, on our server, when someone try to break a block in a world where you need to claim to build/break something, a red message appear. Can you do that ?

**Comment by zedentox** [comment]
Something like "You are not allowed to build here !"

**Comment by FabioZumbi12** [comment]
Already have... but will show only if the globalflag "build" is true.

**Comment by zedentox** [comment]
Hum, ok it works ! Thank you !
