### ISSUE TITLE
Admins in my claims can't tp in[BUG] 

### ISSUE THREAD

**Issue by Suim67** [FabioZumbi12/RedProtect#763]
Is there any option to for example when the creator of a claim add someone in his claim, this person would be able to teleport to the claim where he's invited in ? 

Or when the person that has been added use /rp list, he could see all the claims where he can interact

**Comment by FabioZumbi12** [comment]
Theres no way. As a people can have their own regions, and if list the regions where he is member, the list will be too muth large to show. The same with TP.
