### ISSUE TITLE
[Sugestão] Flags para Pixelmon

### ISSUE THREAD

**Issue by CrazieWolf** [FabioZumbi12/RedProtect#764]
Estou querendo saber qual flag usar no meu spawn para que meus players do Pixelmon possam interagir com os itens do mod como o PC e a maquinad e trocas.

gostaria de saber se existe a flag interact e caso nao exista se poderia ser adicionada

Tentei usar perms de porta botao redstone e alavanca mas nao funcionaram

**Comment by FabioZumbi12** [comment]
A flag `chest` serve para interagir com qualquer tipo de item que tenha um inventário, incluindo itens de mods
