### ISSUE TITLE
Question about Global regions and flags

### ISSUE THREAD

**Issue by Magnum97** [FabioZumbi12/RedProtect#765]
**Is your feature request related to a problem? Please describe.**
There is a mention on Spigot page about global region flags.

**Describe the solution you'd like**
I can not figure out how to set global flags. So I need to create a world wide region first?

**Describe alternatives you've considered**
WorldGuard installed along with RP to take care of world not under RP care.

**Additional context**
Please advise if we can do global region, do I need world guard?

**Comment by CloudeLecaw** [comment]
for global flags you have a file called globalflags.conf there u can define flags for all reagons

in config you can define the default flags and there state when a new region is created.

**Comment by Magnum97** [comment]
Great help! Glad to know I can remove WorldGuard - and thank you very much for the example conf.
