### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Sick-FM** [FabioZumbi12/RedProtect#766]
I have a problem with RedProtect. I've installed it on my server, and it automatically enable Whitelist, but i don't want it.

 - Server: Spigot 1.15.2]
 - Plugin Version: Last version
 - Java Version: Java 11

**Comment by FabioZumbi12** [comment]
CTRL+F on config and set this config to false: `whitelist-server-regen=false`

Its about enable whitelist when regerating regions
