### ISSUE TITLE
unable to restart my server

### ISSUE THREAD

**Issue by needwalter** [FabioZumbi12/RedProtect#77]
Hi, It's me.. again !

Well.... i' dont know what is wrong with  my config... when i put the .jar you gave me last time nothing appens. 
This is what i can read :    http://pastebin.com/yBj4TPAQ

It start chargin' and then... it's stop. the server do not start.

If you have a solution.... i will be very happy !
thanks you !

Walt

**Comment by Stuart74** [comment]
Possibly due to the below 

19.06 21:42:50 [Server] INFO java.io.IOException: Server returned HTTP response code: 522 for URL: https://api.curseforge.com/servermods/filesrojectIds=31279

**Comment by FabioZumbi12** [comment]
@Stuart74 you are righth! 
@needwalter Seems to be the PEX updater:

19.06 21:42:50 [Server] INFO at ru.tehkode.libs.net.gravitydevelopment.updater.Updater.read(Updater.java:643) [PermissionsEx-1.23.4.jar:?]
...
19.06 21:42:50 [Server] INFO java.io.IOException: Server returned HTTP response code: 522 for URL: https://api.curseforge.com/servermods/filesrojectIds=31279
19.06 21:42:50 [Server] ERROR null
19.06 21:42:50 [Server] ERROR If you have not recently modified your configuration and this is the first time you are seeing this message, the site may be experiencing temporary downtime.
