### ISSUE TITLE
[BUG] API not reachable?

### ISSUE THREAD

**Issue by mmuziek** [FabioZumbi12/RedProtect#770]
Hey there i try to intergrate RedProtect.
Strange enough when i add it to my maven it seems maven cannot find the artifacts. i tried:
`<dependency>
			<groupId>br.net.fabiozumbi12.RedProtect</groupId>
			<artifactId>RedProtect-Spigot</artifactId>
			<version>LATEST</version>
			<scope>provided</scope>
		</dependency>`
		
		`<dependency>
			<groupId>br.net.fabiozumbi12.RedProtect</groupId>
			<artifactId>RedProtect-Spigot</artifactId>
			<version>7.7.3</version>
			<scope>provided</scope>
		</dependency>`
		
		The latest one completely breaks my maven. and the version one directly returns unfindable.
		the latest one i dived in more deeply and gave me once again not found.
		
		here is the maven error :
		` Failed to collect dependencies at br.net.fabiozumbi12.RedProtect:RedProtect-Spigot:jar:LATEST: Failed to read artifact descriptor for br.net.fabiozumbi12.RedProtect:RedProtect-Spigot:jar:LATEST: Failed to resolve version for br.net.fabiozumbi12.RedProtect:RedProtect-Spigot:jar:LATEST: Could not find metadata br.net.fabiozumbi12.RedProtect:RedProtect-Spigot/maven-metadata.xml in local (C:\Users`
		
		i hope this can be fixed so i can build it in :)

**Comment by FabioZumbi12** [comment]
You need the redprotect core too
