### ISSUE TITLE
[Suggestion] WorldEdit compatibility

### ISSUE THREAD

**Issue by Melvout** [FabioZumbi12/RedProtect#772]
Hi man,

I'm here to suggest a new feature for your plugin.

Is it possible to add a compatibility with WordEdit?

I explain myself: If a player has the WorldEdit permission on a map and RedProtect is installed on this same map. He is able to interact outside his claims because of WorldEdit.

So my question is: Is it possible to grant a permission to a player only to use WorldEdit inside his claims? Or by the use of a flag?

Thanks for your work, have a nice day.

**Comment by FabioZumbi12** [comment]
No way. Its too hard to limit other plugins inside regions.
