### ISSUE TITLE
[Suggestion] Add /rp ban please

### ISSUE THREAD

**Issue by JaayTheLoft** [FabioZumbi12/RedProtect#773]
**Is your feature request related to a problem? Please describe.**
When players are being annoying and not getting off your land, it would be nice to have a way to get them off of your land forever so they can't come back and be annoying.

**Describe the solution you'd like**
Potentially add a command like **/rp ban** to ban them off one of your lands forever. This is widely suggested by members of the community I help run.

**Describe alternatives you've considered**
There isn't really other alternatives. /rp kick kicks them off of the land temporarily, but that doesn't stop them from coming back later.

**Additional context**
N/A

**Comment by FabioZumbi12** [comment]
You use the option `delay-after-kick-region=60` and add a very high time here, and the use `/rp kick <player>`
