### ISSUE TITLE
[BUG] I can only run commands from console and not from game using mohist

### ISSUE THREAD

**Issue by RioStarGT** [FabioZumbi12/RedProtect#777]
I'm trying to use commands like / rp help in game and I don't have permissions to use these commands, previously being in OP. any ideas ?

When I run the commands from the console I can see the help guide for red protect but not from the game.

**Comment by RioStarGT** [comment]
Server: mohist
 - Plugin Version: 
 - Java Version: 1.12.2
 https://imgur.com/5njFAiC  - (console image allowing to execute the / rp command)
 
https://imgur.com/dW9cFyr - (image in game when trying to run rp command)

**Comment by FabioZumbi12** [comment]
Probably you is mesing with permissions and theres some other error on console. Btw, try the latest dev build on http://host.areaz12server.net.br:8081/job/RedProtect/
