### ISSUE TITLE
[BUG]  Signtextes can be colored as Stranger

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#781]
Strangers can change SignTextcolors in Regions

I dont know if this is new in 1.17
But grab a Color of your choice
move into a region that is not yours!
Lets say Red Dye
rightclick a sign.
you will see the signcolor change.

Im sure this was not wanted....

![Snag_bca6356](https://user-images.githubusercontent.com/12080017/124032463-e4486a80-d9f8-11eb-99ea-fc45b8eb0202.png)

![Snag_bca7bc0](https://user-images.githubusercontent.com/12080017/124032479-e8748800-d9f8-11eb-9ed6-e33bd884d516.png)

**Comment by FabioZumbi12** [comment]
Fixed on dev builds

**Comment by CloudeLecaw** [comment]
I can confirm its fixed <3
