### ISSUE TITLE
[BUG] Anyone can harvest berries

### ISSUE THREAD

**Issue by Bartek200219** [FabioZumbi12/RedProtect#782]
**Describe the bug**
Anyone even nonmember can harvest berries
**To Reproduce**
1. Claim terrain with berry
2. player that isn't member can harvest it

**Expected behavior**
I think it should be in flags to decide if player can harvest it or not

**Screenshots and LOGs**
If applicable, add screenshots to help explain your problem. Upload your logs to https://gist.github.com/

**Server and plugins versions (please complete the following information):**
 - Server: Paper 1.17-71
 - Plugin Version: RedProtect-7.7.2
 - Java Version: Java 1.16

**Comment by FabioZumbi12** [comment]
Fixed on latest dev build
