### ISSUE TITLE
[BUG] Horses can destroy fields

### ISSUE THREAD

**Issue by Bartek200219** [FabioZumbi12/RedProtect#783]
**Copy pasted form https://github.com/FabioZumbi12/RedProtect/issues/692**

**Describe the bug**
If you jump with a horse on a field from a foreign claim, the seed is destroyed.

**Screenshots and LOGs**
If applicable, add screenshots to help explain your problem. Upload your logs to https://gist.github.com/

https://user-images.githubusercontent.com/37016424/125490085-cd0d04e8-a165-45a3-a2cd-248f382cc813.mp4

**Server and plugins versions (please complete the following information):**
 - Server: Paper 1.17
 - Plugin Version: RedProtect-7.7.2
 - Java Version: Java 1.16

**Comment by FabioZumbi12** [comment]
Already fixed on latest versions
