### ISSUE TITLE
[BUG] Claim and block limit can be bypassed by adding leaders

### ISSUE THREAD

**Issue by Bartek200219** [FabioZumbi12/RedProtect#784]
**TLDR; Same as https://github.com/FabioZumbi12/RedProtect/issues/730 except that people are adding themselvs by command after creating claim**

**Describe the bug**
By using two accounts, it is possible to bypass the claim and block limit.

**To Reproduce**

1. have 2 accounts
2. first create claim
3. first add second player
4. second remove first player form claim
5. block limit bypassed

**Server and plugins versions (please complete the following information):**
 - Server: Paper 1.17
 - Plugin Version: RedProtect-7.7.2
 - Java Version: [Java 1.16

**Comment by FabioZumbi12** [comment]
On truth, the claim is split by two players. This depends on you and your server policies, as example, on my server is not allowed two accounts of same player.

**Comment by aurel85** [comment]
Regardless of the server's policy, it is not normal that through a few manipulations a player can bypass his /rp blocklimit... This issue is not closed, the plugin should prevent putting a leader player if this causes him to exceed his block limit.

**Comment by aurel85** [comment]
I tested, it's solved. Thanks !
