### ISSUE TITLE
[BUG] copyflag doesn't work if name contains '_'

### ISSUE THREAD

**Issue by Bartek200219** [FabioZumbi12/RedProtect#785]
**Describe the bug**
/rp copyflag doesn't work if name contains `'_'`
**To Reproduce**
create claim that name contains `'_'`
try to copyflag from it

**Screenshots and LOGs**

https://user-images.githubusercontent.com/37016424/125488993-44e7ee0c-faa2-420e-b9eb-f58d80b0ab0c.mp4

**Server and plugins versions (please complete the following information):**
 - Server: Paper 1.17.1-79
 - Plugin Version: RedProtect-7.7.3-b400-Universal
 - Java Version: Java 16

**Comment by FabioZumbi12** [comment]
I cant reproduce, copied from both regions with `_` and success. You need to be leader of both regions to work.
