### ISSUE TITLE
[BUG] 1.17 - Candles can be turned on and off in all regions

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#787]
Well the thread sais it allready..
Stangers can turn on and on the new candles introduced with 1.17 in regions like they want.

May this can be fixed soon :)

RedProtect_7.7.3-Build400

![image](https://user-images.githubusercontent.com/12080017/126270063-5bc2d07c-9048-45d3-9bba-265ef6c62078.png)

**Comment by Bartek200219** [comment]
I think it's the same problem as https://github.com/FabioZumbi12/RedProtect/issues/782 Because it's interaction by right click

**Comment by FabioZumbi12** [comment]
I think its no more possible. Tried here and cant interact with candles

**Comment by CloudeLecaw** [comment]
i will try out today and give you a feedback <3

**Comment by CloudeLecaw** [comment]
Here a Video with Redproects latest Build 422 on Paper 1.19.4

https://streamable.com/6x3306

The Video shows me as a stranger in a region turning of the candles

i cant turn them on aggain but i cant block turning them off :/

So i thing this bug is not fixed yet?
