### ISSUE TITLE
error on thermos 1.7.10-57-1614 and tekkit legends 1.1.1

### ISSUE THREAD

**Issue by mat41997** [FabioZumbi12/RedProtect#79]
logs
http://pastebin.com/vKw4R1RH

**Comment by FabioZumbi12** [comment]
Fixed on next version. Test this version: https://github.com/FabioZumbi12/RedProtect/blob/master/release/RedProtect-6.6.3-b813.jar?raw=true

**Comment by mat41997** [comment]
is fixed, thx ^^
