### ISSUE TITLE
[Suggestion] Add all members in a region

### ISSUE THREAD

**Issue by pys078** [FabioZumbi12/RedProtect#790]
**Is your feature request related to a problem? Please describe.**

I want to use a region to be a store,however other users cant use /rp tp to teleport until i add them into the region.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by FabioZumbi12** [comment]
You can create a rp portal from other rp to teleport players to your store. On Wiki theres some info about rp portal.
