### ISSUE TITLE
[Suggestion] Fix dependency scopes

### ISSUE THREAD

**Issue by rainbowdashlabs** [FabioZumbi12/RedProtect#791]
**Suggstion**
When working with the plugin we get a lot of other dependencies which are not needed in any case and can even produce problems.
![image](https://user-images.githubusercontent.com/46890129/130592723-791facd7-0e18-4ad3-ad9e-f7fff65ad80f.png)
We have for example a paper-api imported or the essentialsx api. This requires developers to define a lot of annoying exclude clauses in their build files.
All this is caused because these dependencies are not marked as provided in the build files.
I don't know where the paper import comes from since it is not present in the pom file of the current spigot version.
So please set your scopes to provided for:
- paper-api
- world edit
- world guard
- EssentialsX
- mypet

Maybe it would be also helpful to relocate the configurate stuff in the core to avoid breaking other plugins when multiple plugins use this dependency with different versions

**Comment by FabioZumbi12** [comment]
Thanks for hint. I have added!
