### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Qkzoh** [FabioZumbi12/RedProtect#792]
The Bug is that you can break the frames with the item they have inside. Those who steal use lava and water to generate cobblestone.

In this way, when a block is generated on top of the frame, it causes the frame to break and throw the item on the floor.

This also happens with player_head. If someone has a head on their protection you can steal it just by putting water on top of it ** see videos below**

**To Reproduce**
1. Go to a player protection
2. you must stand in the last block where you can interact with the frame 
3. Put lava on it
4. Then put water ** Se the videos below **

Expected behavior: Users should not be able to use lava or water buckets on other users' protections. 

**Video**
https://www.youtube.com/watch?v=Yq8NiUK5aDY
https://www.youtube.com/watch?v=kBcjCISn_ec

 - Server: Purpur last dev
 - Plugin Version: Last Dev
 - Java Version: 8

Also tried with: 
java 11, java 16. 
Paper, tuinity, airplane on last dev builds

**Comment by FabioZumbi12** [comment]
Mas se a pessoa pode por agua ou lava na região, ela deve ter a permissão para retirar blocos tbm. Por padrão, se ela nao pode construir, ela tbm nao pode por lava nem agua. Verifica as versões e testa com as ultimas dev builds.
