### ISSUE TITLE
[Duvida] Bloco break/Interact

### ISSUE THREAD

**Issue by ManoJovem** [FabioZumbi12/RedProtect#793]
Fala fabio beleza?

Então brother queria saber como colocar a interagir e quebrar de um item de tal mod no seu plugin.
Exemplo: Aonde eu altero na config que eu posso quebrar/usar túmulo(item de um mod) mesmo em terreno protegido.

Eu tentei por isso mais obtive falha:
```
# Adding world names to the list will automatically enable this on that world.
# To bypass this option, use the permission: redprotect.need-claim-to-build.bypass
needed-claim-to-build {
    # Allow break only this blocks if need claim to build.
    allow-break-blocks=[
        "GRAVESTONE_GRAVESTONE",
        GRAVESTONE
    ]
    # Allow interact with this blocks if need claim to build.
    allow-interact-blocks=[
        "GRAVESTONE_GRAVESTONE",
        GRAVESTONE
```

**Comment by FabioZumbi12** [comment]
Vc precisa saber exatamente o nome do bloco do mod, geralmente tem o nome do mod seguido do bloco em si. Usa o comando `/rp debug-item` com o bloco na mão que ele vai mostrar o nome que o RedProtect entende.
