### ISSUE TITLE
[BUG] Depending on region priority, region messes up

### ISSUE THREAD

**Issue by karl-police** [FabioZumbi12/RedProtect#796]
**Describe the bug**
If you have "sub-regions" inside a big region, so other regions inside of a region and have redstone between two borders of a region. It will mess up depending on what kind of redstone components are in between two regions.

As example, if a redstone wire is claimed but a lever and the piston is not, it will still work fine.
If you have a piston in a region, then create another region inside that region and claim the piston only, then the pistol will not turn on if it gets redstone signal from the region outside.

**To Reproduce**
1. Create a region, doesn't matter how big, make sure it is expanded vertically.
2. Place some redstone work. As example, a lever connected to one redstone wire, which is connected to one sticky piston
3. Now create a region with the wand and left and right click the main piston block and then create another region
4. Try to turn on the piston.
5. You can then experiment with that and change both regions priorities.

Here are some things to note. First, if you create a region within a region, so let's say region1 has priority 5 and region2 has priority 6.
If you enter region2 and then leave region2, then change the priority to something lower, as example 4. The change will not apply. If you change the priority back to something higher, like 6. Enter it, and then change the priority while you're in that region you're changing the priority of, to something lower. Then it will apply the change, otherwise the change won't even load.

The issue with this priority thingy, is that it causes issues with redstone. There should be something like a "redstone Layer" or "redstone Priority", or the plugin should not be thinking that the player is trying to grief their own region with redstone, because I think that's why the redstone doesn't work properly if it lays between to regions.

With this issue, you can not proberly set flags without having to worry about the redstone.

If the "sub-region" has both, the lever and the piston included, there won't be any redstone issue, however it is still not ideal, because there could be even more complex sub-regions just to allow a flag for something like a chest.

**Expected behavior**
The redstone should not get impacted by that.

**Screenshots and LOGs**
If applicable, add screenshots to help explain your problem. Upload your logs to https://gist.github.com/

**Server and plugins versions (please complete the following information):**
![](https://i.imgur.com/G8SkKC9.png)
This is how the "sub-region" selection could look like, as example. Create something like this, put the entire thing in one region and then put the piston block in a separate region within the region that has the entire thing included.

**Comment by CloudeLecaw** [comment]
its normal that pistons can blocks cant be moved out of region. same water and lava..

this is called protection ;)
To make it work the other region must allow it

**Comment by karl-police** [comment]
> its normal that pistons can blocks cant be moved out of region. same water and lava..
> 
> this is called protection ;) To make it work the other region must allow it

I probably didn't figure out how to make the other region allow it, back then I guess
