### ISSUE TITLE
[BUG] the claim system doesnt work below y=0 in the new update

### ISSUE THREAD

**Issue by B-bup** [FabioZumbi12/RedProtect#798]
**Before open an issue, checkout this steps:**

The bug happends when you claim an area in the new 1.18 update. the bugs makes it so that the claim doesnt reach below y=0

1. claim a place
2. go below y=0
3. try using any command for the claim

the server is in 1.18 and is a paper server

**Comment by FabioZumbi12** [comment]
Go to config and look for configuration `minY=0` and set the min value for your world. It already on latest dev builds.
