### ISSUE TITLE
Error EntityExplodeEvent on Thermos-1.7.10-1448-57-server and Tekkit Legends 1.1.1

### ISSUE THREAD

**Issue by mat41997** [FabioZumbi12/RedProtect#80]
logs
http://pastebin.com/b1bQH1AG

timings
http://www.spigotmc.org/go/timings?url=18444798

**Comment by FabioZumbi12** [comment]
Strange...this error only drop if the entity is null... What modpacks are you using?

Anyway, try the latest version: https://www.spigotmc.org/resources/redprotect-for-all-versions-anti-grief-server-protection.15841/update?update=102817

**Comment by mat41997** [comment]
only Tekkit Legends 1.1.1
http://www.technicpack.net/modpack/tekkit-legends.735902

**Comment by FabioZumbi12** [comment]
And have you tested with latest version?

**Comment by mat41997** [comment]
no

**Comment by FabioZumbi12** [comment]
Still with this error?
