### ISSUE TITLE
[Suggestion] Add configurable custom channels to listen for in the ModListener

### ISSUE THREAD

**Issue by emkirsh** [FabioZumbi12/RedProtect#800]
**Is your feature request related to a problem? Please describe.**
I think the mod listener and blocker is a brilliant feature, but I think it's a bit lacking. The problem is that you can only allow or disallow predefined mods/loaders. This lets any hacked clients that use their own branding join without issue.

**Describe the solution you'd like**
I'd love to see two things added:

1. A whitelist mode, essentially reversing the modlistener and blocking everything except defined client brands (such as vanilla).
2. A custom mode, where those with the know-how can add channels to listen for mods they'd like to allow/disallow, without having to edit and recompile from source.

**Describe alternatives you've considered**
One alternative I've considered is forking the plugin, editing files [such as this](https://github.com/FabioZumbi12/RedProtect/blob/master/RedProtect-Spigot/src/main/java/br/net/fabiozumbi12/RedProtect/Bukkit/listeners/ModListener.java) to add custom channels to listen for and recompile the plugin for my own server. The problem with this is I'd have to recompile every time there's an update, and only I would benefit from it.

**Additional context**
This feature would be greatly appreciated, but I can understand it not necessarily being a top priority considering there are other plugins out there that can do this.

Thanks in advance!

**Comment by FabioZumbi12** [comment]
Its a good idea. If you fork and add all of this, lt me know!
