### ISSUE TITLE
[Suggestion] Publish the API to the central repository

### ISSUE THREAD

**Issue by josephjthomas** [FabioZumbi12/RedProtect#804]
### **Please explain your feature request to the best of your abilities:**

Do you think you can publish the API to the central maven repository (https://repo.maven.apache.org/)? That way, developers like me can always switch between snapshots and releases when they want, and don't need to rely on a GitHub repository.
I hope this is something you would consider.

The Sonatype team have heavily reworked their standards and requirements. They allow hosting of almost any open source software nowadays, whether it's an API, a library or a dependency for something else.

Thanks for considering it.

**Comment by FabioZumbi12** [comment]
Its done. The deps its on readme of this repository
