### ISSUE TITLE
Claiming doesn't work properly[BUG] 

### ISSUE THREAD

**Issue by OhaDerErste** [FabioZumbi12/RedProtect#812]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://host.areaz12server.net.br:8081/job/RedProtect>
* Its important to you include the plugin jar name, because version and build info.

**Describe the bug**
Claiming doesnt work properly

**To Reproduce**
Claim a region using the claim wand
execute /rp claim
Check if the region exists

**Expected behavior**
The region should exist

**Screenshots and LOGs**
Video:
https://ohas.website/redprotect-bug.mp4

**Server and plugins versions (please complete the following information):**
 - Server: 
![image](https://user-images.githubusercontent.com/77100649/163465352-440f648a-9fb7-400f-9906-7cce81fdb6a3.png)

 - Plugin Version: RedProtect-7.7.3-b412-Universal
 - Java Version: Openjdk 17

**Additional context**

**Comment by frankinbaka** [comment]
It's really been a recurring and recent problem on my server, players create the board and it just disappears and doesn't create the area.
