### ISSUE TITLE
All the proper permissions added, but still won't let users do /rp flag

### ISSUE THREAD

**Issue by Lonewolfy11** [FabioZumbi12/RedProtect#813]
Basically the title says it all. I posted screenshots of the perms i added on discord #support-international on the FabioZumbi12 dev discord. (Somewhitedude#6154) is my username. Another user in the chat was confused also because I added all the right perms. Any idea what went wrong? thanks.

**Comment by FabioZumbi12** [comment]
Basically you don't need to add none of the permissions. The default perms to players start to use redprotect is already given. Remember that you need a perm plugin and optionally (recommended) vault plugin for spigot version too.
