### ISSUE TITLE
[BUG] Jenkins

### ISSUE THREAD

**Issue by chelminski** [FabioZumbi12/RedProtect#815]
Jenkins link isn't working 
http://host.areaz12server.net.br:8081/job/RedProtect/

![image](https://user-images.githubusercontent.com/62246121/169143678-b1fecd0a-8834-453c-9f19-4f67e0e28650.png)

**Comment by CloudeLecaw** [comment]
i agree the jenkins dev build server is down since a few weeks now :(

**Comment by FabioZumbi12** [comment]
Online again!!
