### ISSUE TITLE
[BUG] White list turn off

### ISSUE THREAD

**Issue by antogonz** [FabioZumbi12/RedProtect#816]
Hello,

I'm using papermc server (paper-1.18.2-337.jar) and redprotect (RedProtect-7.7.3-b410-Universal.jar), I config the parameter white-list=true in server.properties, and when server is running change automatically to white-list=false. If I remove the plugin, that doesn't happen.

Thank you.

**Comment by FabioZumbi12** [comment]
Do a ctrl+f on config file and search for "whitelist" on config and set to false
