### ISSUE TITLE
[Sugestão] NeedClaimToBuild MSG in Wand Item

### ISSUE THREAD

**Issue by Reldnah** [FabioZumbi12/RedProtect#817]
Bom , quando você deixa a opção "NeedClaimToBuild" = True , ela da a mensagem que não pode construir em área desprotegida, até ai ok. 

Mas mesmo com a opção "WAND" no modo de claimar na config. Quando vc clica com o esquerdo e direito do mouse , ele da a mensagem "Você não pode construir em areas desprotegidas!". 

Não é nada prejudicial , e não encontrei na config se tem como desativar para o item do "WAND" , desta forma, minha sugestão é:
Colocar alguma verificação para se for o "Wand item" na mão , não printar essa mensagem de "Você não pode construir em areas desprotegidas!". 

É isso! :D

**Comment by FabioZumbi12** [comment]
Faz tempo que implementei isso ja, mas acredito que essa mensagem apareça justamente pro item Wand dizendo q ele nao vai conseguir claimar. Acho que coloquei proposital.
