### ISSUE TITLE
1.19.4 support[Suggestion] 

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#818]
Since a while 1.19 is out. So it would be nice to have
Sone of the new things added to Redprotect

- the heads of new mobs in the animal/monster flag gui

- a flag or thing to prevent players Killing the new mob Allay on a region

- a protection that players cant steal the Allay the blocks and give thier own blocks to an Allay on a region.
(Be default an Allay is tamed/asigned to the Player that gave him the Block).. current everyone can steal the Allay the item an give then a new one to make the Allay theirs.

**Comment by FabioZumbi12** [comment]
I think Allays already respect animal interact flag (don't remember the name). The other things is already on latest dev build 414+.

**Comment by CloudeLecaw** [comment]
this ticket now can be closed ;)
