### ISSUE TITLE
Permissões feitas no config não funcionam

### ISSUE THREAD

**Issue by pump61** [FabioZumbi12/RedProtect#822]
Estou adicionando alguma configurações no config.conf não são aplicadas ao jogo, como por exemplo o scan de terreno e o limite da altura no nether não são alterados, estou tendo que usar as permissões de bypass pra poder lidar com isso.

Tbm o bloqueio de spawn de mobs nas regiões estão permitindo que Hoglins e Ghast spawnem mesmo com a permissão
desativada.

![image](https://user-images.githubusercontent.com/61327951/175776554-cadaf151-c7d2-40a9-9fb4-30440400aabc.png)
![image](https://user-images.githubusercontent.com/61327951/175776571-a00a4514-df8d-4dfc-a418-efb8d0d50a59.png)

Estou na versão RedProtect-8.0.0-SNAPSHOT-b415-Universal.jar que saiu recentemente.

**Comment by pump61** [comment]
A proteção está apenas protegendo baús, os barris e outros storages não são protegidos.

**Comment by FabioZumbi12** [comment]
Qual a versão do server e a do RedProtect (nome completo da versão do server e nome do .jar do redprotect)?

**Comment by pump61** [comment]
versão do servidor git-Purpur-1669 (MC: 1.19)
versão do redprotect RedProtect-8.0.0-SNAPSHOT-b415-Universal.jar

a questão dos baús foi um mal entendido porem o restante ainda continua

**Comment by pump61** [comment]
depois da atualização que saiu recentemente RedProtect-8.0.0-SNAPSHOT-b416-Universal.jar as traduções não estão mais funcionando, as mensagem estão em inglês mesmo que as configs estejam setadas em pt-br na config

**Comment by jefflima1** [comment]
pump, você consegue disponibilizar a b416 para download?

**Comment by pump61** [comment]
> pump, você consegue disponibilizar a b416 para download?

https://cdn.discordapp.com/attachments/599070005505818644/1023058066436014130/RedProtect-8.0.0-SNAPSHOT-b416-Universal.jar

Desculpa a demora
