### ISSUE TITLE
rp list dont work

### ISSUE THREAD

**Issue by Italoplcl** [FabioZumbi12/RedProtect#823]
When performing the rp list command, an error appears in the console and it does not show what it should.

![image](https://user-images.githubusercontent.com/58242083/176063755-ead3e001-cf7e-4bc9-a000-7b32a93a8310.png)

- Server: git-Purpur-1684 (MC: 1.19)*
- Plugin Version: RedProtect-8.0.0-SNAPSHOT-b415-Universal
- Java Version: 17

**Comment by aurel85** [comment]
Hi,

It's the same thing with Paper 1.19.

**Comment by FabioZumbi12** [comment]
Something related to dependencies. I'll check later.
