### ISSUE TITLE
[BUG] API Documentation points to invalid release

### ISSUE THREAD

**Issue by NotMyFault** [FabioZumbi12/RedProtect#827]
Hey @FabioZumbi12,

the API documentation points out, to use the central repository, but you can't host snapshots in release repositories: https://github.com/FabioZumbi12/RedProtect#maven-repository-api

Could you update the documentation to reflect a release available on the central repository (https://repo1.maven.org/maven2/) or, if needed, cut a release, please?

Thanks in advance.

**Comment by FabioZumbi12** [comment]
Done, thanks.
