### ISSUE TITLE
Lang file for sponge plugin

### ISSUE THREAD

**Issue by iTeeLion** [FabioZumbi12/RedProtect#83]
Hi! Add the lang file/class please. I wanna translate your plugin ^_^

**Comment by FabioZumbi12** [comment]
Hello. 
On first run the lang file is created.

**Comment by FabioZumbi12** [comment]
When you translate, send to me to i add on lang files ^^

**Comment by iTeeLion** [comment]
im in process

**Comment by iTeeLion** [comment]
im in process
