### ISSUE TITLE
[BUG]  Candles can be turned off by rightclick in all regions

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#836]
may you renember this ticket where i reported candles can be turned on and off by region strangers.
https://github.com/FabioZumbi12/RedProtect/issues/787

I tested this now with the Redproects latest 8.1.0 Build 422 on Paper 1.19.4

I made a video shows me as a stranger (and as player of curse, not as admin) in a region turning off the candles by right click on burning once.
https://streamable.com/6x3306

i cant turn them on aggain what is fine =)
So at least the half of this bug from Ticket 787 is fixed as turning them on is fixed now.

So just the turning off of candles by rightclick in regions when your a stranger needs to be fixed now.

**Comment by FabioZumbi12** [comment]
With a brand new user on server, trying to interact with protected regions:

![redprotect](https://user-images.githubusercontent.com/5833818/231910059-cb0a6ea1-8493-4492-a483-e71210181302.gif)

**Comment by CloudeLecaw** [comment]
oh that is intereesting. may its a flag? could you tell me what flag this could be? :->

**Comment by CloudeLecaw** [comment]
i found the answer
its the flag  allow-mod   when set to true stranger can turn of the candles.

Thanks for leading me for pointing this out <3
