### ISSUE TITLE
Right clicking a sign deletes it [BUG] 

### ISSUE THREAD

**Issue by shanefred** [FabioZumbi12/RedProtect#837]
**Describe the bug**
When a player right-clicks a sign they placed, it deletes the sign. This is also true if a player tries to place a new sign on a sign that's already been placed. In that case, it deletes both signs.

**To Reproduce**

1. Install RedProtect.

**Expected behavior**
Right-clicking on signs should not delete them and players should be able to place signs on top of each other to, for example, block water without any signs being deleted.

**Screenshots and LOGs**
N/A

**Server and plugins versions (please complete the following information):**

- Server: Paper 1.19.3 and 1.19.4
- Plugin Version: RedProtect-8.1.0-SNAPSHOT-b422-Spigot.jar
- Java Version: Java 18

**Additional context**
N/A

**Comment by FabioZumbi12** [comment]
Redprotect don't deletes, check if conflict with other plugins
