### ISSUE TITLE
a head in the monster piglin_brute GUI is missing in 1.20.x[BUG] 

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#844]
**Describe the bug**
in the animals GUi where you can disable mobs. one mobhead for the piglin_brute seems to not exists:
![image](https://github.com/FabioZumbi12/RedProtect/assets/12080017/3d5687a7-94e9-4250-905c-73ac8a3bc808)

**To Reproduce**
1. get your server to spigot or paper 1.20.1
2. get RedProtect_8.1.1-Build432 (and may TranslationAPI_1.2-Build16 to have translated Mobnames)
3. start the Server
4. use /rp flag and chooose the monster spawn icon
5. in the GUI look for the head of the Piglin_Brute
 --> You will see a head with a ?

**Expected behavior**
see a head from a piglin brute :3

**Screenshots**
attached in description

**Server and plugins versions (please complete the following information):**
- Server: paper 1.20.1
- Plugin Version: RedProtect_8.1.1-Build432
- Java Version: RedProtect_8.1.1-Build432
- Relevant Plugins: TranslationAPI_1.2-Build16

**Comment by FabioZumbi12** [comment]
Fixed on build 440
