### ISSUE TITLE
[BUG] Water can't flow in the other region

### ISSUE THREAD

**Issue by karl-police** [FabioZumbi12/RedProtect#845]
**Describe the bug**
Water doesn't flow in the other region. While you once said, that it is intended for the last issue I made. I mean yeah, it's a different region. Where is the freaking ability though, to link regions together or something so that I can have one region, where people can access chests. And the other region not...

**To Reproduce**

1. Create a region
2. Create another region near the other region so that the borders are near to each other but not intersecting.
3. Ensure "flow" flag is on true, for both regions
4. Place water bucket

**Expected behavior**
Water flows into the other region as well. Even if this is intended. I create this post because I want something for water to flow into the other regions that you configure. Same for a flag, maybe that says, to allow redstone blocks to take redstone blocks. And I do not know about sculk sensors but I hope they accept signals from other regions as well or something.

**Screenshots and LOGs**
![image](https://github.com/FabioZumbi12/RedProtect/assets/12023782/0cc56011-4247-47ec-8bcd-8e21b2c39f28)

**Server and plugins versions (please complete the following information):**
It's Minecraft 1.20.1. Idk the server version the commands, they said 8.1.0-SNAPSHOT-b422

Bukkit: 1.20.1-R0.1-SNAPSHOT

**Additional context**
Similar to https://github.com/FabioZumbi12/RedProtect/issues/796

**Comment by FabioZumbi12** [comment]
Based on #796 this is intentional as antigrief is not allowed to out fluid between rps
