### ISSUE TITLE
[Suggestion] The ability to addmember but choose what region

### ISSUE THREAD

**Issue by karl-police** [FabioZumbi12/RedProtect#846]
If I have a region in priority -1 that is within a region of priority above -1.

I have to set that lower priority region into a higher and then use `/rp addmember <player>`

But where's `/rp addmember <player> <region>` or something?

**Comment by FabioZumbi12** [comment]
You already can, but was not docummented on wiki. Now is updated: https://github.com/FabioZumbi12/RedProtect/wiki/Commands
