### ISSUE TITLE
[AJUDA] Como liberar explosões em areas não protegidas?

### ISSUE THREAD

**Issue by Knautiluz** [FabioZumbi12/RedProtect#85]
Percebi que depois que instalei o plugin, os Creepers, TNT, deixaram de danificar o terreno mesmo quando a região não é protegida, gostaria que esse tipo de coisa só acontecesse em regiões protegidas...

Dei uma olhada nos arquivos de ajuda, no config.yml e não encontrei como liberar isso, pode me ajudar?

**Comment by FabioZumbi12** [comment]
Vc libera isso no globalflags.yml que eh as flags para lugares desprotegidos, ou "global". habilita lá as opções de dano de mobs e de explosão.

**Comment by Knautiluz** [comment]
Bacana Fabio, funcionou :)
