### ISSUE TITLE
[BUG] turn off animals or monsters Lag

### ISSUE THREAD

**Issue by Razorxd1993** [FabioZumbi12/RedProtect#852]
**Before open an issue, checkout this steps:**

* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://host.areaz12server.net.br:8081/job/RedProtect>
* It's important to you include the plugin jar name, because version and build info.

**Describe the bug**
Hi if you use the command /rp flag and then the function to turn off animals or monsters, then it lags for a few seconds.
This only happens with these two settings.

**To Reproduce**

1. use /rp flag
2. Click on 'Spawn Animals' or 'Spawn Monsters'
3. See error/issue

**Screenshots and LOGs**
no Error in Console

**Server and plugins versions (please complete the following information):**

- Server: Paper 1.20.1
- Plugin Version: RedProtect-8.1.1-SNAPSHOT-b434-Spigot
- Java Version: Java 17

**Comment by FabioZumbi12** [comment]
I can't reproduce. Maybe because mysql database or other gui plugins causing that.
