### ISSUE TITLE
[BUG] `server-enter-command` and `server-exit-command` not run when player gets teleported into the region

### ISSUE THREAD

**Issue by thomas-worm-fernuni** [FabioZumbi12/RedProtect#854]
**Before open an issue, checkout this steps:**

* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://host.areaz12server.net.br:8081/job/RedProtect>
* It's important to you include the plugin jar name, because version and build info.

**Describe the bug**
When an admin teleports the player into the region (e.g. `/tppos PlayerB 5000 40 5000`) the player gets the welcome message of the region but the enter and exit commands aren't run.

**To Reproduce**

1. Create a region.
2. Set a `server-enter-command` flag (e.g. I use `/ptime {player} night` [command from CMI plugin] for setting players personal time to night when he/she enters the zone.)
3. As an admin (having all permissions, even bypass) teleport a non-admin player to this region.
4. The command isn't run, perhaps because RedProtect checks the permission of the porting player and not of the ported player.

**Expected behavior**
The enter command should be run!

**Screenshots and LOGs**
If applicable, add screenshots to help explain your problem. Upload your logs to https://gist.github.com/

**Server and plugins versions (please complete the following information):**

- Server: PaperMC 1.20.2
- Plugin Version: v8.1.1
- Java Version: Java 17

**Additional context**

**Comment by FabioZumbi12** [comment]
Sadly this is a limitation of server. The player need to move before the event fires and redprotect can listen. Nothing can i to do by plugin part.
