### ISSUE TITLE
[Suggestion] Region list placeholder

### ISSUE THREAD

**Issue by chelminski** [FabioZumbi12/RedProtect#857]
Please add a placeholder to the Placeholderapi that displays the list of player's regions.
I would like to display this information as a hologram. E.g.

"Regions you own: %redprotect_player_region_list%" --> "Regions you own: homes, farm, test"

I don't want to give players access to the command `/rp list`. 
I don't want to complicate the server more for new players, so I thought of displaying information about limits and current areas on a hologram.

Examples of new placeholders:
- `%redprotect_player_region_list%` - Shows a list of the player's all regions
- `%redprotect_player_region_list_overworld%` - Shows a list of the player's overworld regions
- `%redprotect_player_region_list_nether%` - Shows a list of the player's nether regions
- `%redprotect_player_region_list_the_end%` - Shows a list of the player's end regions

You can also break it down by permissions.
- `%redprotect_player_region_list_member%`
- `%redprotect_player_region_list_admin%`
- `%redprotect_player_region_list_leader%`

Let me know what you think about it ;)

**Comment by CloudeLecaw** [comment]
Redprotect has some placeholders that are hard to find on  the placeholderAPI site sadly not mentioned on the wiki..

```
%redprotect_player_in_region%
%redprotect_player_used_claims%
%redprotect_player_used_blocks%
%redprotect_player_total_claims%
%redprotect_player_total_blocks%
%redprotect_region_flag_value_<flag name>%```

**Comment by FabioZumbi12** [comment]
The PAPI list is complete on wiki: https://wiki.placeholderapi.com/users/placeholder-list/#redprotect

Btw, good suggestion and maybe i add as i having some time with minecraft again.

**Comment by FabioZumbi12** [comment]
Added on latest dev builds and the PlaceholderAPI owner already updated on PAPI page: https://wiki.placeholderapi.com/users/placeholder-list/#redprotect

**Comment by CloudeLecaw** [comment]
%redprotect_player_region_names_leader%
@chelminski this looks like what you are needing :-)
