### ISSUE TITLE
Error in Flag GUI  - Version : RedProtect_6.6.5-b860

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#86]
i disabled the flag can-back flag in the config

the flag is not listed anymore in the config in the   enabled-flags: list.
i also deleted it  form the gui.

after a restart and also after reload the
flag GUi gets an new entrey for postion slot 38 - the can-back flag.
with its basic setup if a GUI flag is new and untouched...

> `  can-back:
>     slot: 38
>     material: GOLDEN_APPLE
>     name: '&ecan-back'
>     description: '&bDescription: &2Add a flag description here.'
>     description1: ''
>     description2: ''`

i think this is bug and should be fixed :)
Also.... it should be tested with all other flags if this may happens to an other flag too...

**Comment by FabioZumbi12** [comment]
If you removed from 

```
flags-configuration:
  enabled-flags:
```

and from

`flags:`

I think this is because the flag is set on region! If you remove the permissions too, the flag will not show for players but i think will show for you (because is set on region).

**Comment by CloudeLecaw** [comment]
its a but confusing somethimes.

i tried deleting diffent types
flags-configuration:
and in flags:
+ in the gui

Effect was that currently not its not the can-back currently its the teleport flag.
that is generated in the GUI even there was only -pvp in the list.
same with flags. the config sometimes regenerates some basics.

The entries that where created are like the first once u have when u start it the first time :3
i know i could simply not show the gui entry by taking away the permission.

The question is just what causes this effect...

here is how i tested it.
1. Server is started with all flags. (also in the gui with all)
2. i when to the region Spawn
3. i deletet all flags com falgs-config, flags and the gui (only -pvp anymore so that its not empty
5. i saved the files
6. i tried /rp reload
7. i use /rp flag and check the guifile and config.

effect: it sems like taking away to much at once causes a problem somewhere.
the entries are a "copy" of some default values

i will try now to redo it without any regions for the the moment. so that no entry are there on the -pvp so that its not emtpry... i will reply

**Comment by CloudeLecaw** [comment]
hm i tried it now with my current setup and then...the can-back is in the gui aggain...
hm ok i will place this flag to an empty slot in the gi where it does not overwrite my others...

**Comment by FabioZumbi12** [comment]
This is fixed?

**Comment by CloudeLecaw** [comment]
i will test it this night aggain with your new release of the 7.0 b35 :-) i Reply tomorrow :)

**Comment by CloudeLecaw** [comment]
sorry for tis really late Reply.

The Error seems to be fixed now in the latest release 7.0.2

could be that you fixed it earlier allready :3 i wasnt able to test for a while:)
