### ISSUE TITLE
mysql not work on my server

### ISSUE THREAD

**Issue by mat41997** [FabioZumbi12/RedProtect#90]
logs
http://pastebin.com/Mmn4zE0z

config
http://pastebin.com/CStT6Jix

timings
https://timings.aikar.co/v2/?id=556e85963de0486eb585e0c350ef5d7c

ss
![2016-08-23 18_35_53-mysql workbench](https://cloud.githubusercontent.com/assets/5884000/17900792/e5e1e2e4-6960-11e6-85a7-4b499dc3caf1.png)

**Comment by FabioZumbi12** [comment]
I have rewrite all the myswl code! Join on our Discord and download the latest dev version and use the new mysql system!

https://discord.gg/RyEVJC3

The major change is the mysql will use only one database and all regions inside this database.

**Comment by mat41997** [comment]
ok
i use
https://cdn.discordapp.com/attachments/215573884940976148/217565573872222210/RedProtect-6.7.0-b1.028.jar
and work : )

**Comment by FabioZumbi12** [comment]
Good ^^

Let me know if you find some errors. This is a dev build and is not fully tested!

**Comment by mat41997** [comment]
ymm..

TheKarol use a server command: /rp am kotex

and thekarol not can build and tear down on your plot, why?
