### ISSUE TITLE
error - load RedProtect-6.7.0-b1.029

### ISSUE THREAD

**Issue by mat41997** [FabioZumbi12/RedProtect#92]
logs
http://pastebin.com/aK5sr1Ex

timings
https://timings.aikar.co/v2/?id=1e3c620ecefc42e3948a13551816e3f6

**Comment by FabioZumbi12** [comment]
"Plugin already initialized!"

You have two instances of RedProtect running on your server ...

**Comment by mat41997** [comment]
noo.. see
http://pastebin.com/YMGZZCrh

**Comment by FabioZumbi12** [comment]
Please look into your plugins folder and see if theres more of onw redprotect.jar

Its not recomended to load/reload plugin with server running, specially big plugins like this.

**Comment by mat41997** [comment]
no, i don't have duble plugin

ok.

**Comment by FabioZumbi12** [comment]
Solved? Mybe try the latest version if Works!
