### ISSUE TITLE
error - thermos 1.7.10 #1614 ~58 - Thirst-Mod-1.7.10

### ISSUE THREAD

**Issue by mat41997** [FabioZumbi12/RedProtect#94]
i have error

logs
http://pastebin.com/5AjshuwS

timings
http://pastebin.com/KBwAVixP

**Comment by Stuart74** [comment]
More information is required such as 

- more Descriptive Title other than Error so other can see if there problem is already reported
- actions or events that caused this error
- Version of plugin you're using
- And using Pastebin to put the logs in so there is not a wall of text which makes it difficult to diagnose.
- What Build Thermos

Doing at least the above will get you better help from the community.
Thanks Have a great day :)

**Comment by Stuart74** [comment]
Is it crashing your server ? 
Is it preventing your server to start?
What problems is it causing you in game regarding redprotect and thirst mod ? 
Or is it just console spam but not causing issues in game?
Is it triggered by a player as i see some player.entity errors in the logs?

**Comment by mat41997** [comment]
serwer work normaly, only this error in console spam.

**Comment by FabioZumbi12** [comment]
This is some type of potion? Can you see what the player try to consume/use to trown this error?

On error log is water bottle, but on the code, allow only potions.
