### ISSUE TITLE
[Sponge] Suggestion AutoClaiming  and Charging per claim block

### ISSUE THREAD

**Issue by ghost** [FabioZumbi12/RedProtect#97]
It would be awesome since a lot of my players requesting that claiming be even easier and to be like how towny would claim blocks by players just walking over the chunks they want to protect and claim and it auto claim. 

It be also nice to have a cost to claim each chunk bit like how towny works with paying for the chunks that players can claim.

**Comment by FabioZumbi12** [comment]
Sorry, for Redprotect the best way is fences or wand tool. RedProtect dont work with chunks.
