### ISSUE TITLE
Suggestions and bugs.

### ISSUE THREAD

**Issue by Mawobi** [FabioZumbi12/RedProtect#99]
Hey Fabio,
a few things to fix and maybe add :D.

Bugs:
-One big flag: if 2 players are in the same flag gui and one of them toggle an flag, the other one will be able to take out the items of the gui.
-If you have an plugin which drops the head by killing an player, this head will also be removed if the flag "keep-inventory" is true.
-if you have the flag Keep-level on, the player which die will keep his levels, but also drops his xp which will not be removed. so players can farm endless xp on that way.

Suggestions:
Flags:
- force-elytra
- deny-healthregen
- enter-cost (Items or Money amount by enter an region. only if player has enough he can enter.)

-And ould you add a way to allow to eat cakes per flag? i tryed it with "allow-break cake" but you only can break and not eat the cake. This would be really cool.

Nice Regards
~Mawobi

**Comment by FabioZumbi12** [comment]
RedProtect only cancels the drop of inventory and drop of levels using the SPigot API, no other methods. then, i think your other plugins need to listem if inventory is keeping or levels too. Using on my server, on player die with keeplevels, this player keep his levels and dont drop any xp on ground.

 

The flag gui problem is already solved. Only one gui can be openned at one time on same region.
